import type { TopicPractice } from "../types";

export const practice: TopicPractice = {
  questions: [
    {
      name: "Valid Anagram",
      difficulty: "Easy",
      variation: "Count array equality, the template",
      link: "https://leetcode.com/problems/valid-anagram/",
      question: [
        "Given two strings s and t, return true if t is an anagram of s, and false otherwise. An anagram is a rearrangement of all the letters of the original string, using every letter exactly as many times as it occurs.",
        "Example 1:\nInput: s = 'anagram', t = 'nagaram'\nOutput: true\nExplanation: Both strings contain three a, one n, one g, one r and one m.",
        "Example 2:\nInput: s = 'rat', t = 'car'\nOutput: false\nExplanation: s has a t and no c, so the two letter multisets differ.",
        "Constraints:\n- 1 <= s.length, t.length <= 5 * 10^4\n- s and t consist of lowercase English letters",
      ],
      code: `bool isAnagram(string s, string t) {
    if (s.size() != t.size()) return false;   // different lengths can never match
    vector<int> cnt(26, 0);
    for (int i = 0; i < (int)s.size(); i++) {
        cnt[s[i] - 'a']++;                    // one pass, both strings at once
        cnt[t[i] - 'a']--;
    }
    for (int c : cnt) if (c != 0) return false;
    return true;
}`,
      explanation: [
        "The whole pattern lives in one idea: a string, viewed as a multiset of characters, is fully described by 26 integers. Two strings are anagrams exactly when those two vectors of 26 integers are equal, so the problem reduces to comparing two fixed-size arrays.",
        "Incrementing for s and decrementing for t in the same loop is the compact form of that comparison: the array ends at all zeros if and only if every letter appeared the same number of times on both sides. The early length check is what makes it safe - without it a prefix relationship such as s = 'ab', t = 'aab' could not be caught by sign alone in a single fused loop.",
        "The tempting alternative is to sort both strings and compare. It is correct but O(n log n) and it throws away the structure that every later problem in this family needs. Once you have the count array you also get sliding windows, grouping keys and containment tests for free; a sorted copy gives you none of those.",
        "If the alphabet is not known to be lowercase ASCII - Unicode input, for instance - swap the fixed array for a hash map keyed on the code point. The logic is unchanged, only the container differs.",
        "Time: O(n). Space: O(1), since 26 counters do not grow with the input.",
      ],
    },
    {
      name: "Find the Difference",
      difficulty: "Easy",
      variation: "One surplus character",
      link: "https://leetcode.com/problems/find-the-difference/",
      question: [
        "You are given two strings s and t. String t is generated by shuffling the letters of s and then inserting one additional letter at a random position. Return that added letter.",
        "Example 1:\nInput: s = 'abcd', t = 'abcde'\nOutput: 'e'\nExplanation: t contains all of a, b, c, d plus one extra e.",
        "Example 2:\nInput: s = '', t = 'y'\nOutput: 'y'\nExplanation: s is empty, so the whole of t is the inserted letter.",
        "Constraints:\n- 0 <= s.length <= 1000\n- t.length == s.length + 1\n- s and t consist of lowercase English letters",
      ],
      code: `// Count version - the frequency template, and the one that generalises.
char findTheDifferenceCount(string s, string t) {
    vector<int> cnt(26, 0);
    for (char c : t) cnt[c - 'a']++;
    for (char c : s) cnt[c - 'a']--;
    for (int i = 0; i < 26; i++)
        if (cnt[i] > 0) return char('a' + i);  // exactly one letter is left over
    return ' ';                                // unreachable under the constraints
}

// XOR version - the same counts collapsed modulo 2.
char findTheDifference(string s, string t) {
    int x = 0;
    for (char c : s) x ^= c;   // every shared character cancels with its twin
    for (char c : t) x ^= c;
    return char(x);
}`,
      explanation: [
        "Subtracting the multiset of s from the multiset of t leaves a multiset with exactly one element in it, and that element is the answer. The count array computes that difference directly, so the surplus letter is the only index left positive.",
        "The XOR trick works because we are promised exactly one surplus character. XOR is addition modulo 2 on each bit, so a character appearing an even number of times across both strings vanishes and the single odd one survives. That promise is doing real work: with two surplus letters XOR returns their XOR, which is usually not a letter at all, while the count array still reports both.",
        "That is the trap. XOR is shorter and uses no extra memory, but it only answers 'which single element has odd multiplicity'. Reach for it when the problem guarantees a unique odd element, and keep the count array whenever multiplicities matter.",
        "Time: O(n). Space: O(1).",
      ],
    },
    {
      name: "Ransom Note",
      difficulty: "Easy",
      variation: "Multiset containment",
      link: "https://leetcode.com/problems/ransom-note/",
      question: [
        "Given two strings ransomNote and magazine, return true if ransomNote can be constructed by using the letters of magazine. Each letter in magazine may be used at most once.",
        "Example 1:\nInput: ransomNote = 'a', magazine = 'b'\nOutput: false\nExplanation: magazine has no a to spend.",
        "Example 2:\nInput: ransomNote = 'aa', magazine = 'aab'\nOutput: true\nExplanation: magazine supplies two a characters, which is exactly what the note needs; the leftover b is simply unused.",
        "Constraints:\n- 1 <= ransomNote.length, magazine.length <= 10^5\n- both strings consist of lowercase English letters",
      ],
      code: `bool canConstruct(string ransomNote, string magazine) {
    vector<int> cnt(26, 0);
    for (char c : magazine) cnt[c - 'a']++;      // the budget
    for (char c : ransomNote)
        if (--cnt[c - 'a'] < 0) return false;    // spent a letter we did not have
    return true;
}`,
      explanation: [
        "This is the containment version of the same comparison. Instead of asking whether two count vectors are equal, we ask whether one dominates the other coordinate-wise: need[c] <= have[c] for every c. Anagram is the special case where the totals also match.",
        "Spending letters greedily is safe because letters are not interchangeable - an a can only ever be covered by an a. There is no choice to make and therefore nothing to backtrack over, which is why a single decrementing pass is a proof and not just a heuristic.",
        "Checking the counter immediately after the decrement lets us return on the first shortfall without a second sweep over the alphabet. The common slip is to compare only totals, or to compare set membership rather than counts: magazine = 'ab' contains the letter a but still cannot build 'aa'.",
        "Time: O(n + m). Space: O(1).",
      ],
    },
    {
      name: "First Unique Character in a String",
      difficulty: "Easy",
      variation: "Count then rescan in order",
      link: "https://leetcode.com/problems/first-unique-character-in-a-string/",
      question: [
        "Given a string s, find the first non-repeating character in it and return its index. If it does not exist, return -1.",
        "Example 1:\nInput: s = 'leetcode'\nOutput: 0\nExplanation: l occurs once and is the first such character.",
        "Example 2:\nInput: s = 'loveleetcode'\nOutput: 2\nExplanation: l appears at indices 0 and 4 and o at indices 1 and 9, so the first character with count one is v at index 2.",
        "Constraints:\n- 1 <= s.length <= 10^5\n- s consists of lowercase English letters",
      ],
      code: `int firstUniqChar(string s) {
    vector<int> cnt(26, 0);
    for (char c : s) cnt[c - 'a']++;
    for (int i = 0; i < (int)s.size(); i++)
        if (cnt[s[i] - 'a'] == 1) return i;   // rescan in original order, not alphabet order
    return -1;
}`,
      explanation: [
        "Two passes, and the split between them is the point. The first pass answers a question about the whole string (how many times does each letter occur) which cannot be known until the end. The second pass answers a question about position, and it must walk the original string so that 'first' means first by index.",
        "Iterating the 26 counters instead of the string is the classic bug: that finds the alphabetically smallest unique character, not the leftmost one. For 'loveleetcode' the alphabet scan would report c at index 8 rather than v at index 2.",
        "If you truly need one pass, store the first index of each character alongside its count and take the minimum index over all characters with count one. That is more state for no asymptotic gain, but it is the right shape when the input arrives as a stream you cannot revisit.",
        "Time: O(n). Space: O(1).",
      ],
    },
    {
      name: "Longest Palindrome",
      difficulty: "Easy",
      variation: "Parity of counts",
      link: "https://leetcode.com/problems/longest-palindrome/",
      question: [
        "Given a string s consisting of lowercase and uppercase English letters, return the length of the longest palindrome that can be built with those letters. Letters are case sensitive, and you may reorder them freely and discard any you do not want.",
        "Example 1:\nInput: s = 'abccccdd'\nOutput: 7\nExplanation: The counts are a:1, b:1, c:4, d:2. Use both d and all four c as pairs for six characters, then place one leftover letter in the centre, giving for instance 'dccaccd'.",
        "Example 2:\nInput: s = 'a'\nOutput: 1\nExplanation: A single character is already a palindrome.",
        "Constraints:\n- 1 <= s.length <= 2000\n- s consists of lowercase and uppercase English letters",
      ],
      code: `int longestPalindrome(string s) {
    vector<int> cnt(128, 0);            // both letter cases, so index by raw ASCII
    for (unsigned char c : s) cnt[c]++;
    int len = 0;
    bool haveOdd = false;
    for (int f : cnt) {
        len += f / 2 * 2;               // every character is usable in pairs
        if (f % 2) haveOdd = true;      // at least one leftover exists for the centre
    }
    return len + (haveOdd ? 1 : 0);
}`,
      explanation: [
        "A palindrome is determined by its multiset of characters up to one exception: every character must occur an even number of times, except that a single character may occur an odd number of times and then it sits in the middle. So the answer never depends on the order of s, only on the 128 parities and counts.",
        "The greedy is therefore exact rather than approximate. Each character contributes floor(f/2) mirrored pairs and there is no reason to leave a pair unused, since dropping one only shortens the result. After the pairs are placed, at most one unpaired character can be added, and one is available precisely when some count was odd.",
        "Two traps. First, counting the number of odd characters and adding all of them is wrong: only one odd character fits in the centre, so the increment is capped at 1. Second, the problem is case sensitive, so an array of 26 folds A into a and overcounts - 'Aa' has answer 1, not 2.",
        "Time: O(n). Space: O(1).",
      ],
    },
    {
      name: "Group Anagrams",
      difficulty: "Medium",
      variation: "Canonical signature as a hash key",
      link: "https://leetcode.com/problems/group-anagrams/",
      question: [
        "Given an array of strings strs, group together the strings that are anagrams of each other. Return the list of groups in any order, and the strings inside each group in any order.",
        "Example 1:\nInput: strs = ['eat','tea','tan','ate','nat','bat']\nOutput: [['eat','tea','ate'],['tan','nat'],['bat']]\nExplanation: eat, tea and ate share the letters a,e,t; tan and nat share a,n,t; bat is alone.",
        "Example 2:\nInput: strs = ['','b','']\nOutput: [['',''],['b']]\nExplanation: The two empty strings are anagrams of each other.",
        "Constraints:\n- 1 <= strs.length <= 10^4\n- 0 <= strs[i].length <= 100\n- strs[i] consists of lowercase English letters",
      ],
      code: `vector<vector<string>> groupAnagrams(vector<string>& strs) {
    unordered_map<string, vector<string>> groups;
    for (const string& w : strs) {
        string key = w;
        sort(key.begin(), key.end());     // canonical form shared by all anagrams of w
        groups[key].push_back(w);
    }
    vector<vector<string>> res;
    res.reserve(groups.size());
    for (auto& kv : groups) res.push_back(std::move(kv.second));
    return res;
}

// Alternative key built from counts - avoids the log factor per word.
string countKey(const string& w) {
    vector<int> cnt(26, 0);
    for (char c : w) cnt[c - 'a']++;
    string key;
    for (int i = 0; i < 26; i++) {
        key += '#';                        // separator so 1,11 cannot collide with 11,1
        key += to_string(cnt[i]);
    }
    return key;
}`,
      explanation: [
        "Grouping by an equivalence relation becomes a hash-map problem the moment you can compute a canonical representative of each class. Being an anagram is exactly 'having the same count vector', so any faithful encoding of that vector works as a key: the sorted string, or the 26 counts serialised.",
        "The key must be injective on classes in both directions - equal keys must imply anagram, and anagrams must imply equal keys. Sorting gives that immediately. A hand-rolled numeric key does not always: concatenating counts without separators makes the vectors (1,11) and (11,1) collide, and multiplying prime numbers per letter overflows 64 bits well before a 100-character word.",
        "Sorting costs O(L log L) per word against O(L + 26) for the count key, so the count key wins for long words while the sorted key wins on brevity and is fine at L <= 100. Both are O(1) extra space per distinct group beyond the output.",
        "Time: O(n * L log L) with sorted keys, or O(n * (L + 26)) with count keys, where L is the maximum word length. Space: O(n * L) for the map and the answer.",
      ],
    },
    {
      name: "Sort Characters By Frequency",
      difficulty: "Medium",
      variation: "Order by count, counting sort on frequencies",
      link: "https://leetcode.com/problems/sort-characters-by-frequency/",
      question: [
        "Given a string s, sort it in decreasing order based on the frequency of its characters. The frequency of a character is the number of times it appears in the string. Return any string that satisfies this ordering; characters with equal frequency may appear in any relative order.",
        "Example 1:\nInput: s = 'tree'\nOutput: 'eert'\nExplanation: e occurs twice while r and t occur once each, so both e must come before r and t. 'eetr' would also be accepted.",
        "Example 2:\nInput: s = 'Aabb'\nOutput: 'bbAa'\nExplanation: b occurs twice, A and a once each. Upper and lower case are treated as different characters, so 'bbaA' is equally valid.",
        "Constraints:\n- 1 <= s.length <= 5 * 10^5\n- s consists of uppercase and lowercase English letters and digits",
      ],
      code: `string frequencySort(string s) {
    vector<int> cnt(128, 0);
    for (unsigned char c : s) cnt[c]++;
    int mx = *max_element(cnt.begin(), cnt.end());
    string res;
    res.reserve(s.size());
    for (int f = mx; f >= 1; f--)                 // buckets of frequency, high to low
        for (int c = 0; c < 128; c++)
            if (cnt[c] == f) res.append(f, char(c));   // all f copies together
    return res;
}`,
      explanation: [
        "The count array is not only for comparisons - it is also the sort key. Once the 128 counts are known the answer is just the characters emitted in non-increasing order of count, with each character repeated its own count of times.",
        "Because a frequency is an integer between 1 and n, we can skip comparison sorting entirely and bucket by frequency: walk f from the maximum down to 1 and emit every character whose count equals f. The outer loop runs at most n times but the inner work is bounded by 128 per level, and the total number of appended characters is exactly n.",
        "The subtle requirement is that all copies of a character stay contiguous. Emitting one character per unit of frequency in a global sorted order would interleave characters of equal count and produce an invalid answer even though the counts look right.",
        "The alphabet here includes digits and both cases, so 128 ASCII slots are needed; a 26-slot array silently merges A with a and indexes out of range for digits.",
        "Time: O(n + 128 * maxFreq) which is O(n) in practice, or O(n + k log k) with an explicit sort of the k <= 128 distinct characters. Space: O(n) for the output.",
      ],
    },
    {
      name: "Find All Anagrams in a String",
      difficulty: "Medium",
      variation: "Fixed-size sliding window over counts",
      link: "https://leetcode.com/problems/find-all-anagrams-in-a-string/",
      question: [
        "Given two strings s and p, return an array of all the start indices of the substrings of s that are anagrams of p. The answer may be returned in any order.",
        "Example 1:\nInput: s = 'cbaebabacd', p = 'abc'\nOutput: [0,6]\nExplanation: The substring starting at 0 is 'cba' and the one starting at 6 is 'bac', both anagrams of 'abc'.",
        "Example 2:\nInput: s = 'abab', p = 'ab'\nOutput: [0,1,2]\nExplanation: 'ab', 'ba' and 'ab' are all anagrams of 'ab'.",
        "Constraints:\n- 1 <= s.length, p.length <= 3 * 10^4\n- s and p consist of lowercase English letters",
      ],
      code: `vector<int> findAnagrams(string s, string p) {
    int n = s.size(), k = p.size();
    vector<int> res;
    if (n < k) return res;
    vector<int> cnt(26, 0);
    for (char c : p) cnt[c - 'a']++;
    int need = k;                                // characters of p still unmatched
    for (int i = 0; i < n; i++) {
        if (cnt[s[i] - 'a']-- > 0) need--;       // only a still-required char reduces need
        if (i >= k && ++cnt[s[i - k] - 'a'] > 0) need++;  // char sliding out becomes required again
        if (need == 0) res.push_back(i - k + 1);
    }
    return res;
}`,
      explanation: [
        "Every candidate substring has length exactly p.length, so the windows form a chain in which consecutive windows differ by one character in and one character out. Recomputing the count vector per window is O(n * k); updating it incrementally is O(1) per step, and that is the whole optimisation.",
        "Comparing the two vectors after each slide would still cost 26 per step. The counter need removes that: cnt holds the residual demand of p, so cnt[c] > 0 means 'p still wants another c'. A character entering the window decrements its demand and only counts as progress if the demand was positive; a character leaving restores demand and only loses progress if it becomes positive. need == 0 is therefore equivalent to the window being an anagram, checked in O(1).",
        "The signs matter. Counts are allowed to go negative for characters the window has in surplus, and those surpluses are exactly what need refuses to credit. Clamping at zero, or testing need == 0 before the removal step, both break the invariant.",
        "The tempting wrong approach is to hash or sort each window independently. It is correct but quadratic, and it hides the fact that the state can be maintained rather than rebuilt.",
        "Time: O(n). Space: O(1) beyond the output.",
      ],
    },
    {
      name: "Permutation in String",
      difficulty: "Medium",
      variation: "Existence of an anagram window, matched-slot counter",
      link: "https://leetcode.com/problems/permutation-in-string/",
      question: [
        "Given two strings s1 and s2, return true if s2 contains a permutation of s1 as a contiguous substring, and false otherwise.",
        "Example 1:\nInput: s1 = 'ab', s2 = 'eidbaooo'\nOutput: true\nExplanation: s2 contains the substring 'ba', which is a permutation of 'ab'.",
        "Example 2:\nInput: s1 = 'ab', s2 = 'eidboaoo'\nOutput: false\nExplanation: No window of length two in s2 uses exactly one a and one b; the a and b in s2 are separated by an o.",
        "Constraints:\n- 1 <= s1.length, s2.length <= 10^4\n- s1 and s2 consist of lowercase English letters",
      ],
      code: `bool checkInclusion(string s1, string s2) {
    int n = s1.size(), m = s2.size();
    if (n > m) return false;
    vector<int> diff(26, 0);
    for (char c : s1) diff[c - 'a']++;
    for (int i = 0; i < n; i++) diff[s2[i] - 'a']--;   // seed the first window
    int zeros = 0;
    for (int i = 0; i < 26; i++) if (diff[i] == 0) zeros++;
    if (zeros == 26) return true;
    for (int i = n; i < m; i++) {
        int in = s2[i] - 'a', out = s2[i - n] - 'a';
        if (--diff[in] == 0) zeros++; else if (diff[in] == -1) zeros--;
        if (++diff[out] == 0) zeros++; else if (diff[out] == 1) zeros--;
        if (zeros == 26) return true;
    }
    return false;
}`,
      explanation: [
        "This is the decision version of the previous problem, and it is worth writing with a different bookkeeping device to see the same invariant from another angle. Keep diff = count(s1) - count(window). The window is a permutation of s1 exactly when all 26 entries of diff are zero.",
        "Tracking the number of zero entries turns that global test into O(1). When an entry changes by one, the only ways the zero count can move are: it just became 0, so a zero was gained; or it was 0 and moved off, so a zero was lost. Testing the new value against 0 handles the first case, and against -1 after a decrement or +1 after an increment handles the second, since those values can only be reached from 0.",
        "Order inside the loop is free here because the entering and leaving characters are updated independently, but the seed matters: zeros must be computed after the first window is subtracted, and the first window has to be tested before any slide, otherwise a match at index 0 is missed.",
        "A frequent wrong answer checks whether the counts of s1 are a subset of the counts of some window without fixing the window length. Any long enough window contains the letters; the point is that the window must contain nothing else, which is what fixing the length to s1.length enforces.",
        "Time: O(n + m). Space: O(1).",
      ],
    },
    {
      name: "Determine if Two Strings Are Close",
      difficulty: "Medium",
      variation: "Multiset of counts, alphabet invariant",
      link: "https://leetcode.com/problems/determine-if-two-strings-are-close/",
      question: [
        "Two strings are considered close if one can be obtained from the other by repeatedly applying either of these operations: swap any two existing characters of the string, or transform every occurrence of one existing character into another existing character and simultaneously every occurrence of that other character into the first. Given two strings word1 and word2, return true if they are close and false otherwise.",
        "Example 1:\nInput: word1 = 'abc', word2 = 'bca'\nOutput: true\nExplanation: Swaps alone reorder abc into bca.",
        "Example 2:\nInput: word1 = 'cabbba', word2 = 'abbccc'\nOutput: true\nExplanation: word1 has counts a:2, b:3, c:1 and word2 has counts a:1, b:2, c:3. Both use exactly the letters a, b, c, and both count multisets are {1,2,3}, so the counts can be permuted into place by swapping the roles of the letters.",
        "Constraints:\n- 1 <= word1.length, word2.length <= 10^5\n- word1 and word2 contain only lowercase English letters",
      ],
      code: `bool closeStrings(string word1, string word2) {
    if (word1.size() != word2.size()) return false;
    vector<int> a(26, 0), b(26, 0);
    for (char c : word1) a[c - 'a']++;
    for (char c : word2) b[c - 'a']++;
    for (int i = 0; i < 26; i++)
        if ((a[i] == 0) != (b[i] == 0)) return false;   // the sets of used letters must agree
    sort(a.begin(), a.end());
    sort(b.begin(), b.end());
    return a == b;                                      // and the count multisets must agree
}`,
      explanation: [
        "Work out what each operation preserves. Swapping two characters changes nothing about the count vector at all. Transforming every x into y and every y into x permutes two entries of the count vector but cannot create or destroy a letter, because the operation is only allowed between characters that already exist. So two invariants survive every sequence of moves: the set of distinct letters used, and the multiset of non-zero counts.",
        "Those two invariants are also sufficient. Given equal letter sets and equal count multisets, repeatedly apply the transform operation to move each count onto the letter that needs it - a permutation is a product of transpositions, and every transposition here is legal because both letters are present - then use swaps to fix the order. Hence the test is exact, not merely necessary.",
        "Sorting the 26-slot arrays compares the count multisets, and the zero-versus-non-zero pass compares the letter sets. Both checks are needed and neither implies the other: 'a' and 'aa' have the same letter set but different multisets, while 'aabb' and 'ccdd' have the same multiset {2,2} and no letters in common.",
        "Time: O(n + m) plus a constant-size sort. Space: O(1).",
      ],
    },
    {
      name: "Minimum Window Substring",
      difficulty: "Hard",
      variation: "Variable-size window covering a multiset",
      link: "https://leetcode.com/problems/minimum-window-substring/",
      question: [
        "Given two strings s and t, return the shortest substring of s that contains every character of t including duplicates. If there is no such substring, return the empty string. The answer is guaranteed to be unique when it exists.",
        "Example 1:\nInput: s = 'ADOBECODEBANC', t = 'ABC'\nOutput: 'BANC'\nExplanation: 'BANC' at index 9 has length 4 and covers A, B and C. 'ADOBEC' also covers them but is longer.",
        "Example 2:\nInput: s = 'a', t = 'aa'\nOutput: ''\nExplanation: s has a single a, so no window can supply two.",
        "Constraints:\n- 1 <= s.length, t.length <= 10^5\n- s and t consist of uppercase and lowercase English letters",
      ],
      code: `string minWindow(string s, string t) {
    if (t.size() > s.size()) return "";
    vector<int> need(128, 0);
    for (unsigned char c : t) need[c]++;
    int missing = t.size();                  // total remaining demand, duplicates included
    int bestLen = INT_MAX, bestStart = 0, left = 0;
    for (int right = 0; right < (int)s.size(); right++) {
        if (need[(unsigned char)s[right]]-- > 0) missing--;   // surplus chars go negative
        while (missing == 0) {                                // window is valid: shrink it
            if (right - left + 1 < bestLen) {
                bestLen = right - left + 1;
                bestStart = left;
            }
            if (++need[(unsigned char)s[left]] > 0) missing++; // this char became required again
            left++;
        }
    }
    return bestLen == INT_MAX ? "" : s.substr(bestStart, bestLen);
}`,
      explanation: [
        "Unlike the anagram windows, the length is not fixed, so the state is a pair of pointers plus the residual demand vector need. The invariant is that need[c] counts how many more copies of c the window still owes, with negative values recording surplus. missing is the sum of the positive parts, so missing == 0 means the window covers t.",
        "Correctness of the two-pointer sweep rests on monotonicity: for a fixed right, if the window [left, right] is valid then so is every window [left', right] with left' <= left. So for each right there is a unique smallest valid left, and because that boundary never moves backwards as right grows, left can be advanced monotonically and every candidate minimum is examined. Each index enters and leaves once, so the sweep is linear even though it contains a nested loop.",
        "Allowing negative counts is what makes duplicates work. If surplus characters were clamped at zero, a window over 'AAB' looking for 'AB' could not tell that the second A is expendable, and the shrink step would refuse to drop it.",
        "Two traps: shrinking while the window is merely non-empty rather than while it is valid, which loses the optimum; and recording the answer after advancing left, which reports a window one character too short. Record first, then shrink.",
        "The input is mixed case, so index the counters by raw byte over 128 slots rather than folding to 26.",
        "Time: O(n + m). Space: O(1) for the fixed alphabet, plus O(bestLen) for the returned string.",
      ],
    },
    {
      name: "Substring with Concatenation of All Words",
      difficulty: "Hard",
      variation: "Word-level anagram window",
      link: "https://leetcode.com/problems/substring-with-concatenation-of-all-words/",
      question: [
        "You are given a string s and an array words of strings that all have the same length. A concatenated substring of s is a substring formed by joining every string in words exactly once, in any order, with nothing in between. Return the starting indices of all such substrings of s, in any order.",
        "Example 1:\nInput: s = 'barfoothefoobarman', words = ['foo','bar']\nOutput: [0,9]\nExplanation: 'barfoo' starts at index 0 and 'foobar' starts at index 9; both are permutations of foo and bar.",
        "Example 2:\nInput: s = 'wordgoodgoodgoodbestword', words = ['word','good','best','word']\nOutput: []\nExplanation: The concatenation needs two copies of word, one good and one best, adjacent in some order, and no window of length 16 in s provides exactly that.",
        "Constraints:\n- 1 <= s.length <= 10^4\n- 1 <= words.length <= 5000\n- 1 <= words[i].length <= 30\n- s and words[i] consist of lowercase English letters",
      ],
      code: `vector<int> findSubstring(string s, vector<string>& words) {
    int n = s.size(), m = words.size(), w = words[0].size();
    vector<int> res;
    if (n < (long long)m * w) return res;
    unordered_map<string, int> need;
    for (const string& x : words) need[x]++;
    for (int off = 0; off < w; off++) {          // one independent window per start residue
        unordered_map<string, int> have;
        int cnt = 0, left = off;
        for (int right = off; right + w <= n; right += w) {
            string cur = s.substr(right, w);
            if (!need.count(cur)) {              // an unknown word breaks every window across it
                have.clear();
                cnt = 0;
                left = right + w;
                continue;
            }
            have[cur]++;
            cnt++;
            while (have[cur] > need[cur]) {       // too many copies: drop words from the front
                have[s.substr(left, w)]--;
                cnt--;
                left += w;
            }
            if (cnt == m) {                      // exactly all words, none spare
                res.push_back(left);
                have[s.substr(left, w)]--;
                cnt--;
                left += w;
            }
        }
    }
    return res;
}`,
      explanation: [
        "This is Find All Anagrams with the alphabet promoted from characters to fixed-length words. Because every word has the same length w, any valid start index is congruent to some residue modulo w, and within one residue class the string is just a sequence of tokens. Run the sliding window once per residue and every start index is covered exactly once.",
        "The counts are now a hash map from word to remaining demand, and the window is valid when it holds m tokens with no token exceeding its demand. Two events shrink it: an over-represented token, which is fixed by dropping tokens from the front until the excess is gone, and a token that is not in words at all, which invalidates every window containing it and so justifies resetting the state and jumping past it.",
        "The reason the shrink loop is correct is the same monotonicity as before, applied to tokens: dropping from the front can only reduce counts, so it eventually clears the excess, and no valid window starting further left was skipped because any such window would have contained the same excess.",
        "The trap is scanning every character offset from 0 to n-1 and rebuilding the map for each, which is O(n * m) work and times out at the upper limits. Splitting by residue and sliding keeps every token parsed a constant number of times per residue.",
        "A second trap is comparing whole hash maps for equality after each step; the token counter cnt together with the per-token demand check gives the same answer in O(1) amortised time.",
        "Time: O(n * w) expected, from w residues each scanning O(n / w) tokens with O(w) substring and hashing cost. Space: O(m * w) for the two maps.",
      ],
    },
  ],
};
