import type { TopicPractice } from "../types";

export const practice: TopicPractice = {
  questions: [
    {
      name: "Domino and Tromino Tiling",
      difficulty: "Medium",
      variation: "Two-row frontier, the smallest broken profile",
      link: "https://leetcode.com/problems/domino-and-tromino-tiling/",
      question: [
        "You have two shapes of tile: a 2x1 domino, and a tromino shaped like the letter L. Both may be rotated freely. Given an integer n, return the number of ways to tile a board of 2 rows and n columns so that every cell is covered exactly once and no tile sticks out. Two tilings are different if there is some pair of side-adjacent cells covered by one tile in the first tiling but not in the second. Return the answer modulo 10^9 + 7.",
        "Example 1:\nInput: n = 3\nOutput: 5\nExplanation: Three tilings use dominoes only - three verticals, or a horizontal pair in columns 0-1 plus a vertical in column 2, or a vertical in column 0 plus a horizontal pair in columns 1-2. The other two tile the 2x3 board with a pair of L-trominoes.",
        "Example 2:\nInput: n = 1\nOutput: 1\nExplanation: Only a single vertical domino fits in a 2x1 board.",
        "Constraints:\n- 1 <= n <= 1000",
      ],
      code: `int numTilings(int n) {
    const long long MOD = 1000000007;
    // dp[i][s]: columns 0..i-1 are completely full, and s is the set of cells
    // of column i that tiles from earlier columns have already claimed.
    // bit 0 = top row, bit 1 = bottom row.
    vector<array<long long, 4>> dp(n + 1, {0, 0, 0, 0});
    dp[0][0] = 1;
    for (int i = 0; i < n; i++) {
        long long a = dp[i][0], b = dp[i][1], c = dp[i][2], d = dp[i][3];
        dp[i + 1][0] = (a + d) % MOD;          // vertical domino, or column i was already full
        dp[i + 1][1] = (a + c) % MOD;          // tromino poking into the top row, or a top horizontal
        dp[i + 1][2] = (a + b) % MOD;          // mirror image of the line above
        dp[i + 1][3] = (a + b + c) % MOD;      // two horizontals, or a tromino closing one row
    }
    return (int)dp[n][0];   // nothing may protrude past the last column
}`,
      explanation: [
        "The state is not 'how many columns are done' but 'how many columns are done, plus what the ragged edge in front of them looks like'. That ragged edge is the profile. With 2 rows the profile is a 2-bit mask, so there are only 4 states per column and the whole DP is four running numbers.",
        "The transition is driven by one rule: always resolve the topmost empty cell of the current column, and enumerate every tile that can cover it. That makes the cases disjoint (each tiling is generated by exactly one sequence of choices) and exhaustive, which is what a counting DP needs. From an empty column the choices are a vertical domino, two stacked horizontals, or one of the two trominoes; from a half-filled column the single empty cell must take a horizontal or the tail of a tromino.",
        "The tempting shortcut is to guess the recurrence f(n) = 2*f(n-1) + f(n-3) from the first few terms. It is correct here, but it does not generalise, and if you cannot derive it you cannot debug it. The profile formulation is the derivation, and it is the same code that later handles 3, 4 or 10 rows.",
        "Reading dp[n][0] rather than summing dp[n] is the boundary condition: any state with bits set at column n describes a tile hanging off the board.",
        "Time: O(n) - four states per column, constant work each. Space: O(1) if you keep only the previous column, O(n) as written.",
      ],
    },
    {
      name: "Tiling a Grid With Dominoes (M3TILE)",
      difficulty: "Medium",
      variation: "Fixed 3-wide strip, cell-by-cell frontier",
      link: "https://www.spoj.com/problems/M3TILE/",
      question: [
        "Count the number of ways to tile a rectangle of 3 rows and n columns completely with 2x1 dominoes, which may be placed horizontally or vertically. The input contains several test cases, one integer n per line, and ends with the value -1. For each n print the number of tilings on its own line.",
        "Example 1:\nInput:\n2\n4\n10\n-1\nOutput:\n3\n11\n571\nExplanation: A 3x2 block has 3 tilings: three stacked horizontal dominoes; or two verticals in rows 0-1 with a horizontal in row 2; or a horizontal in row 0 with two verticals in rows 1-2. Odd n would print 0 because the area 3n is then odd.",
        "Constraints:\n- 0 <= n <= 30\n- answers fit in a 64-bit integer",
      ],
      code: `int m = 3;                 // mask width: the strip is 3 cells across
vector<long long> nxt;     // dp layer indexed by the next row's claimed cells

// Fill position j of the current row. occ = cells of this row already covered by
// vertical dominoes from the row above; down = cells this row pushes into the next.
void fillRow(int j, int occ, int down, long long ways, bool lastRow) {
    if (j == m) {
        if (!lastRow || down == 0) nxt[down] += ways;   // nothing may hang below the board
        return;
    }
    if (occ >> j & 1) { fillRow(j + 1, occ, down, ways, lastRow); return; }   // already covered
    fillRow(j + 1, occ, down | (1 << j), ways, lastRow);                      // vertical domino
    if (j + 1 < m && !(occ >> (j + 1) & 1))
        fillRow(j + 2, occ, down, ways, lastRow);                             // horizontal domino
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    int n;
    while (cin >> n && n != -1) {
        // Rotate the rectangle: sweep n rows of width 3, so the mask stays 3 bits.
        vector<long long> cur(1 << m, 0);
        cur[0] = 1;
        for (int i = 0; i < n; i++) {
            nxt.assign(1 << m, 0);
            for (int occ = 0; occ < (1 << m); occ++)
                if (cur[occ]) fillRow(0, occ, 0, cur[occ], i == n - 1);
            cur = nxt;
        }
        cout << cur[0] << "\\n";
    }
    return 0;
}`,
      explanation: [
        "Sweep the board one row at a time, but fill each row cell by cell. The state between rows is a mask of which cells of the upcoming row are already occupied by vertical dominoes reaching down from the row just finished. That mask is the profile, and it is all the history the rest of the board can see.",
        "The recursion inside fillRow is the transition. It walks left to right and, at the first uncovered cell, tries only the two tiles that can cover that specific cell: a vertical domino (which marks the same column in the next row) or a horizontal domino (which consumes the neighbour to its right). Because every tiling covers its leftmost uncovered cell exactly once, the enumeration is a bijection with tilings - no double counting, no gaps.",
        "A 3x30 board has a 30-bit profile if you sweep by columns, which is 10^9 states. Sweeping by rows of width 3 gives 8 states. Always orient the sweep so the mask sits on the short side; that choice is the difference between an instant answer and a hopeless one.",
        "The lastRow flag is the only boundary rule, and forgetting it is the classic bug: without it you count tilings that push dominoes out through the bottom edge. Odd 3n gives 0 for free - no special case needed.",
        "Time: O(n * 2^m) states with O(m) amortised enumeration per state, so O(n * m * 2^m) with m = 3. Space: O(2^m).",
      ],
    },
    {
      name: "Number of Ways to Paint N x 3 Grid",
      difficulty: "Medium",
      variation: "Column profile of colours instead of occupancy",
      link: "https://leetcode.com/problems/number-of-ways-to-paint-n-3-grid/",
      question: [
        "You are given a grid of n rows and 3 columns. Paint every cell red, yellow or green so that no two cells sharing a side have the same colour. Return the number of ways to paint the grid, modulo 10^9 + 7.",
        "Example 1:\nInput: n = 1\nOutput: 12\nExplanation: A single row of 3 cells must have the middle colour differ from both neighbours: 3 * 2 * 2 = 12 colourings.",
        "Example 2:\nInput: n = 2\nOutput: 54\nExplanation: Of the 12 * 12 pairs of rows, only 54 have no column where the two rows agree.",
        "Constraints:\n- 1 <= n <= 5000",
      ],
      code: `int numOfWays(int n) {
    const long long MOD = 1000000007;
    // A profile here is a whole row of 3 colours, written base 3.
    vector<int> rows;
    for (int s = 0; s < 27; s++) {
        int a = s % 3, b = (s / 3) % 3, c = s / 9;
        if (a != b && b != c) rows.push_back(s);   // horizontally valid rows only
    }
    int k = rows.size();
    vector<vector<int>> nb(k);
    for (int i = 0; i < k; i++)
        for (int j = 0; j < k; j++) {
            int x = rows[i], y = rows[j];
            bool ok = true;
            for (int c = 0; c < 3; c++) { if (x % 3 == y % 3) ok = false; x /= 3; y /= 3; }
            if (ok) nb[i].push_back(j);            // stackable: differ in every column
        }
    vector<long long> dp(k, 1), ndp;               // first row: each valid row once
    for (int r = 1; r < n; r++) {
        ndp.assign(k, 0);
        for (int i = 0; i < k; i++)
            for (int j : nb[i]) ndp[j] = (ndp[j] + dp[i]) % MOD;
        dp = ndp;
    }
    long long ans = 0;
    for (long long v : dp) ans = (ans + v) % MOD;
    return (int)ans;
}`,
      explanation: [
        "Profile DP is not only about tiling. The idea is that the frontier between the finished part and the rest carries a bounded amount of information, so it can be an index. Here the frontier is the last painted row, and the information is its 3 colours - a base-3 mask instead of a bitmask.",
        "Split the constraints by direction. Horizontal constraints are internal to a row, so filter them once when enumerating the 27 candidate rows down to 12. Vertical constraints relate consecutive rows, so they become the legality test on transitions. Separating the two is what makes the state small.",
        "Precomputing the compatibility lists turns each layer into a fixed sparse matrix-vector product. Without it you would re-test 12 * 12 colour comparisons per row, which still passes here but is the habit that fails once the row is 5 cells wide.",
        "The known two-variable shortcut (aba-type rows and abc-type rows, 6 of each) is a hand simplification of exactly this transition matrix. Deriving it is fine; guessing it is how you get a wrong constant.",
        "Time: O(n * K * K) with K = 12 valid rows, plus O(K * K * 3) setup. Space: O(K * K) for the compatibility lists.",
      ],
    },
    {
      name: "Corn Fields",
      difficulty: "Medium",
      variation: "Row profile with blocked cells",
      link: "http://poj.org/problem?id=3254",
      question: [
        "Farmer John has a rectangular pasture of M rows and N columns. Some squares are fertile and some are barren. He wants to plant grass on a set of fertile squares such that no two chosen squares share an edge. Count the number of ways to do this, including the way that plants nothing at all, modulo 100000000. The first line holds M and N, then M lines of N values follow, where 1 means fertile and 0 means barren.",
        "Example 1:\nInput:\n2 3\n1 1 1\n0 1 0\nOutput:\n9\nExplanation: The fertile squares are the whole top row plus the middle of the bottom row. If the top middle square is planted it blocks the other three, giving 1 way. Otherwise the top-left, top-right and bottom-middle squares are pairwise non-adjacent, giving all 8 of their subsets. Total 1 + 8 = 9.",
        "Constraints:\n- 1 <= M <= 12\n- 1 <= N <= 12",
      ],
      code: `int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    int rows, cols;
    cin >> rows >> cols;
    vector<int> fertile(rows, 0);
    for (int i = 0; i < rows; i++)
        for (int j = 0; j < cols; j++) {
            int x; cin >> x;
            if (x) fertile[i] |= 1 << j;
        }
    const long long MOD = 100000000;
    vector<int> ok;
    for (int s = 0; s < (1 << cols); s++)
        if (!(s & (s << 1))) ok.push_back(s);      // no two chosen cells side by side in a row
    vector<long long> dp(1 << cols, 0), ndp;
    dp[0] = 1;                                     // an empty row above row 0
    for (int i = 0; i < rows; i++) {
        ndp.assign(1 << cols, 0);
        for (int m : ok) {
            if ((m & fertile[i]) != m) continue;   // every planted cell must be fertile
            for (int p : ok)
                if (dp[p] && !(p & m)) ndp[m] = (ndp[m] + dp[p]) % MOD;   // vertical check
        }
        dp = ndp;
    }
    long long ans = 0;
    for (int m : ok) ans = (ans + dp[m]) % MOD;
    cout << ans << "\\n";
    return 0;
}`,
      explanation: [
        "The profile is the planted mask of the previous row. That is enough because adjacency only reaches one row back: once row i is fixed, rows 0..i-1 can never constrain row i+1.",
        "Three independent filters keep the state space tiny. Horizontal adjacency is checked once per candidate mask with the s & (s << 1) test. The terrain is checked with a subset test against the fertile mask of that row. Vertical adjacency is the transition guard p & m. Each constraint is applied at exactly the place where it is decidable.",
        "The empty set counts, which is why dp starts at mask 0 with value 1 and the final answer sums over all masks. A common wrong answer here comes from trying to force at least one planted cell, or from summing only dp[0].",
        "Restricting both loops to the precomputed ok list matters: for N = 12 there are 4096 masks but only 377 with no two adjacent bits, so the pair loop shrinks by more than 100x.",
        "Time: O(M * F * F) where F is the number of adjacency-free masks (F ~ Fibonacci(N+2), 377 for N = 12). Space: O(2^N).",
      ],
    },
    {
      name: "Counting Tilings",
      difficulty: "Hard",
      variation: "General n x m domino tiling, modular",
      link: "https://cses.fi/problemset/task/2181",
      question: [
        "Your task is to count the number of ways you can fill an n x m grid using 1x2 and 2x1 dominoes so that every square is covered exactly once. Print the answer modulo 10^9 + 7. The only input line contains n and m.",
        "Example 1:\nInput:\n4 7\nOutput:\n781",
        "Example 2:\nInput:\n1 3\nOutput:\n0\nExplanation: The area is odd, so no set of dominoes can cover it.",
        "Constraints:\n- 1 <= n, m <= 10",
      ],
      code: `const long long MOD = 1000000007;
int m;                     // mask width, always the shorter side
vector<long long> nxt;

// Walk position j of the current row. occ = cells already covered from above,
// down = cells of the next row claimed by vertical dominoes placed here.
void fillRow(int j, int occ, int down, long long ways, bool lastRow) {
    if (j == m) {
        if (!lastRow || down == 0) nxt[down] = (nxt[down] + ways) % MOD;
        return;
    }
    if (occ >> j & 1) { fillRow(j + 1, occ, down, ways, lastRow); return; }
    fillRow(j + 1, occ, down | (1 << j), ways, lastRow);         // stand a domino up
    if (j + 1 < m && !(occ >> (j + 1) & 1))
        fillRow(j + 2, occ, down, ways, lastRow);                // lay a domino flat
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    int n;
    cin >> n >> m;
    if (m > n) swap(n, m);   // sweep along the long side, mask the short one
    vector<long long> cur(1 << m, 0);
    cur[0] = 1;
    for (int i = 0; i < n; i++) {
        nxt.assign(1 << m, 0);
        for (int occ = 0; occ < (1 << m); occ++)
            if (cur[occ]) fillRow(0, occ, 0, cur[occ], i == n - 1);
        cur = nxt;
    }
    cout << cur[0] << "\\n";
    return 0;
}`,
      explanation: [
        "This is the canonical broken profile problem. 'Broken' refers to the frontier being ragged in the middle of a row: cells to the left of the cursor belong to the next row's story, cells to the right still belong to this row's. The mask plus the cursor position together describe that ragged boundary exactly.",
        "Correctness rests on the leftmost-uncovered-cell rule. At every step the algorithm commits a tile to one specific cell - the first one not yet covered - and enumerates the only two tiles that can cover it. Every complete tiling therefore corresponds to exactly one path through the recursion, so the counts neither duplicate nor miss.",
        "Transposing when m > n is not cosmetic. A 1x10 by 10 sweep costs 10 * 1024 states; the other orientation is identical in answer and identical in cost here, but for a 2 x 1000 board the wrong orientation is 2^1000 states. Make the mask the short side, always.",
        "Two traps: allowing down != 0 after the final row silently counts tilings that hang off the bottom, and taking the modulus only at the end overflows. Note also that an odd n*m falls out as 0 with no special handling.",
        "Time: O(n * 2^m * m). Space: O(2^m) - two rolling layers.",
      ],
    },
    {
      name: "Mondriaan's Dream",
      difficulty: "Hard",
      variation: "Exact 64-bit tiling counts, many test cases",
      link: "http://poj.org/problem?id=2411",
      question: [
        "Count the number of ways to fill a rectangle of h by w with 2x1 dominoes, where each domino may be placed horizontally or vertically and the whole rectangle must be covered without overlaps. The input contains several test cases, one line per case with h and w, and terminates with a line containing two zeros. Print the exact count for each case, one per line.",
        "Example 1:\nInput:\n1 2\n1 3\n2 2\n2 3\n2 11\n4 11\n0 0\nOutput:\n1\n0\n2\n3\n144\n51205\nExplanation: A 1x3 strip has odd area so the count is 0. The 2 by n counts are Fibonacci numbers, and 2 by 11 gives 144.",
        "Constraints:\n- 1 <= h, w <= 11\n- answers fit in a signed 64-bit integer",
      ],
      code: `int m;                     // mask width = min(h, w)
vector<long long> nxt;

void fillRow(int j, int occ, int down, long long ways, bool lastRow) {
    if (j == m) {
        if (!lastRow || down == 0) nxt[down] += ways;
        return;
    }
    if (occ >> j & 1) { fillRow(j + 1, occ, down, ways, lastRow); return; }
    fillRow(j + 1, occ, down | (1 << j), ways, lastRow);
    if (j + 1 < m && !(occ >> (j + 1) & 1))
        fillRow(j + 2, occ, down, ways, lastRow);
}

int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    int h, w;
    while (cin >> h >> w && (h || w)) {      // the 0 0 line ends the input
        m = min(h, w);
        int n = max(h, w);                   // a rectangle and its transpose tile alike
        vector<long long> cur(1 << m, 0);
        cur[0] = 1;
        for (int i = 0; i < n; i++) {
            nxt.assign(1 << m, 0);
            for (int occ = 0; occ < (1 << m); occ++)
                if (cur[occ]) fillRow(0, occ, 0, cur[occ], i == n - 1);
            cur = nxt;
        }
        cout << cur[0] << "\\n";
    }
    return 0;
}`,
      explanation: [
        "Same profile DP as Counting Tilings with the modulus removed, which is the interesting difference: the answer must be exact. An 11x11 board has odd area so it is 0, and the largest real count here (11x10) is about 1.2 * 10^12, comfortably inside a signed 64-bit integer but far outside a 32-bit one. Using int here is the single most common wrong answer.",
        "The state is the mask of cells in the upcoming row already claimed by vertical dominoes, and the transition enumerates tiles for the leftmost uncovered cell. Because a tiling of an h by w rectangle maps one-to-one to a tiling of its transpose, taking m = min(h, w) is free correctness-wise and caps the mask at 2^11.",
        "Multi-test input demands that every layer be reset per case. Reusing a dirty nxt or forgetting to reinitialise cur[0] = 1 leaks counts from the previous rectangle - a bug that shows up only from the second test case onward.",
        "There is no closed form worth reaching for; the exact-value versions of this problem are precisely why the profile technique exists.",
        "Time: O(T * n * 2^m * m) for T test cases. Space: O(2^m).",
      ],
    },
    {
      name: "Painting a Grid With Three Different Colors",
      difficulty: "Hard",
      variation: "Wider colour profile, long sweep",
      link: "https://leetcode.com/problems/painting-a-grid-with-three-different-colors/",
      question: [
        "You are given two integers m and n. Consider an m x n grid where each cell is initially white. Paint each cell red, green or blue so that no two adjacent cells have the same colour, where two cells are adjacent if they share a side. Return the number of ways to colour the grid, modulo 10^9 + 7.",
        "Example 1:\nInput: m = 1, n = 1\nOutput: 3\nExplanation: One cell, three colours.",
        "Example 2:\nInput: m = 1, n = 2\nOutput: 6\nExplanation: Three choices for the first cell and two for the second.",
        "Example 3:\nInput: m = 5, n = 5\nOutput: 580986",
        "Constraints:\n- 1 <= m <= 5\n- 1 <= n <= 1000",
      ],
      code: `int colorTheGrid(int m, int n) {
    const long long MOD = 1000000007;
    int total = 1;
    for (int i = 0; i < m; i++) total *= 3;        // 3^m candidate columns
    vector<int> cols;
    for (int s = 0; s < total; s++) {
        int t = s;
        bool ok = true;
        for (int r = 0; r + 1 < m; r++) {          // vertical clashes inside one column
            if (t % 3 == (t / 3) % 3) { ok = false; break; }
            t /= 3;
        }
        if (ok) cols.push_back(s);
    }
    int k = cols.size();
    vector<vector<int>> nb(k);
    for (int i = 0; i < k; i++)
        for (int j = 0; j < k; j++) {
            int x = cols[i], y = cols[j];
            bool ok = true;
            for (int r = 0; r < m; r++) {          // adjacent columns differ in every row
                if (x % 3 == y % 3) { ok = false; break; }
                x /= 3; y /= 3;
            }
            if (ok) nb[i].push_back(j);
        }
    vector<long long> dp(k, 1), ndp;
    for (int c = 1; c < n; c++) {
        ndp.assign(k, 0);
        for (int i = 0; i < k; i++)
            if (dp[i]) for (int j : nb[i]) ndp[j] = (ndp[j] + dp[i]) % MOD;
        dp = ndp;
    }
    long long ans = 0;
    for (long long v : dp) ans = (ans + v) % MOD;
    return (int)ans;
}`,
      explanation: [
        "The profile is one full column written in base 3. The asymmetry of the constraints (m <= 5 but n up to 1000) dictates the sweep direction: mask the short side, iterate the long one. Doing it the other way would need 3^1000 states.",
        "Only 3 * 2^(m-1) of the 3^m columns are internally legal - 48 when m = 5 - because each cell below the top has 2 choices. Filtering first, then precomputing which pairs of legal columns can stand next to each other, reduces every one of the n-1 layers to walking a small adjacency list.",
        "The trap is trying to encode the profile as something smaller, like a count of colours or a canonical form up to colour permutation. Colour symmetry does compress the state (3 colours are interchangeable, so classes of columns behave alike), but the naive version of that idea breaks the transition test, because compatibility depends on the actual colours in each row, not on the pattern shape.",
        "For much larger n the layer step is a fixed linear map, so matrix exponentiation over the k x k compatibility matrix gives O(k^3 log n). At n <= 1000 the plain loop is far simpler and fast enough.",
        "Time: O(3^m * m + k^2 * m + n * k^2) with k <= 48. Space: O(k^2).",
      ],
    },
    {
      name: "Number of Ways to Build Sturdy Brick Wall",
      difficulty: "Hard",
      variation: "Profile as a seam mask, arbitrary tile lengths",
      link: "https://leetcode.com/problems/number-of-ways-to-build-sturdy-brick-wall/",
      question: [
        "You are given integers height and width representing the dimensions of a brick wall, and an array bricks of distinct brick lengths. Every brick has height 1 and a length taken from bricks, bricks cannot be rotated, and you have an unlimited supply of each length. Each row must be exactly width units long with no gaps and no overhang. A wall is sturdy if no two adjacent rows join bricks at the same horizontal position, except at the two ends of the wall. Return the number of sturdy wall designs, modulo 10^9 + 7.",
        "Example 1:\nInput: height = 2, width = 3, bricks = [1,2]\nOutput: 2\nExplanation: The three possible rows are 1+1+1 (seams at 1 and 2), 1+2 (seam at 1) and 2+1 (seam at 2). Only the pairs (1+2, 2+1) and (2+1, 1+2) have no shared seam.",
        "Example 2:\nInput: height = 1, width = 1, bricks = [5]\nOutput: 0\nExplanation: No brick of length 5 fits into a wall of width 1.",
        "Constraints:\n- 1 <= height <= 100\n- 1 <= width <= 10\n- 1 <= bricks.length <= 10\n- 1 <= bricks[i] <= 10, all values distinct",
      ],
      code: `int buildWall(int height, int width, vector<int>& bricks) {
    const long long MOD = 1000000007;
    vector<int> rows;                     // each row stored as its mask of internal seams
    function<void(int, int)> dfs = [&](int pos, int mask) {
        if (pos == width) { rows.push_back(mask); return; }
        for (int b : bricks)
            if (pos + b <= width) {
                int np = pos + b;
                // the seam at the far wall is not an internal seam, so do not record it
                dfs(np, np == width ? mask : mask | (1 << (np - 1)));
            }
    };
    dfs(0, 0);
    int k = rows.size();
    vector<long long> dp(k, 1), ndp;      // bottom row: each layout once
    for (int h = 1; h < height; h++) {
        ndp.assign(k, 0);
        for (int i = 0; i < k; i++)
            if (dp[i])
                for (int j = 0; j < k; j++)
                    if (!(rows[i] & rows[j])) ndp[j] = (ndp[j] + dp[i]) % MOD;   // disjoint seams
        dp = ndp;
    }
    long long ans = 0;
    for (long long v : dp) ans = (ans + v) % MOD;
    return (int)ans;
}`,
      explanation: [
        "The right profile is not the bricks in the previous row but its seam positions: a mask of width-1 bits where bit p-1 means the row has a joint p units from the left. Sturdiness is then exactly 'the two masks share no bit', a single bitwise AND.",
        "Because the brick lengths are distinct, a seam mask determines its row uniquely, so enumerating masks by DFS enumerates rows without duplicates. If lengths could repeat you would have to count layouts per mask and weight the transitions, which is a good sanity check that you understood why this shortcut is legal.",
        "Two off-by-one traps live here. The seam at position width must not be recorded, or every pair of rows would clash and the answer would be 0 for height > 1. And position 0 is not a seam either, which is why the bit index is np - 1.",
        "Rows come from compositions of width using the allowed lengths, so k <= 2^(width-1) = 512. That makes the quadratic layer step about 260k operations, times 100 layers - trivially fast, and there is no need for anything cleverer.",
        "Time: O(k^2 * height) with k <= 512, plus O(k * bricks) enumeration. Space: O(k).",
      ],
    },
    {
      name: "Artillery Positions",
      difficulty: "Hard",
      variation: "Frontier spanning two previous rows",
      link: "http://poj.org/problem?id=1185",
      question: [
        "A battlefield is a grid of N rows and M columns. Each cell is either plain ground, marked P, or mountain, marked H. Artillery units may only be placed on plain cells. A unit attacks the two cells immediately above, the two below, the two to its left and the two to its right, so two units may not be placed within a distance of 2 along the same row or the same column. Place as many units as possible and print that maximum count. The first line holds N and M, followed by N lines of M characters each.",
        "Example 1:\nInput:\n5 4\nPHPP\nPPHH\nPPPP\nPHPP\nPHHP\nOutput:\n6\nExplanation: One optimal placement is (0,0), (0,3), (1,1), (2,2), (3,0) and (3,3) using zero-based row and column indices. Every one of those cells is plain, the two pairs sharing a column are 3 rows apart, and the two pairs sharing a row are 3 columns apart.",
        "Constraints:\n- 1 <= N <= 100\n- 1 <= M <= 10",
      ],
      code: `int main() {
    ios::sync_with_stdio(false);
    cin.tie(nullptr);
    int n, m;
    cin >> n >> m;
    vector<int> plain(n, 0);
    for (int i = 0; i < n; i++) {
        string s;
        cin >> s;
        for (int j = 0; j < m; j++) if (s[j] == 'P') plain[i] |= 1 << j;
    }
    vector<int> ok;
    for (int s = 0; s < (1 << m); s++)
        if (!(s & (s << 1)) && !(s & (s << 2))) ok.push_back(s);   // row-internal range 2
    int K = ok.size();
    // dp[a][b] = best count with row i-2 using ok[a] and row i-1 using ok[b].
    vector<vector<int>> dp(K, vector<int>(K, -1));
    dp[0][0] = 0;                                   // ok[0] is the empty mask
    for (int i = 0; i < n; i++) {
        vector<vector<int>> nd(K, vector<int>(K, -1));
        for (int a = 0; a < K; a++)
            for (int b = 0; b < K; b++) {
                if (dp[a][b] < 0) continue;         // unreachable pair
                for (int c = 0; c < K; c++) {
                    if ((ok[c] & plain[i]) != ok[c]) continue;   // terrain
                    if (ok[c] & ok[b]) continue;                 // one row apart
                    if (ok[c] & ok[a]) continue;                 // two rows apart
                    int val = dp[a][b] + __builtin_popcount(ok[c]);
                    nd[b][c] = max(nd[b][c], val);
                }
            }
        dp = nd;
    }
    int ans = 0;
    for (auto& row : dp)
        for (int v : row) ans = max(ans, v);
    cout << ans << "\\n";
    return 0;
}`,
      explanation: [
        "The vertical constraint reaches two rows back, so the frontier must remember two rows, not one. The state is the pair of masks for rows i-2 and i-1. That is the general rule for profile DP: the state is whatever slice of history the constraints can still touch, and its width is the reach of the longest constraint.",
        "Only 60 of the 1024 masks for M = 10 survive the within-a-row range check, because s & (s << 1) and s & (s << 2) together forbid any two chosen columns closer than 3. Iterating over that filtered list is what makes the triple loop affordable: 60^3 is 216k per row, 21.6M overall.",
        "This is a maximisation, not a count, so unreachable states must be distinguishable from zero-valued ones. Marking them -1 and skipping them prevents a state that cannot exist from contributing a bogus optimum. Initialising the whole table to 0 instead is the usual subtle bug in optimisation profile DPs.",
        "Treating the two rows above row 0 as empty masks makes the boundary uniform, so no special-casing of i = 0 or i = 1 is needed.",
        "Time: O(N * F^3) where F is the number of legal row masks (F = 60 for M = 10). Space: O(F^2).",
      ],
    },
    {
      name: "Maximize Grid Happiness",
      difficulty: "Hard",
      variation: "Broken profile with a three-valued frontier and budgets",
      link: "https://leetcode.com/problems/maximize-grid-happiness/",
      question: [
        "You are given four integers m, n, introvertsCount and extrovertsCount describing an m x n grid and a number of introverts and extroverts. You choose how many of each to place, at most one person per cell, and you do not have to place everyone. An introvert starts with 120 happiness and an extrovert with 40. For each of the up to four side-adjacent neighbours a person has, an introvert loses 30 happiness and an extrovert gains 20 happiness - each person's own happiness is adjusted once per neighbour, independently of that neighbour's type. Return the maximum possible total happiness of the grid.",
        "Example 1:\nInput: m = 2, n = 3, introvertsCount = 1, extrovertsCount = 2\nOutput: 240\nExplanation: Place the introvert alone in one corner and the two extroverts side by side elsewhere: 120 for the isolated introvert, and 40 + 20 twice for the adjacent extroverts, giving 120 + 60 + 60 = 240.",
        "Example 2:\nInput: m = 3, n = 1, introvertsCount = 2, extrovertsCount = 1\nOutput: 260\nExplanation: Introvert, extrovert, introvert down the column: 120 - 30 for each introvert plus 40 + 20 + 20 for the extrovert, giving 90 + 90 + 80 = 260.",
        "Constraints:\n- 1 <= m, n <= 5\n- 0 <= introvertsCount, extrovertsCount <= 6",
      ],
      code: `class Solution {
    int M, N, POW3;
    vector<vector<vector<vector<int>>>> memo;
    static int adj(int t) { return t == 1 ? -30 : 20; }   // what a neighbour does to a score

    int solve(int pos, int mask, int in, int ex) {
        if (pos == M * N || (in == 0 && ex == 0)) return 0;
        int& res = memo[pos][mask][in][ex];
        if (res != -1) return res;
        int up = mask / (POW3 / 3);                  // top digit: the cell N steps back
        int left = (pos % N == 0) ? 0 : mask % 3;    // low digit: the previous cell
        int keep = (mask % (POW3 / 3)) * 3;          // drop the digit that just fell off
        int best = solve(pos + 1, keep, in, ex);     // leave this cell empty
        for (int t = 1; t <= 2; t++) {               // 1 = introvert, 2 = extrovert
            if (t == 1 && in == 0) continue;
            if (t == 2 && ex == 0) continue;
            int gain = (t == 1 ? 120 : 40);
            if (pos >= N && up) gain += adj(t) + adj(up);     // both sides of the pair change
            if (left) gain += adj(t) + adj(left);
            best = max(best, gain + solve(pos + 1, keep + t, in - (t == 1), ex - (t == 2)));
        }
        return res = best;
    }

public:
    int getMaxGridHappiness(int m, int n, int introvertsCount, int extrovertsCount) {
        M = m; N = n;
        POW3 = 1;
        for (int i = 0; i < n; i++) POW3 *= 3;
        memo.assign(m * n, vector<vector<vector<int>>>(POW3,
            vector<vector<int>>(introvertsCount + 1, vector<int>(extrovertsCount + 1, -1))));
        return solve(0, 0, introvertsCount, extrovertsCount);
    }
};
`,
      explanation: [
        "This is broken profile in its purest form: the decision is made one cell at a time, and the frontier is the last n cells in row-major order. Those cells are exactly the ones whose neighbours are not yet all decided - the cell n steps back is the one directly above the cursor, and the cell one step back is to its left. Everything older can be forgotten.",
        "The frontier is a base-3 number because a cell has three states, not two. Sliding it forward is mask % 3^(n-1) * 3 + t: shift left one digit, which pushes out the digit for the cell whose neighbours are now all settled, and append the new cell's state.",
        "Score bookkeeping is where this problem is usually lost. When two people become neighbours, both of their happiness values change, so the delta for a new placement is its own base value plus adj(newType) + adj(neighbourType) for each already-placed neighbour. Charging only the new person's side halves the interaction and gives too small an answer.",
        "Only the up and left neighbours are ever examined. That is not a simplification - every adjacent pair in the grid is an (up, current) or (left, current) pair for exactly one cursor position, so each interaction is scored exactly once.",
        "Placing nobody is legal and the counts are budgets rather than requirements, hence the explicit empty option and the early return once both budgets hit zero.",
        "Time: O(m*n * 3^n * I * E * 3) states and transitions, at most about 25 * 243 * 7 * 7 * 3. Space: O(m*n * 3^n * I * E).",
      ],
    },
  ],
};
