import type { TopicContent } from "../types";

export const awsIam: TopicContent = {
  quickSummary: [
    "AWS IAM (Identity and Access Management) controls who (authentication) can do what (authorization) on which AWS resources. Principals include IAM users (human identities with long-lived credentials), groups (collections of users sharing permissions), and roles (assumable identities for temporary access).",
    "IAM policies are JSON documents defining permissions. AWS managed policies are pre-built by AWS, customer managed policies are created by you, and inline policies are embedded directly in a user/group/role. Policies evaluate using the principle: explicit deny > explicit allow > implicit deny.",
    "IAM roles are the preferred method for granting permissions to AWS services (EC2, Lambda, ECS) and for cross-account access. Roles provide temporary credentials via STS (Security Token Service), eliminating the need for long-lived access keys.",
    "Permission boundaries set the maximum permissions a principal can have, even if their identity policies grant more. Combined with Service Control Policies (SCPs) at the AWS Organizations level, they create guardrails that prevent privilege escalation.",
    "The principle of least privilege means granting only the minimum permissions required for a task. Implement it with specific resource ARNs (not *), condition keys, and regular access review using IAM Access Analyzer and credential reports."
  ],

  detailed: [
    "## IAM Users, Groups, and Roles\n\n**IAM Users:**\n- Represent individual identities (people or applications) with permanent credentials\n- Credentials: password (console access) and/or access keys (API/CLI access)\n- Each user can have up to 2 access keys (for rotation without downtime)\n- Best practice: minimize IAM users; prefer federation with an external identity provider (Okta, Azure AD) via IAM Identity Center\n- Never use the root account for daily operations — it has unrestricted access and cannot be constrained by IAM policies\n\n**IAM Groups:**\n- Collections of IAM users — groups cannot contain other groups\n- Permissions attached to groups apply to all member users\n- A user can belong to up to 10 groups\n- Use groups to manage permissions by job function (Developers, DBAdmins, ReadOnly)\n- Groups are NOT principals — you cannot reference a group in a resource policy or assume a group\n\n**IAM Roles:**\n- Assumable identities providing temporary security credentials\n- No permanent credentials — credentials are generated by STS when the role is assumed\n- Trust policy defines WHO can assume the role (other accounts, services, federated users)\n- Permission policy defines WHAT the role can do\n- Use cases:\n  - EC2 instance profiles: grant AWS permissions to applications on EC2 without access keys\n  - Lambda execution roles: define what a Lambda function can access\n  - Cross-account access: grant access to resources in another AWS account\n  - Federation: map external identity provider groups to IAM roles\n  - Service-linked roles: pre-configured roles for AWS services to act on your behalf\n\n**When to use what:**\n- Human users: IAM Identity Center (SSO) with federated roles — not IAM users\n- Applications on AWS: IAM roles (instance profiles, task roles, execution roles)\n- Applications outside AWS: IAM roles with external identity provider federation\n- Break-glass access: dedicated IAM user with MFA, stored securely, used only in emergencies",

    "## IAM Policies Deep Dive\n\nPolicies are JSON documents that define permissions. Understanding policy types and evaluation is essential.\n\n**Policy structure:**\n```json\n{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [{\n    \"Effect\": \"Allow\" or \"Deny\",\n    \"Action\": [\"service:action\"],\n    \"Resource\": [\"arn:aws:...\"],\n    \"Condition\": { \"operator\": { \"key\": \"value\" } }\n  }]\n}\n```\n\n**Policy types (in evaluation order):**\n1. **Service Control Policies (SCPs):** Organization-level guardrails. Apply to all principals in the account. Cannot grant permissions, only restrict them\n2. **Permission boundaries:** Maximum permissions for IAM users and roles. Cannot grant, only restrict\n3. **Identity-based policies:** Attached to users, groups, or roles. These grant permissions\n   - AWS managed: created and maintained by AWS (e.g., AmazonS3ReadOnlyAccess)\n   - Customer managed: created by you, reusable across principals\n   - Inline: embedded directly in a single user, group, or role\n4. **Resource-based policies:** Attached to resources (S3 bucket policies, SQS queue policies, KMS key policies). Can grant cross-account access without assuming a role\n5. **Session policies:** Passed when assuming a role via STS, further restricting the session\n\n**Policy evaluation logic:**\n- Start with implicit deny (everything is denied by default)\n- Evaluate all applicable policies\n- Any explicit deny in any policy = denied (deny always wins)\n- If no explicit deny, check for explicit allow\n- If no explicit allow = denied (implicit deny)\n- For cross-account: BOTH the identity policy (source account) AND resource policy (target account) must allow\n\n**Condition keys (powerful restrictions):**\n- `aws:SourceIp`: restrict by IP range\n- `aws:MultiFactorAuthPresent`: require MFA\n- `aws:RequestedRegion`: restrict to specific regions\n- `aws:PrincipalTag`: restrict based on user/role tags\n- `s3:prefix`: restrict S3 operations to specific key prefixes",

    "## STS and Temporary Credentials\n\nAWS Security Token Service (STS) provides temporary, limited-privilege credentials.\n\n**How STS works:**\n- A principal calls `sts:AssumeRole` (or similar API)\n- STS returns temporary credentials: access key, secret key, and session token\n- Credentials expire after a configurable duration (15 minutes to 12 hours for roles, up to 36 hours for federation)\n- The temporary credentials carry the permissions of the assumed role\n\n**STS API calls:**\n- `AssumeRole`: assume a role in the same or different account\n- `AssumeRoleWithSAML`: assume a role using SAML assertion from an identity provider\n- `AssumeRoleWithWebIdentity`: assume a role using an OIDC token (used by EKS pods, mobile apps)\n- `GetSessionToken`: get temporary credentials for an IAM user with MFA\n- `GetFederationToken`: create temporary credentials for federated users\n\n**Cross-account access pattern:**\n1. Account B creates a role with a trust policy allowing Account A\n2. Account A's user/role has permission to call `sts:AssumeRole` on Account B's role\n3. Account A assumes the role, receives temporary credentials scoped to Account B\n4. Uses temporary credentials to access Account B's resources\n\n**Instance profiles and service roles:**\n- EC2 instance profile: role automatically provides temporary credentials via instance metadata (169.254.169.254)\n- ECS task role: each task gets its own role credentials via the task credential endpoint\n- Lambda execution role: Lambda assumes the role for each invocation\n- These eliminate the need to store access keys on instances or in code\n\n**Security advantages of temporary credentials:**\n- Auto-expire — no risk of leaked long-lived keys\n- Can be scoped to specific permissions for the session\n- Auditable — CloudTrail logs every AssumeRole call\n- Easily revocable by modifying the role's trust policy",

    "## Permission Boundaries and SCPs\n\nThese are guardrail mechanisms that limit the maximum permissions a principal can have.\n\n**Permission Boundaries:**\n- An advanced IAM feature that sets the maximum permissions an IAM user or role can receive\n- The effective permissions are the INTERSECTION of identity policies and the permission boundary\n- If a boundary allows s3:* and the identity policy allows s3:GetObject and ec2:*, the effective permission is only s3:GetObject\n- Cannot be applied to groups, only to users and roles\n- Key use case: delegation. Allow a developer to create IAM roles but only with a specific permission boundary, preventing privilege escalation\n\n**Service Control Policies (SCPs):**\n- Applied at the AWS Organizations level to OUs (Organizational Units) or accounts\n- Set the maximum permissions for all principals in the affected accounts\n- Cannot grant permissions — only restrict what identity policies can grant\n- Do NOT affect the management account (root account of the organization)\n- Common SCPs:\n  - Deny access to specific regions\n  - Deny disabling CloudTrail or GuardDuty\n  - Deny creating IAM users with console access (force SSO)\n  - Require encryption for specific services\n  - Deny leaving the organization\n\n**Effective permissions formula:**\n```\nEffective = SCP intersection Permission Boundary intersection Identity Policy\n```\nFor resource-based policies, they can grant access independently (they are additive for same-account access).\n\n**Guardrail strategy:**\n- SCPs: organization-wide guardrails (prevent disabling security services, restrict regions)\n- Permission boundaries: delegated administration (allow teams to create roles within limits)\n- Identity policies: actual permission grants for day-to-day work\n- Resource policies: cross-account access and service-specific controls",

    "## Least Privilege and Access Review\n\nImplementing least privilege is an ongoing process, not a one-time configuration.\n\n**Implementing least privilege:**\n- Start with zero permissions and add only what is required\n- Use specific resource ARNs instead of wildcards: `arn:aws:s3:::my-bucket/*` not `*`\n- Use conditions to narrow permissions: MFA required, source IP restriction, time-based\n- Avoid managed policies that are too broad (e.g., AmazonS3FullAccess when only read is needed)\n- Use IAM policy simulator to test policies before applying\n\n**IAM Access Analyzer:**\n- Identifies resources shared with external entities (S3 buckets, IAM roles, KMS keys, Lambda functions, SQS queues)\n- Policy generation: analyzes CloudTrail logs to generate least-privilege policies based on actual API activity\n- Policy validation: checks policies for errors and security warnings\n- Unused access analysis: identifies unused roles, access keys, and permissions\n\n**Credential report and access advisor:**\n- Credential report: CSV listing all IAM users and their credential status (password age, MFA, access key age, last used)\n- Access advisor: shows services each user/role has accessed and when, helping identify unused permissions\n- Review both regularly (monthly) to identify and remove stale access\n\n**Access key hygiene:**\n- Rotate access keys every 90 days (or shorter per compliance requirements)\n- Never embed keys in source code — use Secrets Manager, Parameter Store, or environment variables in CI/CD\n- Delete unused access keys identified by credential reports\n- Prefer IAM roles over access keys wherever possible\n- Enable MFA for all human users, enforce with IAM policy conditions\n\n**MFA best practices:**\n- Hardware MFA tokens for root account and highly privileged users\n- Virtual MFA (TOTP apps) for regular users\n- Enforce MFA via IAM policies using `aws:MultiFactorAuthPresent` condition\n- Use MFA for critical operations: deleting production resources, modifying IAM policies, accessing billing"
  ],

  interviewQA: [
    {
      q: "What is the difference between IAM roles and IAM users?",
      a: "IAM users have permanent credentials (passwords and access keys) tied to a specific person or application. Roles have no permanent credentials — when assumed, STS issues temporary credentials that expire automatically. Roles are assumable by services (EC2, Lambda), other accounts, or federated users. Key differences: (1) Roles provide temporary credentials, eliminating the risk of leaked long-lived keys. (2) Roles can be assumed by multiple principals (services, users, accounts). (3) Roles are the recommended way to grant permissions to AWS services and for cross-account access. Best practice is to minimize IAM users and use roles with federation through IAM Identity Center.",
      followUps: ["How does an EC2 instance get role credentials?", "What is the trust policy on a role?"]
    },
    {
      q: "Explain how IAM policy evaluation works when multiple policies apply.",
      a: "IAM evaluates all applicable policies together. The logic is: (1) Everything starts as implicitly denied. (2) The effective permissions are the intersection of SCPs, permission boundaries, and the union of identity and resource policies. (3) An explicit deny in ANY policy overrides any allow — deny always wins. For same-account access: evaluate SCPs (if applicable), permission boundaries (if set), then check identity policies for an allow. For cross-account: both the source account's identity policy and the target account's resource policy must allow the action (unless using resource-based policies which can be additive). The common mistake is thinking multiple allow statements are multiplicative — they are not. An allow in one policy and a deny in another results in denied.",
      followUps: ["How do resource-based policies differ in evaluation?", "What is the difference between implicit and explicit deny?"]
    },
    {
      q: "How would you implement a delegation model where developers can create IAM roles but cannot escalate their own privileges?",
      a: "Use permission boundaries. (1) Create a permission boundary policy that defines the maximum permissions any developer-created role can have (e.g., S3 and DynamoDB access only). (2) Grant developers iam:CreateRole and iam:PutRolePolicy permissions, but add a condition requiring they attach the permission boundary: `iam:PermissionsBoundary` condition key must match the boundary ARN. (3) This means any role they create is automatically limited by the boundary, regardless of what policies they attach. (4) Additionally, their own permissions should not include iam:DeleteRolePermissionsBoundary to prevent them from removing the boundary. This prevents privilege escalation because developers cannot create roles with more permissions than the boundary allows.",
      followUps: ["What are SCPs and how do they complement boundaries?", "Can permission boundaries be applied to groups?"]
    },
    {
      q: "How do you audit and reduce IAM permissions to enforce least privilege?",
      a: "Multi-step approach: (1) Enable IAM Access Analyzer to identify resources with external access and generate least-privilege policies from CloudTrail activity. (2) Review credential reports monthly — identify users with unused access keys, missing MFA, or old passwords. (3) Use Access Advisor to see which services each role/user actually uses and remove unused permissions. (4) Start new roles with minimal permissions and add as needed, rather than starting broad. (5) Replace wildcard resources in policies with specific ARNs. (6) Implement SCPs to prevent dangerous actions organization-wide. (7) Set up automated alerts for IAM changes using CloudTrail and EventBridge. The key is making this a continuous process, not a one-time audit."
    }
  ],

  mcqs: [
    {
      q: "An IAM policy has an explicit Allow on s3:* and another policy has an explicit Deny on s3:DeleteObject. What happens when the user tries to delete an S3 object?",
      options: ["Allowed — the Allow policy takes precedence", "Denied — explicit Deny always overrides Allow", "Allowed — the most recent policy wins", "Error — conflicting policies are invalid"],
      answerIndex: 1,
      explanation: "In IAM policy evaluation, an explicit Deny ALWAYS overrides any Allow, regardless of where the deny appears. This is fundamental to IAM security."
    },
    {
      q: "Which is the recommended way to grant an EC2 instance access to S3?",
      options: ["Store access keys in environment variables on the instance", "Create an IAM user and embed keys in the application code", "Attach an IAM role via an instance profile", "Use the root account credentials"],
      answerIndex: 2,
      explanation: "IAM roles via instance profiles provide temporary credentials automatically rotated by STS. This eliminates the risk of leaked long-lived access keys and is the AWS best practice."
    },
    {
      q: "Service Control Policies (SCPs) can:",
      options: [
        "Grant additional permissions beyond identity policies",
        "Restrict the maximum permissions available in member accounts",
        "Override the management account's permissions",
        "Replace IAM policies entirely"
      ],
      answerIndex: 1,
      explanation: "SCPs set the maximum permissions ceiling for all principals in affected accounts. They cannot grant permissions, only restrict what identity policies can allow. They do not affect the management account."
    },
    {
      q: "What is the purpose of a permission boundary?",
      options: [
        "Define the minimum permissions a role must have",
        "Set the maximum permissions a user or role can receive regardless of identity policies",
        "Create a firewall around specific AWS resources",
        "Limit the number of API calls a principal can make"
      ],
      answerIndex: 1,
      explanation: "Permission boundaries cap the maximum permissions. Effective permissions are the intersection of the boundary and identity policies — even if an identity policy grants broader access, the boundary limits it."
    },
    {
      q: "Which STS API would you use for cross-account access?",
      options: ["GetSessionToken", "AssumeRole", "GetFederationToken", "DecodeAuthorizationMessage"],
      answerIndex: 1,
      explanation: "AssumeRole allows a principal in one account to assume a role in another account, receiving temporary credentials scoped to the target role's permissions."
    }
  ],

  flashcards: [
    { front: "IAM Policy Evaluation Order", back: "1. Explicit Deny (always wins) 2. SCPs (organization guardrails) 3. Permission Boundaries (max ceiling) 4. Identity Policies (actual grants) 5. Resource Policies (additive for same-account). Implicit deny if no explicit allow." },
    { front: "IAM Role vs. IAM User", back: "User: permanent credentials (password, access keys), for specific identity. Role: no permanent credentials, temporary via STS, assumable by services/accounts/federated users. Prefer roles over users." },
    { front: "Instance Profile", back: "Container for an IAM role attached to an EC2 instance. Provides temporary credentials via instance metadata (169.254.169.254) without storing access keys." },
    { front: "Permission Boundary", back: "Advanced feature setting maximum permissions ceiling for users/roles. Effective permissions = intersection of boundary and identity policies. Used for safe delegation." },
    { front: "SCP", back: "Service Control Policy — AWS Organizations guardrail restricting maximum permissions in member accounts. Cannot grant, only deny. Does not affect management account." },
    { front: "STS AssumeRole", back: "API that returns temporary credentials (access key, secret key, session token) for a specified role. Credentials expire after configurable duration (15 min to 12 hours)." },
    { front: "IAM Access Analyzer", back: "Tool that identifies resources shared externally, generates least-privilege policies from CloudTrail, validates policies, and finds unused access. Essential for ongoing least-privilege enforcement." },
    { front: "Least Privilege Principle", back: "Grant only minimum permissions required. Use specific ARNs (not *), conditions (MFA, IP, region), and regular access reviews. Start restrictive and add, never start broad and reduce." }
  ],

  glossary: [
    { term: "IAM", definition: "Identity and Access Management — AWS service for controlling authentication (who) and authorization (what they can do) for AWS resources." },
    { term: "IAM Role", definition: "An assumable identity with temporary credentials provided by STS. Used by services, cross-account access, and federated users instead of long-lived access keys." },
    { term: "STS", definition: "Security Token Service — AWS service that provides temporary, limited-privilege security credentials for IAM roles and federated users." },
    { term: "SCP", definition: "Service Control Policy — organization-level policy that sets maximum permission guardrails for all principals in member accounts." },
    { term: "Permission Boundary", definition: "IAM feature that sets the maximum permissions a user or role can receive, regardless of what their identity policies grant." },
    { term: "Managed Policy", definition: "Standalone IAM policy that can be attached to multiple users, groups, or roles. AWS managed (maintained by AWS) or customer managed (created by you)." },
    { term: "Resource Policy", definition: "Policy attached directly to a resource (S3 bucket, SQS queue, KMS key) that specifies who can access it, including cross-account principals." },
    { term: "IAM Access Analyzer", definition: "AWS service that identifies external resource sharing, generates least-privilege policies from CloudTrail, and detects unused access." }
  ]
};
