import type { TopicContent } from "../types";

export const compilersInterpreters: TopicContent = {
  quickSummary: [
    "A compiler translates an entire source program into machine code (or another target language) before execution; an interpreter executes the source directly, statement by statement.",
    "Compilation phases: lexing (tokens) -> parsing (AST) -> semantic analysis (types/scopes) -> IR generation -> optimisation -> code generation.",
    "JIT (Just-In-Time) compilers blend both approaches: they interpret or compile to bytecode first, then compile hot paths to native code at runtime for peak performance.",
    "Modern language implementations often combine techniques — Python compiles to bytecode interpreted by a VM, Java compiles to bytecode then JIT-compiles, and Rust/C compile fully ahead of time.",
  ],
  detailed: [
    "The front end of a compiler handles lexing (scanning), which breaks source text into tokens — identifiers, keywords, literals, operators, and punctuation. A lexer is typically implemented as a finite automaton (often generated from regular expressions by tools like Flex or re2c). Whitespace and comments are usually discarded. The output is a flat stream of tokens with position metadata for error reporting.",
    "Parsing takes the token stream and builds an Abstract Syntax Tree (AST) according to the language's context-free grammar. Recursive-descent parsers (LL) are simple to write by hand; bottom-up parsers (LR, LALR) handle a wider class of grammars and are commonly generated by tools like Yacc/Bison. Operator precedence and associativity are encoded in the grammar or handled by Pratt parsing. The AST strips away syntactic sugar and concrete syntax, leaving only the structural meaning of the program.",
    "Semantic analysis walks the AST to enforce rules that cannot be captured by a context-free grammar: type checking, scope resolution, overload resolution, definite assignment, lifetime analysis, and more. This phase populates symbol tables mapping names to their declarations, types, and memory locations. Many modern languages perform type inference here (Hindley-Milner in ML/Haskell, local inference in Rust/Kotlin). Errors caught at this stage — type mismatches, use of undeclared variables, visibility violations — are the most common compiler errors developers encounter.",
    "The middle end lowers the AST into an Intermediate Representation (IR) — a platform-independent form suitable for analysis and optimisation. LLVM IR, GCC's GIMPLE/RTL, and JVM bytecode are well-known examples. Optimisation passes then transform the IR: constant folding, dead-code elimination, common-subexpression elimination, loop-invariant code motion, inlining, vectorisation, and register allocation. Each pass is ideally a composable IR-to-IR transformation.",
    "The back end performs code generation: instruction selection (mapping IR operations to target ISA instructions), register allocation (graph colouring or linear scan), and instruction scheduling (reordering to exploit CPU pipelines). For AOT compilers, the output is object files linked into an executable. JIT compilers like V8's TurboFan or HotSpot's C2 perform code generation at runtime, using profiling data (type feedback, branch frequencies) to make better optimisation decisions than any static compiler could.",
  ],
  deepDive: [
    "Bytecode virtual machines sit between pure interpretation and full compilation. The compiler emits compact, portable bytecode instructions for a virtual stack or register machine. The VM's interpreter loop dispatches each instruction — a tight switch/case or computed-goto loop. CPython, the JVM, the CLR, Lua, and Ruby all use this architecture. The bytecode level is where many optimisations like inline caching (for dynamic dispatch) and hidden classes (V8) are implemented.",
    "JIT compilation uses runtime profiling to identify hot code paths and compiles them to optimised native code. Tiered compilation (used by HotSpot and .NET) starts with interpretation or a quick baseline compiler, then promotes frequently-executed methods to an optimising compiler. Speculative optimisation assumes observed types and branch patterns will continue; if assumptions are violated, the JIT deoptimises — falling back to interpreted or baseline code and recompiling with updated profiles. This on-stack replacement (OSR) mechanism is critical for long-running loops.",
    "Whole-program and link-time optimisation (LTO/WPO) break the traditional separate-compilation model. Instead of optimising each translation unit in isolation, the compiler sees all modules at once and can inline across file boundaries, devirtualise calls, and eliminate dead code globally. LLVM's ThinLTO scales this to large codebases by computing a summary graph per module, then performing cross-module passes selectively. The trade-off is longer build times, but the resulting binaries can be significantly smaller and faster.",
    "Garbage collection, while not strictly a compiler phase, is tightly coupled with the runtime a compiler targets. Generational collectors (JVM G1, .NET GC) partition the heap by object age, collecting the young generation frequently and cheaply. Write barriers, card tables, and safepoints are all concepts the compiler must emit code for. Languages with manual memory management (C, C++, Rust's ownership model) move this burden to the programmer or type system, eliminating GC pauses but requiring compile-time analysis of lifetimes and aliasing.",
  ],
  code: [
    {
      language: "python",
      caption: "A minimal recursive-descent parser for arithmetic expressions",
      source: `import re
from dataclasses import dataclass
from typing import Union

# --- Lexer ---
TOKEN_SPEC = [
    ("NUM",   r"\\d+(\\.\\d*)?"),
    ("PLUS",  r"\\+"),
    ("MINUS", r"-"),
    ("MUL",   r"\\*"),
    ("DIV",   r"/"),
    ("LPAREN", r"\\("),
    ("RPAREN", r"\\)"),
    ("SKIP",  r"[ \\t]+"),
]
TOKEN_RE = re.compile("|".join(f"(?P<{name}>{pat})" for name, pat in TOKEN_SPEC))

def tokenize(text):
    tokens = []
    for m in TOKEN_RE.finditer(text):
        kind = m.lastgroup
        if kind != "SKIP":
            tokens.append((kind, m.group()))
    return tokens

# --- AST Nodes ---
@dataclass
class Num:
    value: float

@dataclass
class BinOp:
    op: str
    left: "Expr"
    right: "Expr"

Expr = Union[Num, BinOp]

# --- Recursive-Descent Parser (handles precedence) ---
class Parser:
    def __init__(self, tokens):
        self.tokens = tokens
        self.pos = 0

    def peek(self):
        return self.tokens[self.pos] if self.pos < len(self.tokens) else None

    def consume(self, expected=None):
        tok = self.tokens[self.pos]
        if expected and tok[0] != expected:
            raise SyntaxError(f"Expected {expected}, got {tok}")
        self.pos += 1
        return tok

    def parse_expr(self) -> Expr:          # + and - (lowest precedence)
        left = self.parse_term()
        while self.peek() and self.peek()[0] in ("PLUS", "MINUS"):
            op = self.consume()[1]
            left = BinOp(op, left, self.parse_term())
        return left

    def parse_term(self) -> Expr:          # * and /
        left = self.parse_factor()
        while self.peek() and self.peek()[0] in ("MUL", "DIV"):
            op = self.consume()[1]
            left = BinOp(op, left, self.parse_factor())
        return left

    def parse_factor(self) -> Expr:        # numbers and parenthesised exprs
        tok = self.peek()
        if tok[0] == "NUM":
            self.consume()
            return Num(float(tok[1]))
        elif tok[0] == "LPAREN":
            self.consume("LPAREN")
            node = self.parse_expr()
            self.consume("RPAREN")
            return node
        raise SyntaxError(f"Unexpected token: {tok}")

# --- Tree-walking interpreter ---
def evaluate(node: Expr) -> float:
    if isinstance(node, Num):
        return node.value
    l, r = evaluate(node.left), evaluate(node.right)
    return {"+": l + r, "-": l - r, "*": l * r, "/": l / r}[node.op]

# Usage
tokens = tokenize("3 + 4 * (2 - 1)")
tree = Parser(tokens).parse_expr()
print(evaluate(tree))  # 7.0`,
    },
    {
      language: "c",
      caption: "Bytecode compiler and stack-based VM for integer arithmetic",
      source: `#include <stdio.h>
#include <stdlib.h>

typedef enum { OP_PUSH, OP_ADD, OP_SUB, OP_MUL, OP_DIV, OP_HALT } OpCode;

typedef struct { OpCode op; int operand; } Instruction;

/* Simple stack-based VM */
int vm_run(Instruction *code) {
    int stack[256];
    int sp = -1;
    int ip = 0;

    for (;;) {
        Instruction instr = code[ip++];
        switch (instr.op) {
            case OP_PUSH: stack[++sp] = instr.operand; break;
            case OP_ADD:  { int b = stack[sp--]; stack[sp] += b; } break;
            case OP_SUB:  { int b = stack[sp--]; stack[sp] -= b; } break;
            case OP_MUL:  { int b = stack[sp--]; stack[sp] *= b; } break;
            case OP_DIV:  { int b = stack[sp--]; stack[sp] /= b; } break;
            case OP_HALT: return stack[sp];
        }
    }
}

int main(void) {
    /* Bytecode for: 3 + 4 * 2  =>  PUSH 3, PUSH 4, PUSH 2, MUL, ADD */
    Instruction program[] = {
        {OP_PUSH, 3},
        {OP_PUSH, 4},
        {OP_PUSH, 2},
        {OP_MUL, 0},
        {OP_ADD, 0},
        {OP_HALT, 0},
    };
    printf("Result: %d\\n", vm_run(program));  /* 11 */
    return 0;
}`,
    },
  ],
  diagrams: [
    {
      title: "Compiler Pipeline",
      kind: "flow",
      caption:
        "Source code flows through lexing, parsing, semantic analysis, IR generation, optimisation passes, and code generation to produce an executable.",
    },
    {
      title: "JIT Compilation Architecture",
      kind: "architecture",
      caption:
        "Bytecode interpreter with profiling, tiered compilation (baseline -> optimising), on-stack replacement, and deoptimisation feedback loop.",
    },
  ],
  animations: [
    {
      title: "Compiling '3 + 4 * 2' step by step",
      steps: [
        {
          label: "Lexing",
          detail:
            "The source string '3 + 4 * 2' is scanned left to right, producing tokens: [NUM(3), PLUS, NUM(4), MUL, NUM(2)].",
        },
        {
          label: "Parsing",
          detail:
            "The parser builds an AST respecting operator precedence: BinOp(+, Num(3), BinOp(*, Num(4), Num(2))). Multiplication binds tighter than addition.",
        },
        {
          label: "Semantic analysis",
          detail:
            "The type checker verifies all operands are numeric. Symbol resolution confirms no undefined variables (this expression has none).",
        },
        {
          label: "IR generation",
          detail:
            "The AST is lowered to stack-based bytecode: PUSH 3, PUSH 4, PUSH 2, MUL, ADD — a postfix (reverse-Polish) representation.",
        },
        {
          label: "Optimisation",
          detail:
            "Constant folding recognises 4 * 2 = 8 at compile time, reducing the bytecode to: PUSH 3, PUSH 8, ADD (or even PUSH 11).",
        },
        {
          label: "Code generation / execution",
          detail:
            "The back end emits native instructions (e.g., mov eax, 11; ret) or the VM executes the bytecode on a virtual stack to produce the result 11.",
        },
      ],
    },
  ],
  comparison: {
    columns: ["Aspect", "Compiler (AOT)", "Interpreter", "JIT Compiler"],
    rows: [
      [
        "When translation happens",
        "Before execution (build time)",
        "During execution (line by line)",
        "During execution (hot paths compiled at runtime)",
      ],
      [
        "Startup speed",
        "Slow (must compile first)",
        "Fast (runs immediately)",
        "Medium (interpret first, compile later)",
      ],
      [
        "Peak performance",
        "High (fully optimised ahead of time)",
        "Low (interpretation overhead per instruction)",
        "Highest (uses runtime profile data for optimisation)",
      ],
      [
        "Error detection",
        "At compile time (many errors caught early)",
        "At runtime (errors found when line executes)",
        "Mix (some at compile, some at runtime)",
      ],
      [
        "Portability",
        "Platform-specific binary",
        "Source runs anywhere interpreter exists",
        "Bytecode portable; JIT targets host platform",
      ],
      [
        "Examples",
        "GCC, Clang/LLVM, Rust, Go",
        "CPython, Ruby MRI, Bash",
        "V8 (JS), HotSpot (Java), PyPy",
      ],
    ],
  },
  interviewQA: [
    {
      q: "Walk me through what happens when you compile a C file into an executable.",
      a: "The preprocessor expands macros and includes. The lexer tokenises the result. The parser builds an AST per translation unit. Semantic analysis checks types and resolves symbols. The compiler generates IR (e.g., LLVM IR), runs optimisation passes, then emits assembly. The assembler converts assembly to relocatable object files. Finally, the linker resolves cross-module symbols and produces the executable.",
      followUps: [
        "What is the difference between static and dynamic linking?",
        "Where does link-time optimisation (LTO) fit into this pipeline?",
        "What are translation units and how do they affect compilation speed?",
      ],
    },
    {
      q: "What is the difference between an AST and a parse tree (CST)?",
      a: "A parse tree (concrete syntax tree) includes every grammar production — parentheses, semicolons, syntactic sugar — mirroring the grammar one-to-one. An AST abstracts away this syntactic noise, keeping only the semantically meaningful structure. For example, the parentheses in '(a + b)' appear in the CST but not the AST, because the tree structure already encodes grouping.",
      followUps: [
        "Why might a language tool (like a formatter) prefer a CST over an AST?",
        "How do lossless syntax trees (like Roslyn or rust-analyzer) differ from traditional ASTs?",
      ],
    },
    {
      q: "How does a JIT compiler achieve better performance than an AOT compiler?",
      a: "A JIT has access to runtime information that a static compiler lacks: actual types flowing through polymorphic call sites, branch frequencies, loop trip counts, and loaded classes. It can speculatively inline virtual calls, eliminate type checks for monomorphic sites, and generate code specialised to the observed data. If assumptions break, the JIT deoptimises and recompiles. AOT compilers must be conservative since they lack this runtime profile.",
      followUps: [
        "What is on-stack replacement (OSR) and why is it needed?",
        "What are the downsides of JIT compilation?",
        "How does profile-guided optimisation (PGO) bring some JIT benefits to AOT compilers?",
      ],
    },
    {
      q: "Explain how garbage collection interacts with the compiler and runtime.",
      a: "The compiler must emit write barriers (code that notifies the GC when a reference is updated), generate stack maps so the GC can find root pointers, and insert safepoint checks where the GC can pause the mutator. The runtime implements the collector — mark-and-sweep, copying, or generational — and coordinates pauses. Languages like Go use a concurrent tri-colour collector with very short pauses; Java's G1 and ZGC aim for sub-millisecond pauses on large heaps.",
      followUps: [
        "What is the difference between a tracing GC and reference counting?",
        "How does Rust avoid GC entirely?",
      ],
    },
  ],
  followUps: [
    "How do LLVM's architecture and IR design enable multi-language, multi-target compilation?",
    "What are the trade-offs between tree-walking interpreters, bytecode VMs, and native compilation?",
    "How do modern type systems (dependent types, linear types) affect the semantic analysis phase?",
  ],
  mcqs: [
    {
      q: "Which compilation phase converts source text into a stream of tokens?",
      options: [
        "Parsing",
        "Lexical analysis (lexing/scanning)",
        "Semantic analysis",
        "Code generation",
      ],
      answerIndex: 1,
      explanation:
        "Lexical analysis (scanning) reads characters and groups them into tokens — identifiers, keywords, literals, and operators. Parsing then organises tokens into a tree.",
    },
    {
      q: "What kind of grammar do most programming language parsers use?",
      options: [
        "Regular grammar",
        "Context-free grammar",
        "Context-sensitive grammar",
        "Unrestricted grammar",
      ],
      answerIndex: 1,
      explanation:
        "Parsers use context-free grammars (CFGs), processed by LL or LR parsers. Lexers use regular grammars. Some language features (like indentation sensitivity) require context-sensitive extensions.",
    },
    {
      q: "Which optimisation replaces 'x = 3 * 4' with 'x = 12' at compile time?",
      options: [
        "Dead-code elimination",
        "Loop unrolling",
        "Constant folding",
        "Register allocation",
      ],
      answerIndex: 2,
      explanation:
        "Constant folding evaluates expressions with known constant operands at compile time, replacing them with the result.",
    },
    {
      q: "In a JIT compiler, what happens during deoptimisation?",
      options: [
        "The JIT produces more aggressive native code",
        "The runtime falls back from optimised native code to interpreted/baseline code",
        "The compiler removes dead code",
        "The garbage collector reclaims JIT-compiled code",
      ],
      answerIndex: 1,
      explanation:
        "Deoptimisation occurs when a speculative assumption (e.g., a monomorphic call site) is invalidated. The runtime discards the optimised code and reverts to a less optimised or interpreted version, then may recompile with updated profile data.",
    },
    {
      q: "What is the primary advantage of an Intermediate Representation (IR)?",
      options: [
        "It makes programs run faster at runtime",
        "It decouples the front end (language-specific) from the back end (target-specific)",
        "It eliminates the need for a lexer",
        "It replaces the AST entirely",
      ],
      answerIndex: 1,
      explanation:
        "An IR provides a common language-independent, target-independent representation. Multiple language front ends can compile to the same IR, and multiple back ends can generate code from it — this is the design philosophy behind LLVM.",
    },
  ],
  exercises: [
    "Extend the recursive-descent parser above to support unary minus (e.g., '-3 + 4') and exponentiation with right associativity (e.g., '2 ^ 3 ^ 2' = 512).",
    "Write a lexer and parser for a simple JSON subset (objects, arrays, strings, numbers, booleans, null) and output the parsed data structure.",
    "Implement three constant-folding and dead-code elimination passes over an AST for arithmetic expressions. Measure the before/after instruction count.",
    "Build a bytecode compiler and stack-based VM for a tiny language with variables, if/else, and while loops. Support at least integer arithmetic and boolean conditions.",
  ],
  flashcards: [
    {
      front: "What does a lexer (scanner) do?",
      back: "It reads source characters and groups them into tokens — the smallest meaningful units like identifiers, keywords, literals, and operators.",
    },
    {
      front: "AST vs CST (parse tree)",
      back: "A CST mirrors the grammar exactly, including all syntactic details. An AST abstracts away syntax (parentheses, semicolons) and retains only semantic structure.",
    },
    {
      front: "What is an Intermediate Representation (IR)?",
      back: "A language-independent and (usually) target-independent form of a program used for analysis and optimisation. Examples: LLVM IR, JVM bytecode, GCC GIMPLE.",
    },
    {
      front: "Name three common compiler optimisations.",
      back: "Constant folding (evaluate compile-time constants), dead-code elimination (remove unreachable code), and inlining (replace function calls with the function body).",
    },
    {
      front: "JIT vs AOT compilation",
      back: "AOT compiles before execution (longer build, fast startup). JIT compiles at runtime using profiling data (fast startup, peak performance after warm-up).",
    },
    {
      front: "What is register allocation?",
      back: "The process of mapping an unbounded number of IR variables to a finite number of CPU registers. Commonly solved via graph colouring or linear scan algorithms.",
    },
    {
      front: "What is deoptimisation?",
      back: "When a JIT's speculative assumption is violated, the runtime discards optimised code and falls back to interpreted or baseline-compiled code, then may recompile.",
    },
    {
      front: "What is a symbol table?",
      back: "A data structure built during semantic analysis that maps identifiers to their declarations, types, scopes, and memory locations.",
    },
  ],
  revisionNotes: [
    "Compiler pipeline: Source -> Tokens (lexer) -> AST (parser) -> Annotated AST (semantic analysis) -> IR -> Optimised IR -> Machine code (codegen).",
    "Lexers use regular expressions / finite automata. Parsers use context-free grammars (LL for top-down, LR for bottom-up).",
    "Semantic analysis catches errors that grammars cannot: type mismatches, undeclared variables, scope violations. It builds and queries symbol tables.",
    "IR decouples front ends from back ends: N languages x M targets = N + M compilers instead of N x M. This is LLVM's key insight.",
    "JIT compilers use speculative optimisation with deoptimisation as a safety net. Profile-guided optimisation (PGO) brings similar benefits to AOT.",
    "Register allocation is NP-hard in general but solved well in practice by graph colouring (Chaitin) or linear scan (for JIT speed).",
  ],
  cheatSheet: [
    "Lexer: source chars -> tokens (regex/DFA). Parser: tokens -> AST (LL/LR/Pratt).",
    "Semantic analysis: type checking, scope resolution, symbol tables. Catches errors grammar cannot express.",
    "IR examples: LLVM IR (SSA form), JVM bytecode (stack-based), GCC GIMPLE (tree-based).",
    "Key optimisations: constant folding, DCE, CSE, inlining, loop-invariant code motion, vectorisation.",
    "AOT: compile once, run fast. JIT: interpret first, compile hot paths with profile data. Tiered: combine both.",
    "GC interaction: compiler emits write barriers, safepoints, and stack maps so the collector can find roots.",
  ],
  resources: [
    {
      label: "Crafting Interpreters (Robert Nystrom)",
      kind: "book",
      note: "Free online book walking through two complete interpreters: a tree-walker in Java and a bytecode VM in C.",
    },
    {
      label: "Engineering a Compiler (Cooper & Torczon)",
      kind: "book",
      note: "Comprehensive compiler textbook covering front end, optimisation, and code generation with practical algorithms.",
    },
    {
      label: "LLVM Tutorial: Kaleidoscope",
      kind: "docs",
      note: "Official LLVM tutorial building a simple language front end that compiles to LLVM IR with JIT support.",
    },
    {
      label: "V8 Blog — TurboFan JIT Design",
      kind: "article",
      note: "Technical articles on V8's optimising compiler, speculative optimisation, and deoptimisation mechanisms.",
    },
    {
      label: "github.com/nickel-lang/nickel",
      kind: "repo",
      note: "A well-structured modern language implementation in Rust with clear lexer/parser/evaluator separation — good for study.",
    },
  ],
  glossary: [
    {
      term: "Lexer (Scanner)",
      definition:
        "The compiler phase that breaks source text into a sequence of tokens using regular expressions or a finite automaton.",
    },
    {
      term: "Abstract Syntax Tree (AST)",
      definition:
        "A tree representation of a program's syntactic structure, stripped of concrete syntax details like parentheses and delimiters.",
    },
    {
      term: "Semantic Analysis",
      definition:
        "The phase that enforces context-sensitive rules — type checking, scope resolution, and other constraints beyond what the grammar captures.",
    },
    {
      term: "Intermediate Representation (IR)",
      definition:
        "A platform-independent program representation used between the front end and back end for analysis and optimisation.",
    },
    {
      term: "JIT (Just-In-Time) Compilation",
      definition:
        "Compilation that occurs at runtime, translating bytecode or IR to native code using profiling data for optimisation.",
    },
    {
      term: "AOT (Ahead-Of-Time) Compilation",
      definition:
        "Compilation that translates source code to native machine code before execution, as in traditional C/C++/Rust compilers.",
    },
    {
      term: "Constant Folding",
      definition:
        "A compiler optimisation that evaluates expressions with compile-time-known operands, replacing them with the result.",
    },
    {
      term: "Deoptimisation",
      definition:
        "The process by which a JIT compiler discards speculatively optimised code when runtime assumptions are violated, falling back to a safer execution mode.",
    },
  ],
};
