import type { TopicContent } from "../types";

export const consumersGroups: TopicContent = {
  quickSummary: [
    "A Kafka consumer group is a set of consumers that cooperatively consume a topic, with each partition assigned to exactly one consumer in the group, enabling parallel processing.",
    "Offsets track each consumer group's position in each partition. Consumers commit offsets to the __consumer_offsets internal topic to record progress.",
    "Rebalancing is the process of redistributing partitions among consumers when group membership changes (consumer joins, leaves, or crashes). It causes temporary processing pauses.",
    "Cooperative rebalancing (incremental) minimizes disruption by only reassigning partitions that need to move, unlike eager rebalancing which revokes all partitions before reassigning.",
  ],
  detailed: [
    "A consumer group is identified by a group.id string. When multiple consumers share the same group.id and subscribe to the same topic, Kafka distributes the topic's partitions among them. Each partition is assigned to exactly one consumer in the group at any time. If there are more consumers than partitions, the excess consumers sit idle as standby. If a consumer fails, its partitions are reassigned to remaining consumers. This model provides both load balancing and fault tolerance.",
    "Consumer offsets represent the position of a consumer group in each partition. The offset is the index of the next message to be read. When a consumer processes a batch of messages, it commits the offset to tell Kafka where it left off. Offsets are stored in the __consumer_offsets internal topic (a compacted topic with 50 partitions by default). There are two commit modes: auto-commit (enable.auto.commit=true, commits periodically) and manual commit (commitSync() or commitAsync()). Auto-commit risks both duplicates and data loss.",
    "The group coordinator is a specific broker responsible for managing a consumer group. It handles join/leave requests, triggers rebalances, and tracks member heartbeats. The coordinator for a group is the broker that hosts the partition of __consumer_offsets to which the group's offsets are written (determined by hash(group.id) % 50). The group leader is the first consumer to join; it receives the full list of members and computes the partition assignment.",
    "Eager rebalancing (the default before Kafka 2.4) uses a stop-the-world approach: when a rebalance is triggered, all consumers revoke all their partitions, rejoin the group, and receive new assignments. During this window, no consumer processes any messages. This causes latency spikes and can take seconds to minutes in large groups.",
    "Cooperative rebalancing (incremental, introduced in Kafka 2.4 via KIP-429) minimizes disruption. Instead of revoking all partitions, only the partitions that need to move are revoked and reassigned. Consumers that keep their partitions continue processing without interruption. Set partition.assignment.strategy to CooperativeStickyAssignor to enable it.",
    "Static group membership (KIP-345) assigns a persistent group.instance.id to each consumer. When a consumer with a static ID disconnects and reconnects within session.timeout.ms, it gets back the same partitions without triggering a rebalance. This is valuable for stateful consumers where rebalancing is expensive because state must be rebuilt.",
  ],
  deepDive: [
    "The consumer group protocol involves several phases. (1) FindCoordinator: the consumer discovers which broker is the group coordinator. (2) JoinGroup: the consumer sends its subscriptions and supported assignment strategies to the coordinator, which waits for all members and selects the group leader. (3) SyncGroup: the leader computes partition assignments and sends them to the coordinator for distribution. (4) Heartbeat: consumers periodically send heartbeats (heartbeat.interval.ms, default 3s). If a consumer misses heartbeats for session.timeout.ms (default 45s), it is considered dead and a rebalance is triggered. (5) LeaveGroup: sent on graceful shutdown for immediate rebalance.",
    "Partition assignment strategies determine how partitions are distributed. RangeAssignor (default): sorts partitions and consumers, divides partitions into contiguous ranges. RoundRobinAssignor: distributes partitions evenly in round-robin. StickyAssignor: minimizes partition movement during rebalancing. CooperativeStickyAssignor: same as StickyAssignor but uses cooperative rebalancing protocol. For most production use, CooperativeStickyAssignor is recommended.",
    "Consumer lag monitoring is critical for operational health. Lag is the difference between the log-end offset of a partition and the consumer group's committed offset. Tools: kafka-consumer-groups.sh --describe shows per-partition lag. Burrow provides lag evaluation with consumer state classification (OK, WARNING, STALLED, STOPPED). JMX metrics records-lag-max and records-lag expose lag in the consumer client.",
    "The max.poll.interval.ms setting (default 5 minutes) controls how long the coordinator waits between poll() calls before considering the consumer dead. If message processing takes longer than this interval, the consumer is evicted. This is distinct from session.timeout.ms (heartbeat-based liveness). A common pitfall: a consumer with slow processing fails to call poll() within the interval, gets evicted, and enters a cycle of rebalances.",
    "Exactly-once consumption requires careful offset management. Disable auto-commit, process messages, commit offsets manually. For database sinks, store the offset in the database alongside business data in the same transaction. On restart, read the last committed offset from the database and seek to it, bypassing the __consumer_offsets topic.",
  ],
  code: [
    {
      language: "java",
      caption: "Consumer group with manual offset commit and graceful shutdown",
      source: [
        "Properties props = new Properties();",
        "props.put(\"bootstrap.servers\", \"localhost:9092\");",
        "props.put(\"group.id\", \"order-processor\");",
        "props.put(\"key.deserializer\", \"org.apache.kafka.common.serialization.StringDeserializer\");",
        "props.put(\"value.deserializer\", \"org.apache.kafka.common.serialization.StringDeserializer\");",
        "props.put(\"enable.auto.commit\", \"false\");",
        "props.put(\"auto.offset.reset\", \"earliest\");",
        "props.put(\"max.poll.records\", \"500\");",
        "",
        "// Enable cooperative rebalancing",
        "props.put(\"partition.assignment.strategy\",",
        "    \"org.apache.kafka.clients.consumer.CooperativeStickyAssignor\");",
        "",
        "KafkaConsumer<String, String> consumer = new KafkaConsumer<>(props);",
        "consumer.subscribe(List.of(\"orders\"));",
        "",
        "final AtomicBoolean running = new AtomicBoolean(true);",
        "Runtime.getRuntime().addShutdownHook(new Thread(() -> {",
        "    running.set(false);",
        "    consumer.wakeup(); // Breaks out of poll()",
        "}));",
        "",
        "try {",
        "    while (running.get()) {",
        "        ConsumerRecords<String, String> records =",
        "            consumer.poll(Duration.ofMillis(1000));",
        "",
        "        for (ConsumerRecord<String, String> record : records) {",
        "            processOrder(record.key(), record.value());",
        "        }",
        "",
        "        if (!records.isEmpty()) {",
        "            consumer.commitSync();",
        "        }",
        "    }",
        "} catch (WakeupException e) {",
        "    if (running.get()) throw e;",
        "} finally {",
        "    consumer.commitSync();",
        "    consumer.close();",
        "}",
      ].join("\n"),
    },
    {
      language: "java",
      caption: "Consumer with rebalance listener for stateful processing",
      source: [
        "consumer.subscribe(List.of(\"events\"), new ConsumerRebalanceListener() {",
        "    @Override",
        "    public void onPartitionsRevoked(Collection<TopicPartition> partitions) {",
        "        // Commit offsets for partitions being revoked",
        "        Map<TopicPartition, OffsetAndMetadata> offsets = new HashMap<>();",
        "        for (TopicPartition tp : partitions) {",
        "            long offset = currentOffsets.getOrDefault(tp, 0L);",
        "            offsets.put(tp, new OffsetAndMetadata(offset + 1));",
        "        }",
        "        consumer.commitSync(offsets);",
        "",
        "        // Flush any buffered state for these partitions",
        "        for (TopicPartition tp : partitions) {",
        "            flushStateStore(tp);",
        "        }",
        "        log.info(\"Revoked partitions: {}\", partitions);",
        "    }",
        "",
        "    @Override",
        "    public void onPartitionsAssigned(Collection<TopicPartition> partitions) {",
        "        for (TopicPartition tp : partitions) {",
        "            initializeStateStore(tp);",
        "            long savedOffset = loadOffsetFromStateStore(tp);",
        "            if (savedOffset >= 0) {",
        "                consumer.seek(tp, savedOffset);",
        "            }",
        "        }",
        "        log.info(\"Assigned partitions: {}\", partitions);",
        "    }",
        "});",
      ].join("\n"),
    },
    {
      language: "cpp",
      caption: "Static group membership to avoid unnecessary rebalances",
      source: [
        "#include <cppkafka/consumer.h>",
        "#include <cppkafka/configuration.h>",
        "#include <csignal>",
        "#include <iostream>",
        "#include <unistd.h>",
        "",
        "// Get hostname for stable instance ID",
        "std::string getHostname() {",
        "    char buf[256];",
        "    gethostname(buf, sizeof(buf));",
        "    return std::string(buf);",
        "}",
        "",
        "volatile sig_atomic_t running = 1;",
        "void signalHandler(int) { running = 0; }",
        "",
        "int main() {",
        "    std::signal(SIGINT, signalHandler);",
        "",
        "    cppkafka::Configuration config = {",
        "        {\"metadata.broker.list\", \"localhost:9092\"},",
        "        {\"group.id\", \"analytics-group\"},",
        "        {\"enable.auto.commit\", \"false\"},",
        "        {\"auto.offset.reset\", \"earliest\"},",
        "        // Static membership: use hostname as stable instance ID",
        "        {\"group.instance.id\", \"analytics-\" + getHostname()},",
        "        // Increase session timeout for static members",
        "        {\"session.timeout.ms\", \"300000\"},   // 5 minutes",
        "        {\"heartbeat.interval.ms\", \"10000\"},",
        "        {\"max.poll.interval.ms\", \"600000\"},  // 10 minutes",
        "    };",
        "",
        "    cppkafka::Consumer consumer(config);",
        "    consumer.subscribe({\"events\"});",
        "",
        "    while (running) {",
        "        auto messages = consumer.poll(std::chrono::milliseconds(1000));",
        "        for (const auto& msg : messages) {",
        "            if (!msg.get_error()) {",
        "                processEvent(msg.get_payload());",
        "            }",
        "        }",
        "        if (!messages.empty()) {",
        "            consumer.commit();",
        "        }",
        "    }",
        "",
        "    consumer.commit();",
        "    return 0;",
        "}",
      ].join("\n"),
    },
    {
      language: "cpp",
      caption: "Monitoring consumer group lag programmatically",
      source: [
        "#include <librdkafka/rdkafkacpp.h>",
        "#include <iostream>",
        "#include <vector>",
        "#include <memory>",
        "",
        "int main() {",
        "    std::string errstr;",
        "    auto conf = std::unique_ptr<RdKafka::Conf>(",
        "        RdKafka::Conf::create(RdKafka::Conf::CONF_GLOBAL));",
        "    conf->set(\"metadata.broker.list\", \"localhost:9092\", errstr);",
        "",
        "    auto consumer = std::unique_ptr<RdKafka::KafkaConsumer>(",
        "        RdKafka::KafkaConsumer::create(conf.get(), errstr));",
        "",
        "    std::string groupId = \"order-processor\";",
        "",
        "    // Fetch committed offsets for the consumer group",
        "    std::vector<RdKafka::TopicPartition*> partitions;",
        "    RdKafka::ErrorCode err = consumer->committed(partitions, 5000);",
        "",
        "    // Query end offsets (high watermarks)",
        "    int64_t totalLag = 0;",
        "    for (auto* tp : partitions) {",
        "        int64_t low = 0, high = 0;",
        "        consumer->query_watermark_offsets(",
        "            tp->topic(), tp->partition(), &low, &high, 5000);",
        "",
        "        int64_t committed = tp->offset();",
        "        int64_t lag = high - committed;",
        "        totalLag += lag;",
        "",
        "        std::cout << \"  \" << tp->topic() << \"-\" << tp->partition()",
        "                  << \": committed=\" << committed",
        "                  << \", latest=\" << high",
        "                  << \", lag=\" << lag << \"\\n\";",
        "    }",
        "",
        "    std::cout << \"Total lag: \" << totalLag << \"\\n\";",
        "",
        "    if (totalLag > 10000) {",
        "        std::cout << \"WARNING: Consumer group lag is \"",
        "                  << totalLag << \"\\n\";",
        "    }",
        "",
        "    // Clean up",
        "    for (auto* tp : partitions) delete tp;",
        "    consumer->close();",
        "    return 0;",
        "}",
      ].join("\n"),
    },
  ],
  diagrams: [
    {
      title: "Consumer Group Partition Assignment",
      kind: "architecture",
      caption: "6 partitions distributed among 3 consumers in a group; each consumer owns 2 partitions.",
    },
    {
      title: "Rebalancing Protocol Sequence",
      kind: "sequence",
      caption: "JoinGroup -> leader computes assignment -> SyncGroup distributes assignments -> consumers resume.",
    },
    {
      title: "Eager vs Cooperative Rebalancing",
      kind: "flow",
      caption: "Eager: revoke all, reassign all (stop-the-world). Cooperative: revoke only moving partitions (incremental).",
    },
  ],
  animations: [
    {
      title: "Consumer Group Rebalance on Member Join",
      steps: [
        { label: "Stable state", detail: "Consumer A owns P0,P1,P2. Consumer B owns P3,P4,P5. Both processing normally." },
        { label: "New consumer joins", detail: "Consumer C starts with same group.id. Sends JoinGroup to coordinator." },
        { label: "Rebalance triggered", detail: "Coordinator notifies A and B via heartbeat response that a rebalance is needed." },
        { label: "Eager: all revoked", detail: "A and B revoke all partitions. No consumer processes any messages during rebalance." },
        { label: "Leader computes", detail: "Consumer A (leader) computes new assignment: A=P0,P1; B=P2,P3; C=P4,P5." },
        { label: "SyncGroup", detail: "Leader sends assignment to coordinator. Coordinator distributes to all members." },
        { label: "Resume processing", detail: "All three consumers start processing their assigned partitions." },
      ],
    },
    {
      title: "Cooperative Rebalance on Member Join",
      steps: [
        { label: "Stable state", detail: "Consumer A owns P0,P1,P2. Consumer B owns P3,P4,P5." },
        { label: "Consumer C joins", detail: "Sends JoinGroup. Coordinator triggers rebalance." },
        { label: "First rebalance", detail: "Leader computes target: A=P0,P1; B=P3,P4; C=P2,P5. Revokes only P2 from A and P5 from B." },
        { label: "Partial revocation", detail: "A continues processing P0,P1. B continues processing P3,P4. Only moved partitions pause." },
        { label: "Second rebalance", detail: "Revoked partitions P2 and P5 are now assigned to C." },
        { label: "All processing", detail: "A processes P0,P1. B processes P3,P4. C processes P2,P5. Minimal disruption." },
      ],
    },
  ],
  comparison: {
    columns: ["Property", "Eager Rebalancing", "Cooperative Rebalancing"],
    rows: [
      ["Partition revocation", "All partitions from all consumers", "Only partitions that need to move"],
      ["Processing during rebalance", "Fully stopped", "Continues for non-moving partitions"],
      ["Rebalance phases", "Single phase", "Two phases (revoke then assign)"],
      ["Downtime", "Seconds to minutes", "Minimal (only moved partitions)"],
      ["Assignment strategy", "Range, RoundRobin", "CooperativeStickyAssignor"],
      ["Kafka version", "All versions", "2.4+ (KIP-429)"],
      ["Complexity", "Simple protocol", "More complex, two-phase"],
      ["Best for", "Small groups, infrequent changes", "Large groups, frequent scaling"],
    ],
  },
  interviewQA: [
    {
      q: "What happens when a consumer in a group crashes?",
      a: "The group coordinator detects the crash when heartbeats stop arriving for session.timeout.ms (default 45s). It marks the consumer as dead and triggers a rebalance. The crashed consumer's partitions are redistributed among remaining healthy consumers. Any uncommitted offsets are lost, so messages after the last commit will be reprocessed (at-least-once semantics).",
      followUps: [
        "How does static membership affect crash detection?",
        "What is the difference between session.timeout.ms and max.poll.interval.ms?",
      ],
    },
    {
      q: "Explain the difference between session.timeout.ms and max.poll.interval.ms.",
      a: "session.timeout.ms (default 45s) is the heartbeat-based timeout. If the coordinator receives no heartbeat within this period, the consumer is considered dead. Heartbeats are sent by a background thread. max.poll.interval.ms (default 5 minutes) is the processing-based timeout. If the consumer does not call poll() within this interval, the coordinator considers it stuck and evicts it. A consumer can be heartbeating fine but still get evicted if processing takes too long. The first detects crashes; the second detects hung consumers.",
      followUps: [
        "What happens if processing consistently takes longer than max.poll.interval.ms?",
        "How should you tune these values?",
      ],
    },
    {
      q: "What is cooperative rebalancing and why is it better?",
      a: "Cooperative rebalancing (incremental, KIP-429) avoids the stop-the-world pause of eager rebalancing. In eager mode, all consumers revoke all partitions, then get new assignments -- no processing occurs during this window. In cooperative mode, only the partitions that actually need to move are revoked. Consumers that keep their partitions continue processing without interruption. Use CooperativeStickyAssignor to enable it.",
      followUps: [
        "Can you mix eager and cooperative consumers in the same group?",
        "What is the CooperativeStickyAssignor?",
      ],
    },
    {
      q: "How does static group membership work?",
      a: "Static membership (KIP-345) assigns a persistent group.instance.id to each consumer. When a consumer with a static ID disconnects and reconnects within session.timeout.ms, the coordinator recognizes it and restores its previous partition assignment without triggering a rebalance. This is valuable for rolling deployments and stateful consumers where rebalancing forces expensive state migration. The tradeoff is longer detection time for truly dead consumers.",
    },
  ],
  mcqs: [
    {
      q: "Where are consumer group offsets stored in Kafka?",
      options: [
        "In ZooKeeper",
        "In the __consumer_offsets internal topic",
        "In a file on the consumer's local disk",
        "In the topic's partition metadata",
      ],
      answerIndex: 1,
      explanation: "Since Kafka 0.9, consumer offsets are stored in the __consumer_offsets internal compacted topic.",
    },
    {
      q: "What triggers a consumer group rebalance?",
      options: [
        "A producer sends a new message",
        "A consumer joins or leaves the group, or a consumer fails to heartbeat",
        "The broker restarts",
        "The topic's retention policy changes",
      ],
      answerIndex: 1,
      explanation: "Rebalancing is triggered by changes in group membership: a new consumer joining, an existing consumer leaving, or subscription changes.",
    },
    {
      q: "What is the role of the group leader in Kafka?",
      options: [
        "It coordinates heartbeats for all consumers",
        "It stores offsets for the group",
        "It computes the partition assignment and sends it to the coordinator",
        "It handles all message consumption for the group",
      ],
      answerIndex: 2,
      explanation: "The group leader (first consumer to join) receives member metadata and computes partition assignments, which it sends to the coordinator for distribution.",
    },
    {
      q: "What happens if a consumer group has 10 consumers but the topic has only 6 partitions?",
      options: [
        "Each consumer gets a fraction of each partition",
        "6 consumers get one partition each; 4 consumers sit idle",
        "The extra consumers are rejected from the group",
        "Partitions are split to match the consumer count",
      ],
      answerIndex: 1,
      explanation: "Each partition is assigned to exactly one consumer. With 6 partitions and 10 consumers, 4 consumers will be idle standby members.",
    },
    {
      q: "Which assignment strategy supports cooperative rebalancing?",
      options: [
        "RangeAssignor",
        "RoundRobinAssignor",
        "StickyAssignor",
        "CooperativeStickyAssignor",
      ],
      answerIndex: 3,
      explanation: "CooperativeStickyAssignor (KIP-429) is the only built-in strategy that uses the cooperative rebalancing protocol.",
    },
  ],
  flashcards: [
    { front: "Consumer group", back: "Set of consumers sharing a group.id. Partitions distributed among members. Max active consumers = partition count." },
    { front: "Consumer offset", back: "Position of a consumer group in a partition. Stored in __consumer_offsets topic. Committed manually or automatically." },
    { front: "Group coordinator", back: "Broker managing a specific consumer group. Handles joins, leaves, heartbeats, rebalances. Determined by hash(group.id) % 50." },
    { front: "Group leader", back: "First consumer to join. Computes partition assignment and sends to coordinator for distribution." },
    { front: "Eager rebalancing", back: "Stop-the-world: all partitions revoked from all consumers, then reassigned. Full processing pause." },
    { front: "Cooperative rebalancing", back: "Incremental: only moving partitions revoked. Non-moving partitions continue processing. Two-phase protocol." },
    { front: "Static membership", back: "group.instance.id persists across restarts. Consumer gets same partitions back without rebalance if it reconnects in time." },
    { front: "session.timeout.ms", back: "Heartbeat timeout (default 45s). No heartbeat in this window = consumer considered dead." },
    { front: "max.poll.interval.ms", back: "Processing timeout (default 5min). No poll() call in this window = consumer evicted as hung." },
    { front: "Consumer lag", back: "log-end offset minus committed offset. Indicates how far behind a consumer group is." },
  ],
  revisionNotes: [
    "Consumer group = consumers with same group.id. Each partition assigned to exactly one consumer.",
    "Offsets stored in __consumer_offsets (compacted, 50 partitions). Auto-commit or manual (commitSync/commitAsync).",
    "Group coordinator = broker hosting the group's __consumer_offsets partition. Group leader = first consumer to join.",
    "Rebalance triggers: consumer join/leave/crash, subscription change, partition count change.",
    "Eager rebalance: revoke all -> reassign all. Stop-the-world. Default before Kafka 2.4.",
    "Cooperative rebalance: revoke only moving partitions. Two-phase. Use CooperativeStickyAssignor.",
    "Static membership: group.instance.id avoids rebalance on restart. Good for stateful consumers and rolling deploys.",
    "session.timeout.ms = heartbeat liveness (45s). max.poll.interval.ms = processing liveness (5min).",
    "Monitor lag with kafka-consumer-groups.sh --describe, Burrow, or JMX records-lag-max.",
    "For exactly-once to external DB: store Kafka offset in DB with business data, seek on restart.",
  ],
  cheatSheet: [
    "List groups: kafka-consumer-groups.sh --list --bootstrap-server localhost:9092",
    "Describe group: kafka-consumer-groups.sh --describe --group <id>",
    "Reset offsets: kafka-consumer-groups.sh --reset-offsets --to-earliest --group <id> --topic <topic> --execute",
    "Cooperative rebalance: partition.assignment.strategy=CooperativeStickyAssignor",
    "Static membership: group.instance.id=<stable-id>, increase session.timeout.ms",
    "Manual commit: enable.auto.commit=false, call commitSync() after processing",
    "Graceful shutdown: consumer.wakeup() from shutdown hook, commitSync() in finally block",
    "Rebalance listener: subscribe(topics, ConsumerRebalanceListener) for onPartitionsRevoked/Assigned",
  ],
  resources: [
    { label: "Kafka Consumer Documentation", kind: "docs", note: "Official Apache Kafka consumer configuration and API reference" },
    { label: "KIP-429: Incremental Cooperative Rebalancing", kind: "docs", note: "Design document for cooperative rebalancing protocol" },
    { label: "KIP-345: Static Membership", kind: "docs", note: "Design document for static consumer group membership" },
    { label: "Burrow - Kafka Consumer Lag Checking", kind: "repo", note: "LinkedIn's tool for monitoring consumer lag with state evaluation" },
    { label: "Kafka: The Definitive Guide (Ch. 4)", kind: "book", note: "O'Reilly book covering Kafka consumers and consumer groups in depth" },
    { label: "Confluent - Consumer Group Protocol", kind: "article", note: "Detailed walkthrough of the consumer group protocol internals" },
  ],
  glossary: [
    { term: "Consumer group", definition: "A set of consumers sharing a group.id that cooperatively consume a topic's partitions." },
    { term: "Offset", definition: "A sequential position marker in a partition indicating which message to read next." },
    { term: "__consumer_offsets", definition: "Internal compacted Kafka topic storing committed offsets for all consumer groups." },
    { term: "Group coordinator", definition: "The broker responsible for managing a specific consumer group's membership and rebalancing." },
    { term: "Rebalancing", definition: "The process of redistributing partition assignments among consumers when group membership changes." },
    { term: "Cooperative rebalancing", definition: "Incremental rebalancing that only revokes partitions that need to move, minimizing processing disruption." },
    { term: "Static membership", definition: "Consumer group feature where a persistent instance ID allows a consumer to reclaim its partitions without rebalancing." },
    { term: "Consumer lag", definition: "The offset difference between a partition's latest message and a consumer group's last committed offset." },
  ],

  exercises: [
    "You have a Kafka topic with **12 partitions** and a consumer group with 3 consumers. Draw the partition assignment using the *RangeAssignor*. Now a 4th consumer joins. Trace the **eager rebalancing** protocol step-by-step: which partitions are revoked, how long processing pauses, and the final assignment. Repeat the exercise using **CooperativeStickyAssignor** and compare the disruption.",
    "Design an **exactly-once processing pipeline** that reads orders from a Kafka topic and writes them to PostgreSQL. Disable `enable.auto.commit`, use manual `commitSync()`, and store the Kafka offset *in the same database transaction* as the order data. Explain what happens on consumer crash: how do you `seek()` to the correct offset on restart? What is the risk of *duplicate processing* if you commit offsets to `__consumer_offsets` separately from the database write?",
    "Your consumer group's **lag is growing** at 200 messages/sec on a topic with 6 partitions and 3 consumers. Walk through a systematic diagnosis: (1) check per-partition lag with `kafka-consumer-groups.sh --describe`, (2) determine if the bottleneck is *slow processing* (high `max.poll.interval.ms` usage) or *insufficient parallelism*. Propose two fixes: adding consumers (up to what limit?) and tuning `max.poll.records` and `fetch.max.bytes`. Calculate the expected improvement.",
    "Implement a **ConsumerRebalanceListener** that handles *stateful processing*. On `onPartitionsRevoked`, flush an in-memory aggregation buffer and commit offsets for the revoked partitions. On `onPartitionsAssigned`, initialize the state store for new partitions and seek to the last checkpointed offset. Why is this listener critical for stateful consumers? What goes wrong without it during a rebalance?",
    "Compare **static group membership** (`group.instance.id`) versus dynamic membership for a consumer group running on Kubernetes with rolling deployments. With dynamic membership, each pod restart triggers a rebalance. Calculate the total *rebalance downtime* for a rolling deployment of 6 pods with `session.timeout.ms=45s`. With static membership and `session.timeout.ms=300s`, how does the behavior change? What is the trade-off for truly *dead* consumers?"
  ],
};
