import type { TopicContent } from "../types";

export const designPaymentSystem: TopicContent = {
  quickSummary: [
    "Payment systems require exactly-once semantics through idempotency keys — every payment request carries a unique key so that retries (due to network failures, timeouts, or client crashes) never result in double-charging the customer.",
    "Double-entry bookkeeping is the foundation of financial correctness: every transaction creates two entries (debit from one account, credit to another) that must always sum to zero, providing a built-in audit trail and error detection mechanism.",
    "The payment state machine (CREATED → PROCESSING → SUCCEEDED/FAILED) ensures that each payment transitions through well-defined states with clear rules for what retries, refunds, and chargebacks are valid at each state.",
    "Reconciliation is the process of comparing internal records against external payment provider records (bank statements, PSP reports) to detect discrepancies — it runs daily/hourly and is the ultimate source of truth for financial accuracy.",
    "PCI DSS compliance mandates that raw card numbers never touch your application servers — tokenization through a PCI-compliant vault (like Stripe or Adyen) replaces card data with opaque tokens that your system stores and references safely.",
    "Scale is not the hard part — 1M payments/day is only ~12 QPS average (~100 QPS at flash-sale peak) — so the design optimizes for correctness over throughput: multi-PSP routing with per-provider circuit breakers, deduped webhook processing, and daily reconciliation form the resilience backbone.",
  ],
  detailed: [
    "## Scale Envelope: Low QPS, Extreme Correctness\nPayments are the opposite of most system design problems — the load is modest but the correctness bar is absolute. Run the numbers: 1 million payments/day is roughly 12 payments/second average, and even a flash-sale peak of about 100/second is trivially handled by a handful of application servers and a single well-tuned Postgres primary. Storage is equally small: at ~2 KB per payment record plus ledger entries, a year of 1M/day is under 1 TB. So capacity math takes thirty seconds in this interview — the math that matters is correctness math. Every payment produces ledger entries that must sum to exactly zero; across 1M payments/day, a bug with a 0.01% double-charge rate is 100 wrongly charged customers per day, which is a regulatory incident, not a metrics blip. Key insight: interviewers use this question to test whether you optimize for the right axis — say explicitly that you will trade latency and throughput for consistency, durability, and auditability (synchronous replication, serializable transactions on money paths, append-only records), the reverse of a feed or cache design.",

    "## Idempotency and Exactly-Once Payment Processing\nThe most critical property of a payment system is that a payment is processed exactly once — never zero times (lost payment) and never more than once (double charge). Network failures make this challenging: when a client sends a payment request and the connection drops before receiving a response, the client does not know whether the payment succeeded. The solution is an idempotency key: a unique identifier (UUID) generated by the client and included with every payment request and every retry of it. The server stores the key alongside the full serialized response in a transactional database write; when a retry arrives with the same key, the server replays the stored response without reprocessing — the client cannot tell a replay from the original. To reason about why this must be end-to-end, walk the three failure windows of a single attempt: (1) the request is lost before the server receives it — no state exists, a retry is safely a fresh attempt; (2) the server processed the payment but the response is lost in transit — state exists, so a naive retry double-charges, and only the stored-response replay saves you; (3) the server crashed mid-processing — the key row exists marked in-progress, so the retry must either wait, return 409, or trigger recovery by querying the PSP for the attempt's fate. The client can never distinguish these three windows from the outside, which is exactly why the same key must flow through every hop — client to gateway to payment service to PSP (Stripe and Adyen both accept idempotency keys), so dedup happens at every layer that might independently retry. Common mistake: storing the idempotency key in Redis with a TTL but the payment in Postgres — a crash between the two writes reintroduces the double-charge; key and payment state must commit in the same database transaction. Keys expire after a configurable window (typically 24-48 hours), and the pattern extends to every mutating operation: refunds, captures, and voids all carry their own keys.",

    "## Double-Entry Bookkeeping and Ledger Design\nEvery financial movement in the system is recorded as a pair of ledger entries: a debit (money leaving) from one account and a credit (money arriving) to another. A customer paying $100 creates a debit of $100 from the customer's payment account and a credit of $100 to the merchant's receivables account. This invariant — debits always equal credits — provides automatic error detection: if the ledger does not balance, something is wrong. Key insight: the ledger is the source of truth and payment rows are just a projection of it — when the two disagree, the ledger wins, because it is the record auditors and regulators will read. The ledger is an append-only, immutable data structure: entries are never modified or deleted, only new entries are added (corrections are recorded as reversal entries). Each entry has a unique ID, timestamp, amount, currency, account, direction (debit/credit), and a reference to the payment or transaction it belongs to. The ledger supports multi-currency by recording amounts in the original currency with an exchange rate at the time of the transaction. Account balances are derived by summing all ledger entries for that account — never stored as a mutable field, which would create a single point of failure. For performance, materialized balance views are maintained and periodically reconciled against the ledger sum.",

    "## Payment State Machine and Lifecycle\nA payment moves through a well-defined state machine: CREATED (initial request received), PROCESSING (submitted to payment provider), AUTHORIZED (funds reserved but not captured), CAPTURED (funds transferred), SETTLED (funds deposited to merchant), FAILED (permanently rejected), and REFUNDED (funds returned to customer). State transitions are governed by strict rules: a payment can only move from PROCESSING to AUTHORIZED or FAILED, never directly to SETTLED. Each transition is logged with a timestamp and reason. The state machine prevents invalid operations — you cannot refund a payment that is still PROCESSING, and you cannot capture an AUTHORIZED payment twice. Timeouts are critical: if a payment is in PROCESSING for more than 30 seconds without a response from the payment provider, the system queries the provider for status (reconciliation) rather than assuming failure. Stuck payments (neither confirmed nor denied by the provider) are flagged for manual review. Every backward-looking money movement is modeled as a compensation, not a state edit: a refund does not un-capture a payment, it adds a REFUND_PENDING to REFUNDED path with its own reversal ledger entries; a failed capture after a successful authorization is compensated by an explicit void of the authorization. In practice: the state machine is implemented as a database column guarded by a transition table (or CHECK constraints), and every transition row carries the actor, reason, and timestamp so the audit log falls out for free.",

    "## Reconciliation and Settlement\nReconciliation is the process of comparing the payment system's internal records against external records from payment providers, banks, and card networks. It runs at multiple frequencies: real-time (streaming provider webhooks and matching against pending payments), hourly (batch comparison of transaction counts and totals), and daily (full settlement file reconciliation). Discrepancies fall into categories: missing transactions (present in internal records but not in provider reports, or vice versa), amount mismatches (internal amount differs from provider amount, often due to currency conversion), and status mismatches (internal shows succeeded but provider shows failed). Each discrepancy is logged, classified by severity, and routed to the appropriate team. Auto-resolution handles common cases: a 'missing in provider' record that appears in the next batch is automatically matched. Settlement is the actual transfer of funds from the payment provider to the merchant's bank account, typically with a delay of 1-3 business days. The settlement amount may differ from the gross payment amount due to provider fees, chargebacks, and reserves.",

    "## Retry Logic, Failure Handling, and Multi-Currency\nPayment processing involves multiple external services (card networks, payment providers, fraud detection), each of which can fail independently. The retry strategy uses exponential backoff with jitter: first retry after 1 second, then 2s, 4s, 8s, up to a maximum of 5 retries over about 30 seconds. Jitter (random variation of +/- 50%) prevents thundering herd when a provider outage resolves. Not all failures are retriable: a 'card declined' response is permanent (no retry), while a 'network timeout' is transient (retry). The system classifies provider error codes into retriable and non-retriable categories. For critical payments, a fallback payment provider can be attempted if the primary provider is down — this requires multi-provider integration with a router that selects the provider based on card type, currency, and success rates. Multi-currency support requires storing amounts in the smallest currency unit (cents for USD, yen for JPY — which has no subunit), recording the exchange rate at transaction time, and supporting refunds in the original currency. Currency conversion fees must be explicitly accounted for in the ledger as a separate line item.",

    "## Multi-PSP Routing, Circuit Breakers, and Failover\nSerious payment platforms integrate multiple PSPs (Stripe, Adyen, direct bank rails) behind a routing layer, for three reasons: availability (any single PSP has outages), cost (interchange and fees vary by card type, region, and volume tiers), and authorization rates (issuers approve the same card at different rates through different acquirers). Each PSP sits behind its own adapter that normalizes the API and error taxonomy, and its own circuit breaker that tracks error rate and latency — when Stripe's breaker opens, new authorizations route to Adyen automatically while in-flight Stripe payments are left to resolve via webhook or reconciliation, never re-sent to a second PSP. The router picks a PSP per transaction using static rules (currency, card scheme, merchant region) plus dynamic signals (rolling auth rate, current breaker state, cost). Failover mid-payment is the subtle part: it is only safe before the first PSP has possibly seen the request — once an authorize call has been sent and timed out, you must resolve its fate with that PSP (status query or webhook) before retrying anywhere, or you risk two authorizations holding the customer's funds twice. Warning: tokens are usually PSP-scoped — a Stripe card token cannot be charged through Adyen — so true failover requires either network tokens, a PSP-agnostic vault, or accepting that failover only applies to new payments, not retries of tokenized ones. Real-world example: large merchants report 1-3% authorization-rate lifts just from smart routing between acquirers, which at meaningful volume dwarfs infrastructure costs.",
  ],
  deepDive: [
    "PCI DSS compliance fundamentally shapes the payment system architecture. The most important principle is minimizing the PCI scope — the fewer systems that touch raw card data, the fewer systems need annual PCI audits (which cost $50K-$500K+ depending on the level). The standard approach is tokenization: the client-side SDK (Stripe.js, Adyen Checkout) collects card details directly from the user's browser and sends them to the payment provider's PCI-compliant infrastructure, which returns an opaque token. Your backend only ever sees this token, never the raw card number. This keeps your entire backend out of PCI scope (SAQ-A or SAQ A-EP level rather than full SAQ-D). The token is stored in your database and used for subsequent charges, recurring payments, and refunds. For recurring payments, the provider stores the card on file and issues a token that can be charged without the customer re-entering card details. Even logging must be careful: never log card numbers, CVVs, or full card PANs — only the last four digits and expiration date may be stored. Network security (TLS everywhere, network segmentation) and access control (role-based, MFA for admin access) are additional PCI requirements that influence the system design.",

    "Distributed transaction handling in payment systems is one of the hardest problems in system design. A payment involves multiple services: your payment service, the fraud detection service, the ledger service, the payment provider API, and the notification service. If the payment provider charges the card but your ledger update fails, the customer is charged without a record — a critical inconsistency. The Saga pattern addresses this: each step is a local transaction with a compensating action. If step 3 fails, compensating actions for steps 2 and 1 are executed (e.g., void the payment provider charge, reverse the fraud hold). Sagas come in two flavors: orchestrated (a central coordinator drives the steps) and choreographed (each service publishes events, and the next service reacts). For payments, orchestrated sagas are preferred because the explicit ordering and error handling are easier to reason about. The orchestrator maintains the saga state (which steps completed, which need compensation) and retries or compensates on failure. The Outbox pattern ensures that database writes and event publications are atomic: the service writes to its database and an outbox table in the same transaction, and a separate process reads the outbox and publishes events, guaranteeing at-least-once delivery.",

    "Fraud detection must be both fast (sub-100ms to avoid degrading checkout experience) and accurate (false positives lose revenue, false negatives lose money to fraud). The fraud system evaluates each payment against a set of rules (velocity checks, amount thresholds, geographic anomalies) and machine learning models (behavioral patterns, device fingerprinting). Real-time scoring runs inline with the payment request — the payment service calls the fraud service synchronously before submitting to the provider. High-risk payments can be held for manual review (adding latency) or auto-declined. The fraud system maintains per-user and per-merchant risk profiles, updated with every transaction. A feedback loop from chargeback data retrains the ML models: every confirmed fraud case improves future detection. 3D Secure (3DS) authentication adds a challenge step for high-risk transactions, shifting liability from the merchant to the card issuer. The trade-off is conversion rate: adding a 3DS step causes 10-30% of customers to abandon the payment. Smart 3DS only triggers for transactions above a risk threshold, balancing security and conversion.",

    "Multi-currency payment processing adds layers of complexity beyond simple exchange rate conversion. Each currency has different rules: some have subunits (USD has cents, GBP has pence) while others do not (JPY, KRW). Amounts must be stored as integers in the smallest unit to avoid floating-point errors — $10.50 is stored as 1050 cents, not 10.5. Exchange rates fluctuate continuously, so the rate must be captured at the exact moment of the transaction and stored immutably with the payment record. For cross-border payments, the customer may pay in their local currency (Dynamic Currency Conversion or DCC), with the merchant receiving the settlement in their base currency. The FX spread (difference between the quoted rate and the market rate) is a revenue source for payment providers. Refunds in multi-currency transactions must use the original exchange rate (not the current rate) to avoid gaining or losing money on the refund. The ledger must track both the original currency amount and the settlement currency amount for accurate accounting.",

    "Exactly-once is an illusion you construct from at-least-once delivery plus deduplication at every boundary — no network hop is ever truly exactly-once. On the outbound side, every PSP call is made with an idempotency key and retried on timeout, which gives at-least-once submission; the PSP's own dedup collapses it to at-most-one charge. On the inbound side, PSP webhooks are the mirror problem: providers explicitly deliver webhooks at-least-once and out of order, so a payment.captured event can arrive twice, or after the refund.succeeded event for the same payment. The webhook processor therefore (1) verifies the signature, (2) persists the raw event keyed by the PSP's event id with a unique constraint — the insert failing IS the dedup, (3) acknowledges 200 immediately and processes asynchronously so slow handling never causes the PSP to redeliver, and (4) treats the event as a hint, not truth: it re-fetches the object from the PSP API before advancing the state machine, which also makes out-of-order delivery harmless because the fetched state is current. Key insight: never write handler logic that assumes an event arrives once or in order — make every handler a pure function of (current state, fetched PSP state) so redelivery and reordering are no-ops. The same discipline applies internally: consumers of the Kafka payment-events topic dedup on event id, and the outbox pattern guarantees the event was published iff the state change committed.",

    "Reconciliation is the system's immune response — it assumes bugs exist and finds them within 24 hours. The anchor is the T+1 settlement file: each morning the PSP delivers a file listing every transaction it settled, with amounts, fees, currencies, and its transaction ids. A reconciliation job loads the file into a staging table and performs a three-way match between the settlement file, the internal payment records, and the ledger entries, matching on the PSP transaction id stored at capture time. Everything that matches on all three is marked reconciled; everything else lands in a discrepancy queue, a first-class table with a severity, a classification (missing-internal, missing-external, amount mismatch, status mismatch, fee mismatch), an owner, and an SLA — not a Slack alert that scrolls away. Auto-resolution handles the boring majority: timing differences (a capture at 23:59 settling in tomorrow's file) auto-match against the next file; missing-internal records trigger an API re-fetch that usually recovers a dropped webhook. The residue is where real money hides — a persistent amount mismatch is often an FX rate captured at authorize but applied at capture, and a status mismatch (we say captured, file says absent) is a customer who was never charged for goods shipped. Two metrics govern the whole function: reconciliation match rate (target 99.99%+ automatic) and discrepancy aging (nothing unexplained older than N days). In practice: teams also reconcile the ledger against itself — a nightly job re-derives every account balance from raw entries and compares it to the materialized balance views, catching projection bugs the external files cannot see.",
  ],
  code: [
    {
      language: "cpp",
      caption: "Payment state machine with validated transitions",
      source: `#include <string>
#include <unordered_map>
#include <unordered_set>
#include <vector>
#include <stdexcept>
#include <chrono>

enum class PaymentState {
    CREATED,
    PROCESSING,
    AUTHORIZED,
    CAPTURED,
    SETTLED,
    FAILED,
    REFUND_PENDING,
    REFUNDED,
    PARTIALLY_REFUNDED,
    CHARGEBACK
};

struct StateTransition {
    PaymentState from;
    PaymentState to;
    std::string reason;
    int64_t timestamp;
};

class PaymentStateMachine {
    // Define valid transitions
    static const std::unordered_map<PaymentState,
        std::unordered_set<PaymentState>>& valid_transitions() {
        static const std::unordered_map<PaymentState,
            std::unordered_set<PaymentState>> transitions = {
            {PaymentState::CREATED,
                {PaymentState::PROCESSING, PaymentState::FAILED}},
            {PaymentState::PROCESSING,
                {PaymentState::AUTHORIZED, PaymentState::CAPTURED,
                 PaymentState::FAILED}},
            {PaymentState::AUTHORIZED,
                {PaymentState::CAPTURED, PaymentState::FAILED}},
            {PaymentState::CAPTURED,
                {PaymentState::SETTLED, PaymentState::REFUND_PENDING,
                 PaymentState::CHARGEBACK}},
            {PaymentState::SETTLED,
                {PaymentState::REFUND_PENDING, PaymentState::CHARGEBACK}},
            {PaymentState::REFUND_PENDING,
                {PaymentState::REFUNDED, PaymentState::PARTIALLY_REFUNDED,
                 PaymentState::FAILED}},
            {PaymentState::PARTIALLY_REFUNDED,
                {PaymentState::REFUND_PENDING}},
        };
        return transitions;
    }

    PaymentState current_;
    std::vector<StateTransition> history_;

public:
    PaymentStateMachine() : current_(PaymentState::CREATED) {}

    PaymentState current() const { return current_; }

    bool can_transition(PaymentState to) const {
        auto it = valid_transitions().find(current_);
        if (it == valid_transitions().end()) return false;
        return it->second.count(to) > 0;
    }

    void transition(PaymentState to, const std::string& reason) {
        if (!can_transition(to)) {
            throw std::runtime_error(
                "Invalid transition from " +
                std::to_string(static_cast<int>(current_)) +
                " to " + std::to_string(static_cast<int>(to))
            );
        }
        auto now = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::system_clock::now().time_since_epoch()
        ).count();
        history_.push_back({current_, to, reason, now});
        current_ = to;
    }

    bool is_terminal() const {
        return current_ == PaymentState::SETTLED ||
               current_ == PaymentState::FAILED ||
               current_ == PaymentState::REFUNDED ||
               current_ == PaymentState::CHARGEBACK;
    }

    bool is_refundable() const {
        return current_ == PaymentState::CAPTURED ||
               current_ == PaymentState::SETTLED ||
               current_ == PaymentState::PARTIALLY_REFUNDED;
    }
};`
    },
    {
      language: "cpp",
      caption: "Idempotency handler with database-backed key store",
      source: `#include <string>
#include <unordered_map>
#include <optional>
#include <chrono>
#include <mutex>
#include <functional>

struct PaymentResult {
    std::string payment_id;
    std::string status;     // "succeeded", "failed", "processing"
    int64_t amount_cents;
    std::string currency;
    std::string error_code;
};

struct IdempotencyEntry {
    std::string key;
    PaymentResult result;
    int64_t created_at;
    bool in_progress;       // Lock to prevent concurrent processing
};

class IdempotencyHandler {
    // In production: backed by database (PostgreSQL) not in-memory
    std::unordered_map<std::string, IdempotencyEntry> store_;
    std::mutex mu_;
    int64_t ttl_ms_ = 48 * 3600 * 1000; // 48 hours

    int64_t now_ms() {
        return std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::system_clock::now().time_since_epoch()
        ).count();
    }

public:
    // Process a payment request with idempotency
    PaymentResult process(
        const std::string& idempotency_key,
        std::function<PaymentResult()> processor
    ) {
        std::lock_guard<std::mutex> lk(mu_);

        auto it = store_.find(idempotency_key);
        if (it != store_.end()) {
            auto& entry = it->second;

            // Check if entry has expired
            if (now_ms() - entry.created_at > ttl_ms_) {
                store_.erase(it);
                // Fall through to process as new
            } else if (entry.in_progress) {
                // Concurrent request with same key
                return {"", "conflict", 0, "", "CONCURRENT_REQUEST"};
            } else {
                // Return cached result (idempotent replay)
                return entry.result;
            }
        }

        // Mark as in-progress to prevent concurrent processing
        store_[idempotency_key] = {
            idempotency_key, {}, now_ms(), true
        };

        // Process the payment
        PaymentResult result = processor();

        // Store result atomically with payment state
        store_[idempotency_key] = {
            idempotency_key, result, now_ms(), false
        };

        return result;
    }

    // Periodic cleanup of expired keys
    void cleanup_expired() {
        std::lock_guard<std::mutex> lk(mu_);
        auto cutoff = now_ms() - ttl_ms_;
        for (auto it = store_.begin(); it != store_.end();) {
            if (it->second.created_at < cutoff)
                it = store_.erase(it);
            else
                ++it;
        }
    }
};`
    },
    {
      language: "cpp",
      caption: "Double-entry ledger with balance computation",
      source: `#include <vector>
#include <string>
#include <unordered_map>
#include <cstdint>
#include <stdexcept>

enum class EntryDirection { DEBIT, CREDIT };

struct LedgerEntry {
    std::string entry_id;
    std::string transaction_id;  // Groups debit + credit pair
    std::string account_id;
    EntryDirection direction;
    int64_t amount_cents;        // Always positive
    std::string currency;
    int64_t timestamp;
    std::string description;
};

class DoubleEntryLedger {
    std::vector<LedgerEntry> entries_;
    int64_t next_entry_id_ = 1;

    std::string gen_entry_id() {
        return "LE-" + std::to_string(next_entry_id_++);
    }

public:
    // Record a double-entry transaction
    void record_transaction(
        const std::string& txn_id,
        const std::string& debit_account,
        const std::string& credit_account,
        int64_t amount_cents,
        const std::string& currency,
        const std::string& description,
        int64_t timestamp
    ) {
        if (amount_cents <= 0) {
            throw std::runtime_error("Amount must be positive");
        }

        // Debit entry (money leaving debit_account)
        entries_.push_back({
            gen_entry_id(), txn_id, debit_account,
            EntryDirection::DEBIT, amount_cents, currency,
            timestamp, description
        });

        // Credit entry (money arriving at credit_account)
        entries_.push_back({
            gen_entry_id(), txn_id, credit_account,
            EntryDirection::CREDIT, amount_cents, currency,
            timestamp, description
        });
    }

    // Get balance for an account (credits - debits)
    int64_t get_balance(const std::string& account_id,
                         const std::string& currency) const {
        int64_t balance = 0;
        for (const auto& entry : entries_) {
            if (entry.account_id == account_id &&
                entry.currency == currency) {
                if (entry.direction == EntryDirection::CREDIT)
                    balance += entry.amount_cents;
                else
                    balance -= entry.amount_cents;
            }
        }
        return balance;
    }

    // Verify the fundamental invariant: all entries sum to zero
    bool verify_balance() const {
        std::unordered_map<std::string, int64_t> txn_sums;
        for (const auto& entry : entries_) {
            int64_t signed_amount =
                (entry.direction == EntryDirection::CREDIT)
                    ? entry.amount_cents
                    : -entry.amount_cents;
            txn_sums[entry.transaction_id] += signed_amount;
        }
        for (const auto& [txn_id, sum] : txn_sums) {
            if (sum != 0) return false; // Imbalanced!
        }
        return true;
    }

    // Record a refund (reversal entry)
    void record_refund(
        const std::string& original_txn_id,
        const std::string& refund_txn_id,
        int64_t refund_amount_cents,
        int64_t timestamp
    ) {
        std::string debit_acct, credit_acct, currency;
        for (const auto& e : entries_) {
            if (e.transaction_id == original_txn_id) {
                currency = e.currency;
                if (e.direction == EntryDirection::DEBIT)
                    debit_acct = e.account_id;
                else
                    credit_acct = e.account_id;
            }
        }

        // Refund reverses the direction
        record_transaction(
            refund_txn_id, credit_acct, debit_acct,
            refund_amount_cents, currency,
            "Refund for " + original_txn_id, timestamp
        );
    }
};`
    },
  ],
  diagrams: [
    {
      title: "Payment System High-Level Architecture",
      kind: "architecture",
      caption: "Layered architecture: the synchronous happy path (authorize then capture) flows down through the gateway, payment core, ledger, and PSP adapters; the asynchronous path (PSP webhooks, Kafka events, T+1 reconciliation, payouts) flows through the async pipeline. Card data bypasses the backend entirely via the PCI vault.",
      mermaid: `graph TB
    subgraph CLIENTS["Clients"]
        CHECKOUT["Checkout UI<br/>generates idempotency key"]
    end
    subgraph GATEWAY["Edge and Gateway"]
        LB["Load Balancer"]
        APIGW["API Gateway<br/>authN, rate limiting"]
    end
    subgraph CORE["Payment Core"]
        PAYSVC["Payment Service<br/>state machine"]
        IDEMSTORE["Idempotency Store<br/>key to stored response"]
        RISKSVC["Risk / Fraud Scoring<br/>inline, sub-100ms"]
    end
    subgraph LEDGERL["Ledger"]
        LEDGERDB["Double-Entry Ledger DB<br/>append-only, immutable"]
        BALVIEW["Balance Views<br/>derived, reconciled to entries"]
    end
    subgraph EXTERNAL["External PSPs"]
        PSPROUTER["PSP Router<br/>failover + smart routing"]
        CBSTRIPE["Circuit Breaker"]
        CBADYEN["Circuit Breaker"]
        CBBANK["Circuit Breaker"]
        STRIPE["Stripe Adapter"]
        ADYEN["Adyen Adapter"]
        BANKS["Bank Rails Adapter<br/>ACH / SEPA"]
    end
    subgraph ASYNC["Async Pipeline"]
        KAFKA["Kafka<br/>payment events"]
        WEBHOOK["Webhook Processor<br/>PSP callbacks, dedup by event id"]
        RECONJOB["Reconciliation Jobs<br/>T+1 settlement files"]
        PAYOUTSVC["Payout Service"]
    end
    subgraph COMPLIANCE["Compliance Boundary"]
        PCIVAULT["PCI Vault<br/>tokenization, card data only here"]
        AUDITLOG["Audit Log<br/>every state transition"]
    end
    CHECKOUT -- "card details, never via backend" --> PCIVAULT
    PCIVAULT -- "token" --> CHECKOUT
    CHECKOUT -- "1. authorize (token + idempotency key)" --> LB
    LB --> APIGW
    APIGW --> PAYSVC
    PAYSVC -- "check / store response" --> IDEMSTORE
    PAYSVC -- "2. score before PSP call" --> RISKSVC
    PAYSVC -- "3. route authorize / capture" --> PSPROUTER
    PSPROUTER --> CBSTRIPE --> STRIPE
    PSPROUTER --> CBADYEN --> ADYEN
    PSPROUTER --> CBBANK --> BANKS
    PAYSVC -- "4. paired debit + credit entries" --> LEDGERDB
    LEDGERDB --> BALVIEW
    PAYSVC -- "publish state changes" --> KAFKA
    PAYSVC --> AUDITLOG
    STRIPE -. "async webhook: captured / settled / disputed" .-> WEBHOOK
    ADYEN -. "async webhook" .-> WEBHOOK
    WEBHOOK -- "dedup, then advance state machine" --> PAYSVC
    STRIPE -. "T+1 settlement file" .-> RECONJOB
    RECONJOB -- "compare against ledger, raise discrepancies" --> LEDGERDB
    KAFKA --> PAYOUTSVC
    PAYOUTSVC -- "merchant payouts via PSP rails" --> PSPROUTER`
    },
    {
      title: "Payment Processing Sequence",
      kind: "sequence",
      caption: "Sequence of operations for processing a payment from client request through fraud check, provider charge, and ledger recording.",
      mermaid: `sequenceDiagram
    participant C as Client
    participant P as Payment Service
    participant I as Idempotency Store
    participant F as Fraud Service
    participant PSP as Payment Provider
    participant L as Ledger Service

    C->>P: Create Payment (idempotency_key)
    P->>I: Check idempotency key
    I-->>P: Key not found (new request)
    P->>P: Create payment record (CREATED)
    P->>F: Evaluate fraud risk
    F-->>P: Risk score: LOW
    P->>P: Transition to PROCESSING
    P->>PSP: Charge card (token, amount)
    PSP-->>P: Charge succeeded
    P->>P: Transition to CAPTURED
    P->>L: Record debit + credit entries
    L-->>P: Ledger updated
    P->>I: Store result with idempotency key
    P-->>C: Payment succeeded`
    },
    {
      title: "Payment State Machine",
      kind: "flow",
      caption: "Complete payment lifecycle showing all valid state transitions including refunds, chargebacks, and failure paths.",
      mermaid: `flowchart TD
    CREATED["CREATED"] --> PROCESSING["PROCESSING"]
    CREATED --> FAILED["FAILED"]
    PROCESSING --> AUTHORIZED["AUTHORIZED"]
    PROCESSING --> CAPTURED["CAPTURED"]
    PROCESSING --> FAILED
    AUTHORIZED --> CAPTURED
    AUTHORIZED --> FAILED
    CAPTURED --> SETTLED["SETTLED"]
    CAPTURED --> REFUND_PENDING["REFUND PENDING"]
    CAPTURED --> CHARGEBACK["CHARGEBACK"]
    SETTLED --> REFUND_PENDING
    SETTLED --> CHARGEBACK
    REFUND_PENDING --> REFUNDED["REFUNDED"]
    REFUND_PENDING --> PARTIAL["PARTIALLY REFUNDED"]
    REFUND_PENDING --> FAILED
    PARTIAL --> REFUND_PENDING`
    },
    {
      title: "Reconciliation Flow",
      kind: "flow",
      caption: "How reconciliation compares internal payment records against external provider reports to detect and resolve discrepancies.",
      mermaid: `flowchart TD
    INTERNAL["Internal Payment Records"] --> COMPARE["Reconciliation Engine"]
    EXTERNAL["Provider Settlement Report"] --> COMPARE
    COMPARE --> MATCH{"Records Match?"}
    MATCH -->|"Yes"| RECONCILED["Mark Reconciled"]
    MATCH -->|"No"| CLASSIFY["Classify Discrepancy"]
    CLASSIFY --> MISSING["Missing Transaction"]
    CLASSIFY --> AMOUNT["Amount Mismatch"]
    CLASSIFY --> STATUS["Status Mismatch"]
    MISSING --> AUTO{"Auto-resolvable?"}
    AMOUNT --> REVIEW["Manual Review Queue"]
    STATUS --> AUTO
    AUTO -->|"Yes"| RESOLVE["Auto-resolve"]
    AUTO -->|"No"| REVIEW
    RESOLVE --> RECONCILED
    REVIEW --> RECONCILED`
    },
  ],
  interviewQA: [
    {
      q: "How would you design a payment system that handles thousands of transactions per second with 99.999% reliability?",
      a: "The core design principle is exactly-once semantics through idempotency. Every payment request carries a client-generated idempotency key (UUID). The payment service checks the idempotency store before processing — if the key exists, return the cached result. The payment flows through a state machine: CREATED -> PROCESSING -> CAPTURED/FAILED, with each transition persisted transactionally. Double-entry bookkeeping records every financial movement as paired debit/credit entries in an append-only ledger. For 99.999% reliability (5.26 minutes downtime/year), the system needs: multi-AZ deployment with automatic failover, circuit breakers for payment provider calls, fallback to secondary providers when the primary is down, and comprehensive retry logic with exponential backoff for transient failures. The database uses synchronous replication across AZs with automated failover. Reconciliation runs continuously, comparing internal records against provider reports to catch any inconsistencies. PCI compliance is achieved by never touching raw card data — clients use the provider's SDK for tokenization.",
      followUps: [
        "How do you handle the case where the payment provider times out?",
        "What is the failure mode if the idempotency store is unavailable?",
        "How would you implement multi-provider failover?",
      ],
    },
    {
      q: "Explain how idempotency works in payment processing and why it is critical.",
      a: "Idempotency ensures that retrying a payment request produces the same result as the original request — the customer is charged exactly once regardless of how many times the request is sent. The client generates a UUID (idempotency key) before making the payment request and includes it in every attempt. On the server side, when a request arrives, the service first checks the idempotency store: if the key exists with a completed result, that result is returned immediately without reprocessing. If the key exists but is marked 'in-progress', the server returns a 409 Conflict (preventing concurrent processing of the same payment). If the key is not found, the server creates an entry marked 'in-progress', processes the payment, and atomically updates the entry with the result. The critical requirement is that the idempotency key storage and the payment result storage happen in the same database transaction — otherwise, a crash between the two writes could leave the system in an inconsistent state. Keys expire after 24-48 hours to prevent unbounded storage growth. This pattern is essential because network failures, client retries, and load balancer timeouts all create scenarios where the same payment request is sent multiple times.",
      followUps: [
        "What happens if the idempotency key store and the payment database are different systems?",
        "How do you handle idempotency for payments that involve multiple steps (authorize then capture)?",
      ],
    },
    {
      q: "How does double-entry bookkeeping work in a payment system, and why is it important?",
      a: "Double-entry bookkeeping records every financial movement as two entries that balance to zero: a debit (money leaving an account) and a credit (money arriving at an account). When a customer pays $100, the system creates a debit of $100 from the customer's payment account and a credit of $100 to the merchant's receivables account. The fundamental invariant — sum of all debits equals sum of all credits — is verified continuously. If the invariant is violated, it indicates a bug or data corruption. The ledger is append-only and immutable: corrections are made by adding reversal entries, not by modifying existing ones. This creates a complete, auditable history of every financial movement. Account balances are derived by summing all entries for that account (credits minus debits), never stored as a mutable counter — this eliminates a class of race conditions and data corruption bugs. For performance, materialized balance views are maintained but periodically reconciled against the ledger sum. This approach is not optional for financial systems — it is a regulatory requirement in most jurisdictions and the basis for financial auditing.",
      followUps: [
        "How do you handle partial refunds in the ledger?",
        "How does multi-currency work in the ledger?",
      ],
    },
    {
      q: "How would you implement reconciliation between your payment system and external payment providers?",
      a: "Reconciliation compares internal records against external records at multiple frequencies. Real-time reconciliation matches incoming provider webhooks (payment confirmations, declines) against pending internal payment records — any unmatched webhook or timeout is flagged immediately. Hourly batch reconciliation aggregates transaction counts and totals per provider and compares against provider dashboard APIs, catching bulk discrepancies. Daily settlement reconciliation downloads the provider's settlement file (a detailed list of all transactions included in the daily settlement) and matches each transaction against internal records by provider transaction ID. Discrepancies are classified: 'missing internal' (provider has a record we do not — possible lost webhook), 'missing provider' (we have a record they do not — possible failed submission), 'amount mismatch' (different amounts — possible currency conversion issue), and 'status mismatch' (we think succeeded, they think failed). Each class has auto-resolution rules: a missing-internal record triggers a re-fetch from the provider API, while an amount mismatch above a threshold is escalated to manual review. The reconciliation system maintains a dashboard showing reconciliation rate (target: 99.99%), open discrepancies, and aging of unresolved items.",
      followUps: [
        "How do you handle reconciliation across time zones and settlement dates?",
        "What if reconciliation reveals a double charge?",
      ],
    },
    {
      q: "How do you handle refunds and chargebacks in a payment system?",
      a: "Refunds are initiated by the merchant and flow through the payment state machine: a CAPTURED or SETTLED payment transitions to REFUND_PENDING, then to REFUNDED (full) or PARTIALLY_REFUNDED. The refund request carries its own idempotency key to prevent double refunds. The system validates that the refund amount does not exceed the original payment amount minus any previous refunds. The ledger records a reversal: a debit from the merchant's account and a credit to the customer's refund account. The actual refund is submitted to the payment provider, which pushes it back through the card network to the customer's bank (taking 5-10 business days to appear on the customer's statement). Chargebacks are initiated by the customer's bank, not the merchant — they are received as webhooks from the payment provider. A chargeback immediately debits the disputed amount from the merchant's account plus a chargeback fee ($15-25 typically). The merchant can contest with evidence (delivery proof, signed receipt) within a deadline (typically 30 days). The system must track chargeback rates per merchant — card networks impose penalties (increased fees, account termination) if chargeback rates exceed thresholds (typically 1% of transactions).",
      followUps: [
        "How would you design the chargeback evidence submission workflow?",
        "How do refund exchange rates work for multi-currency transactions?",
      ],
    },
    {
      q: "Your call to the PSP times out after you sent an authorize request. What do you do?",
      a: "This is the hardest single moment in payment processing because the outcome is unknowable from your side: the PSP may have (a) never received the request, (b) received it and declined, or (c) received it and authorized — and a timeout looks identical in all three cases. The wrong answers are to assume failure (case c leaves the customer's funds held with no record on your side) or to blindly retry through a different PSP (case c plus a second authorization double-holds the customer's funds). The correct sequence: first, the payment stays in PROCESSING — never transition to FAILED on a timeout. Second, retry the same PSP with the same idempotency key; because the PSP dedups on that key, this is safe and resolves cases a and b immediately. Third, if retries are exhausted (PSP outage), query the PSP's status API for the payment by idempotency key or your reference id, and independently rely on the PSP's webhook, which will eventually report the outcome. Fourth, if the outcome is still unknown after a bounded window, issue a void/cancel with the same reference — most PSPs make cancellation of a possibly-nonexistent authorization safe — and only then fail the payment and optionally re-route a fresh attempt (new PSP transaction, same customer intent, guarded by the customer-level idempotency key). Finally, T+1 reconciliation is the backstop: any authorization that slipped through every real-time check shows up in the settlement file and lands in the discrepancy queue. The interviewer is checking that you treat 'unknown' as a first-class state with a resolution protocol, not an error to guess about.",
      followUps: [
        "How long do you keep a payment in PROCESSING before involving the customer?",
        "What does the checkout UI show while the outcome is unknown?",
        "How does this interact with the customer abandoning the session?",
      ],
    },
    {
      q: "PSP webhooks can arrive duplicated, out of order, or not at all. How do you build a correct webhook processor?",
      a: "Design for at-least-once, unordered delivery because that is what every PSP contractually gives you. The pipeline: (1) Verify the webhook signature against the PSP's signing secret to reject forgeries. (2) Insert the raw event into an events table keyed by the PSP's event id with a unique constraint — a duplicate delivery violates the constraint and is acknowledged and dropped; this single insert is the entire dedup mechanism. (3) Return 200 immediately and process asynchronously (the events table doubles as a queue, or you publish to Kafka), because slow synchronous handling causes the PSP to time out and redeliver, creating the very duplicates you are defending against. (4) Handle out-of-order delivery by treating the event as a notification, not a command: the handler re-fetches the payment object from the PSP API and reconciles the state machine against that fetched state, so a stale payment.authorized arriving after payment.captured is a harmless no-op. (5) Make every handler idempotent as a pure function of current internal state plus fetched PSP state — redelivery after a mid-handler crash must converge to the same result. For the not-at-all case, run a sweeper that finds payments stuck in non-terminal states beyond a threshold and polls the PSP directly, with T+1 settlement-file reconciliation as the final backstop. Monitor webhook lag and the stuck-payment count as first-class alerts, because silent webhook loss is how you learn about PSP incidents.",
      followUps: [
        "Why is 'fetch the object, do not trust the event payload' the standard pattern?",
        "How do you replay webhooks after a bug in the handler is fixed?",
        "How would you test out-of-order delivery in CI?",
      ],
    },
  ],
  mcqs: [
    {
      q: "Why must the idempotency key and payment result be stored in the same database transaction?",
      options: [
        "To improve query performance",
        "To prevent double-charging if a crash occurs between storing the key and the payment result",
        "To reduce storage requirements",
        "To comply with PCI DSS",
      ],
      answerIndex: 1,
      explanation: "If the payment is processed and the result stored, but a crash occurs before the idempotency key is recorded, a retry would not find the key and would reprocess the payment — double-charging the customer. Atomic storage of both in one transaction prevents this.",
    },
    {
      q: "In double-entry bookkeeping, what does a balanced ledger (debits equal credits) guarantee?",
      options: [
        "All payments were successful",
        "No money was created or destroyed — every outflow has a corresponding inflow",
        "The exchange rates are correct",
        "All refunds were processed",
      ],
      answerIndex: 1,
      explanation: "The fundamental invariant of double-entry bookkeeping is conservation of money: every debit (outflow) is matched by a credit (inflow) of the same amount. An imbalanced ledger indicates a bug, data corruption, or fraud — money appeared or disappeared without explanation.",
    },
    {
      q: "Why should payment amounts be stored as integers (cents) rather than floating-point numbers?",
      options: [
        "Integers use less storage space",
        "Floating-point arithmetic introduces rounding errors that cause financial discrepancies",
        "Integers are faster to process",
        "Regulatory requirements mandate integer storage",
      ],
      answerIndex: 1,
      explanation: "Floating-point representation cannot exactly represent many decimal fractions (e.g., 0.1 in binary is 0.0001100110011...). Arithmetic on these approximations accumulates rounding errors, causing ledger imbalances. Storing $10.50 as 1050 cents avoids this entirely.",
    },
    {
      q: "What is the purpose of exponential backoff with jitter in payment retry logic?",
      options: [
        "To comply with payment provider rate limits only",
        "To spread out retries over time and prevent thundering herd when a provider recovers from an outage",
        "To reduce the total number of retries",
        "To improve payment success rates",
      ],
      answerIndex: 1,
      explanation: "Without jitter, all clients retry at the same exponential intervals, creating synchronized bursts that can overwhelm a recovering provider. Jitter adds random variation (e.g., +/- 50%) to each interval, spreading retries uniformly over time and giving the provider a chance to recover gracefully.",
    },
  ],
  flashcards: [
    { front: "What is an idempotency key?", back: "A client-generated UUID included with every payment request. The server stores the key alongside the result; retries with the same key return the cached result without reprocessing. Prevents double-charging due to network retries. Keys expire after 24-48 hours." },
    { front: "What is the double-entry bookkeeping invariant?", back: "Sum of all debits must equal sum of all credits (net zero for every transaction). Violations indicate bugs, corruption, or fraud. Ledger is append-only — corrections use reversal entries, never modifications." },
    { front: "Name the key states in a payment state machine.", back: "CREATED -> PROCESSING -> AUTHORIZED -> CAPTURED -> SETTLED. Failure: any state -> FAILED. Refund: CAPTURED/SETTLED -> REFUND_PENDING -> REFUNDED/PARTIALLY_REFUNDED. Chargeback: CAPTURED/SETTLED -> CHARGEBACK." },
    { front: "Why store amounts in smallest currency unit (cents)?", back: "Floating-point arithmetic introduces rounding errors (0.1 cannot be represented exactly in binary). Storing $10.50 as 1050 cents ensures exact arithmetic. Note: JPY and KRW have no subunits — 1 yen is already the smallest unit." },
    { front: "What is reconciliation in payments?", back: "Comparing internal payment records against external provider records to detect discrepancies. Runs at multiple frequencies: real-time (webhooks), hourly (batch totals), daily (settlement files). Target reconciliation rate: 99.99%." },
    { front: "How does PCI compliance affect architecture?", back: "Raw card numbers never touch your servers. Client-side SDK sends card data directly to the PCI-compliant provider, which returns a token. Your backend only handles tokens. This minimizes PCI scope to SAQ-A or SAQ A-EP level." },
    { front: "What is the Saga pattern in payments?", back: "A sequence of local transactions with compensating actions for rollback. If step 3 fails, compensating actions for steps 2 and 1 execute (e.g., void the charge, release the hold). Orchestrated sagas use a central coordinator; choreographed sagas use event-driven reactions." },
    { front: "What are retriable vs non-retriable payment failures?", back: "Retriable: network timeout, 5xx server error, rate limit (429). Non-retriable: card declined, insufficient funds, invalid card, fraud block. Retrying non-retriable errors wastes resources and degrades user experience." },
    { front: "What are the three failure windows an idempotency key protects against?", back: "1) Request lost before the server sees it (retry is a fresh attempt). 2) Response lost after processing (replay the stored response). 3) Server crash mid-processing (in-progress marker; resolve by querying the PSP). The client cannot distinguish them, so the key must flow end-to-end." },
    { front: "What is the protocol when a PSP authorize call times out?", back: "Keep the payment in PROCESSING. Retry the same PSP with the same idempotency key, then query the PSP status API, then rely on the webhook, then void after a bounded window. Never assume failure and never retry a timed-out authorize on a different PSP (risk of double authorization)." },
    { front: "How do you deduplicate PSP webhooks?", back: "Insert the raw event keyed by the PSP's event id with a unique constraint — the failed insert is the dedup. Ack 200 immediately, process asynchronously, and re-fetch the object from the PSP API rather than trusting the event payload, which also neutralizes out-of-order delivery." },
    { front: "Why integrate multiple PSPs, and what is the failover constraint?", back: "Availability (PSP outages), cost (fee differences), and authorization rates (1-3% lift from smart routing). Constraint: failover is only safe for payments the first PSP has definitely not seen; card tokens are usually PSP-scoped, so tokenized retries cannot simply move to another PSP." },
    { front: "What is a discrepancy queue in reconciliation?", back: "A first-class table of reconciliation mismatches from the T+1 settlement-file three-way match (file vs payments vs ledger), each with classification (missing-internal/external, amount, status, fee), severity, owner, and aging SLA. Auto-resolution clears timing differences; humans work the residue." },
  ],
  exercises: [
    "Design the database schema for a payment system including tables for payments (with state machine), idempotency keys, ledger entries, refunds, and reconciliation records. Include indexes, constraints, and explain the choice between SQL and NoSQL.",
    "Implement a payment Saga orchestrator that coordinates: fraud check, payment provider charge, ledger entry, and notification. Define the compensating action for each step and handle partial failures. Test with simulated provider timeouts.",
    "Build a reconciliation engine that compares a CSV settlement file from a payment provider against internal payment records. Classify discrepancies (missing, amount mismatch, status mismatch), implement auto-resolution for common cases, and generate a discrepancy report.",
    "Design a multi-currency payment flow: customer pays in EUR, merchant settles in USD. Handle exchange rate capture, conversion fee accounting, and refund in original currency. Show all ledger entries for the complete lifecycle.",
    "Implement retry logic with exponential backoff and jitter for payment provider calls. Classify error codes into retriable/non-retriable, implement circuit breaker for sustained failures, and add fallback to a secondary provider.",
  ],
  revisionNotes: [
    "Idempotency key: client-generated UUID, stored atomically with payment result. Retries return cached result. TTL: 24-48 hours. Critical for exactly-once semantics.",
    "Double-entry bookkeeping: every transaction = debit + credit that sum to zero. Append-only ledger. Balances derived from entry sums, never stored as mutable counters.",
    "Payment state machine: CREATED -> PROCESSING -> AUTHORIZED -> CAPTURED -> SETTLED. Terminal states: SETTLED, FAILED, REFUNDED, CHARGEBACK.",
    "Store amounts as integers in smallest currency unit (cents). $10.50 = 1050. JPY has no subunits. Prevents floating-point rounding errors.",
    "Retry strategy: exponential backoff (1s, 2s, 4s, 8s) with jitter (+/- 50%). Max 5 retries. Classify errors as retriable (timeout, 5xx) or non-retriable (declined).",
    "PCI compliance: tokenization via client-side SDK. Never store raw card numbers. Minimize PCI scope to SAQ-A level. Never log PANs or CVVs.",
    "Reconciliation: real-time (webhooks), hourly (batch totals), daily (settlement files). Target: 99.99% reconciliation rate.",
    "Saga pattern for distributed transactions: orchestrated coordinator drives steps with compensating actions. Outbox pattern ensures atomic DB write + event publish.",
    "Refunds reverse the original ledger entries. Validate refund amount <= original - previous refunds. Multi-currency refunds use original exchange rate.",
    "Chargeback rate threshold: typically 1% of transactions. Exceeding triggers card network penalties. Track per-merchant chargeback rates.",
    "Scale math is easy (1M payments/day = ~12/s avg, ~100/s peak); correctness math is the point: ledger entries per transaction must sum to zero, always.",
    "Three failure windows per attempt: request lost (retry = fresh), response lost (replay stored response), crash mid-processing (in-progress marker, resolve via PSP query). Client cannot distinguish them — hence end-to-end idempotency keys.",
    "PSP timeout protocol: stay in PROCESSING, retry same PSP with same key, then status query, then webhook, then void, then reconciliation. Never assume failure; never retry a timed-out authorize on a second PSP.",
    "Webhooks: at-least-once and unordered by contract. Dedup via unique constraint on PSP event id, ack 200 fast, process async, re-fetch object from PSP API instead of trusting the payload.",
    "Multi-PSP: adapter + circuit breaker per PSP, router chooses by currency/scheme/auth-rate/cost. Failover applies to new payments only; tokens are PSP-scoped.",
    "Reconciliation output is a discrepancy queue with classification, severity, owner, and aging SLA — not alerts. Also reconcile ledger against its own derived balance views nightly.",
  ],
  cheatSheet: [
    "Idempotency: client UUID per request, atomic store with result, 24-48h TTL",
    "Double-entry: every txn = debit + credit = zero sum, append-only ledger",
    "State machine: CREATED -> PROCESSING -> AUTHORIZED -> CAPTURED -> SETTLED",
    "Amounts: integers in smallest unit (cents). $10.50 = 1050. No floats ever.",
    "Retry: exponential backoff 1s/2s/4s/8s + jitter, max 5 retries, classify errors",
    "PCI: tokenization via provider SDK, never touch raw card data, SAQ-A scope",
    "Reconciliation: real-time webhooks + hourly batch + daily settlement file",
    "Saga: local txn + compensating action per step, orchestrated coordinator",
    "Refund: validate amount, reverse ledger entries, original exchange rate for multi-currency",
    "99.999% uptime = 5.26 min/year downtime. Multi-AZ, auto-failover, circuit breakers.",
    "Scale: 1M/day = ~12 QPS avg, ~100 QPS peak. Low QPS, max correctness — optimize for consistency, not throughput.",
    "PSP timeout: PROCESSING + retry same key -> status query -> webhook -> void -> reconciliation. Never guess, never cross-PSP retry.",
    "Webhooks: verify signature, unique-constraint dedup on event id, ack fast, process async, re-fetch object.",
    "Multi-PSP: per-PSP adapter + circuit breaker, router by cost/auth-rate, failover for new payments only.",
    "Ledger is source of truth; payment rows are a projection. When they disagree, the ledger wins.",
  ],
  glossary: [
    { term: "Idempotency Key", definition: "A unique identifier (typically UUID) attached to a payment request that ensures the same request processed multiple times produces the same result. Prevents double-charging due to retries." },
    { term: "Double-Entry Bookkeeping", definition: "An accounting method where every financial transaction records equal debits and credits across accounts. The invariant that total debits equal total credits provides built-in error detection." },
    { term: "Payment State Machine", definition: "A finite state machine defining valid payment states (CREATED, PROCESSING, CAPTURED, etc.) and transitions between them, ensuring payments follow a well-defined lifecycle with no invalid transitions." },
    { term: "Reconciliation", definition: "The process of comparing internal financial records against external records (bank statements, provider reports) to detect and resolve discrepancies. The ultimate verification of financial accuracy." },
    { term: "PCI DSS (Payment Card Industry Data Security Standard)", definition: "A set of security standards for organizations handling credit card data. Compliance levels (SAQ-A through SAQ-D) depend on how directly the system handles card data." },
    { term: "Tokenization", definition: "Replacing sensitive card data with a non-sensitive equivalent (token) that can be stored and transmitted safely. The payment provider maintains the token-to-card mapping in their PCI-compliant vault." },
    { term: "Chargeback", definition: "A forced reversal of a payment initiated by the customer's bank. The merchant is debited the disputed amount plus a fee. High chargeback rates (>1%) trigger card network penalties." },
  ],
  animations: [
    {
      title: "Charging once, provably",
      steps: [
        {
          label: "Client requests payment",
          detail: "Sends an idempotency key generated for this attempt.",
        },
        {
          label: "Record intent",
          detail: "A payment row is written as `pending` in the same transaction that stores the key.",
        },
        {
          label: "Call the processor",
          detail: "With the same idempotency key, so the processor also deduplicates.",
        },
        {
          label: "Timeout",
          detail: "The response is lost. Status is unknown — the most important case to handle.",
        },
        {
          label: "Reconcile",
          detail: "Never assume failure. Query the processor by the key, or wait for the webhook, and settle the row accordingly.",
        },
        {
          label: "Ledger",
          detail: "Record double-entry rows, append-only. Never mutate a financial record; correct it with a compensating entry.",
        },
      ],
    },
  ],
  comparison: {
    columns: ["Aspect", "Direct Card Processing", "Payment Gateway (Stripe/Adyen)", "Bank Transfer (ACH/SEPA)", "Digital Wallet (PayPal/Apple Pay)"],
    rows: [
      ["PCI Scope", "Full SAQ-D (highest burden)", "SAQ-A (minimal — tokenized)", "Not applicable", "SAQ-A (tokenized)"],
      ["Settlement Time", "1-3 business days", "2-7 business days (provider dependent)", "1-5 business days", "Instant to 1 day"],
      ["Transaction Fees", "Interchange + markup (~2-3%)", "Fixed % + per-txn (2.9% + $0.30)", "Low flat fee ($0.20-$1.50)", "2.9% + $0.30 typical"],
      ["Chargeback Risk", "High (merchant bears liability)", "Medium (provider tools help)", "Low (hard to reverse)", "Medium (buyer protection)"],
      ["Multi-Currency", "Complex (direct FX handling)", "Built-in (provider handles FX)", "Limited (same-currency networks)", "Built-in"],
      ["Implementation Complexity", "Very high (build everything)", "Low (SDK + API)", "Medium (bank API integration)", "Low (SDK)"],
      ["Recurring Payments", "Must manage card storage", "Built-in token vault", "Mandate-based (easy)", "Varies by provider"],
    ],
  },
  followUps: [
    "How would you design a payment system that supports both real-time payments (like UPI/Pix) and traditional card payments?",
    "How would you implement a marketplace payment system where payments are split between multiple sellers and the platform?",
    "How would you add cryptocurrency payment support alongside traditional payment methods?",
    "How would you design the fraud detection ML pipeline for real-time scoring at payment time?",
    "How would you handle payment system migration from one payment provider to another without downtime?",
    "How would you design a subscription billing system with trials, upgrades, downgrades, and prorated charges?",
    "How would you migrate a running ledger to a new schema while payments continue to flow, without ever showing an unbalanced ledger?",
    "How would you design the payout side — aggregating captured funds, netting fees and refunds, and paying merchants on a schedule?",
    "How would you keep authorization latency low while adding an inline ML fraud model that needs feature lookups?",
  ],
  resources: [
    { label: "Designing Data-Intensive Applications (Kleppmann)", url: "https://dataintensive.net/", kind: "book", note: "Chapters on transactions, consistency, and distributed systems provide the theoretical foundation for payment system design." },
    { label: "Stripe API Documentation", url: "https://docs.stripe.com/api", kind: "docs", note: "The best real-world reference for payment API design: idempotency, webhooks, state machine, and error handling patterns." },
    { label: "How Stripe Builds Payment Infrastructure (Stripe Engineering Blog)", kind: "article", note: "Detailed posts on idempotency keys, ledger design, reconciliation, and the challenges of financial infrastructure at scale." },
    { label: "Payment Systems: Design, Governance, Oversight (Summers)", kind: "book", note: "Academic treatment of payment system design covering clearing, settlement, risk management, and regulatory frameworks." },
    { label: "Building a Modern Payment System (InfoQ Talk)", kind: "video", note: "Conference talk covering state machines, saga patterns, and reconciliation in production payment systems." },
  ],
};
