import type { TopicContent } from "../types";

export const pkiCertificates: TopicContent = {
  quickSummary: [
    "Public Key Infrastructure (PKI) is the framework of policies, hardware, software, and procedures needed to create, manage, distribute, and revoke digital certificates that bind public keys to identities.",
    "X.509 certificates are the standard format containing a subject's public key, identity information, issuer (CA) details, validity period, and the CA's digital signature — used in TLS/SSL, code signing, and email encryption.",
    "The Certificate Authority (CA) chain of trust works hierarchically: root CAs (trusted by OS/browsers) sign intermediate CA certificates, which sign end-entity (leaf) certificates — creating a verifiable trust chain.",
    "Certificate Signing Requests (CSRs) are generated by the entity requesting a certificate, containing their public key and identity information, submitted to a CA for validation and signing.",
  ],
  detailed: [
    `## X.509 Certificate Structure

X.509 is the ITU-T standard for digital certificates, used universally in TLS/SSL, code signing, S/MIME email, and document signing.

**Key fields in an X.509 v3 certificate:**
- **Version**: Almost always v3 (supports extensions)
- **Serial Number**: Unique identifier assigned by the CA
- **Signature Algorithm**: Algorithm the CA used to sign (e.g., SHA256withRSA, ECDSA)
- **Issuer**: Distinguished Name (DN) of the CA that signed the certificate
- **Validity**: Not Before and Not After timestamps
- **Subject**: DN of the certificate holder (e.g., CN=example.com, O=Example Inc)
- **Subject Public Key Info**: The public key and its algorithm (RSA 2048, ECDSA P-256)
- **Extensions (v3)**:
  - Subject Alternative Names (SANs): Additional domains/IPs the cert is valid for
  - Key Usage: What the key can be used for (digital signature, key encipherment)
  - Extended Key Usage: Specific purposes (TLS server auth, client auth, code signing)
  - Basic Constraints: Whether this is a CA certificate and maximum chain depth
  - CRL Distribution Points: Where to check for revocation
  - Authority Information Access: OCSP responder URL

**Certificate encoding formats:**
- **PEM**: Base64-encoded DER with header/footer lines. Human-readable. Most common on Linux.
- **DER**: Binary encoding. Used by Java and Windows.
- **PKCS#12 / PFX**: Binary format bundling certificate + private key + chain. Password-protected.`,

    `## Certificate Authority Chain of Trust

PKI operates on a hierarchical trust model:

**Root CA**: Self-signed certificate that forms the trust anchor. Root CA certificates are pre-installed in operating systems and browsers (the "trust store"). Root CAs are kept offline in HSMs (Hardware Security Modules) for security — if a root CA key is compromised, the entire trust hierarchy collapses.

**Intermediate CA**: Signed by the root CA. Intermediate CAs issue end-entity certificates. They provide a layer of indirection — the root CA key is used rarely (only to sign intermediate certs), limiting its exposure. If an intermediate is compromised, only it is revoked without affecting the root.

**End-entity (leaf) certificate**: Signed by an intermediate CA. This is the certificate presented by a web server during the TLS handshake.

**Verification chain:**
\`\`\`
Browser connects to example.com
  -> Server presents leaf cert (example.com, signed by Intermediate CA)
  -> Server also sends Intermediate CA cert (signed by Root CA)
  -> Browser has Root CA in its trust store
  -> Browser verifies: Root CA signature on Intermediate -> Intermediate signature on Leaf
  -> Chain is valid, connection is trusted
\`\`\`

If any certificate in the chain is expired, revoked, or the signatures don't verify, the chain is broken and the connection is rejected.`,

    `## Certificate Lifecycle: CSR, Issuance, Renewal, Revocation

**Certificate Signing Request (CSR):**
1. The entity generates a public-private key pair
2. Creates a CSR containing: the public key, subject DN (organization, domain), and requested extensions
3. Signs the CSR with the private key (proving possession)
4. Submits the CSR to a CA

**Domain Validation (DV):** CA verifies domain ownership via DNS record, HTTP challenge, or email. Automated (Let's Encrypt). Minutes to issue.

**Organization Validation (OV):** CA verifies the organization's legal existence and domain ownership. Days to issue.

**Extended Validation (EV):** Rigorous verification of legal identity, operational existence, and authority of the requester. Days to weeks. Browsers used to show a green bar (now deprecated in most browsers).

**Revocation mechanisms:**
- **CRL (Certificate Revocation List):** CA publishes a list of revoked certificate serial numbers. Clients download and check. Drawback: CRLs grow large and have caching delays.
- **OCSP (Online Certificate Status Protocol):** Client queries the CA's OCSP responder in real-time for a specific certificate's status. More efficient than CRLs.
- **OCSP Stapling:** The server periodically fetches its own OCSP response and "staples" it to the TLS handshake, eliminating the client's need to contact the CA separately. Recommended for performance and privacy.

**Certificate Transparency (CT):** Public, append-only logs of all issued certificates. Browsers require CT log inclusion, allowing domain owners to detect unauthorized certificate issuance.`,

    `## Certificate Pinning

Certificate pinning restricts which certificates or public keys a client accepts for a specific domain, preventing man-in-the-middle attacks even with a compromised or rogue CA.

**Types of pinning:**
- **Certificate pinning**: Pin the exact leaf certificate. Most restrictive — must update the pin when the certificate is renewed.
- **Public key pinning**: Pin the Subject Public Key Info (SPKI) hash. The pin survives certificate renewal as long as the same key pair is used.
- **CA pinning**: Pin the intermediate or root CA. Less restrictive — any certificate from that CA is accepted.

**Implementation approaches:**
- **HPKP (HTTP Public Key Pinning)**: Deprecated browser standard — too risky, mistakes caused permanent lockout.
- **Mobile app pinning**: Embed expected certificate/key hashes in the app. Most common use case today. Libraries: TrustKit (iOS), OkHttp CertificatePinner (Android).
- **API client pinning**: Configure HTTP clients to accept only specific certificates for specific endpoints.

**Risks of pinning:**
- If the pinned certificate/key is lost or compromised, the application is locked out until updated
- Requires careful key rotation planning — always pin a backup key
- Certificate renewal with a new key breaks the pin
- Not recommended for web browsers (HPKP is deprecated) but valuable for mobile apps and API clients

**Best practice**: Pin the public key of the intermediate CA, and include a backup pin. This survives leaf certificate renewals while still restricting to a specific CA chain.`,

    `## Let's Encrypt and ACME Protocol

**Let's Encrypt** is a free, automated, non-profit Certificate Authority that has fundamentally changed TLS adoption by eliminating cost and complexity barriers.

**ACME (Automatic Certificate Management Environment)** is the protocol (RFC 8555) used by Let's Encrypt for automated certificate issuance and renewal:

1. **Account registration**: Client generates a key pair and registers with the CA
2. **Order creation**: Client requests a certificate for one or more domains
3. **Authorization challenges**: CA issues challenges to prove domain control:
   - **HTTP-01**: Place a file at \`/.well-known/acme-challenge/\` on the domain's web server
   - **DNS-01**: Create a TXT DNS record. Supports wildcard certificates.
   - **TLS-ALPN-01**: Respond to a TLS handshake with a special certificate
4. **Challenge validation**: CA verifies the challenge was completed
5. **Certificate issuance**: Client submits CSR, CA returns the signed certificate
6. **Renewal**: Certificates are valid for 90 days. Automated renewal via cron or certbot runs before expiry.

Tools: Certbot, acme.sh, Caddy (built-in ACME), Traefik (built-in ACME).

Short-lived certificates (90 days) encourage automation and limit the exposure window if a key is compromised. The entire process — from CSR to issued certificate — takes seconds with no human intervention.`,
  ],
  interviewQA: [
    {
      q: "Walk through what happens when a browser verifies a TLS certificate.",
      a: "The browser receives the server's leaf certificate and any intermediate certificates during the TLS handshake. It builds the chain: leaf -> intermediate -> root. It checks each certificate's validity period (not expired, not yet valid), verifies each signature (the root CA's public key verifies the intermediate's signature, the intermediate's public key verifies the leaf's signature), and confirms the root CA is in the browser/OS trust store. It checks the Subject Alternative Names include the requested domain, verifies the certificate hasn't been revoked (via OCSP or CRL), and checks Certificate Transparency logs. If any check fails, the browser shows a security warning.",
    },
    {
      q: "Why are root CAs kept offline and how does the intermediate CA pattern help?",
      a: "Root CA private keys are the ultimate trust anchors — their compromise would invalidate the entire CA hierarchy and every certificate they've signed. Keeping them offline in HSMs means they're physically inaccessible to network attacks. Intermediate CAs provide a buffer: the root key is only used occasionally to sign intermediate certificates, while the intermediates (which are online) handle day-to-day certificate issuance. If an intermediate CA is compromised, it can be revoked using the root without affecting other intermediates or the root itself.",
    },
    {
      q: "What is OCSP stapling and why is it better than regular OCSP?",
      a: "Regular OCSP requires the client (browser) to make a separate request to the CA's OCSP responder during the TLS handshake to check if the certificate is revoked. This adds latency, creates a privacy concern (the CA sees which sites the user visits), and introduces a dependency (if the OCSP responder is down, the check fails or is skipped). OCSP stapling has the server periodically fetch its own OCSP response and attach (staple) it to the TLS handshake. The client gets the revocation status without any extra round trip, the CA doesn't see client IPs, and there's no runtime dependency on the OCSP responder.",
    },
    {
      q: "When should you use certificate pinning and what are the risks?",
      a: "Certificate pinning is most valuable for mobile apps and API clients communicating with known backends — it prevents MITM attacks even with a compromised CA. Risks include lockout if the pinned key is lost or rotated without updating the pin, which in mobile apps means shipping an app update. Best practices: pin the intermediate CA's public key (survives leaf renewal), always include a backup pin, have a key rotation plan, and set reasonable pin expiry. Avoid pinning in browsers (HPKP was deprecated due to lockout risks and abuse potential).",
    },
  ],
  followUps: [
    "What exactly does a certificate prove, and what does it not prove?",
    "How does the chain of trust terminate, and what happens if a root is compromised?",
    "How does revocation work, and why is it considered weak in practice?",
  ],
  mcqs: [
    {
      q: "Why are root CA private keys kept offline in HSMs?",
      options: [
        "To improve certificate issuance speed",
        "To reduce storage costs",
        "Because their compromise would invalidate the entire trust hierarchy",
        "Because root CAs issue certificates directly to websites",
      ],
      answerIndex: 2,
      explanation:
        "Root CA keys are the ultimate trust anchor. Their compromise would require revoking the root and all certificates in its hierarchy. Keeping them offline in HSMs protects against network-based attacks.",
    },
    {
      q: "What does OCSP stapling improve over standard OCSP?",
      options: [
        "It uses stronger encryption",
        "It eliminates the client's need to contact the CA's OCSP responder separately",
        "It increases certificate validity period",
        "It allows self-signed certificates",
      ],
      answerIndex: 1,
      explanation:
        "OCSP stapling has the server fetch and cache its own OCSP response, attaching it to the TLS handshake. This eliminates extra client round-trips, improves privacy, and removes the OCSP responder as a runtime dependency.",
    },
    {
      q: "What ACME challenge type is required for obtaining wildcard certificates from Let's Encrypt?",
      options: ["HTTP-01", "DNS-01", "TLS-ALPN-01", "Email validation"],
      answerIndex: 1,
      explanation:
        "DNS-01 challenges (creating a TXT record) are the only ACME challenge type that supports wildcard certificate issuance, because they prove control over the entire domain, not just a specific server.",
    },
    {
      q: "What is the safest certificate pinning approach for mobile apps?",
      options: [
        "Pin the exact leaf certificate",
        "Pin the root CA certificate",
        "Pin the intermediate CA's public key with a backup pin",
        "Disable certificate validation entirely",
      ],
      answerIndex: 2,
      explanation:
        "Pinning the intermediate CA's public key survives leaf certificate renewals while still restricting to a specific CA chain. Including a backup pin prevents lockout if the primary key is rotated.",
    },
  ],
  flashcards: [
    {
      front: "What is an X.509 certificate?",
      back: "The standard format for digital certificates, containing a subject's public key, identity, issuer (CA), validity period, extensions (SANs, key usage), and the CA's digital signature. Used in TLS, code signing, and email encryption.",
    },
    {
      front: "What is a Certificate Signing Request (CSR)?",
      back: "A message sent to a CA containing the requester's public key, identity information, and requested extensions, signed with the requester's private key. The CA validates the request and issues a signed certificate.",
    },
    {
      front: "What is Certificate Transparency (CT)?",
      back: "Public, append-only logs of all issued certificates. Allows domain owners to detect unauthorized or misissued certificates for their domains. Browsers like Chrome require CT log inclusion for certificates to be trusted.",
    },
    {
      front: "What is the difference between DV, OV, and EV certificates?",
      back: "DV (Domain Validation): proves domain ownership only (automated, minutes). OV (Organization Validation): verifies organization's legal existence (days). EV (Extended Validation): rigorous identity verification (days/weeks). All provide the same encryption strength.",
    },
    {
      front: "Why do Let's Encrypt certificates expire after 90 days?",
      back: "Short validity encourages automation (no manual renewals), limits the exposure window if a private key is compromised, and promotes the use of ACME protocol for fully automated certificate lifecycle management.",
    },
    {
      front: "What is the chain of trust in PKI?",
      back: "Root CA (pre-trusted by OS/browsers, kept offline) signs Intermediate CA certs, which sign end-entity (leaf) certs. Verification walks the chain: leaf -> intermediate -> root. If any link is broken (expired, revoked, bad signature), the chain is invalid.",
    },
    {
      front: "What is HPKP and why was it deprecated?",
      back: "HTTP Public Key Pinning was a browser mechanism to pin certificate keys via HTTP headers. Deprecated because configuration mistakes caused permanent site lockout, and it could be abused by attackers who gained temporary control of headers.",
    },
  ],
  resources: [
    {
      label: "Bulletproof TLS and PKI — Ivan Ristić",
      kind: "book",
    },
    {
      label: "Let's Encrypt documentation — how it works",
      kind: "docs",
    },
  ],
  glossary: [
    {
      term: "PKI (Public Key Infrastructure)",
      definition:
        "The framework of policies, procedures, and technology for creating, managing, distributing, and revoking digital certificates that bind public keys to verified identities.",
    },
    {
      term: "X.509",
      definition:
        "The ITU-T standard format for digital certificates, specifying the structure of certificate fields including subject, issuer, validity, public key, and extensions.",
    },
    {
      term: "Certificate Authority (CA)",
      definition:
        "A trusted entity that issues digital certificates after validating the identity of the certificate requester. Root CAs are pre-trusted by operating systems and browsers.",
    },
    {
      term: "CSR (Certificate Signing Request)",
      definition:
        "A signed message containing a public key and identity information, submitted to a CA to request issuance of a digital certificate.",
    },
    {
      term: "OCSP (Online Certificate Status Protocol)",
      definition:
        "A protocol for real-time checking of a certificate's revocation status by querying the issuing CA's OCSP responder, more efficient than downloading full CRLs.",
    },
    {
      term: "Certificate Pinning",
      definition:
        "A security technique that restricts which certificates or public keys a client accepts for a specific domain, preventing MITM attacks even with a compromised CA.",
    },
    {
      term: "ACME (Automatic Certificate Management Environment)",
      definition:
        "RFC 8555 protocol for automated certificate issuance and renewal, used by Let's Encrypt and other CAs to enable fully automated TLS certificate lifecycle management.",
    },
  ],
  deepDive: [
    `**Public Key Infrastructure** is fundamentally a *trust distribution system*. At its core, PKI solves the problem of **binding a public key to a verified identity** in a scalable way. The *root of trust* begins with **Root Certificate Authorities**, whose self-signed certificates are embedded in every major OS and browser \`trust store\`. These root CAs use **Hardware Security Modules (HSMs)** — tamper-resistant devices that store the root private key *offline* — because a compromised root key would \`invalidate\` the **entire certificate hierarchy** beneath it. The mathematical foundation relies on **asymmetric cryptography**: the CA signs a certificate's hash with its *private key*, and anyone with the CA's *public key* can verify that signature using algorithms like \`RSA-2048\`, \`ECDSA P-256\`, or the newer \`Ed25519\`.`,

    `The **certificate validation pipeline** is more nuanced than a simple *chain walk*. When a TLS client receives a **leaf certificate**, it must perform several checks: verify the \`notBefore\` and \`notAfter\` timestamps, confirm the **Subject Alternative Names (SANs)** include the requested hostname, validate every signature from *leaf* up to a trusted **root CA**, and check revocation status via \`OCSP\` or \`CRL\`. Modern browsers also enforce **Certificate Transparency (CT)** — requiring that certificates appear in *publicly auditable*, **append-only logs** (typically \`2-3 independent logs\`). This prevents CAs from issuing *rogue certificates* without detection. The \`Expect-CT\` header and **SCTs (Signed Certificate Timestamps)** embedded in certificates provide *cryptographic proof* of CT log inclusion.`,

    `**Automated certificate management** via the \`ACME\` protocol has revolutionized PKI operations. Tools like \`certbot\`, \`acme.sh\`, and built-in support in **Caddy** and **Traefik** handle the entire lifecycle: *key generation*, **CSR creation**, \`challenge validation\` (HTTP-01, DNS-01, TLS-ALPN-01), *certificate issuance*, and **automated renewal**. For production deployments, best practices include using \`DNS-01\` challenges for **wildcard certificates** (\`*.example.com\`), implementing *OCSP stapling* in your web server config (\`ssl_stapling on\` in **Nginx**), and configuring \`CAA DNS records\` to restrict which CAs can issue certificates for your domain. The shift toward **short-lived certificates** (90 days with *Let's Encrypt*, and proposals for even shorter *6-day certificates*) reflects a broader trend of treating certificates as **ephemeral, automatically rotated credentials** rather than long-lived static assets.`,
  ],
  code: [
    {
      language: "cpp",
      caption: "Verifying an X.509 certificate chain using OpenSSL in C++",
      source: `#include <openssl/x509.h>
#include <openssl/x509_vfy.h>
#include <openssl/pem.h>
#include <iostream>

bool verifyCertificateChain(const char* certFile, const char* caFile) {
    // Load the certificate to verify
    FILE* fp = fopen(certFile, "r");
    X509* cert = PEM_read_X509(fp, nullptr, nullptr, nullptr);
    fclose(fp);

    // Create a trusted certificate store and load CA certs
    X509_STORE* store = X509_STORE_new();
    X509_STORE_load_locations(store, caFile, nullptr);

    // Create a verification context
    X509_STORE_CTX* ctx = X509_STORE_CTX_new();
    X509_STORE_CTX_init(ctx, store, cert, nullptr);

    // Perform verification
    int result = X509_verify_cert(ctx);

    if (result != 1) {
        int err = X509_STORE_CTX_get_error(ctx);
        std::cerr << "Verification failed: "
                  << X509_verify_cert_error_string(err) << std::endl;
    } else {
        std::cout << "Certificate chain verified successfully." << std::endl;
    }

    // Cleanup
    X509_STORE_CTX_free(ctx);
    X509_STORE_free(store);
    X509_free(cert);
    return result == 1;
}

int main() {
    verifyCertificateChain("server.pem", "ca-bundle.pem");
    return 0;
}`,
    },
    {
      language: "javascript",
      caption: "Generating a CSR and self-signed certificate with Node.js (node-forge)",
      source: `const forge = require("node-forge");

// Generate a 2048-bit RSA key pair
const keys = forge.pki.rsa.generateKeyPair(2048);

// Create a Certificate Signing Request (CSR)
const csr = forge.pki.createCertificationRequest();
csr.publicKey = keys.publicKey;
csr.setSubject([
  { name: "commonName", value: "example.com" },
  { name: "organizationName", value: "Example Inc" },
  { name: "countryName", value: "US" },
]);

// Add Subject Alternative Names extension
csr.setAttributes([{
  name: "extensionRequest",
  extensions: [{
    name: "subjectAltName",
    altNames: [
      { type: 2, value: "example.com" },       // DNS
      { type: 2, value: "www.example.com" },    // DNS
      { type: 7, ip: "192.168.1.1" },           // IP
    ],
  }],
}]);

// Sign the CSR with the private key
csr.sign(keys.privateKey, forge.md.sha256.create());

// Verify the CSR signature
const verified = csr.verify();
console.log("CSR valid:", verified);

// Output CSR in PEM format
const csrPem = forge.pki.certificationRequestToPem(csr);
console.log(csrPem);`,
    },
    {
      language: "javascript",
      caption: "Implementing TLS certificate pinning in a Node.js HTTPS client",
      source: `const https = require("https");
const crypto = require("crypto");
const tls = require("tls");

// SHA-256 fingerprint of the expected certificate's public key (SPKI pin)
const PINNED_SPKI_HASH = "base64+encoded+sha256+hash+of+spki==";

function makeSecureRequest(hostname, path) {
  return new Promise((resolve, reject) => {
    const options = {
      hostname,
      port: 443,
      path,
      method: "GET",
      // Custom certificate verification with pinning
      checkServerIdentity: (host, cert) => {
        // First, perform standard hostname verification
        const err = tls.checkServerIdentity(host, cert);
        if (err) return err;

        // Extract the public key and compute its SHA-256 hash
        const pubkey = cert.pubkey;
        const spkiHash = crypto
          .createHash("sha256")
          .update(pubkey)
          .digest("base64");

        // Compare against our pinned hash
        if (spkiHash !== PINNED_SPKI_HASH) {
          return new Error(
            \`Certificate pin mismatch! Expected: \${PINNED_SPKI_HASH}, Got: \${spkiHash}\`
          );
        }
        console.log("Certificate pin verified successfully");
        return undefined;
      },
    };

    const req = https.request(options, (res) => {
      let data = "";
      res.on("data", (chunk) => (data += chunk));
      res.on("end", () => resolve({ status: res.statusCode, body: data }));
    });
    req.on("error", reject);
    req.end();
  });
}

makeSecureRequest("api.example.com", "/v1/data")
  .then((res) => console.log("Response:", res.status))
  .catch((err) => console.error("Pin verification failed:", err.message));`,
    },
  ],
  diagrams: [
    {
      title: "PKI Certificate Chain of Trust",
      kind: "flow",
      caption: "Hierarchical trust model from root CA down to end-entity leaf certificates, showing the verification path browsers follow during TLS handshake.",
      mermaid: `flowchart TD
    ROOT["Root CA\\n(Self-signed, offline in HSM)\\nTrusted by OS/Browser"]
    INT1["Intermediate CA 1\\n(Signed by Root CA)\\nOnline, issues certs"]
    INT2["Intermediate CA 2\\n(Signed by Root CA)\\nOnline, issues certs"]
    LEAF1["Leaf Certificate\\nexample.com\\n(Signed by Intermediate CA 1)"]
    LEAF2["Leaf Certificate\\napi.example.com\\n(Signed by Intermediate CA 1)"]
    LEAF3["Leaf Certificate\\nother.org\\n(Signed by Intermediate CA 2)"]
    BROWSER["Browser / TLS Client"]

    ROOT -->|Signs| INT1
    ROOT -->|Signs| INT2
    INT1 -->|Signs| LEAF1
    INT1 -->|Signs| LEAF2
    INT2 -->|Signs| LEAF3
    BROWSER -->|"Verifies chain:\\nLeaf → Intermediate → Root"| LEAF1

    style ROOT fill:#4a9,stroke:#333,color:#fff
    style INT1 fill:#49a,stroke:#333,color:#fff
    style INT2 fill:#49a,stroke:#333,color:#fff
    style LEAF1 fill:#a94,stroke:#333,color:#fff
    style LEAF2 fill:#a94,stroke:#333,color:#fff
    style LEAF3 fill:#a94,stroke:#333,color:#fff
    style BROWSER fill:#94a,stroke:#333,color:#fff`,
    },
    {
      title: "ACME Certificate Issuance Flow",
      kind: "sequence",
      caption: "Step-by-step sequence of the ACME protocol used by Let's Encrypt for automated certificate issuance via HTTP-01 challenge.",
      mermaid: `sequenceDiagram
    participant Client as ACME Client<br/>(certbot)
    participant CA as Let's Encrypt<br/>CA Server
    participant DNS as DNS / Web Server

    Client->>CA: 1. Register account (public key)
    CA-->>Client: Account created

    Client->>CA: 2. Request certificate for example.com
    CA-->>Client: Authorization challenge (HTTP-01 token)

    Client->>DNS: 3. Place token at<br/>/.well-known/acme-challenge/{token}
    Client->>CA: 4. Notify: challenge is ready

    CA->>DNS: 5. Fetch http://example.com/.well-known/acme-challenge/{token}
    DNS-->>CA: Token + key authorization

    CA-->>Client: 6. Challenge validated

    Client->>CA: 7. Submit CSR
    CA-->>Client: 8. Signed X.509 certificate + chain

    Note over Client,CA: Certificate valid for 90 days.<br/>Renew automatically before expiry.`,
    },
  ],
  animations: [
    {
      title: "Verifying a certificate chain",
      steps: [
        {
          label: "Server presents its chain",
          detail: "Leaf certificate for the domain, plus any intermediates.",
        },
        {
          label: "Check the leaf",
          detail: "Does the hostname match? Is it within its validity dates? Is the key usage correct?",
        },
        {
          label: "Walk up",
          detail: "The leaf's signature is verified using the intermediate's public key.",
        },
        {
          label: "Reach a root",
          detail: "The intermediate is verified against a root certificate already in the client's trust store.",
        },
        {
          label: "Trust established",
          detail: "Trust flows down from a root the client already trusted — nothing in the chain was trusted on its own say-so.",
        },
        {
          label: "Any break fails",
          detail: "A wrong hostname, an expired certificate, or an unknown root aborts the connection before data flows.",
        },
      ],
    },
  ],
  comparison: {
    columns: [
      "Feature",
      "DV (Domain Validation)",
      "OV (Organization Validation)",
      "EV (Extended Validation)",
    ],
    rows: [
      [
        "**Validation scope**",
        "*Domain ownership* only",
        "*Domain* + **organization legal identity**",
        "*Domain* + **rigorous legal, operational, physical verification**",
      ],
      [
        "**Issuance time**",
        "Minutes (automated via `ACME`)",
        "1-3 business days",
        "1-2 weeks",
      ],
      [
        "**Cost**",
        "*Free* (Let's Encrypt) or low cost",
        "**$50-$200**/year",
        "**$150-$500+**/year",
      ],
      [
        "**Browser indicator**",
        "Padlock icon only",
        "Padlock icon only",
        "Padlock + *organization name* (legacy; most browsers **removed** green bar)",
      ],
      [
        "**Use case**",
        "Blogs, personal sites, *internal APIs*",
        "**Business websites**, e-commerce",
        "**Banking**, financial services, *high-trust sites*",
      ],
      [
        "**Wildcard support**",
        "Yes (via `DNS-01`)",
        "Yes",
        "**No** (each subdomain must be individually validated)",
      ],
      [
        "**Automation**",
        "Fully automated (`certbot`, `ACME`)",
        "*Partially* manual",
        "**Fully manual** verification process",
      ],
    ],
  },
  exercises: [
    "Use `openssl` to generate a **2048-bit RSA key pair**, create a **CSR** with SANs for `example.com` and `www.example.com`, then *self-sign* the certificate. Inspect the certificate with `openssl x509 -text -noout` and identify all **v3 extensions**.",
    "Set up a local **CA hierarchy**: create a *root CA* certificate, use it to sign an **intermediate CA** certificate, then use the intermediate to sign a *leaf certificate*. Verify the full chain with `openssl verify -CAfile root.pem -untrusted intermediate.pem leaf.pem`.",
    "Install `certbot` and use the **ACME protocol** with the `--dry-run` flag to simulate obtaining a certificate for a domain you control. Compare the *HTTP-01* and *DNS-01* challenge flows, and document the **pros and cons** of each.",
    "Implement **certificate pinning** in a Node.js application: extract the `SPKI` hash of a server's certificate using `openssl s_client` and `openssl x509 -pubkey`, then write a client that *rejects connections* if the pin does not match. Test with both **matching** and **mismatched** pins.",
    "Configure **OCSP stapling** on an Nginx or Apache server. Use `openssl s_client -status` to verify the *stapled response* is present in the TLS handshake. Compare the handshake time **with and without** stapling enabled.",
  ],
  cheatSheet: [
    "Generate a **private key**: `openssl genpkey -algorithm RSA -out key.pem -pkeyopt rsa_keygen_bits:2048`",
    "Create a **CSR**: `openssl req -new -key key.pem -out csr.pem -subj \"/CN=example.com/O=Example Inc\"`",
    "**Self-sign** a certificate: `openssl req -x509 -key key.pem -in csr.pem -out cert.pem -days 365`",
    "Inspect a certificate: `openssl x509 -in cert.pem -text -noout` -- shows *issuer*, **subject**, `SANs`, validity, and **extensions**",
    "Verify a **chain of trust**: `openssl verify -CAfile ca-bundle.pem -untrusted intermediate.pem server.pem`",
    "Check **OCSP stapling**: `openssl s_client -connect example.com:443 -status` -- look for *OCSP Response Status: successful*",
  ],
  revisionNotes: [
    "**PKI** is a *hierarchical trust system*: **Root CAs** (offline, in `HSMs`) sign **Intermediate CAs**, which sign *leaf certificates*. The browser verifies the chain from leaf to a trusted root in its `trust store`.",
    "**Certificate types** differ in *validation rigor*: `DV` (automated, domain-only), `OV` (organization verified), `EV` (rigorous legal verification). All provide **identical encryption** -- the difference is *identity assurance*.",
    "**Revocation checking** has three mechanisms: `CRL` (bulk download of revoked serials -- *stale and large*), `OCSP` (real-time check -- *adds latency and privacy concerns*), and **OCSP Stapling** (server-side caching -- *best practice* for performance and privacy).",
    "The **ACME protocol** (`RFC 8555`) enables *fully automated* certificate lifecycle: account registration, challenge-based domain validation (`HTTP-01`, `DNS-01`, `TLS-ALPN-01`), CSR submission, and **90-day certificate** issuance. Tools: `certbot`, `acme.sh`, **Caddy**, **Traefik**.",
    "**Certificate pinning** binds a client to specific *certificates or public keys* for a domain, preventing **MITM** even with a compromised CA. Best practice: pin the **intermediate CA's SPKI hash** + a *backup pin*. Avoid `HPKP` (deprecated due to lockout risks).",
  ],
};
