import type { TopicContent } from "../types";

export const pkiCertificates: TopicContent = {
  quickSummary: [
    "Public Key Infrastructure (PKI) is the framework of policies, hardware, software, and procedures needed to create, manage, distribute, and revoke digital certificates that bind public keys to identities.",
    "X.509 certificates are the standard format containing a subject's public key, identity information, issuer (CA) details, validity period, and the CA's digital signature — used in TLS/SSL, code signing, and email encryption.",
    "The Certificate Authority (CA) chain of trust works hierarchically: root CAs (trusted by OS/browsers) sign intermediate CA certificates, which sign end-entity (leaf) certificates — creating a verifiable trust chain.",
    "Certificate Signing Requests (CSRs) are generated by the entity requesting a certificate, containing their public key and identity information, submitted to a CA for validation and signing.",
  ],
  detailed: [
    `## X.509 Certificate Structure

X.509 is the ITU-T standard for digital certificates, used universally in TLS/SSL, code signing, S/MIME email, and document signing.

**Key fields in an X.509 v3 certificate:**
- **Version**: Almost always v3 (supports extensions)
- **Serial Number**: Unique identifier assigned by the CA
- **Signature Algorithm**: Algorithm the CA used to sign (e.g., SHA256withRSA, ECDSA)
- **Issuer**: Distinguished Name (DN) of the CA that signed the certificate
- **Validity**: Not Before and Not After timestamps
- **Subject**: DN of the certificate holder (e.g., CN=example.com, O=Example Inc)
- **Subject Public Key Info**: The public key and its algorithm (RSA 2048, ECDSA P-256)
- **Extensions (v3)**:
  - Subject Alternative Names (SANs): Additional domains/IPs the cert is valid for
  - Key Usage: What the key can be used for (digital signature, key encipherment)
  - Extended Key Usage: Specific purposes (TLS server auth, client auth, code signing)
  - Basic Constraints: Whether this is a CA certificate and maximum chain depth
  - CRL Distribution Points: Where to check for revocation
  - Authority Information Access: OCSP responder URL

**Certificate encoding formats:**
- **PEM**: Base64-encoded DER with header/footer lines. Human-readable. Most common on Linux.
- **DER**: Binary encoding. Used by Java and Windows.
- **PKCS#12 / PFX**: Binary format bundling certificate + private key + chain. Password-protected.`,

    `## Certificate Authority Chain of Trust

PKI operates on a hierarchical trust model:

**Root CA**: Self-signed certificate that forms the trust anchor. Root CA certificates are pre-installed in operating systems and browsers (the "trust store"). Root CAs are kept offline in HSMs (Hardware Security Modules) for security — if a root CA key is compromised, the entire trust hierarchy collapses.

**Intermediate CA**: Signed by the root CA. Intermediate CAs issue end-entity certificates. They provide a layer of indirection — the root CA key is used rarely (only to sign intermediate certs), limiting its exposure. If an intermediate is compromised, only it is revoked without affecting the root.

**End-entity (leaf) certificate**: Signed by an intermediate CA. This is the certificate presented by a web server during the TLS handshake.

**Verification chain:**
\`\`\`
Browser connects to example.com
  -> Server presents leaf cert (example.com, signed by Intermediate CA)
  -> Server also sends Intermediate CA cert (signed by Root CA)
  -> Browser has Root CA in its trust store
  -> Browser verifies: Root CA signature on Intermediate -> Intermediate signature on Leaf
  -> Chain is valid, connection is trusted
\`\`\`

If any certificate in the chain is expired, revoked, or the signatures don't verify, the chain is broken and the connection is rejected.`,

    `## Certificate Lifecycle: CSR, Issuance, Renewal, Revocation

**Certificate Signing Request (CSR):**
1. The entity generates a public-private key pair
2. Creates a CSR containing: the public key, subject DN (organization, domain), and requested extensions
3. Signs the CSR with the private key (proving possession)
4. Submits the CSR to a CA

**Domain Validation (DV):** CA verifies domain ownership via DNS record, HTTP challenge, or email. Automated (Let's Encrypt). Minutes to issue.

**Organization Validation (OV):** CA verifies the organization's legal existence and domain ownership. Days to issue.

**Extended Validation (EV):** Rigorous verification of legal identity, operational existence, and authority of the requester. Days to weeks. Browsers used to show a green bar (now deprecated in most browsers).

**Revocation mechanisms:**
- **CRL (Certificate Revocation List):** CA publishes a list of revoked certificate serial numbers. Clients download and check. Drawback: CRLs grow large and have caching delays.
- **OCSP (Online Certificate Status Protocol):** Client queries the CA's OCSP responder in real-time for a specific certificate's status. More efficient than CRLs.
- **OCSP Stapling:** The server periodically fetches its own OCSP response and "staples" it to the TLS handshake, eliminating the client's need to contact the CA separately. Recommended for performance and privacy.

**Certificate Transparency (CT):** Public, append-only logs of all issued certificates. Browsers require CT log inclusion, allowing domain owners to detect unauthorized certificate issuance.`,

    `## Certificate Pinning

Certificate pinning restricts which certificates or public keys a client accepts for a specific domain, preventing man-in-the-middle attacks even with a compromised or rogue CA.

**Types of pinning:**
- **Certificate pinning**: Pin the exact leaf certificate. Most restrictive — must update the pin when the certificate is renewed.
- **Public key pinning**: Pin the Subject Public Key Info (SPKI) hash. The pin survives certificate renewal as long as the same key pair is used.
- **CA pinning**: Pin the intermediate or root CA. Less restrictive — any certificate from that CA is accepted.

**Implementation approaches:**
- **HPKP (HTTP Public Key Pinning)**: Deprecated browser standard — too risky, mistakes caused permanent lockout.
- **Mobile app pinning**: Embed expected certificate/key hashes in the app. Most common use case today. Libraries: TrustKit (iOS), OkHttp CertificatePinner (Android).
- **API client pinning**: Configure HTTP clients to accept only specific certificates for specific endpoints.

**Risks of pinning:**
- If the pinned certificate/key is lost or compromised, the application is locked out until updated
- Requires careful key rotation planning — always pin a backup key
- Certificate renewal with a new key breaks the pin
- Not recommended for web browsers (HPKP is deprecated) but valuable for mobile apps and API clients

**Best practice**: Pin the public key of the intermediate CA, and include a backup pin. This survives leaf certificate renewals while still restricting to a specific CA chain.`,

    `## Let's Encrypt and ACME Protocol

**Let's Encrypt** is a free, automated, non-profit Certificate Authority that has fundamentally changed TLS adoption by eliminating cost and complexity barriers.

**ACME (Automatic Certificate Management Environment)** is the protocol (RFC 8555) used by Let's Encrypt for automated certificate issuance and renewal:

1. **Account registration**: Client generates a key pair and registers with the CA
2. **Order creation**: Client requests a certificate for one or more domains
3. **Authorization challenges**: CA issues challenges to prove domain control:
   - **HTTP-01**: Place a file at \`/.well-known/acme-challenge/\` on the domain's web server
   - **DNS-01**: Create a TXT DNS record. Supports wildcard certificates.
   - **TLS-ALPN-01**: Respond to a TLS handshake with a special certificate
4. **Challenge validation**: CA verifies the challenge was completed
5. **Certificate issuance**: Client submits CSR, CA returns the signed certificate
6. **Renewal**: Certificates are valid for 90 days. Automated renewal via cron or certbot runs before expiry.

Tools: Certbot, acme.sh, Caddy (built-in ACME), Traefik (built-in ACME).

Short-lived certificates (90 days) encourage automation and limit the exposure window if a key is compromised. The entire process — from CSR to issued certificate — takes seconds with no human intervention.`,
  ],
  interviewQA: [
    {
      q: "Walk through what happens when a browser verifies a TLS certificate.",
      a: "The browser receives the server's leaf certificate and any intermediate certificates during the TLS handshake. It builds the chain: leaf -> intermediate -> root. It checks each certificate's validity period (not expired, not yet valid), verifies each signature (the root CA's public key verifies the intermediate's signature, the intermediate's public key verifies the leaf's signature), and confirms the root CA is in the browser/OS trust store. It checks the Subject Alternative Names include the requested domain, verifies the certificate hasn't been revoked (via OCSP or CRL), and checks Certificate Transparency logs. If any check fails, the browser shows a security warning.",
    },
    {
      q: "Why are root CAs kept offline and how does the intermediate CA pattern help?",
      a: "Root CA private keys are the ultimate trust anchors — their compromise would invalidate the entire CA hierarchy and every certificate they've signed. Keeping them offline in HSMs means they're physically inaccessible to network attacks. Intermediate CAs provide a buffer: the root key is only used occasionally to sign intermediate certificates, while the intermediates (which are online) handle day-to-day certificate issuance. If an intermediate CA is compromised, it can be revoked using the root without affecting other intermediates or the root itself.",
    },
    {
      q: "What is OCSP stapling and why is it better than regular OCSP?",
      a: "Regular OCSP requires the client (browser) to make a separate request to the CA's OCSP responder during the TLS handshake to check if the certificate is revoked. This adds latency, creates a privacy concern (the CA sees which sites the user visits), and introduces a dependency (if the OCSP responder is down, the check fails or is skipped). OCSP stapling has the server periodically fetch its own OCSP response and attach (staple) it to the TLS handshake. The client gets the revocation status without any extra round trip, the CA doesn't see client IPs, and there's no runtime dependency on the OCSP responder.",
    },
    {
      q: "When should you use certificate pinning and what are the risks?",
      a: "Certificate pinning is most valuable for mobile apps and API clients communicating with known backends — it prevents MITM attacks even with a compromised CA. Risks include lockout if the pinned key is lost or rotated without updating the pin, which in mobile apps means shipping an app update. Best practices: pin the intermediate CA's public key (survives leaf renewal), always include a backup pin, have a key rotation plan, and set reasonable pin expiry. Avoid pinning in browsers (HPKP was deprecated due to lockout risks and abuse potential).",
    },
  ],
  mcqs: [
    {
      q: "Why are root CA private keys kept offline in HSMs?",
      options: [
        "To improve certificate issuance speed",
        "To reduce storage costs",
        "Because their compromise would invalidate the entire trust hierarchy",
        "Because root CAs issue certificates directly to websites",
      ],
      answerIndex: 2,
      explanation:
        "Root CA keys are the ultimate trust anchor. Their compromise would require revoking the root and all certificates in its hierarchy. Keeping them offline in HSMs protects against network-based attacks.",
    },
    {
      q: "What does OCSP stapling improve over standard OCSP?",
      options: [
        "It uses stronger encryption",
        "It eliminates the client's need to contact the CA's OCSP responder separately",
        "It increases certificate validity period",
        "It allows self-signed certificates",
      ],
      answerIndex: 1,
      explanation:
        "OCSP stapling has the server fetch and cache its own OCSP response, attaching it to the TLS handshake. This eliminates extra client round-trips, improves privacy, and removes the OCSP responder as a runtime dependency.",
    },
    {
      q: "What ACME challenge type is required for obtaining wildcard certificates from Let's Encrypt?",
      options: ["HTTP-01", "DNS-01", "TLS-ALPN-01", "Email validation"],
      answerIndex: 1,
      explanation:
        "DNS-01 challenges (creating a TXT record) are the only ACME challenge type that supports wildcard certificate issuance, because they prove control over the entire domain, not just a specific server.",
    },
    {
      q: "What is the safest certificate pinning approach for mobile apps?",
      options: [
        "Pin the exact leaf certificate",
        "Pin the root CA certificate",
        "Pin the intermediate CA's public key with a backup pin",
        "Disable certificate validation entirely",
      ],
      answerIndex: 2,
      explanation:
        "Pinning the intermediate CA's public key survives leaf certificate renewals while still restricting to a specific CA chain. Including a backup pin prevents lockout if the primary key is rotated.",
    },
  ],
  flashcards: [
    {
      front: "What is an X.509 certificate?",
      back: "The standard format for digital certificates, containing a subject's public key, identity, issuer (CA), validity period, extensions (SANs, key usage), and the CA's digital signature. Used in TLS, code signing, and email encryption.",
    },
    {
      front: "What is a Certificate Signing Request (CSR)?",
      back: "A message sent to a CA containing the requester's public key, identity information, and requested extensions, signed with the requester's private key. The CA validates the request and issues a signed certificate.",
    },
    {
      front: "What is Certificate Transparency (CT)?",
      back: "Public, append-only logs of all issued certificates. Allows domain owners to detect unauthorized or misissued certificates for their domains. Browsers like Chrome require CT log inclusion for certificates to be trusted.",
    },
    {
      front: "What is the difference between DV, OV, and EV certificates?",
      back: "DV (Domain Validation): proves domain ownership only (automated, minutes). OV (Organization Validation): verifies organization's legal existence (days). EV (Extended Validation): rigorous identity verification (days/weeks). All provide the same encryption strength.",
    },
    {
      front: "Why do Let's Encrypt certificates expire after 90 days?",
      back: "Short validity encourages automation (no manual renewals), limits the exposure window if a private key is compromised, and promotes the use of ACME protocol for fully automated certificate lifecycle management.",
    },
    {
      front: "What is the chain of trust in PKI?",
      back: "Root CA (pre-trusted by OS/browsers, kept offline) signs Intermediate CA certs, which sign end-entity (leaf) certs. Verification walks the chain: leaf -> intermediate -> root. If any link is broken (expired, revoked, bad signature), the chain is invalid.",
    },
    {
      front: "What is HPKP and why was it deprecated?",
      back: "HTTP Public Key Pinning was a browser mechanism to pin certificate keys via HTTP headers. Deprecated because configuration mistakes caused permanent site lockout, and it could be abused by attackers who gained temporary control of headers.",
    },
  ],
  glossary: [
    {
      term: "PKI (Public Key Infrastructure)",
      definition:
        "The framework of policies, procedures, and technology for creating, managing, distributing, and revoking digital certificates that bind public keys to verified identities.",
    },
    {
      term: "X.509",
      definition:
        "The ITU-T standard format for digital certificates, specifying the structure of certificate fields including subject, issuer, validity, public key, and extensions.",
    },
    {
      term: "Certificate Authority (CA)",
      definition:
        "A trusted entity that issues digital certificates after validating the identity of the certificate requester. Root CAs are pre-trusted by operating systems and browsers.",
    },
    {
      term: "CSR (Certificate Signing Request)",
      definition:
        "A signed message containing a public key and identity information, submitted to a CA to request issuance of a digital certificate.",
    },
    {
      term: "OCSP (Online Certificate Status Protocol)",
      definition:
        "A protocol for real-time checking of a certificate's revocation status by querying the issuing CA's OCSP responder, more efficient than downloading full CRLs.",
    },
    {
      term: "Certificate Pinning",
      definition:
        "A security technique that restricts which certificates or public keys a client accepts for a specific domain, preventing MITM attacks even with a compromised CA.",
    },
    {
      term: "ACME (Automatic Certificate Management Environment)",
      definition:
        "RFC 8555 protocol for automated certificate issuance and renewal, used by Let's Encrypt and other CAs to enable fully automated TLS certificate lifecycle management.",
    },
  ],
};
