import type { TopicContent } from "../types";

export const subsequenceDp: TopicContent = {
  quickSummary: [
    "Every subsequence-counting DP is the same include/exclude recurrence: `ways(i, t) = ways(i-1, t) + ways(i-1, t - a[i])` — skip the element, or take it.",
    "Counting means **summing** branches, so the base case is `dp[0] = 1` (the one empty subsequence) and everything is taken modulo 10^9+7.",
    "Counting *distinct* subsequences needs a dedupe term: subtract the count from just before the character's previous occurrence. O(n) time, O(n) space.",
  ],
  detailed: [
    "A subsequence keeps relative order but allows gaps, so at every index there are exactly two choices: include or exclude. That binary fan-out is 2^n paths, and the reason DP works is that many of those paths land on the same `(index, accumulated value)` pair — classic overlapping subproblems.\n\nKey insight: the transition never *reorders* elements, so unlike coin change there is no combination-versus-permutation ambiguity here. Position order is baked into the state.",
    "## Counting subsequences that sum to a target\n\n`dp[t]` = number of subsequences of the elements processed so far that sum to `t`. Base `dp[0] = 1`. For each element `x`, sweep `t` **downward**: `dp[t] += dp[t - x]`. The reverse direction is the same 0/1 discipline as subset sum — it keeps the right-hand side on the previous row so each element is used at most once. O(n·T) time, O(T) space.\n\nCommon mistake: assuming zeros are harmless. A zero element doubles every count, since it can be in or out of any subsequence. The reverse loop with `x = 0` computes `dp[t] += dp[t]`, which doubles correctly — but only if the loop bound is `t >= 0` rather than `t > 0`.",
    "## Distinct subsequences of a string\n\nCount how many *distinct* strings can be formed. Naively `dp[i] = 2·dp[i-1]` — each old subsequence either takes `s[i]` or not — but if `s[i]` appeared before at position `j`, everything that was formed by appending that earlier copy is regenerated identically now. Subtract exactly those: `dp[i] = 2·dp[i-1] − dp[j-1]`, where `j` is the previous occurrence.\n\nWarning: under a modulus that subtraction can go negative. Write `dp[i] = (2*dp[i-1] - dp[j-1] + MOD) % MOD` — omitting the `+ MOD` is the most common bug in this recurrence.",
    "Counting is the gentle end of subsequence DP. The optimisation end — **Longest Increasing Subsequence**, **LCS**, and **Edit Distance** — keeps the same include/exclude shape but replaces the sum with a max or min and usually adds a second index.",
  ],
  code: [
    {
      language: "cpp",
      caption: "Count subsequences summing to a target — include/exclude, reverse loop",
      source: `// Number of subsequences of 'a' (non-negative values) with sum == T.
// dp[t] = ways to reach t.  Include/exclude: dp[t] += dp[t - x].
// Time O(n*T).  Space O(T).
const long long MOD = 1000000007LL;

long long countSubsequencesWithSum(const vector<int>& a, int T) {
    vector<long long> dp(T + 1, 0);
    dp[0] = 1;                            // the empty subsequence sums to 0

    for (int x : a)
        for (int t = T; t >= x; --t)      // DOWNWARD => each element used once
            dp[t] = (dp[t] + dp[t - x]) % MOD;
            // exclude = dp[t] as it stands (previous row)
            // include = dp[t - x], also previous row thanks to the direction

    return dp[T];
}
// x == 0 is handled correctly: the bound t >= 0 makes dp[t] += dp[t],
// doubling every count -- a zero really can be in or out of any subsequence.`,
    },
    {
      language: "cpp",
      caption: "Distinct subsequences of a string — dedupe by last occurrence",
      source: `// Number of DISTINCT subsequences of s, including the empty one.
// dp[i] = distinct subsequences of the prefix s[0..i-1].
// Time O(n).  Space O(n).
long long distinctSubsequences(const string& s) {
    int n = (int)s.size();
    vector<long long> dp(n + 1, 0);
    dp[0] = 1;                            // only the empty subsequence

    vector<int> last(256, 0);             // last[c] = 1-based index of prev c

    for (int i = 1; i <= n; ++i) {
        unsigned char c = s[i - 1];
        dp[i] = (2 * dp[i - 1]) % MOD;    // take s[i-1] or not
        if (last[c] != 0) {
            int j = last[c];              // previous occurrence, 1-based
            // Subtract the ones already generated by that earlier copy.
            dp[i] = (dp[i] - dp[j - 1] % MOD + MOD) % MOD;
        }
        last[c] = i;
    }
    return dp[n];                          // subtract 1 to exclude the empty one
}
// "aba": dp = 1, 2, 4, 7  -> {"", a, b, ab, aa, ba, aba}`,
    },
  ],
  cheatSheet: [
    "Include/exclude: `ways(i, t) = ways(i-1, t) + ways(i-1, t - a[i])`. Base `dp[0] = 1`.",
    "Reverse the inner loop for use-once semantics — same rule as 0/1 subset sum.",
    "Counting overflows fast: `long long` plus `% 1e9+7` at every addition.",
    "Distinct subsequences: `dp[i] = 2·dp[i-1] − dp[last[c]-1]`, and always `+ MOD` before the final `%`.",
    "Zeros double the count. `dp[0] = 1` is the empty subsequence — subtract 1 if the problem excludes it.",
  ],
  interviewQA: [
    {
      q: "Count the distinct subsequences of a string and justify the subtraction term.",
      a: "Let `dp[i]` be the number of distinct subsequences of the prefix of length `i`, with `dp[0] = 1` for the empty one. Adding character `c = s[i-1]`, every existing subsequence can either not take `c` — that is `dp[i-1]` of them — or take `c` appended at the end, another `dp[i-1]`. So the naive count is `2·dp[i-1]`. The overcount comes from repeats: if `c` occurred earlier at 1-based position `j`, then at that step I already appended this same character to every subsequence of the prefix of length `j-1`, producing exactly the same strings I am producing again now. Those duplicates number `dp[j-1]`, so `dp[i] = 2·dp[i-1] − dp[j-1]`. It is `j-1` and not `j` because only the subsequences that existed *before* that earlier copy were extended by it. The algorithm is one pass with a last-occurrence table: O(n) time, O(n) space, or O(1) extra beyond the table if I only need the final value modulo a prime — and under a modulus I must add MOD before the final reduction so the subtraction never goes negative.",
      followUps: [
        "How do you exclude the empty subsequence from the count?",
        "How would this change if you needed distinct subsequences of a given length k?",
      ],
    },
    {
      q: "Why does subsequence counting not have the combinations-versus-permutations problem that coin change does?",
      a: "Because the state already carries position. In coin change the items are an unordered supply, so whether `1+2` and `2+1` are the same answer depends on whether the loop structure lets a coin be re-offered after later coins — hence the loop-order rule. In subsequence DP the recurrence walks the array once, in order, deciding include or exclude for element `i` before ever looking at element `i+1`. Each subsequence therefore corresponds to exactly one path through the decision tree — one subset of indices — and no reordering is representable. That is also why the inner capacity loop must run backwards: not to fix ordering, but to enforce that each index is decided once. The remaining subtlety is duplicate *values* versus duplicate *index sets*: if the problem counts distinct strings rather than distinct index sets, I need the last-occurrence subtraction, which is a different kind of deduplication entirely.",
      followUps: [
        "Give an input where index-set counting and distinct-value counting differ.",
        "How would you count subsequences of a fixed length that sum to T?",
      ],
    },
  ],
  flashcards: [
    {
      front: "Include/exclude recurrence",
      back: "`ways(i, t) = ways(i-1, t) + ways(i-1, t - a[i])`, base `dp[0] = 1` for the empty subsequence. Reverse the inner loop for use-once semantics.",
    },
    {
      front: "Distinct subsequences dedupe term",
      back: "`dp[i] = 2·dp[i-1] − dp[j-1]` where `j` is the previous occurrence of `s[i-1]`. Under a modulus, add MOD before reducing.",
    },
    {
      front: "Why do zeros matter when counting subsequences by sum?",
      back: "A zero can be in or out of any subsequence, so it doubles every count. The reverse loop with bound `t >= 0` produces `dp[t] += dp[t]`, which is exactly right.",
    },
  ],
};
