import type { Area } from "../types";

export const apiDesign: Area = {
  slug: "api-design",
  title: "API Design",
  icon: "🔌",
  stream: "Backend & Data",
  blurb:
    "REST vs GraphQL vs gRPC, versioning, pagination, auth, and the status codes people get wrong under pressure.",

  mustKnow: [
    "REST models resources with nouns and uses HTTP verbs for actions. `POST /users`, not `POST /createUser`.",
    "GET and HEAD are safe (no side effects). GET, PUT, DELETE are idempotent; POST and PATCH are not.",
    "2xx success, 3xx redirect, 4xx the client's fault, 5xx the server's fault. Returning 200 with an error body is the most common API design mistake.",
    "401 means not authenticated (who are you?); 403 means authenticated but not permitted (I know who you are, and no).",
    "Version from day one — URL path (`/v1/`) is the pragmatic default because it's visible, cacheable, and trivially routable.",
    "Cursor pagination scales; offset pagination degrades on deep pages and is unstable under concurrent writes.",
    "Validate every input at the boundary with a schema, and never trust a client-supplied id, role, or price.",
    "Return a machine-readable error shape: a stable error code, a human message, and a correlation id — not a stack trace.",
    "Rate limit and document the limits, returning 429 with `Retry-After`.",
    "PUT replaces the whole resource; PATCH applies a partial update. Using PUT for partial updates silently nulls omitted fields.",
  ],

  sheets: [
    {
      title: "Status codes you'll be asked about",
      points: [
        "200 OK — success with a body. 201 Created — include a `Location` header. 202 Accepted — async, work queued. 204 No Content — success, nothing to return (typical for DELETE).",
        "301 permanent redirect (browser caches it), 302/307 temporary, 304 Not Modified (conditional GET hit).",
        "400 malformed request. 401 unauthenticated. 403 forbidden. 404 not found. 405 method not allowed. 409 conflict (duplicate, version mismatch). 410 gone. 422 semantically invalid. 429 rate limited.",
        "500 unexpected server error. 502 bad gateway. 503 unavailable (include `Retry-After`). 504 upstream timeout.",
        "Use 404 rather than 403 when revealing existence itself would leak information.",
        "Never return 200 with `{ \"error\": ... }` — it defeats every client, proxy, and monitoring layer.",
      ],
    },
    {
      title: "REST design rules",
      points: [
        "Plural nouns for collections: `/users`, `/users/42`, `/users/42/orders`.",
        "Nest only one level deep; beyond that, use query filters (`/orders?userId=42`).",
        "Filtering, sorting, and pagination belong in query parameters, not the path.",
        "Actions that aren't CRUD are still resources: `POST /orders/42/refunds` beats `POST /refundOrder`.",
        "Return the created/updated resource so the client doesn't need a follow-up GET.",
        "Use ISO-8601 UTC timestamps and stable, opaque ids (avoid exposing sequential ids that leak volume).",
        "`snake_case` or `camelCase` — pick one and never mix.",
        "Support `If-None-Match`/`ETag` for cacheable reads and `If-Match` for optimistic concurrency.",
      ],
    },
    {
      title: "Pagination",
      points: [
        "Offset/limit — simple, allows jumping to page N, but O(offset) on the database and unstable when rows are inserted or deleted mid-paging.",
        "Cursor/keyset — opaque cursor encoding the last sort key; constant time per page, stable under writes, no arbitrary page jumps.",
        "Always cap `limit` server-side; an uncapped limit is a denial-of-service vector.",
        "Return pagination metadata: `next_cursor`, and `has_more` rather than an expensive total count.",
        "A total count on a large table is often the slowest part of the response — make it optional or approximate.",
        "The cursor must encode the full sort key including a tiebreaker (e.g. `created_at` + `id`), or rows with equal keys are skipped or repeated.",
      ],
    },
    {
      title: "Versioning and evolution",
      points: [
        "Additive changes are backward-compatible: new optional fields, new endpoints, new enum values clients can ignore.",
        "Breaking changes: removing or renaming a field, changing a type, making an optional field required, changing error semantics.",
        "URL versioning (`/v1/users`) — visible, cacheable, easy to route. The pragmatic default.",
        "Header versioning (`Accept: application/vnd.api.v2+json`) — purer REST, harder to debug and cache.",
        "Deprecation process: announce, emit a `Deprecation`/`Sunset` header, monitor usage per client, then remove.",
        "Never break v1 while it has traffic — measure who's still calling it before you delete it.",
      ],
    },
    {
      title: "API security checklist",
      points: [
        "Authenticate every endpoint by default; make public access the explicit exception.",
        "Authorise per object, not just per route — check the caller owns the resource (IDOR is the most common real API vulnerability).",
        "Validate and coerce all input against a schema; reject unknown fields for write endpoints.",
        "Never accept client-supplied prices, roles, or user ids for privileged fields — mass assignment is a classic breach.",
        "Rate limit per user and per IP; stricter on auth endpoints.",
        "TLS everywhere; HSTS; no secrets in URLs (they land in logs and referrers).",
        "Log with a correlation id, but never log tokens, passwords, or PII.",
        "Return generic errors externally, detailed ones internally.",
      ],
    },
  ],

  decisions: [
    {
      title: "REST vs GraphQL vs gRPC",
      options: [
        {
          name: "REST",
          pick: ["Public APIs and third-party integrations — universally understood.", "HTTP caching matters (CDN, browser, proxies).", "Resource-shaped domain, simple tooling, easy debugging with curl."],
          cost: ["Over-fetching and under-fetching — clients take what the endpoint gives.", "Multiple round trips to assemble a screen.", "Endpoint sprawl as clients diverge."],
        },
        {
          name: "GraphQL",
          pick: ["Many different clients needing different shapes of the same data.", "Deeply nested/related data where REST would need several calls.", "Rapid frontend iteration without backend changes."],
          cost: ["HTTP caching is largely lost (everything is a POST to one endpoint).", "N+1 resolution unless you use DataLoader.", "Query complexity is an attack surface — needs depth/cost limits.", "More server complexity and a steeper learning curve."],
        },
        {
          name: "gRPC",
          pick: ["Internal service-to-service calls where performance matters.", "Strongly-typed contracts generated from protobuf.", "Streaming (bidirectional, server-push).", "Polyglot microservices."],
          cost: ["Not natively browser-callable (needs grpc-web and a proxy).", "Binary payloads are hard to debug by eye.", "Proto schema management and codegen in the build."],
        },
      ],
      verdict: "Public API → REST. Many clients with divergent data needs → GraphQL. Internal high-performance service-to-service → gRPC. Plenty of systems use REST externally and gRPC internally.",
      topic: "graphql",
    },
    {
      title: "Session cookies vs JWT",
      options: [
        {
          name: "Server session + cookie",
          pick: ["Traditional web apps.", "You need instant revocation — delete the session and it's gone.", "You want small cookies and server-controlled state."],
          cost: ["Session storage that every instance must reach (Redis), which is a shared dependency.", "Slightly more infrastructure."],
        },
        {
          name: "JWT",
          pick: ["Stateless services that shouldn't share a session store.", "Cross-domain or third-party API access.", "Short-lived access tokens with a refresh token."],
          cost: ["You CANNOT revoke a JWT before expiry without a blocklist — which reintroduces the state you were avoiding.", "Bigger than a session id, sent on every request.", "Easy to misconfigure: `alg: none`, weak secrets, no audience check."],
        },
      ],
      verdict: "Same-origin web app → session cookie, `HttpOnly; Secure; SameSite`. Distributed APIs → short-lived JWT access token plus a revocable refresh token. Either way, the token lives in an HttpOnly cookie, not localStorage.",
      topic: "sessions-vs-tokens",
    },
    {
      title: "Sync request/response vs webhook vs polling",
      options: [
        {
          name: "Synchronous",
          pick: ["Fast operations where the caller needs the result now."],
          cost: ["Couples caller to callee latency and availability; times out on slow work."],
        },
        {
          name: "Webhook (push)",
          pick: ["Notifying a third party of an event as it happens.", "Avoids wasteful polling and gives low latency."],
          cost: ["The receiver must be publicly reachable and highly available.", "You must sign payloads, retry with backoff, and expect duplicate deliveries — so receivers need idempotency.", "Ordering isn't guaranteed."],
        },
        {
          name: "Polling",
          pick: ["The client can't receive inbound connections.", "Simplicity, and the event rate is low.", "202 + a status endpoint for long-running jobs."],
          cost: ["Wasteful at scale and adds latency proportional to the interval."],
        },
      ],
      verdict: "Long-running work → 202 plus a status URL. Third-party event notification → signed webhooks with retries, and document that delivery is at-least-once.",
    },
  ],

  qa: [
    {
      id: "api-rest-vs-graphql",
      q: "REST or GraphQL — how do you choose?",
      a: "It comes down to who the clients are and how much their data needs diverge. REST gives you one shape per endpoint, which is a strength for a public API — it's cacheable at every layer, debuggable with curl, universally understood, and each endpoint has a clear contract. Its weakness is over- and under-fetching: a mobile client that needs three fields gets thirty, and a screen needing data from four resources makes four round trips. GraphQL inverts this: clients declare exactly the shape they need, which removes both problems and lets frontend teams iterate without backend changes — genuinely valuable when you have web, iOS, Android, and partner clients wanting different subsets. The costs are real though. HTTP caching largely disappears because everything is a POST to one URL, so you need application-level caching instead. Resolvers introduce N+1 by default and need DataLoader. And an arbitrary query language is an attack surface, requiring depth limits, complexity scoring, and persisted queries in production.",
      why: "It's the most-asked API question and rewards conditional rather than tribal answers.",
      trap: "Saying GraphQL is 'more modern' or 'better'. Losing HTTP caching is a significant, concrete cost that a public read-heavy API can't easily absorb.",
      followUps: ["How do you cache GraphQL?", "What stops a malicious deeply-nested query?"],
      depth: "Core",
      tags: ["rest", "graphql"],
      topic: "graphql",
    },
    {
      id: "api-idempotent-methods",
      q: "Which HTTP methods are idempotent, and why does it matter?",
      a: "GET, HEAD, PUT, and DELETE are idempotent: making the same call twice leaves the server in the same state as making it once. GET and HEAD are additionally safe, meaning they shouldn't change state at all. POST and PATCH are not idempotent — two POSTs create two resources, and a PATCH that increments a counter applies twice. It matters because retries are unavoidable: clients retry on timeout, load balancers retry on connection failure, and proxies may retry automatically for idempotent methods specifically. So a POST that times out leaves the client genuinely unable to know whether it succeeded, which is why any non-idempotent operation with real consequences — payments, orders, sending messages — needs an idempotency key so the server can recognise and de-duplicate the retry. Note that DELETE being idempotent means deleting twice should succeed or return 404, not error; and PUT being idempotent is why it replaces the whole resource rather than modifying part of it.",
      why: "It links HTTP semantics to real distributed-systems reliability rather than being trivia.",
      trap: "Confusing idempotent with 'returns the same response'. A second DELETE returning 404 is still idempotent — the state is unchanged.",
      followUps: ["How do you make POST safely retryable?", "Why is PATCH not idempotent?"],
      depth: "Core",
      tags: ["http", "reliability"],
      topic: "idempotency",
    },
    {
      id: "api-401-403",
      q: "401 or 403?",
      a: "401 Unauthorized means the request lacks valid authentication — the server doesn't know who you are, or your credentials are missing, malformed, or expired. The name is a historical misnomer; it really means unauthenticated, and the response should include a `WWW-Authenticate` header telling the client how to authenticate. 403 Forbidden means the server knows exactly who you are and you're still not allowed — a valid token for a user without the required role or without ownership of that resource. The practical rule is that 401 invites the client to retry with credentials, while 403 tells it not to bother. There's a security nuance worth adding: if the existence of a resource is itself sensitive, returning 403 confirms it exists, so returning 404 instead is often correct — an attacker enumerating ids learns nothing. And an expired token should be 401, not 403, so clients know to refresh rather than giving up.",
      why: "It's a small question that reliably separates careful API designers from careless ones.",
      trap: "Returning 403 for an expired token. The client will treat it as permanent and won't attempt a refresh.",
      followUps: ["When would you return 404 instead of 403?", "What should an expired JWT return?"],
      depth: "Core",
      tags: ["http", "auth"],
      topic: "authn-vs-authz",
    },
    {
      id: "api-versioning",
      q: "How do you version an API?",
      a: "First, minimise the need: most changes can be additive, and clients should ignore unknown fields, so adding optional fields and new endpoints needs no version bump. Breaking changes — removing or renaming a field, changing a type, tightening validation, changing error semantics — do. The pragmatic default is URL path versioning, `/v1/users`, because it's visible in logs, trivially routable, cacheable, and unambiguous when debugging. Header-based versioning via content negotiation is theoretically purer, keeping the URL as the resource identity, but it's harder to test, harder to cache, and easier to get wrong. Whichever you choose, the important part is the lifecycle rather than the mechanism: publish a deprecation policy, emit `Deprecation` and `Sunset` headers, instrument usage per client and per version so you know exactly who would break, contact those consumers, and only then remove. Running two versions concurrently is the cost of the promise you made, and it's usually cheaper to keep v1 alive than to break a partner integration.",
      why: "Versioning is where API design meets organisational reality, and measuring usage before removal is the mark of experience.",
      trap: "Versioning every endpoint independently. It gets unmanageable; version the API surface.",
      followUps: ["Which changes are safe to make without a version bump?", "How do you know when it's safe to delete v1?"],
      depth: "Intermediate",
      tags: ["versioning", "evolution"],
      topic: "api-versioning",
    },
    {
      id: "api-errors",
      q: "What should an API error response look like?",
      a: "It should use the correct status code and carry a stable, machine-readable body. The status code does the coarse routing — 4xx means the client should change something, 5xx means the server failed — and clients, proxies, load balancers, and dashboards all depend on it, which is why returning 200 with an error payload is so damaging: every layer thinks it succeeded. The body should include a stable error code string that clients can branch on and that never changes even if the wording does, a human-readable message for developers, and a correlation id that appears in your logs so support can find the exact request. For validation failures, include per-field detail so the client can highlight the right input. RFC 9457 (formerly 7807) `application/problem+json` gives a standard shape with `type`, `title`, `status`, `detail`, and `instance`, which is worth adopting rather than inventing your own. Critically, never leak stack traces, SQL, or internal hostnames — log those, return the correlation id.",
      why: "Error design determines whether integrating with your API is pleasant or miserable, and it's often an afterthought.",
      trap: "Returning a different error shape per endpoint. Clients then need per-endpoint handling and get it wrong.",
      followUps: ["Why is a stable error code better than matching on the message?", "What is `application/problem+json`?"],
      depth: "Intermediate",
      tags: ["errors", "design"],
      topic: "error-handling",
    },
    {
      id: "api-idor",
      q: "What is IDOR and how do you prevent it?",
      a: "Insecure Direct Object Reference: the API authenticates the caller but doesn't check they're allowed to access the specific object requested, so `GET /invoices/1234` returns someone else's invoice simply because the caller is logged in. It's consistently among the most common real-world API vulnerabilities because route-level authentication feels like it's done the job, and because the bug is invisible in testing — your test user owns their own data, so it always works. The fix is object-level authorisation on every request: scope the query by the caller's identity (`WHERE id = ? AND org_id = ?`) rather than fetching then checking, since fetch-then-check is easy to forget and easy to get wrong. Enforce it in a shared layer — a policy function, a repository that always applies the tenant filter, or row-level security in the database — so it can't be forgotten per endpoint. Using non-sequential ids helps a little by making enumeration harder, but it's obfuscation and not a control.",
      why: "It's the vulnerability most likely to exist in a real codebase and the mitigation is a design decision, not a patch.",
      trap: "Treating UUIDs as the fix. They slow enumeration; they don't authorise anything.",
      followUps: ["Where should the ownership check live?", "How does row-level security help?"],
      depth: "Advanced",
      tags: ["security"],
      topic: "rbac-abac",
    },
    {
      id: "api-rate-limit-design",
      q: "How would you expose rate limits to clients?",
      a: "Make them predictable and self-describing. Return `429 Too Many Requests` when exceeded, with a `Retry-After` header giving seconds or a date so the client knows exactly when to try again rather than guessing or hammering. On every response — not just rejections — include the limit headers (`RateLimit-Limit`, `RateLimit-Remaining`, `RateLimit-Reset`) so a well-behaved client can self-throttle before hitting the wall. Document the limits, the window, and what the limit is keyed on, since per-user, per-IP, and per-endpoint limits behave very differently for a client behind a NAT or a shared proxy. Consider different tiers per plan, and stricter limits on expensive or sensitive endpoints such as login, search, or report generation. Server-side, use a token bucket if you want to allow bursts within a sustained rate, keep counters in shared storage so the limit doesn't multiply by instance count, and decide explicitly whether to fail open or closed if that store is unavailable.",
      why: "Client-facing detail here is what makes an API usable at scale, and the fail-open question shows operational thinking.",
      trap: "Returning 429 with no `Retry-After`. Clients then retry immediately and make the overload worse.",
      followUps: ["Token bucket or sliding window, and why?", "What do you do if the Redis holding counters is down?"],
      depth: "Intermediate",
      tags: ["rate-limiting"],
      topic: "rate-limiting",
    },
    {
      id: "api-bulk",
      q: "How do you design a bulk endpoint?",
      a: "The hard question isn't the request shape, it's partial failure. If a client posts 1,000 records and 3 are invalid, all-or-nothing means one bad row wastes 997 good ones, while all-or-some means the response must tell the client precisely which succeeded and which failed and why. Usually per-item results are the right answer: return 207 Multi-Status or a 200 with an array of results, each carrying the client's own item reference, a status, and an error where applicable — the client reference matters, because matching by array index is fragile. Alongside that: cap the batch size and document the cap, since an unbounded batch is a memory and timeout hazard; make the operation idempotent with an idempotency key so a timeout retry doesn't double-insert everything; and for genuinely large jobs switch to asynchronous processing — accept the payload, return 202 with a job id, and expose a status endpoint, which also lets you stream results and avoid request timeouts entirely.",
      why: "Partial failure is the substance of the question, and candidates who only design the happy path miss it.",
      trap: "Returning a single status code for the whole batch. The client can't tell what to retry, so it retries everything.",
      followUps: ["How does the client match results to submitted items?", "When would you switch to an async job?"],
      depth: "Advanced",
      tags: ["design", "reliability"],
    },
    {
      id: "api-caching",
      q: "How do you make an API cacheable?",
      a: "Start with correct method semantics: only GET and HEAD are cacheable, so an action modelled as POST can never be cached by anything. Then set `Cache-Control` deliberately — `max-age` for how long it's fresh, `s-maxage` for shared caches like a CDN, `private` for anything user-specific so intermediaries don't store it, and `no-store` for genuinely sensitive responses. Add validators so that even after expiry the client can revalidate cheaply: an `ETag` (a hash or version of the representation) or `Last-Modified`, which lets the client send `If-None-Match` and receive a 304 with no body, saving bandwidth if not a round trip. `stale-while-revalidate` is useful for serving a slightly stale response instantly while refreshing in the background. The critical mistake to avoid is caching personalised responses in a shared cache without a correct cache key or `private` — that serves one user's data to another, which is a security incident rather than a performance bug. `Vary` must list any header the response depends on, such as `Accept-Language` or `Authorization`.",
      why: "Caching is the cheapest scaling lever, and the personalisation trap is a real leak pattern.",
      trap: "Omitting `private` or `Vary` on an authenticated response served through a CDN.",
      followUps: ["How does ETag revalidation save work?", "What does `stale-while-revalidate` buy you?"],
      depth: "Advanced",
      tags: ["caching", "http"],
      topic: "http",
    },
    {
      id: "api-put-patch",
      q: "PUT or PATCH?",
      a: "PUT replaces the entire resource with the representation you send, so any field you omit is conceptually removed or reset — that's what makes it idempotent, since sending the same full representation twice yields the same state. PATCH applies a partial modification, sending only the fields to change. The common bug is using PUT with a partial body: the server either nulls the omitted fields, which silently destroys data, or ignores the omission, which makes it not really PUT and confuses every client that reads the spec. PATCH's own subtlety is that its semantics aren't fully defined by HTTP — you choose. A simple merge (send `{status: 'active'}` and only that changes) is the common convention, formalised as JSON Merge Patch, but it can't express deleting a field versus leaving it alone unless you assign a meaning to null, and it can't do array operations well. JSON Patch, an array of explicit operations, is more expressive and more awkward. Whichever you pick, document it, because clients cannot infer it.",
      why: "It's a small distinction that produces real data-loss bugs when confused.",
      trap: "Sending a partial body to PUT. Depending on the server you either wipe fields or get non-standard behaviour.",
      followUps: ["How do you distinguish 'set to null' from 'don't change' in a merge patch?", "Why is PATCH not idempotent in general?"],
      depth: "Intermediate",
      tags: ["http", "rest"],
      topic: "rest",
    },
    {
      id: "api-long-running",
      q: "How do you handle an operation that takes two minutes?",
      a: "Don't hold the request open — proxies, load balancers, and browsers all impose timeouts you don't control, and a blocked connection consumes a server slot for the whole duration. The standard pattern is to accept the work and return immediately: validate the input synchronously so obvious errors still surface as a 400, enqueue the job, and return `202 Accepted` with a job id and a `Location` header pointing at a status resource. The client then polls that status endpoint, which returns state (`pending`, `running`, `succeeded`, `failed`), progress if you can provide it, and on completion either the result or a link to it. For better client experience you can push instead of polling — a webhook, server-sent events, or a WebSocket — which removes the latency of the poll interval. Two things to get right regardless: make submission idempotent so a retried request doesn't start a second job, and give the job a retention and cleanup policy so status records don't accumulate forever.",
      why: "It's a common real requirement — exports, imports, video processing, report generation — with a well-established shape.",
      trap: "Increasing the gateway timeout to accommodate it. That ties up connections and still fails at some larger input.",
      followUps: ["How do you stop a retry starting a duplicate job?", "When is a webhook better than polling?"],
      depth: "Intermediate",
      tags: ["async", "design"],
      topic: "background-jobs",
    },
    {
      id: "api-grpc",
      q: "When would you choose gRPC?",
      a: "For internal service-to-service communication where you control both ends. It gives you a strongly-typed contract in protobuf that generates client and server code in every language, which removes a whole category of integration bugs and makes breaking changes visible at build time rather than at runtime. The wire format is compact binary over HTTP/2, so it's meaningfully faster and lighter than JSON over HTTP/1.1, with multiplexing over a single connection avoiding head-of-line blocking, and it supports streaming in both directions, which REST does awkwardly at best. The costs are why it's rarely a public API: browsers can't call it directly without grpc-web and a proxy, the binary payload can't be inspected with curl or read in a log, and you take on proto file management, code generation in the build, and a schema-evolution discipline. So the common architecture is gRPC between services and REST or GraphQL at the edge, which gets the internal performance and typing without imposing the tooling on external consumers.",
      why: "It shows awareness that internal and external APIs have genuinely different constraints.",
      trap: "Proposing gRPC for a public or browser-facing API. The tooling burden lands on consumers who didn't choose it.",
      followUps: ["How does protobuf handle backward compatibility?", "What does HTTP/2 multiplexing fix?"],
      depth: "Advanced",
      tags: ["grpc", "protocols"],
      topic: "grpc",
    },
  ],

  pitfalls: [
    "Don't return 200 with an error body — it breaks clients, proxies, and monitoring.",
    "Don't use 403 for an expired token — 401 tells the client to refresh.",
    "Don't put verbs in REST paths — `POST /orders/42/refunds`, not `POST /refundOrder`.",
    "Don't use offset pagination for large or frequently-changing collections.",
    "Don't rely on UUIDs to prevent IDOR — authorise per object.",
    "Don't send a partial body to PUT — that's what PATCH is for.",
    "Don't return 429 without `Retry-After`.",
    "Don't cache an authenticated response in a shared cache without `private` and a correct `Vary`.",
  ],

  numbers: [
    { label: "Default gateway timeout", value: "~30–60 s", note: "Anything longer needs 202 + a status endpoint." },
    { label: "Max page size", value: "cap at 100–1000", note: "An uncapped `limit` is a DoS vector." },
    { label: "JWT access token TTL", value: "5–15 min", note: "Short, because you can't revoke it; pair with a revocable refresh token." },
    { label: "Cookie size limit", value: "~4 KB", note: "Sent on every request — keep tokens small." },
  ],

  relatedTopics: ["rest", "graphql", "grpc", "api-versioning", "pagination-filtering", "idempotency", "rate-limiting", "authn-vs-authz", "sessions-vs-tokens", "jwt", "error-handling", "http"],
};
