import type { Area } from "../types";

export const behavioral: Area = {
  slug: "behavioral",
  title: "Behavioral & Communication",
  icon: "💬",
  stream: "Behavioral",
  blurb:
    "STAR done properly, the six stories that cover almost every question, and the answers to 'why are you leaving' and 'what's your expectation'.",

  mustKnow: [
    "Use STAR: Situation (brief), Task (your responsibility), Action (what YOU did), Result (measurable outcome). Most of the time goes on Action.",
    "Prepare 5–6 concrete stories and map them onto many questions. You are not inventing answers live; you are selecting and framing.",
    "Say 'I', not 'we'. Interviewers cannot credit you for what the team did — name your specific contribution, then credit others explicitly.",
    "Quantify results. 'Reduced p95 latency from 1.2 s to 300 ms' beats 'improved performance' every time.",
    "The failure question is about self-awareness. Pick a real failure, own it without excuses, and spend most of the answer on what changed afterwards.",
    "The conflict question is about how you handle disagreement, not about winning. Show that you sought to understand, used evidence, and committed to the outcome.",
    "Never criticise a previous employer, manager, or colleague. State what you're moving toward, not what you're escaping.",
    "Ask questions at the end — about the team, the work, and how success is measured. Having none reads as disinterest.",
    "For 'tell me about yourself', give a 90-second arc: where you are now, the most relevant thing you've done, why this role.",
    "Salary: give a researched range, anchor slightly high, and say it's flexible depending on the whole package.",
  ],

  sheets: [
    {
      title: "The six stories that cover almost everything",
      points: [
        "1. A hard technical problem you solved — shows depth, debugging method, and judgement.",
        "2. A project you led or drove end to end — shows ownership, planning, and delivery.",
        "3. A conflict or disagreement — with a peer, a manager, or another team.",
        "4. A failure or a mistake you made — shows self-awareness and what you changed.",
        "5. Working under pressure: an incident, a tight deadline, a shifting requirement.",
        "6. Something you influenced without authority — persuaded a team, changed a decision, drove adoption.",
        "Write each once, with numbers, and rehearse until you can tell it in two minutes.",
        "Most questions are one of these six wearing a different hat.",
      ],
    },
    {
      title: "STAR, calibrated",
      points: [
        "Situation — 2 sentences. Enough context to understand the stakes; no org chart.",
        "Task — 1 sentence. What YOU specifically owned.",
        "Action — 60–70% of the answer. Concrete steps, the alternatives you weighed, and why you chose what you chose.",
        "Result — quantified where possible, plus what you learned or changed afterwards.",
        "Total: 2–3 minutes. Then stop and let them ask follow-ups.",
        "If a metric is confidential, use relative figures: 'cut build time by roughly 60%'.",
        "Avoid: no numbers, all context and no action, or a result that's really the team's.",
      ],
    },
    {
      title: "Questions worth asking them",
      points: [
        "What does success look like for this role in the first six months?",
        "What's the biggest technical challenge the team is facing right now?",
        "How do decisions get made when engineers disagree on an approach?",
        "What does the path from commit to production look like, and how long does it take?",
        "How much of the work is new development versus maintaining existing systems?",
        "What's the on-call situation, and how is the load managed?",
        "How is technical debt prioritised against feature work?",
        "What's something about working here that surprised you?",
        "Avoid: questions answered on the careers page; anything only about perks in an early round.",
      ],
    },
    {
      title: "Red flags interviewers watch for",
      points: [
        "Blaming others for every failure — no ownership.",
        "'We' throughout, so your actual contribution is invisible.",
        "Criticising a previous employer at length.",
        "No questions at the end.",
        "Vagueness under follow-up — a sign the story isn't really yours.",
        "Inability to name a weakness, or a fake one ('I work too hard').",
        "Dismissing testing, code review, documentation, or on-call as someone else's job.",
        "Rigidity — no example of ever changing your mind based on evidence.",
      ],
    },
    {
      title: "The awkward questions, answered",
      points: [
        "'Why are you leaving?' — point forward: scope, technical direction, growth. Never a complaint.",
        "'Biggest weakness?' — a real one, plus the concrete system you've built to manage it.",
        "'Where do you see yourself in 5 years?' — direction and the kind of problems you want, not a job title.",
        "'Why this company?' — something specific about the product, the domain, or the engineering problems. Generic praise is transparent.",
        "'Expected salary?' — a researched range for the level and location; ask what's budgeted if pressed first.",
        "'Do you have other offers?' — be honest and neutral; don't invent leverage you can't substantiate.",
        "'Tell me about yourself' — 90 seconds: now, most relevant achievement, why this role.",
      ],
    },
  ],

  decisions: [
    {
      title: "Which failure story to tell",
      options: [
        {
          name: "A real, consequential failure",
          pick: ["Something that genuinely went wrong and mattered — a broken deploy, a wrong technical bet, a missed deadline.", "You can articulate the cause honestly and the specific change you made afterwards."],
          cost: ["Requires being vulnerable and choosing something you've genuinely processed."],
        },
        {
          name: "A trivial or disguised-strength failure",
          pick: ["Nothing. 'I cared too much about quality' reads as evasion and costs you credibility."],
          cost: ["Interviewers hear this constantly; it signals either no self-awareness or unwillingness to be honest."],
        },
      ],
      verdict: "Pick a real failure with real consequences, own it in one sentence without excuses, and spend the rest on what you changed. Don't pick something that undermines your core competence for the role.",
      topic: "common-behavioral-questions",
    },
    {
      title: "Naming a number first on salary",
      options: [
        {
          name: "Give a researched range",
          pick: ["You've researched the market for the level, location, and company stage.", "You want to anchor before they do.", "Some jurisdictions require them to post a band — use it."],
          cost: ["Anchoring too low caps you; too high can end the conversation early."],
        },
        {
          name: "Deflect once, then answer",
          pick: ["'What's the band for this level?' is a reasonable first response and often gets you the range.", "You genuinely don't know the market yet."],
          cost: ["Deflecting more than once reads as evasive and wastes goodwill."],
        },
      ],
      verdict: "Ask for their band once. If pressed, give a researched range, anchor at the upper end of realistic, and say the whole package matters. Never give a single number.",
      topic: "salary-negotiation",
    },
  ],

  qa: [
    {
      id: "beh-tell-me",
      q: "Tell me about yourself.",
      a: "Give a 90-second arc, not a career history. Start with where you are now in one sentence — role, focus, and the kind of systems you work on. Then the most relevant thing you've done for this specific role, with a concrete outcome: 'most recently I led the migration of our search backend, which cut p95 latency from 800 ms to 200 ms and let us retire two services'. Then why this role, tied to something specific about the company or the problem, which shows you've done more than skim the job description. What makes this answer land is relevance and brevity: you are choosing which parts of your history to surface based on what this role needs, and leaving obvious hooks the interviewer can pull on. What loses people is chronology — starting at university and walking forward — because it buries the relevant material and uses up the goodwill you have at the start of the conversation. It's the one question you can be certain of, so it should be rehearsed until it sounds unrehearsed.",
      why: "It sets the frame for the entire interview, and a rambling answer costs you attention you don't get back.",
      trap: "Reciting your CV chronologically. They have your CV; they want to know what's relevant and why you're here.",
      followUps: ["Why are you looking to move?", "What are you looking for in your next role?"],
      depth: "Core",
      tags: ["opening"],
      topic: "common-hr-questions",
    },
    {
      id: "beh-star",
      q: "How should you structure a behavioral answer?",
      a: "STAR, weighted correctly. Situation gets two sentences — just enough context to make the stakes clear, without an org chart or a product history. Task gets one sentence stating what you specifically owned, which matters because it separates your responsibility from the team's. Action should be sixty to seventy percent of the answer: the concrete steps you took, the alternatives you considered, and why you chose as you did — the reasoning is what's actually being assessed, since anyone can describe an outcome. Result closes it with a quantified outcome where possible and what you learned or changed afterwards. Two calibration points. Say 'I' for your own actions and 'we' only where it's genuinely accurate, then credit colleagues explicitly, because an answer entirely in 'we' leaves the interviewer unable to assess you. And stop at two or three minutes rather than continuing to fill silence — a crisp answer invites follow-up questions, which is where the real conversation happens.",
      why: "Structure is what makes a good story legible; unstructured answers lose even when the underlying work was strong.",
      trap: "Spending most of the time on Situation. Context is scene-setting; the Action is the answer.",
      followUps: ["What if you don't have a metric for the result?", "How long should an answer be?"],
      depth: "Core",
      tags: ["technique"],
      topic: "star-method",
    },
    {
      id: "beh-conflict",
      q: "Tell me about a disagreement with a colleague.",
      a: "Pick a genuine technical or process disagreement where the outcome mattered, and structure the answer around how you handled it rather than who was right. Describe the substance briefly — say, a colleague wanted to introduce a new datastore while you thought the existing one would scale for the foreseeable horizon. Then show the behaviours being assessed: that you sought to understand their reasoning first, and can articulate their position fairly, because being able to state the other side accurately is the strongest signal available here; that you moved the discussion from opinion to evidence, by prototyping, benchmarking, or writing down the trade-offs; and that you escalated appropriately or committed to the decision once made. Crucially, an answer where you were wrong and changed your mind is at least as strong as one where you prevailed — it demonstrates you update on evidence. What fails is a story where the colleague was simply unreasonable, or where you avoided the conflict entirely, or where you were overruled and quietly resented it.",
      why: "Disagreement is constant in engineering, and the interviewer is assessing whether working with you is productive.",
      trap: "Making it a story about being right. The assessment is about the process, and 'I was right and they came round' reads as inflexible.",
      followUps: ["Tell me about a time you changed your mind.", "How do you handle being overruled?"],
      depth: "Core",
      tags: ["conflict"],
      topic: "common-behavioral-questions",
    },
    {
      id: "beh-failure",
      q: "Tell me about a time you failed.",
      a: "Choose something real and consequential — a design decision that didn't survive contact with production, an outage you caused, a deadline you missed, a project that shipped and wasn't used. Then structure it so most of the answer is forward-looking. State what happened and own your part in one or two sentences without hedging or distributing blame; qualifying it heavily is what makes an answer sound evasive. Explain what you actually did about it at the time — how you detected it, how you communicated, how you mitigated — because response matters as much as the mistake. Then, and this is the bulk of the answer, what changed as a result: the specific practice, check, or habit you adopted, ideally with evidence it stuck, such as a postmortem you wrote or a guardrail you added that caught something later. The failure mode here is choosing something trivial or a disguised strength, which reads as unwillingness to be honest. One sensible constraint: don't choose a failure in the core competency this role requires.",
      why: "It's a direct test of self-awareness and whether you learn, which predicts how you'll handle the inevitable mistakes here.",
      trap: "'I'm a perfectionist' or a failure that was really someone else's. Both signal you can't or won't examine your own work.",
      followUps: ["What would you do differently now?", "How did you communicate it at the time?"],
      depth: "Core",
      tags: ["failure", "self-awareness"],
      topic: "common-behavioral-questions",
    },
    {
      id: "beh-why-leaving",
      q: "Why are you leaving your current role?",
      a: "Point forward rather than back. Frame it around what you're moving toward — greater scope, a technical domain you want to go deeper in, a stage of company you're better suited to, an area where you want to grow — and connect that to something specific about this role. If there's a factual reason like a layoff, a reorganisation, or a relocation, state it plainly and without drama; those are common and unremarkable. What damages you is criticising your current employer, manager, or colleagues, even when the criticism is entirely justified, because the interviewer has no way to verify it and will reasonably wonder how you'll describe them in a year. It also shifts the conversation to a place with no upside for you. If you're leaving something genuinely bad, translate it into a positive: a lack of technical direction becomes wanting to work somewhere with a clear engineering vision; a stalled career becomes wanting more ownership. Keep it short — thirty seconds — and move the conversation to what attracts you here.",
      why: "It's asked in essentially every interview and it's the easiest place to accidentally lose an offer.",
      trap: "Venting, even mildly. It's the single most common self-inflicted damage in behavioral rounds.",
      followUps: ["What would have made you stay?", "What are you looking for that you don't have now?"],
      depth: "Core",
      tags: ["hr"],
      topic: "common-hr-questions",
    },
    {
      id: "beh-weakness",
      q: "What's your biggest weakness?",
      a: "Name a real one, then show the system you've built around it. The structure that works is: the weakness stated plainly, a specific instance where it cost something, and the concrete mechanism you now use to manage it — for example, a tendency to go too deep on a technical problem before checking it's the right problem, which cost a week on an optimisation nobody needed, now managed by writing down the expected impact before starting and checking in with a colleague at a fixed point. That structure works because it demonstrates the thing actually being assessed, which is self-awareness and the ability to improve deliberately, rather than the absence of flaws. Two things to avoid. The disguised strength — perfectionism, working too hard, caring too much — is transparent and interviewers hear it constantly, so it reads as either low self-awareness or unwillingness to be candid. And don't name a weakness that's central to the job you're applying for; choose something real but not disqualifying.",
      why: "The question is entirely about self-awareness, and a non-answer is itself the answer.",
      trap: "'I'm a perfectionist.' It's the most-heard answer and it signals evasion.",
      followUps: ["How has that changed over the last year?", "What feedback do you get most often?"],
      depth: "Core",
      tags: ["hr", "self-awareness"],
      topic: "common-hr-questions",
    },
    {
      id: "beh-influence",
      q: "Tell me about a time you influenced a decision without authority.",
      a: "This question separates senior candidates, because seniority is largely the ability to change outcomes you don't control. Pick something concrete — persuading a team to adopt a practice, changing a technical direction, getting a piece of debt prioritised — and show the method rather than the conclusion. The elements that make it credible: you understood the other party's constraints and incentives before advocating, because an argument that ignores what someone is measured on will fail regardless of its technical merit; you brought evidence rather than opinion, such as a prototype, a measurement, or a written analysis of trade-offs, since a working demonstration moves people that an argument doesn't; you found the person whose support mattered and made the case in their terms; and you were willing to run a bounded experiment rather than demanding a wholesale commitment. Close with the outcome and, ideally, evidence it lasted. If the attempt partly failed, that's still a strong story if you can say what you'd do differently.",
      why: "It's the clearest behavioral signal of seniority, and many candidates have no prepared example for it.",
      trap: "Describing a case where you simply escalated to a manager who decided. That's authority, not influence.",
      followUps: ["What did you do when someone still disagreed?", "How did you know it stuck?"],
      depth: "Intermediate",
      tags: ["leadership", "influence"],
      topic: "leadership-principles",
    },
    {
      id: "beh-pressure",
      q: "Tell me about a high-pressure situation — an outage or a hard deadline.",
      a: "For an incident, the structure interviewers want is: what you did to stop the bleeding first, and only then what you did to find the root cause. Mitigation before diagnosis is the mark of someone who has actually handled production — roll back, fail over, disable the feature, then investigate with the pressure off. Show communication as an explicit action, not an afterthought: who you told, how often, and what you told them, because in an incident the information flow is half the job and it's the part candidates most often omit. Then the resolution, the follow-up, and specifically the blameless postmortem and the concrete changes that came out of it — a monitor, a guardrail, a runbook. For a deadline story, the assessed behaviour is different: it's whether you flagged the risk early and negotiated scope explicitly, rather than working weekends silently and delivering something rushed. Saying 'I told the stakeholder in week two that all three features wouldn't fit, and we agreed to cut one' is a much stronger answer than heroics.",
      why: "It reveals whether someone has genuine production experience and whether they communicate under stress.",
      trap: "Presenting heroic overtime as the solution. It signals poor estimation and poor escalation, and it doesn't scale.",
      followUps: ["What did the postmortem change?", "How did you decide what to cut?"],
      depth: "Intermediate",
      tags: ["incidents", "pressure"],
      topic: "common-behavioral-questions",
    },
    {
      id: "beh-questions-to-ask",
      q: "What should you ask the interviewer?",
      a: "Ask things whose answers would actually change your decision, which is both genuinely useful and the most convincing form of interest. Good areas: what success looks like in the first six months, which tells you how the role is really defined; the biggest technical challenge the team faces now; how decisions get made when engineers disagree, which reveals the engineering culture better than any values page; what the path from commit to production looks like and how long it takes, which tells you a great deal about engineering maturity; the split between new development and maintenance; how on-call works and how the load is managed; and how technical debt gets prioritised against features. Tailor them to the interviewer — ask an engineer about the codebase and daily work, a manager about team structure and growth, a senior leader about direction and priorities. Having no questions reads as disinterest and is a genuine negative signal. So does asking only about perks and holiday in an early round, though those are entirely fair once you're discussing an offer.",
      why: "It's the part of the interview candidates most often waste, and it's where you can both gather real information and demonstrate seriousness.",
      trap: "Saying 'no, I think you've covered everything'. Have three questions written down regardless.",
      followUps: ["What would make you turn down an offer?", "What matters most to you in a team?"],
      depth: "Core",
      tags: ["closing"],
      topic: "hr-fundamentals",
    },
    {
      id: "beh-salary",
      q: "What are your salary expectations?",
      a: "Research before you're asked, so you have a defensible range for the level, location, and company stage from sources like Levels.fyi, Glassdoor, or posted bands — and note that many jurisdictions now require the band to be published, so check first. When asked, it's reasonable to turn it around once: 'what's the band for this level?' often gets you the range and costs nothing. If pressed, give a range rather than a single number, anchored so the bottom of your range is a number you'd genuinely accept, since you will not be offered above the bottom. Frame it as flexible depending on the total package — base, equity, bonus, and level — which keeps the conversation open and signals you understand compensation is multi-dimensional. Two things to avoid: naming a single number, which removes all room, and inventing competing offers you don't have, which is easy to be caught out on and ends badly. And remember the strongest position in any negotiation is being willing to walk, which comes from having a realistic sense of the market rather than from tactics.",
      why: "It's the question most likely to cost you money, and it's entirely predictable, so it should be prepared.",
      trap: "Giving a single number, or giving any number without research. Both leave money on the table.",
      followUps: ["What if the band is below your range?", "How do you value equity against base?"],
      depth: "Intermediate",
      tags: ["negotiation"],
      topic: "salary-negotiation",
    },
    {
      id: "beh-explain-technical",
      q: "Explain a technical concept to a non-technical stakeholder.",
      a: "Start with what it means for them, not with how it works. A product manager asking why a migration takes six weeks doesn't need the schema; they need to know what it enables, what it risks, and what it costs — so lead with 'this lets us support the enterprise customers we keep losing, and until it's done every new feature in this area takes twice as long'. Then use an analogy grounded in something they know, keeping it accurate enough that it won't mislead them later, since a memorable but wrong analogy is worse than none. Then offer depth in layers and let them pull: give the one-paragraph version and pause, rather than delivering everything you know. Avoid jargon, or define it once if the term is genuinely needed for future conversations. And close by making the decision explicit — the options, the trade-offs, and your recommendation — because a stakeholder usually needs to decide something, not to understand a system. This is a skill worth naming as such, because it's most of the difference between a senior engineer's influence and a mid-level engineer's.",
      why: "Communication with non-engineers is a large part of senior work and is directly assessed here.",
      trap: "Demonstrating how much you know. The assessment is whether the listener can now make a decision.",
      followUps: ["How would you explain technical debt to a CFO?", "How do you push back on an unrealistic deadline?"],
      depth: "Intermediate",
      tags: ["communication"],
      topic: "hr-fundamentals",
    },
  ],

  pitfalls: [
    "Don't answer in 'we' throughout — the interviewer can't assess a team.",
    "Don't criticise a past employer, manager, or colleague, however justified.",
    "Don't give a disguised-strength weakness — it reads as evasion.",
    "Don't spend most of a STAR answer on the Situation.",
    "Don't tell a conflict story where you were simply right and they came round.",
    "Don't present overtime heroics as a success — it signals poor estimation and escalation.",
    "Don't say you have no questions at the end.",
    "Don't give a single salary number, or any number you haven't researched.",
    "Don't improvise stories — prepare six, with numbers, and rehearse them.",
  ],

  numbers: [
    { label: "STAR answer length", value: "2–3 min", note: "Action is 60–70% of it." },
    { label: "'Tell me about yourself'", value: "~90 seconds", note: "Now → most relevant achievement → why this role." },
    { label: "Stories to prepare", value: "5–6", note: "They cover the overwhelming majority of questions." },
    { label: "Questions to have ready", value: "3+", note: "Tailored to who is interviewing you." },
  ],

  relatedTopics: ["star-method", "common-behavioral-questions", "common-hr-questions", "hr-fundamentals", "leadership-principles", "salary-negotiation"],
};
