import type { Area } from "../types";

export const cachingMessaging: Area = {
  slug: "caching-messaging",
  title: "Caching & Messaging",
  icon: "⚡",
  stream: "Backend & Data",
  blurb:
    "Redis, Kafka, queues, and the two hardest problems in the field — cache invalidation and exactly-once delivery.",

  mustKnow: [
    "Caching trades freshness for speed. Every cache introduces staleness; the design question is how much you can tolerate and for which data.",
    "Cache-aside is the default: check cache → miss → read database → populate. The application owns the logic.",
    "There are only two ways to invalidate: a TTL (time-based, simple, bounded staleness) or explicit deletion on write (precise, easy to miss a path).",
    "A cache stampede happens when a hot key expires and every request misses at once. Mitigate with single-flight locking, jittered TTLs, and probabilistic early refresh.",
    "Redis is single-threaded for command execution, so every command is atomic — but one slow command (`KEYS *`) blocks every client.",
    "A queue distributes work to competing consumers (each message handled once); pub/sub broadcasts to all subscribers.",
    "Kafka is a durable, partitioned, replayable log — consumers track their own offset, so messages aren't deleted on read.",
    "Ordering is only guaranteed within a Kafka partition, so the partition key determines what stays ordered.",
    "Exactly-once end-to-end doesn't exist across system boundaries — use at-least-once delivery plus idempotent consumers.",
    "Always have a dead-letter queue and monitor consumer lag; a queue silently backing up is the standard failure.",
  ],

  sheets: [
    {
      title: "Caching patterns",
      points: [
        "Cache-aside (lazy loading) — app checks cache, on miss reads the DB and populates. Default; only requested data is cached.",
        "Read-through — the cache itself loads on miss. Cleaner app code, needs cache support.",
        "Write-through — write to cache and DB together. Reads are always fresh; writes are slower.",
        "Write-behind (write-back) — write to cache, flush to DB asynchronously. Fast writes, real data-loss window.",
        "Refresh-ahead — proactively refresh hot keys before expiry; avoids stampedes on predictable hot data.",
        "Eviction policies: LRU (default choice), LFU (better for skewed access), TTL-only, random.",
        "Cache what is expensive to compute and read far more often than written. Caching everything wastes memory and multiplies staleness.",
      ],
    },
    {
      title: "Redis in practice",
      points: [
        "Data types: String, Hash (objects), List (queues), Set, Sorted Set (leaderboards, rate limiting, delayed queues), Stream, HyperLogLog, Bitmap, Geo.",
        "Single-threaded command execution → every command is atomic; `MULTI/EXEC` groups commands; Lua scripts run atomically.",
        "Never run `KEYS *` in production — it's O(n) and blocks everything. Use `SCAN`.",
        "Persistence: RDB (point-in-time snapshots, fast restart, some loss) vs AOF (append-only log, more durable, slower). Often both.",
        "`SETEX`/`SET key val EX n` for TTL; `INCR` for atomic counters; `SETNX` for a simple lock (use Redlock or a proper library for real distributed locks).",
        "Cluster mode shards by hash slot; multi-key operations must share a hash tag to land on one slot.",
        "Redis is not durable by default — treat it as a cache unless you have configured and tested otherwise.",
      ],
    },
    {
      title: "Kafka essentials",
      points: [
        "Topic → partitions → ordered, immutable, append-only log. Messages persist by retention policy, not by consumption.",
        "Producers choose a partition by key hash (same key → same partition → ordered) or round-robin.",
        "Consumer group: each partition is assigned to exactly one consumer in the group — so parallelism is capped by partition count.",
        "Offsets are tracked per consumer group; committing after processing gives at-least-once, before gives at-most-once.",
        "Replication factor + `min.insync.replicas` + `acks=all` is what makes writes durable.",
        "Rebalancing pauses consumption — frequent rebalances (from long processing or short `max.poll.interval.ms`) look like an outage.",
        "Consumer lag is THE metric: how far behind the log a group is.",
        "Compacted topics keep only the latest value per key — useful as a changelog or materialised state.",
      ],
    },
    {
      title: "Queue reliability checklist",
      points: [
        "Idempotent consumers — assume every message can arrive twice.",
        "Dead-letter queue for poison messages, with an alert; a silently-discarded message is worse than a failure.",
        "Retry with exponential backoff and jitter; cap attempts before dead-lettering.",
        "Visibility timeout / ack deadline must exceed worst-case processing time, or the message is redelivered while still being processed.",
        "Monitor queue depth, consumer lag, and message age — age is the one that maps to user impact.",
        "Poison-message handling: a message that always fails will block an ordered partition forever.",
        "Schema versioning on messages — producers and consumers deploy independently.",
        "Decide ordering requirements explicitly; global ordering costs you parallelism.",
      ],
    },
    {
      title: "Where to cache (outermost first)",
      points: [
        "Browser cache — `Cache-Control`, free, zero network.",
        "CDN / edge — static assets and cacheable responses close to the user.",
        "API gateway / reverse proxy — full response caching for anonymous traffic.",
        "Application in-process — tiny, static, per-instance data (feature flags, config). Inconsistent across replicas.",
        "Distributed cache (Redis) — shared across instances: sessions, hot rows, computed results.",
        "Database — query cache, materialised views, and the buffer pool itself.",
        "The further out you cache, the cheaper the hit and the harder the invalidation.",
      ],
    },
  ],

  decisions: [
    {
      title: "Kafka vs RabbitMQ vs SQS",
      options: [
        {
          name: "Kafka",
          pick: ["High-throughput event streaming.", "Multiple independent consumers of the same stream.", "Replay — reprocess history after a bug or to build a new view.", "Ordering within a key, and event sourcing."],
          cost: ["Operationally heavy (though managed options exist).", "No per-message ack or delay; retry semantics are yours to build.", "Parallelism capped by partition count."],
        },
        {
          name: "RabbitMQ",
          pick: ["Task distribution with per-message acknowledgement.", "Complex routing: topic exchanges, fanout, headers.", "Priority queues, per-message TTL, delayed delivery."],
          cost: ["Lower throughput than Kafka.", "Messages are removed on ack — no replay.", "Queue buildup degrades broker performance."],
        },
        {
          name: "SQS / managed queue",
          pick: ["You want zero operational burden.", "Simple work distribution at any scale.", "Already on AWS."],
          cost: ["Standard queues are at-least-once and unordered (FIFO queues trade throughput for order).", "Polling model; less routing flexibility.", "Vendor lock-in."],
        },
      ],
      verdict: "Event log you may replay, with several consumers → Kafka. Task queue with rich routing → RabbitMQ. Simple distribution with no ops → SQS.",
      topic: "queues-vs-pubsub",
    },
    {
      title: "TTL vs explicit invalidation",
      options: [
        {
          name: "TTL",
          pick: ["You can define an acceptable staleness window.", "Many write paths, so explicit invalidation would be easy to miss.", "Simple, self-healing — a bug in invalidation corrects itself on expiry."],
          cost: ["Data is stale for up to the TTL.", "Synchronised expiry causes stampedes unless jittered.", "Wasted refreshes for data that didn't change."],
        },
        {
          name: "Explicit invalidation on write",
          pick: ["Freshness matters and writes are well-controlled.", "Expensive-to-compute values you don't want to recompute on a timer."],
          cost: ["Miss one write path and the cache is wrong indefinitely — the worst failure mode.", "Distributed invalidation is racy: a delete can be overtaken by a concurrent repopulate.", "Harder to reason about as write paths multiply."],
        },
      ],
      verdict: "Use both: explicit invalidation for correctness, a TTL underneath as a safety net so any missed path self-corrects.",
      topic: "cache-invalidation",
    },
    {
      title: "In-process cache vs distributed cache",
      options: [
        {
          name: "In-process",
          pick: ["Nanosecond access, no network hop.", "Small, rarely-changing data: config, feature flags, reference tables."],
          cost: ["Duplicated per instance and inconsistent between them — the same request can get different answers from different pods.", "Lost on restart; competes with heap and GC.", "Invalidation must fan out to every instance."],
        },
        {
          name: "Distributed (Redis)",
          pick: ["Shared state that must be consistent across instances: sessions, rate-limit counters, hot rows.", "Survives instance restarts; capacity independent of app memory."],
          cost: ["A network round trip (~0.5 ms) per access.", "Another component to run, secure, and monitor.", "A new failure mode — decide fail-open or fail-closed up front."],
        },
      ],
      verdict: "Anything that must be consistent across replicas goes in Redis. In-process only for small, static, staleness-tolerant data — and bound it.",
      topic: "distributed-caching",
    },
  ],

  qa: [
    {
      id: "cache-invalidation",
      q: "Why is cache invalidation hard?",
      a: "Because a cache is a second copy of the truth, and keeping two copies in agreement across concurrent writers and unreliable networks is genuinely difficult. There are only two mechanisms — expire on a timer, or delete on write — and both have failure modes. A TTL bounds staleness but guarantees you serve stale data for that window, and if many keys expire together you get a stampede. Explicit invalidation is precise but fragile: every code path that writes must remember to invalidate, and the one path someone forgets leaves the cache permanently wrong, which is far worse than briefly stale. It's also racy in a distributed setting — a reader can fetch the old value from the database, get descheduled, and write it into the cache after another thread's invalidation has already run, leaving stale data with a fresh TTL. The practical answer is defence in depth: invalidate explicitly for correctness, put a TTL underneath so any missed path self-heals, and for the racy case use versioned keys or write-through so the ordering can't invert.",
      why: "It's a famous problem and the good answer explains the specific failure modes rather than repeating the joke.",
      trap: "Choosing invalidation-only. Missing one write path leaves permanently wrong data with no self-correction.",
      followUps: ["Describe the read-repopulate race.", "How do versioned cache keys sidestep invalidation?"],
      depth: "Intermediate",
      tags: ["caching"],
      topic: "cache-invalidation",
    },
    {
      id: "cache-stampede-2",
      q: "What is a cache stampede and how do you handle it?",
      a: "When a heavily-requested key expires, every concurrent request misses simultaneously and they all query the database at once. A key serving ten thousand requests a second turns into ten thousand identical queries against a database sized for a few hundred, which can take it down — and then retries keep it down. It's most dangerous for your hottest keys, precisely the ones the cache was protecting. The mitigations are usually combined. Single-flight or lock-based repopulation: the first request to miss takes a short distributed lock and recomputes while the others either wait briefly or serve the stale value, so exactly one query goes through. Probabilistic early expiry: as a key nears its TTL each request has a small, rising chance of refreshing it, so one refreshes early and the rest keep hitting a warm cache. And jittered TTLs so keys populated together don't expire together — which also addresses the related cold-start problem where a cache restart or deploy sends everything to the database at once.",
      why: "It's a real outage pattern that shows whether someone has operated a cache under load rather than just added one.",
      trap: "Treating a cache as pure upside. It changes your failure modes, and a stampede or cold start can be worse than having no cache.",
      followUps: ["Why serve stale rather than block on the lock?", "What happens to your database when Redis restarts?"],
      depth: "Advanced",
      tags: ["caching", "reliability"],
      topic: "cache-strategies",
    },
    {
      id: "msg-queue-vs-pubsub",
      q: "Queue vs pub/sub — what's the difference?",
      a: "A queue is for work distribution: several consumers compete, and each message is delivered to exactly one of them, so adding consumers increases throughput. Pub/sub is for event broadcast: every subscriber receives every message, so adding subscribers adds new reactions to the same events rather than more capacity. The distinction matters because it determines what happens when you scale — if you deploy three replicas of a service subscribed to a fanout topic, each one processes every message, which means the email you meant to send once gets sent three times. Kafka blurs the line usefully: a consumer group behaves as a queue, since each partition goes to one member, while multiple independent groups each receive the full stream, so you get both semantics from one topic. That's why Kafka suits event-driven architectures where one event feeds several unrelated systems — analytics, search indexing, notifications — each consuming at its own pace and able to replay history independently.",
      why: "Confusing the two produces duplicate side effects, which is a common and embarrassing production bug.",
      trap: "Scaling a pub/sub subscriber horizontally and expecting work sharing. Every replica gets every message unless they share a consumer group.",
      followUps: ["How does a Kafka consumer group give you both?", "What breaks if you add a replica of a fanout subscriber?"],
      depth: "Core",
      tags: ["messaging"],
      topic: "queues-vs-pubsub",
    },
    {
      id: "msg-exactly-once",
      q: "Can you get exactly-once delivery?",
      a: "Not end to end across system boundaries. The reason is fundamental: after processing a message the consumer must acknowledge, and that acknowledgement can be lost, so the broker cannot distinguish 'processed but ack lost' from 'never processed'. Acknowledging before processing gives at-most-once, where a crash loses work; acknowledging after gives at-least-once, where a crash causes redelivery. There's no third option that survives arbitrary failure. What systems like Kafka call exactly-once is exactly-once processing within their transactional boundary — idempotent producers plus atomically committing offsets and output records in one transaction — which is real and useful for Kafka-to-Kafka pipelines, but it doesn't extend to a side effect in an external system such as charging a card or sending an email. So the practical architecture everyone actually uses is at-least-once delivery plus idempotent consumers: give each message a stable id, record processed ids, and make the handler safe to run twice. That produces exactly-once *effects*, which is what people actually want.",
      why: "The 'exactly-once effects, not exactly-once delivery' distinction is a clear seniority marker.",
      trap: "Claiming a broker guarantees exactly-once. Ask what happens to an external side effect on redelivery and the claim collapses.",
      followUps: ["How do you make a consumer idempotent?", "What does Kafka's transactional API actually cover?"],
      depth: "Advanced",
      tags: ["messaging", "reliability"],
      topic: "delivery-guarantees",
    },
    {
      id: "kafka-partitions",
      q: "How do Kafka partitions and consumer groups interact?",
      a: "A topic is split into partitions, each an ordered append-only log. Within a consumer group, each partition is assigned to exactly one consumer, which is what prevents two members processing the same message — and it means parallelism is capped by partition count, so ten consumers on a four-partition topic leaves six idle. Ordering is guaranteed only within a partition, so the producer's partition key decides what stays ordered: keying by user id means all events for a user are ordered relative to each other while different users process in parallel, which is usually exactly the guarantee you want. Two operational consequences. Adding partitions later changes the key-to-partition mapping, so ordering across the change isn't preserved and you should over-provision partitions rather than plan to add them. And rebalancing — triggered by a consumer joining, leaving, or failing to poll within `max.poll.interval.ms` — pauses consumption for the group, so slow processing causes a rebalance, which causes lag, which looks like an outage.",
      why: "Partition count and key choice are the two decisions that most affect a Kafka deployment, and both are hard to change later.",
      trap: "Adding consumers to increase throughput without adding partitions. The extras sit idle.",
      followUps: ["What happens to ordering when you add partitions?", "Why does slow processing trigger a rebalance?"],
      depth: "Advanced",
      tags: ["kafka"],
      topic: "topics-partitions",
    },
    {
      id: "redis-single-thread",
      q: "Redis is single-threaded — isn't that a bottleneck?",
      a: "Rarely, and the design buys more than it costs. Because commands execute one at a time on a single thread, every command is atomic without any locking, which removes an entire class of concurrency bugs and makes operations like `INCR` and `SETNX` reliable primitives for counters and locks. There's no lock contention, no context switching, and no cache-coherency traffic, and since Redis is in-memory it's bound by memory bandwidth and network I/O rather than CPU — a single instance handles on the order of a hundred thousand operations per second, which is more than most applications need. Modern Redis does use additional threads for I/O and background tasks like persistence and key eviction; only command execution is serial. The real risk is that one slow command blocks every client: `KEYS *` on a large keyspace, a big `SORT`, a Lua script with a loop, or deleting a huge collection synchronously. That's why you use `SCAN` instead of `KEYS`, `UNLINK` instead of `DEL` for large values, and keep Lua scripts short.",
      why: "It reframes an apparent weakness as a design trade-off, and the slow-command hazard is a genuine production issue.",
      trap: "Assuming single-threaded means slow. The atomicity guarantee is why Redis is usable as a coordination primitive at all.",
      followUps: ["Why is `KEYS` dangerous and what replaces it?", "How would you implement a distributed lock safely?"],
      depth: "Intermediate",
      tags: ["redis"],
      topic: "redis-data-structures",
    },
    {
      id: "msg-dlq",
      q: "What is a dead-letter queue and why do you need one?",
      a: "A separate queue where messages go after repeatedly failing to process. Without one you face two bad options: retry forever, in which case a single malformed message blocks the queue — and on an ordered partition, blocks everything behind it indefinitely — or discard after N attempts, in which case data disappears silently and nobody finds out until someone notices missing records weeks later. A DLQ gives you a third option: park the message with its failure context, let the main queue continue, and alert on the DLQ becoming non-empty so a human investigates. The details that make it useful are capturing the error and stack trace alongside the original payload, retrying with exponential backoff before dead-lettering so transient failures recover on their own, and having a documented, tested replay path for after you fix the bug. The alert matters as much as the queue — an unmonitored DLQ is just a slower way to lose messages.",
      why: "It's a small operational practice whose absence causes silent data loss, which is the worst failure class.",
      trap: "Creating a DLQ without alerting or a replay mechanism. It becomes a graveyard nobody looks at.",
      followUps: ["How do you distinguish a transient failure from a poison message?", "What does the replay path look like?"],
      depth: "Intermediate",
      tags: ["messaging", "reliability"],
      topic: "rabbitmq-reliability",
    },
    {
      id: "msg-outbox",
      q: "How do you reliably publish an event when you also write to the database?",
      a: "The naive version — commit the transaction, then publish — has a gap: if the process dies between the two, the database changed but no event was emitted, and downstream systems are permanently inconsistent. Publishing first is worse, because the transaction might roll back and you've announced something that didn't happen. You can't wrap a database transaction and a broker publish in one atomic operation without distributed transactions, which are slow and operationally painful. The standard solution is the transactional outbox: within the same database transaction as your business write, insert a row into an `outbox` table describing the event. That's atomic by construction, since it's one transaction in one database. A separate relay process then reads unpublished outbox rows and publishes them to the broker, marking them sent — either by polling the table or by tailing the database's change log with CDC, which is more efficient. The relay may publish twice if it crashes after sending but before marking, so consumers still need to be idempotent, but no event is ever lost.",
      why: "It's the canonical dual-write problem and the outbox pattern is the answer senior candidates are expected to name.",
      trap: "Assuming a try/catch around both operations fixes it. Process death between them isn't catchable.",
      followUps: ["Why is CDC better than polling the outbox table?", "Why do consumers still need idempotency?"],
      depth: "Advanced",
      tags: ["messaging", "consistency"],
      topic: "event-sourcing",
    },
    {
      id: "cache-what-to-cache",
      q: "How do you decide what to cache?",
      a: "Look for data that's expensive to produce and read far more often than it changes — that ratio is the whole decision. A query taking 200 ms and read a thousand times a minute while changing hourly is an obvious candidate; a query taking 2 ms and read once per user session is not, and caching it adds a network hop, memory, and staleness for no benefit. Then check that the access pattern is skewed enough for a cache to help: caching works because of locality, so if requests are uniformly spread over ten million keys your hit rate will be near zero and you've added latency to every request. Then ask what staleness costs — a like count can be a minute old, a permission check cannot. Finally, be honest about what you're hiding: caching an N+1 query pattern or a missing index makes the symptom disappear while the underlying problem stays and reappears on every cache miss, deploy, and cold start. Fix the query first, then cache what's genuinely expensive.",
      why: "The 'caching hides bad queries' point is what separates thoughtful engineers from people who add Redis reflexively.",
      trap: "Caching everything. Memory is finite, and each cached item is another thing that can be stale or wrong.",
      followUps: ["What hit rate makes a cache worthwhile?", "How would you find your hot keys?"],
      depth: "Intermediate",
      tags: ["caching", "design"],
      topic: "caching-basics",
    },
    {
      id: "msg-backpressure",
      q: "What is backpressure and how do you handle it in a message system?",
      a: "It's the signal that a consumer can't keep up with a producer, and handling it means deciding what to sacrifice — because you cannot keep accepting work faster than you can do it forever. Without a strategy the queue grows without bound until you exhaust memory or disk, and the failure is abrupt and total. The options are to slow the producer, which is genuine backpressure and works when the producer is under your control; to buffer, which is what a queue is for, but only as a shock absorber for bursts, not a sustained mismatch; to shed load by rejecting requests early with a 429 or 503, which is far better than collapsing; or to scale consumers, which is the real fix when the load is legitimate — though remember Kafka caps parallelism at partition count. The signals to watch are queue depth, consumer lag, and message age, with age the most useful because it maps directly to user-visible delay. The trap is unbounded buffering, which converts a manageable slowdown into an out-of-memory crash and loses everything in flight.",
      why: "It's the systems-thinking version of a performance question and shows whether someone designs for overload.",
      trap: "Sizing the queue larger to cope. An unbounded buffer delays the failure and makes it worse.",
      followUps: ["Why is message age better than queue depth as an alert?", "When is load shedding the right answer?"],
      depth: "Advanced",
      tags: ["reliability", "messaging"],
      topic: "backpressure",
    },
  ],

  pitfalls: [
    "Don't rely on invalidation alone — add a TTL underneath so a missed write path self-corrects.",
    "Don't add a cache without addressing stampede and cold start.",
    "Don't cache to hide an N+1 or a missing index — fix the query first.",
    "Don't scale a pub/sub subscriber horizontally without a consumer group — every replica gets every message.",
    "Don't claim exactly-once delivery — say at-least-once plus idempotent consumers.",
    "Don't add Kafka consumers beyond the partition count — they sit idle.",
    "Don't run `KEYS *` in production — it blocks every client.",
    "Don't publish an event outside the database transaction — use the outbox pattern.",
    "Don't leave a DLQ unmonitored — that's silent data loss.",
  ],

  numbers: [
    { label: "Redis ops/sec (single instance)", value: "~100k+", note: "Memory- and network-bound, not CPU-bound." },
    { label: "Redis round trip", value: "~0.5 ms", note: "vs ~100 ns for in-process — the cost of consistency across replicas." },
    { label: "Kafka consumer parallelism", value: "= partition count", note: "Extra consumers in a group idle." },
    { label: "Useful cache hit ratio", value: "> 80%", note: "Below this, the added hop may cost more than it saves." },
    { label: "Key queue alert", value: "Oldest message age", note: "Maps to user-visible delay better than depth." },
  ],

  relatedTopics: ["caching-basics", "cache-strategies", "cache-invalidation", "distributed-caching", "redis-data-structures", "redis-patterns", "kafka-fundamentals", "topics-partitions", "queues-vs-pubsub", "delivery-guarantees", "backpressure", "event-sourcing"],
};
