import type { Area } from "../types";

export const databases: Area = {
  slug: "databases",
  title: "Databases & SQL",
  icon: "🗄️",
  stream: "Backend & Data",
  blurb:
    "Indexes, transactions, isolation, and the N+1 query — the four things that account for most real database interview questions and most real production incidents.",

  mustKnow: [
    "An index is a sorted structure (usually a B+ tree) that turns a full table scan into a logarithmic lookup. It speeds reads and slows writes, and costs storage.",
    "A composite index on (a, b, c) can serve queries filtering on a, or a+b, or a+b+c — a left-to-right prefix. It cannot serve a query filtering only on b.",
    "Wrapping an indexed column in a function (`WHERE LOWER(email) = ...`) disables the index unless you built a matching expression index.",
    "ACID: Atomicity (all or nothing), Consistency (constraints hold), Isolation (concurrent transactions don't corrupt each other), Durability (committed means survives a crash).",
    "The default isolation level is usually READ COMMITTED (Postgres, Oracle, SQL Server) or REPEATABLE READ (MySQL InnoDB) — know your database's default, because it changes which anomalies are possible.",
    "N+1 is the most common performance bug in application code: one query for a list, then one per row. Fix by joining or batching, not by caching.",
    "Normalise to remove update anomalies; denormalise deliberately, for a measured read path, accepting that you now own consistency.",
    "`EXPLAIN ANALYZE` is the first tool for any slow query — read it before changing anything.",
    "Replication gives read scaling and failover but introduces replication lag, so a read right after a write may not see it.",
    "Sharding scales writes beyond one machine but costs you cross-shard joins, distributed transactions, and a shard key you can't easily change.",
  ],

  sheets: [
    {
      title: "Indexing rules",
      points: [
        "B+ tree: the default; supports equality, ranges, sorting, and prefix matching (`LIKE 'abc%'` but not `LIKE '%abc'`).",
        "Composite index column order matters: put equality-filtered columns first, then the range/sort column.",
        "Covering index — includes every column the query needs, so it never touches the table (index-only scan).",
        "Selectivity: an index on a boolean is usually useless; the planner will scan instead.",
        "Every index slows INSERT/UPDATE/DELETE and consumes space — audit for unused indexes.",
        "Foreign keys are not automatically indexed in most databases; missing FK indexes cause slow joins and lock contention on delete.",
        "Hash index: equality only, no ranges. GIN/GiST: full-text, arrays, JSONB, geospatial.",
        "Partial index (`WHERE status = 'active'`) is small and fast when queries always filter that way.",
      ],
    },
    {
      title: "Isolation levels and what they permit",
      points: [
        "READ UNCOMMITTED — dirty reads possible. Essentially never used.",
        "READ COMMITTED — no dirty reads; non-repeatable reads and phantoms possible. Postgres default.",
        "REPEATABLE READ — same row reads consistently within the transaction; phantoms possible in theory (Postgres's implementation prevents them via snapshot isolation). MySQL InnoDB default.",
        "SERIALIZABLE — as if transactions ran one at a time. Correct, but costs throughput and produces serialisation failures you must retry.",
        "Dirty read: reading uncommitted data. Non-repeatable read: same row, different value on re-read. Phantom: same query, new rows appear.",
        "MVCC (Postgres, MySQL InnoDB, Oracle): readers don't block writers and writers don't block readers — each sees a snapshot.",
        "Lost update: two read-modify-writes, one overwrites the other. Fix with `SELECT ... FOR UPDATE`, an atomic `UPDATE ... SET x = x + 1`, or optimistic locking on a version column.",
      ],
    },
    {
      title: "Diagnosing a slow query",
      points: [
        "1. `EXPLAIN ANALYZE` — compare estimated vs actual rows; a large gap means stale statistics.",
        "2. Look for Seq Scan on a large table where an index should apply.",
        "3. Check the join algorithm: nested loop over many rows is usually a missing index.",
        "4. Check for a Sort node that an index could satisfy.",
        "5. Confirm the index isn't disabled by a function, a type mismatch, or leading-wildcard LIKE.",
        "6. Check for N+1 in the application — one slow query is often 500 fast ones.",
        "7. `ANALYZE` to refresh statistics; check bloat and whether autovacuum is keeping up.",
        "8. Only after all that: consider caching, denormalising, or a materialised view.",
      ],
    },
    {
      title: "SQL you should write without hesitating",
      points: [
        "`JOIN` types: INNER (matches only), LEFT (all left rows, NULLs for missing right), FULL OUTER.",
        "`GROUP BY` with `HAVING` to filter aggregates — `WHERE` filters rows before grouping, `HAVING` after.",
        "Window functions: `ROW_NUMBER() OVER (PARTITION BY x ORDER BY y)` for top-N-per-group; `LAG`/`LEAD` for row-to-row comparison; running totals with `SUM() OVER (ORDER BY ...)`.",
        "CTEs (`WITH`) for readability; recursive CTEs for hierarchies and graph walks.",
        "`COALESCE` for NULL defaults; remember `NULL != NULL`, so use `IS NULL`.",
        "`EXISTS` over `IN (subquery)` for large subqueries; `NOT IN` breaks badly with NULLs.",
        "Keyset pagination (`WHERE id > ? ORDER BY id LIMIT n`) instead of `OFFSET` on deep pages.",
        "`INSERT ... ON CONFLICT DO UPDATE` (upsert) instead of a read-then-write race.",
      ],
    },
    {
      title: "Scaling path, in order",
      points: [
        "1. Fix the queries — indexes, N+1, and pagination usually buy an order of magnitude.",
        "2. Connection pooling (PgBouncer) — connections are expensive; hundreds of app instances × a pool each will exhaust the server.",
        "3. Cache reads (Redis) for expensive, tolerably-stale queries.",
        "4. Read replicas — scale reads; accept replication lag and route read-after-write to the primary.",
        "5. Vertical scaling — often the cheapest real answer; modern hardware goes a long way.",
        "6. Partitioning — split one big table by range or list within one database; helps pruning and maintenance.",
        "7. Sharding — last resort. Splits writes across machines and costs cross-shard queries and transactions.",
      ],
    },
  ],

  decisions: [
    {
      title: "SQL vs NoSQL",
      options: [
        {
          name: "Relational (Postgres/MySQL)",
          pick: ["Data has relationships and you'll query it in ways you can't fully predict.", "You need multi-row transactions and referential integrity.", "Reporting and ad-hoc analytics matter.", "Default choice for most applications."],
          cost: ["Horizontal write scaling is hard.", "Schema changes need migrations.", "A rigid schema can slow early iteration."],
        },
        {
          name: "Document (MongoDB, DynamoDB)",
          pick: ["Access patterns are known and stable, and one document serves a whole screen.", "Nested/variable structure per record.", "You need horizontal write scale with a natural partition key."],
          cost: ["Joins are manual or absent; duplicated data means you own consistency.", "Ad-hoc queries you didn't design for are expensive or impossible.", "Denormalised updates fan out across many documents."],
        },
        {
          name: "Key-value (Redis, DynamoDB)",
          pick: ["Lookups by a single key at very high throughput: sessions, caches, counters, feature flags."],
          cost: ["No querying by value; you must design every access path as a key."],
        },
      ],
      verdict: "Default to relational — Postgres handles JSON, full-text, and geospatial too. Choose NoSQL for a specific, known access pattern that relational genuinely can't serve at your scale.",
      topic: "cap-and-nosql",
    },
    {
      title: "Normalise vs denormalise",
      options: [
        {
          name: "Normalised",
          pick: ["Write-heavy or frequently-updated data.", "You want one place to change each fact — no update anomalies.", "Default for transactional systems."],
          cost: ["Read paths need joins, which cost more as tables grow.", "Deeply-normalised schemas can need many joins for one screen."],
        },
        {
          name: "Denormalised",
          pick: ["A specific, measured, read-heavy path where joins are the bottleneck.", "Analytics and reporting tables.", "Data that is effectively immutable once written (order line items keeping the price at purchase time)."],
          cost: ["You now own consistency — every copy must be updated together, or they drift.", "Storage duplication and larger writes."],
        },
      ],
      verdict: "Normalise by default, denormalise a specific read path after measuring — and be explicit about how the copies stay in sync.",
      topic: "normalization",
    },
    {
      title: "Optimistic vs pessimistic locking",
      options: [
        {
          name: "Optimistic (version column)",
          pick: ["Conflicts are rare.", "Long user-facing edits — you can't hold a lock while a form sits open.", "You want high concurrency."],
          cost: ["The loser's work is rejected and must be retried or merged, so the UI has to handle it.", "Under high contention, retry storms waste work."],
        },
        {
          name: "Pessimistic (`SELECT ... FOR UPDATE`)",
          pick: ["Conflicts are common and retries are expensive.", "Short critical sections: decrementing inventory, moving money."],
          cost: ["Holds locks, so it reduces concurrency and risks deadlocks.", "A held lock across a network call or user think-time is a serious bug."],
        },
      ],
      verdict: "Rare conflicts or long think-time → optimistic. Frequent conflicts and short transactions → pessimistic. Never hold a lock across a user interaction.",
      topic: "isolation-levels",
    },
    {
      title: "Read replicas vs caching vs sharding",
      options: [
        {
          name: "Read replicas",
          pick: ["Read-heavy load and you want a mostly-transparent fix.", "You also want a failover target."],
          cost: ["Replication lag breaks read-after-write, so you must route those reads to the primary.", "Doesn't help write load at all."],
        },
        {
          name: "Cache (Redis)",
          pick: ["A hot subset of data read far more often than written.", "Expensive computed results.", "You can tolerate bounded staleness."],
          cost: ["Invalidation is genuinely hard.", "A new failure mode and a cold-start/stampede problem."],
        },
        {
          name: "Sharding",
          pick: ["Write throughput or dataset size genuinely exceeds one machine."],
          cost: ["Cross-shard joins and transactions become application problems.", "Rebalancing and a shard key you can't easily change later.", "Every operational task gets harder."],
        },
      ],
      verdict: "Read load → replicas or cache. Write load or size → partition, then shard. Try query fixes and vertical scaling first; they're usually cheaper than either.",
      topic: "replication-partitioning",
    },
  ],

  qa: [
    {
      id: "db-index",
      q: "How does an index make a query faster, and what does it cost?",
      a: "Without an index the database reads every row to find matches — a sequential scan, O(n). An index is a separate sorted structure, usually a B+ tree, mapping column values to row locations, so a lookup descends the tree in O(log n) and jumps straight to the rows. Because the leaves are sorted and linked, it also serves range queries and can satisfy an `ORDER BY` without a separate sort. The costs are threefold: storage, since the index duplicates the indexed columns; write amplification, because every INSERT, UPDATE, or DELETE must maintain every affected index, so a table with eight indexes has slow writes; and planner complexity. There's also a subtlety worth mentioning — an index isn't always used even when it exists. If a query matches a large fraction of the table, a sequential scan is genuinely faster than many random index lookups, and the planner will correctly choose it.",
      why: "It's the most fundamental database question and the 'planner may ignore it' point shows real understanding.",
      trap: "Assuming more indexes is always better. Indexes tax every write, and unused ones are pure cost.",
      followUps: ["Why would the planner skip an index?", "What is a covering index?"],
      depth: "Core",
      tags: ["indexing", "performance"],
      topic: "indexing",
    },
    {
      id: "db-composite-index",
      q: "You have an index on (country, city, name). Which queries can use it?",
      a: "A composite index is sorted by the columns in order, so it serves any left-to-right prefix. Filtering on country alone works; country plus city works; all three works. Filtering on city alone cannot use it, because the index is sorted by country first, so all the rows for a given city are scattered across the structure — the same reason a phone book sorted by surname can't help you find everyone named 'James'. A query on country with a range on city can use both columns, but a further condition on name won't benefit, because once you use a range the remaining columns are no longer sorted usefully — which is why the rule is to put equality-filtered columns first and the range or sort column last. The index can also satisfy `ORDER BY country, city` without sorting, which is often a bigger win than the filtering itself.",
      why: "The leftmost-prefix rule is the highest-value indexing fact and directly diagnoses a lot of slow queries.",
      trap: "Believing an index on three columns serves any combination of them. Only prefixes.",
      followUps: ["Why does a range condition stop later columns being useful?", "How do you index for `WHERE a = ? ORDER BY b`?"],
      depth: "Intermediate",
      tags: ["indexing"],
      topic: "indexing",
    },
    {
      id: "db-n-plus-1",
      q: "What is the N+1 query problem?",
      a: "You run one query to fetch a list, then one additional query per item to fetch something related — 1 + N queries where 2 would do. Fetching 100 posts and then each post's author is 101 round trips, and even if each takes a millisecond, network latency dominates and the endpoint takes hundreds of milliseconds instead of a few. It's usually invisible in the code because an ORM's lazy loading makes `post.author` look like a property access rather than a query. The fixes are eager loading with a join or a second batched query using `WHERE id IN (...)`, which turns N queries into one; in GraphQL the standard tool is DataLoader, which batches and de-duplicates within a request tick. Detection matters as much as the fix: log query counts per request, or use an APM that shows them, because the pattern scales invisibly — it's fine with 10 rows in development and catastrophic with 10,000 in production.",
      why: "It's the single most common application-level database bug and interviewers ask it because it's ubiquitous.",
      trap: "Fixing it by caching. Caching hides the latency for repeat requests but leaves the underlying pattern and the cold path.",
      followUps: ["How does DataLoader batch?", "How would you detect N+1 in production?"],
      depth: "Core",
      tags: ["performance", "orm"],
      topic: "query-optimization",
    },
    {
      id: "db-acid",
      q: "Explain ACID.",
      a: "Atomicity means a transaction is all or nothing — if any statement fails, the whole thing rolls back and no partial effect remains, which is what makes a money transfer safe. Consistency means the database moves from one valid state to another, respecting constraints, foreign keys, and triggers; it's the property most dependent on you defining the constraints in the first place. Isolation means concurrent transactions don't see each other's intermediate states, though how strictly is governed by the isolation level, and this is where most real subtlety lives. Durability means once you get a commit acknowledgement, the data survives a crash — implemented with a write-ahead log flushed to disk before the commit returns. The useful thing to add is that these aren't binary: isolation is a spectrum you choose, and durability can be relaxed for throughput with asynchronous commits, which is a real trade-off some systems make deliberately.",
      why: "It's the standard question, and the 'isolation is a dial, not a boolean' framing is what makes an answer stand out.",
      trap: "Treating consistency as meaning the same thing as in CAP. In ACID it's about constraints; in CAP it's about all nodes seeing the same data.",
      followUps: ["How does a write-ahead log give durability?", "How does ACID consistency differ from CAP consistency?"],
      depth: "Core",
      tags: ["transactions"],
      topic: "acid-transactions",
    },
    {
      id: "db-isolation",
      q: "What anomalies do the isolation levels allow?",
      a: "READ UNCOMMITTED allows dirty reads — seeing another transaction's uncommitted changes, which may then roll back — and is effectively never used. READ COMMITTED prevents dirty reads but allows non-repeatable reads, where re-reading a row within your transaction gives a different value because someone committed in between, and phantoms, where re-running a range query returns new rows. REPEATABLE READ fixes non-repeatable reads by giving your transaction a consistent snapshot of rows it has read; the SQL standard still permits phantoms, though Postgres's snapshot-based implementation prevents them. SERIALIZABLE guarantees the outcome equals some serial ordering, which costs throughput and, in Postgres, surfaces as serialisation failures your application must catch and retry. The practical point: know your default, because Postgres defaults to READ COMMITTED and MySQL InnoDB to REPEATABLE READ, so identical application code behaves differently on each.",
      why: "It's where correctness bugs under concurrency come from, and knowing the defaults differ is a strong signal.",
      trap: "Assuming a higher isolation level prevents lost updates. Even REPEATABLE READ allows a read-modify-write race unless you lock explicitly or use an atomic update.",
      followUps: ["How do you prevent a lost update?", "What is a serialisation failure and how do you handle it?"],
      depth: "Advanced",
      tags: ["transactions", "concurrency"],
      topic: "isolation-levels",
    },
    {
      id: "db-mvcc",
      q: "What is MVCC?",
      a: "Multi-Version Concurrency Control keeps multiple versions of each row so that readers never block writers and writers never block readers. When a transaction updates a row, the database writes a new version rather than overwriting; each version is tagged with the transaction that created it, and each transaction sees a snapshot consisting of the versions committed before it started. That's what makes a long analytical query possible while writes continue, without either blocking the other. The cost is that old versions accumulate and must be cleaned up — Postgres's autovacuum, InnoDB's purge thread — and if cleanup falls behind you get table bloat, degraded scans, and in Postgres the risk of transaction ID wraparound. A related operational trap: a long-running or idle-in-transaction session holds back cleanup for the whole database, because its snapshot may still need those old versions, so one forgotten open transaction can bloat everything.",
      why: "It explains Postgres's operational quirks and shows the candidate has run a database, not just queried one.",
      trap: "Thinking MVCC removes the need for locking entirely. Writes to the same row still conflict and still need locks.",
      followUps: ["Why does a long-running transaction cause bloat?", "What is transaction ID wraparound?"],
      depth: "Advanced",
      tags: ["internals", "concurrency"],
      topic: "isolation-levels",
    },
    {
      id: "db-explain",
      q: "How do you read an EXPLAIN plan?",
      a: "Read it as a tree, innermost first, and use `EXPLAIN ANALYZE` so you get actual timings and row counts rather than estimates alone. The first thing to check is estimated versus actual rows: a large discrepancy means the planner's statistics are stale or its assumptions are wrong, and every downstream choice it made is suspect — the fix is usually `ANALYZE`, or increasing the statistics target on a skewed column. Then look at scan types — a sequential scan on a large table where you expected an index lookup, and whether the index is being used but with a filter discarding most rows. Then joins: a nested loop is right for a few rows and disastrous for many, and seeing one over a large outer relation usually means a missing index on the inner side. Look for explicit Sort nodes an index could have satisfied, and for spills to disk indicating `work_mem` is too small. Finally, check where time actually accumulates, since the most expensive node is often not the one you expected.",
      why: "It's the practical diagnostic skill, and mentioning estimate-versus-actual first is what an experienced engineer does.",
      trap: "Reading only the total cost number. The cost is an arbitrary unit for comparing plans, not milliseconds.",
      followUps: ["What does a big estimate/actual gap tell you?", "When is a sequential scan the right choice?"],
      depth: "Advanced",
      tags: ["performance", "tooling"],
      topic: "query-optimization",
    },
    {
      id: "db-transaction-pattern",
      q: "Two users buy the last item simultaneously. How do you prevent overselling?",
      a: "The naive code reads the stock, checks it's above zero, and writes stock minus one — a read-modify-write race where both transactions read 1 and both write 0, selling two items. There are three correct fixes. The simplest is to make the update atomic and conditional: `UPDATE items SET stock = stock - 1 WHERE id = ? AND stock > 0`, then check the affected row count — the database serialises the row update, so exactly one succeeds. Second, pessimistic locking: `SELECT ... FOR UPDATE` inside the transaction takes a row lock so the second transaction waits, which is appropriate when you need to do more work between reading and writing. Third, optimistic locking with a version column, updating `WHERE version = ?` and retrying on failure, which suits low-contention cases. A database constraint like `CHECK (stock >= 0)` is worth adding regardless as a final backstop. What doesn't work is checking in application code outside a transaction.",
      why: "It's a concrete concurrency problem with several valid answers, so it shows how the candidate reasons about trade-offs.",
      trap: "Wrapping the read and write in a transaction and assuming that's enough. At READ COMMITTED it doesn't prevent the lost update — you need a lock or an atomic conditional update.",
      followUps: ["Why doesn't a plain transaction prevent this?", "How would you handle it across two services?"],
      depth: "Advanced",
      tags: ["concurrency", "transactions"],
      topic: "isolation-levels",
    },
    {
      id: "db-pagination",
      q: "Why is `OFFSET` pagination slow on deep pages?",
      a: "Because the database must generate and discard every row before the offset. `LIMIT 20 OFFSET 100000` sorts and walks 100,020 rows to return 20, so page one is instant and page five thousand times out — the cost grows linearly with page depth. It's also incorrect under concurrent writes: if a row is inserted or deleted while the user pages, rows shift and they see a duplicate or miss one entirely. Keyset (or cursor) pagination fixes both: remember the sort key of the last row and query `WHERE (created_at, id) < (?, ?) ORDER BY created_at DESC, id DESC LIMIT 20`, which uses the index to seek directly to the position, giving constant time per page regardless of depth, and stable results under concurrent modification. The trade-off is that you lose random access to arbitrary page numbers, so it suits infinite scroll and APIs better than a numbered pager — which is usually an acceptable UI change.",
      why: "It's a real scaling problem with a clean, specific answer, and the correctness argument is often forgotten.",
      trap: "Only mentioning performance. The instability under concurrent inserts is arguably the worse problem.",
      followUps: ["Why include the id in the keyset?", "How do you support jumping to page 500?"],
      depth: "Intermediate",
      tags: ["pagination", "performance"],
      topic: "pagination-filtering",
    },
    {
      id: "db-window-functions",
      q: "When would you use a window function?",
      a: "When you need a value computed across a set of related rows while keeping every row in the output — which is exactly what `GROUP BY` can't do, since it collapses rows. The canonical cases are ranking within groups, using `ROW_NUMBER() OVER (PARTITION BY department ORDER BY salary DESC)` and filtering to rank one for top-per-group; running totals with `SUM(amount) OVER (ORDER BY date)`; comparing a row to its neighbour with `LAG` or `LEAD`, for month-over-month deltas or gap detection; and computing a per-row percentage of a group total by dividing by `SUM(x) OVER (PARTITION BY g)`. Before window functions you'd write a self-join or a correlated subquery, which is slower and much harder to read. The one gotcha is that you can't reference a window function in `WHERE`, because windows are evaluated after filtering — you wrap the query in a CTE or subquery and filter outside.",
      why: "Window functions separate people who write real analytical SQL from people who only do CRUD.",
      trap: "Trying to filter on `ROW_NUMBER()` in the same query's `WHERE` clause. It's evaluated too late; wrap it.",
      followUps: ["Write top-3 earners per department.", "What's the difference between `RANK` and `DENSE_RANK`?"],
      depth: "Intermediate",
      tags: ["sql"],
      topic: "window-functions",
    },
    {
      id: "db-cap",
      q: "What does CAP actually tell you?",
      a: "That when a network partition occurs, a distributed system must choose between remaining available and remaining consistent — it cannot do both. Consistency here means linearizability, every read seeing the latest write; availability means every request gets a non-error response. The framing that's often misunderstood is that you don't 'pick two' in normal operation: partitions are a fact of networks, not a choice, so the real decision is only what happens during one. A CP system like a strongly-consistent store or a consensus-based database refuses writes on the minority side rather than diverge; an AP system like Cassandra or DynamoDB in eventual mode accepts writes everywhere and reconciles later. The more practically useful extension is PACELC, which adds that even when there's no partition you still trade latency against consistency — which is the trade-off you actually make every day, since synchronous replication across regions is correct and slow.",
      why: "CAP is quoted constantly and understood rarely; the PACELC extension shows genuine depth.",
      trap: "Saying a system 'picks CA'. You can't opt out of partitions; CA describes a single-node system.",
      followUps: ["What does PACELC add?", "Where does a Postgres primary with sync replicas sit?"],
      depth: "Advanced",
      tags: ["distributed"],
      topic: "cap-theorem",
    },
    {
      id: "db-sharding",
      q: "When do you shard, and what does it cost?",
      a: "You shard when a single machine can no longer hold the data or absorb the write throughput, and only after exhausting cheaper options — query and index fixes, connection pooling, caching, read replicas, vertical scaling, and table partitioning within one database. Sharding splits rows across independent databases by a shard key, so each handles a fraction of the load. The costs are substantial and permanent. Queries that don't include the shard key must fan out to every shard and merge results, so your access patterns must align with the key. Joins across shards become application-level work. Transactions spanning shards need two-phase commit or a saga, giving up simple atomicity. Unique constraints and auto-increment ids no longer work globally. Rebalancing when you add shards is an operational project, which is why consistent hashing or many virtual shards mapped to fewer physical ones is standard. And choosing the key is close to irreversible, so a poor choice — one that creates hot shards, like sharding by tenant when one tenant is enormous — is expensive to correct.",
      why: "It's a judgement question; the right answer emphasises how much you should avoid it.",
      trap: "Proposing sharding as an early scaling step. Most systems asking about it need better indexes.",
      followUps: ["How do you pick a shard key?", "How do you rebalance without downtime?"],
      depth: "Advanced",
      tags: ["scaling", "distributed"],
      topic: "sharding",
    },
    {
      id: "db-soft-delete",
      q: "Soft delete or hard delete?",
      a: "Soft delete sets a `deleted_at` timestamp and filters it out on read, keeping the row for audit, undo, and referential integrity with historical records. It's the right default in most business systems, because deletion is usually a user action you may need to reverse or explain. But the costs accumulate and are worth naming: every query must remember the filter, and forgetting it once leaks deleted data; unique constraints break, since a deleted row still occupies the unique email, requiring a partial unique index on `WHERE deleted_at IS NULL`; tables grow without bound; and joins can pull in deleted parents unless every path filters. Hard delete is simpler and is required for genuine compliance cases — GDPR erasure means the data actually goes, including from backups and downstream systems. A common middle path is soft delete for a retention window, then a background job that hard-deletes or archives, giving you undo without unbounded growth.",
      why: "It's a design trade-off with real operational consequences that most candidates have only considered from one side.",
      trap: "Choosing soft delete without addressing unique constraints. It's the failure that shows up as 'this email is already taken' for an account the user deleted.",
      followUps: ["How do you keep a unique email with soft deletes?", "How does GDPR erasure interact with this?"],
      depth: "Intermediate",
      tags: ["modelling"],
    },
    {
      id: "db-migrations",
      q: "How do you change a schema with zero downtime?",
      a: "By making every change backward-compatible and rolling it out in phases, because during a deploy old and new application code run simultaneously against one schema. To add a column: add it nullable or with a default, deploy code that writes it, backfill in batches, then add the NOT NULL constraint. To remove one: stop writing it, deploy, then drop it — never in the same release, or the old instances break. To rename: add the new column, dual-write to both, backfill, migrate reads, stop writing the old, then drop it — a rename in place is an outage. The operational details matter as much: avoid long-held locks, since in Postgres an `ALTER TABLE` that rewrites the table blocks everything and even adding a constraint takes a lock, so use `NOT VALID` then `VALIDATE` and always set a lock timeout; build indexes with `CONCURRENTLY`; and backfill in batches with pauses so you don't saturate I/O or bloat replication lag.",
      why: "It's a strong senior signal — the expand/migrate/contract pattern is learned from having broken production.",
      trap: "Dropping or renaming a column in the same deploy that stops using it. The old pods are still running.",
      followUps: ["Why `CREATE INDEX CONCURRENTLY`?", "How do you backfill 100M rows safely?"],
      depth: "Advanced",
      tags: ["operations", "migrations"],
    },
    {
      id: "db-connection-pool",
      q: "Why do you need a connection pool, and how do you size it?",
      a: "Because establishing a database connection is expensive — a TCP handshake, authentication, and in Postgres an entire backend process with its own memory — so opening one per request adds latency and quickly exhausts the server. A pool keeps a set of established connections and hands them out, so the cost is paid once. Sizing is counter-intuitive: bigger is not better, because a database can only genuinely execute as many queries as it has cores and disks to serve, and beyond that connections just queue while adding context-switching and memory overhead. A common starting formula is roughly cores × 2 plus effective spindle count, which usually lands in the low tens, not hundreds. The trap in modern deployments is multiplication: fifty application instances each with a pool of twenty is a thousand connections against a server configured for a hundred, which is why a proxy like PgBouncer in transaction pooling mode sits in front and multiplexes — though transaction mode breaks session-level features like prepared statements and advisory locks, which you have to account for.",
      why: "The multiplication problem is a real production outage pattern in containerised deployments.",
      trap: "Raising the pool size to fix timeouts. That usually makes it worse — the queue moves into the database.",
      followUps: ["What breaks in PgBouncer transaction mode?", "How do serverless functions complicate pooling?"],
      depth: "Advanced",
      tags: ["operations", "performance"],
    },
  ],

  pitfalls: [
    "Don't say 'add an index' without saying which columns and in what order — the leftmost-prefix rule is the point.",
    "Don't fix N+1 with caching — fix the query pattern.",
    "Don't assume a transaction alone prevents lost updates — you need a lock or an atomic conditional update.",
    "Don't confuse ACID consistency (constraints) with CAP consistency (all nodes agree).",
    "Don't propose sharding before indexes, caching, replicas, and vertical scaling.",
    "Don't use OFFSET for deep pagination — it's slow and unstable under writes.",
    "Don't drop or rename a column in the same deploy that stops using it.",
    "Don't raise the connection pool size to fix timeouts — check the total across all instances.",
  ],

  numbers: [
    { label: "SSD random read", value: "~100 µs", note: "vs ~10 ms for spinning disk — why indexes matter less on NVMe but still matter." },
    { label: "Memory read", value: "~100 ns", note: "~1000× faster than SSD; the reason caching works." },
    { label: "Same-datacenter round trip", value: "~0.5 ms", note: "Why 101 queries beats you even when each is fast." },
    { label: "Pool size starting point", value: "~cores × 2", note: "Usually tens, not hundreds — and count across ALL app instances." },
    { label: "Postgres default isolation", value: "READ COMMITTED", note: "MySQL InnoDB defaults to REPEATABLE READ." },
  ],

  relatedTopics: [
    "indexing",
    "query-optimization",
    "acid-transactions",
    "isolation-levels",
    "normalization",
    "sharding",
    "replication-partitioning",
    "cap-theorem",
    "pagination-filtering",
    "sql-basics",
  ],
};
