import type { Area } from "../types";

export const dsa: Area = {
  slug: "dsa",
  title: "DSA & Complexity",
  icon: "🧮",
  stream: "CS Core",
  blurb:
    "The pattern vocabulary that turns 'I've never seen this problem' into 'this is a sliding window' — plus talking about complexity without fumbling.",

  mustKnow: [
    "Big-O describes growth rate as input grows, dropping constants and lower-order terms. State BOTH time and space, and say whether it's worst or average case.",
    "Hash map lookup is O(1) average — it converts 'search for something' from O(n) into O(1), and is the single most common optimisation in interviews.",
    "Sorting costs O(n log n). If the input is sorted, or you can afford to sort it, two pointers and binary search become available.",
    "Two pointers works on sorted arrays or when scanning from both ends; sliding window works on contiguous subarrays/substrings with a constraint.",
    "BFS finds the shortest path in an UNWEIGHTED graph; DFS explores deeply and suits path/cycle/connectivity questions. Dijkstra handles non-negative weights.",
    "Recursion + memoisation (top-down) and tabulation (bottom-up) are the same DP; pick whichever is clearer, and mention the other.",
    "A heap gives you the min or max in O(1) and insert/extract in O(log n) — the answer to almost every 'top k' question.",
    "Binary search applies whenever the search space is monotonic, not just to sorted arrays — including 'binary search on the answer'.",
    "Amortised is not average: a dynamic array append is O(1) amortised because occasional O(n) resizes are spread over n cheap appends.",
    "Always state the approach and its complexity BEFORE coding, and ask about input size, duplicates, negatives, empty input, and whether you may mutate the input.",
  ],

  sheets: [
    {
      title: "Complexity of the operations you'll quote",
      points: [
        "Array: index O(1); search O(n); insert/delete at end O(1) amortised, at front O(n).",
        "Hash map/set: insert, lookup, delete O(1) average, O(n) worst; no ordering.",
        "Balanced BST (TreeMap): all of the above O(log n), and it keeps keys sorted — range queries and predecessor/successor.",
        "Heap: peek O(1), push/pop O(log n), build from array O(n).",
        "Linked list: insert/delete at a known node O(1); search O(n); no random access.",
        "Trie: insert/search a word O(L) in the word's length, independent of dictionary size.",
        "Sorting: comparison sorts are Ω(n log n); counting/radix are O(n + k) for bounded integer keys.",
        "Graph traversal: BFS/DFS O(V + E). Dijkstra with a binary heap O((V + E) log V).",
      ],
    },
    {
      title: "Pattern → signal in the question",
      points: [
        "'Contiguous subarray/substring with a constraint' → sliding window.",
        "'Pair/triplet summing to a target' in a sorted array → two pointers (sort first if allowed).",
        "'Top / smallest / k-th k elements' → heap of size k, or quickselect for O(n) average.",
        "'Shortest path, unweighted' → BFS. 'With non-negative weights' → Dijkstra. 'Any negative weights' → Bellman-Ford.",
        "'Number of islands / connected regions' → DFS/BFS flood fill, or union-find.",
        "'Next greater/smaller element', 'valid parentheses', 'histogram' → monotonic stack.",
        "'Prefix / autocomplete / word dictionary' → trie.",
        "'Count of something over ranges' → prefix sums (or a Fenwick/segment tree if updates are needed).",
        "'Ways to do X' / 'min cost to reach' / overlapping subproblems → dynamic programming.",
        "'Generate all combinations/permutations/subsets' → backtracking.",
        "'Detect a cycle in a linked list' / 'find the duplicate' → fast and slow pointers.",
        "'Merge overlapping intervals' → sort by start, then sweep.",
      ],
    },
    {
      title: "Talking through a problem (the script)",
      points: [
        "1. Restate the problem and give one example back — catches misunderstandings in 20 seconds.",
        "2. Ask constraints: input size, value ranges, duplicates, negatives, empty/null, sorted?, may I mutate?",
        "3. State the brute force and its complexity. Never skip this — it proves you understand the problem.",
        "4. Name the bottleneck, then the pattern that removes it ('the inner scan is O(n); a hash map makes it O(1)').",
        "5. State the target complexity before coding, and confirm it's what they want.",
        "6. Code, narrating decisions, not syntax.",
        "7. Trace one example by hand, then check edge cases: empty, single element, all duplicates, overflow.",
        "8. State final time and space, and name one thing you'd change with different constraints.",
      ],
    },
    {
      title: "Edge cases that catch people",
      points: [
        "Empty input, single element, all elements identical.",
        "Negative numbers — breaks many sliding-window and prefix assumptions.",
        "Integer overflow: use `left + (right - left) / 2` in binary search rather than `(left + right) / 2`.",
        "Off-by-one in binary search: pick `while (lo < hi)` or `while (lo <= hi)` and be consistent about the invariant.",
        "Cycles in graphs — track visited, or you loop forever.",
        "Duplicates when the problem says 'unique' — clarify before assuming.",
        "Modifying a collection while iterating it.",
        "Recursion depth on large inputs — mention converting to an iterative solution with an explicit stack.",
      ],
    },
    {
      title: "Space complexity people forget to count",
      points: [
        "Recursion stack: a recursive DFS on a graph of n nodes is O(n) space even with no explicit data structure.",
        "The output itself is usually excluded by convention — say so explicitly.",
        "Sorting: most library sorts are O(log n) space (introsort) or O(n) (Timsort/mergesort).",
        "A hash map of every element is O(n) — that's often the space you traded for time.",
        "In-place means O(1) EXTRA space, not zero space.",
      ],
    },
  ],

  decisions: [
    {
      title: "Hash map vs sorting",
      options: [
        {
          name: "Hash map",
          pick: ["You need O(1) membership, counting, or 'have I seen this'.", "Order doesn't matter.", "One pass is possible."],
          cost: ["O(n) extra space.", "No ordering, so no range queries or 'next largest'.", "Worst case O(n) per lookup with adversarial keys."],
        },
        {
          name: "Sort first",
          pick: ["The problem needs order: k-th smallest, ranges, grouping adjacent equal items.", "It unlocks two pointers or binary search.", "You need O(1) extra space and can sort in place."],
          cost: ["O(n log n) time, which is worse than a single hash pass when you only needed membership.", "Mutates the input unless you copy."],
        },
      ],
      verdict: "Membership or counting → hash map, O(n). Anything needing order → sort, O(n log n), and the sorted structure often gives the rest for free.",
    },
    {
      title: "BFS vs DFS",
      options: [
        {
          name: "BFS",
          pick: ["Shortest path in an unweighted graph — the first time you reach a node is via a shortest path.", "Level-by-level processing.", "The target is likely near the source."],
          cost: ["Queue can hold an entire level, so space is O(width), which is huge for wide graphs."],
        },
        {
          name: "DFS",
          pick: ["Cycle detection, topological sort, connectivity, path enumeration.", "Backtracking problems.", "Memory matters — space is O(depth)."],
          cost: ["Does NOT give shortest paths.", "Recursion can overflow the stack on deep graphs; use an explicit stack."],
        },
      ],
      verdict: "Shortest path unweighted → BFS. Structure, cycles, or exhaustive exploration → DFS.",
      topic: "graphs",
    },
    {
      title: "Memoisation (top-down) vs tabulation (bottom-up)",
      options: [
        {
          name: "Top-down memo",
          pick: ["The recurrence is natural to express recursively.", "Only a subset of states is actually reachable — you compute only what you need.", "Faster to derive from the brute force."],
          cost: ["Recursion stack space and call overhead; can overflow on deep state spaces."],
        },
        {
          name: "Bottom-up table",
          pick: ["You need the whole table anyway.", "You want to optimise space by keeping only the last row or two.", "No recursion depth risk."],
          cost: ["You must work out a correct iteration order up front, which is the hard part.", "Computes states you may not need."],
        },
      ],
      verdict: "Derive with memoisation, then convert to tabulation if you need the space optimisation. Say both in the interview.",
    },
    {
      title: "Quickselect vs heap for 'top k'",
      options: [
        {
          name: "Min-heap of size k",
          pick: ["Streaming data where you can't hold everything.", "k is much smaller than n.", "You want the k elements in sorted order."],
          cost: ["O(n log k) time; the log factor is real when k is large."],
        },
        {
          name: "Quickselect",
          pick: ["All data is in memory and you want the best average time.", "You only need the k elements, unordered."],
          cost: ["O(n) average but O(n²) worst case without a good pivot strategy.", "Mutates the array; the result is unordered."],
        },
      ],
      verdict: "Streaming or k ≪ n → heap, O(n log k). In-memory and you want average O(n) → quickselect, but mention the worst case.",
    },
  ],

  qa: [
    {
      id: "dsa-bigo",
      q: "Explain Big-O to someone who hasn't seen it.",
      a: "It describes how the cost of an algorithm grows as the input grows, ignoring constants and machine details. We keep only the dominant term, so 3n² + 5n + 9 is O(n²), because for large enough n the n² term dwarfs everything else. The point is to compare algorithms independent of hardware: an O(n) algorithm eventually beats an O(n²) one no matter how fast the machine running the latter. Big-O specifically is an upper bound, typically used for the worst case; Ω is a lower bound and Θ is a tight bound where both match. In an interview you're almost always asked for worst-case time and space in Big-O. Worth adding: constants matter in practice, so for small n an O(n²) algorithm with a tiny constant can beat an O(n log n) one — which is why real sort implementations switch to insertion sort under a threshold.",
      why: "It's the vocabulary the entire coding interview runs on; fumbling it undermines everything after.",
      trap: "Saying O(n) means 'takes n seconds'. It describes growth, not absolute time.",
      followUps: ["What's the difference between O and Θ?", "When would an O(n²) algorithm beat an O(n log n) one?"],
      depth: "Core",
      tags: ["complexity"],
      topic: "big-o-notation",
    },
    {
      id: "dsa-amortized",
      q: "What does amortised O(1) mean for a dynamic array append?",
      a: "It means the average cost per operation over a sequence is O(1), even though individual operations can be O(n). A dynamic array keeps a capacity larger than its length; appending is a single write until the array is full, at which point it allocates a new array of double the size and copies everything, which is O(n). But because capacity doubles, those copies happen exponentially less often — the total copying work across n appends is n/2 + n/4 + n/8 … which sums to less than n, so the total is O(n) for n appends and O(1) each on average. The doubling is essential: growing by a constant amount instead would make the total O(n²). Amortised is different from average-case, which is about a distribution of inputs; amortised is a guarantee about any sequence of operations.",
      why: "It's the standard test for whether someone understands cost over time rather than per call.",
      trap: "Conflating amortised with average. Average is probabilistic; amortised holds for every sequence.",
      followUps: ["Why double rather than add a fixed amount?", "Where else does amortised analysis appear?"],
      depth: "Intermediate",
      tags: ["complexity", "arrays"],
      topic: "amortized-analysis",
    },
    {
      id: "dsa-sliding-window",
      q: "When do you use a sliding window, and what does it save?",
      a: "When the answer concerns a contiguous subarray or substring subject to a constraint — longest substring without repeating characters, smallest subarray with sum at least K, maximum sum of size K. The brute force checks every subarray, which is O(n²) or worse. The window insight is that as you extend the right edge, you never need to move the left edge backwards, so each element enters and leaves the window at most once and the whole scan is O(n). There are two shapes: fixed-size, where you slide both edges together and maintain a running aggregate, and variable-size, where you expand right until the constraint breaks then contract left until it holds again. You usually need an auxiliary structure — a hash map of counts for character problems, a running sum for numeric ones. The classic failure is applying it to arrays with negative numbers where the constraint isn't monotonic as the window grows, which breaks the 'never move left backwards' guarantee.",
      why: "It's one of the highest-frequency patterns and the O(n²)→O(n) reasoning is exactly what interviewers want to hear.",
      trap: "Using it on a problem with negative numbers where extending the window can make the sum smaller — the monotonicity the technique relies on is gone.",
      followUps: ["Solve 'longest substring without repeating characters'.", "Why do negatives break it?"],
      depth: "Intermediate",
      tags: ["patterns", "arrays"],
      topic: "arrays-strings",
    },
    {
      id: "dsa-two-pointers",
      q: "What problems suit two pointers?",
      a: "Two main shapes. Opposite ends, on a sorted array: to find a pair summing to a target, start at both ends and move the left pointer right if the sum is too small or the right pointer left if it's too big — each step eliminates a whole row of the implicit n² comparison matrix, giving O(n) after the O(n log n) sort. This generalises to three-sum by fixing one element and running two pointers on the rest. Same direction, at different speeds: the fast-and-slow pointer detects a cycle in a linked list, because if there's a cycle the fast pointer eventually laps the slow one; it also finds the middle of a list in one pass and locates a duplicate in an array treated as a functional graph. The common theme is replacing a nested loop with a single coordinated pass, so the win is O(n²) to O(n) with O(1) extra space.",
      why: "It comes up constantly and the 'why it's correct' argument distinguishes memorisation from understanding.",
      trap: "Applying the opposite-ends variant to an unsorted array. The move-left-or-right decision is only valid because sortedness tells you which direction helps.",
      followUps: ["Why does fast-and-slow detect a cycle?", "How do you extend two-sum to three-sum?"],
      depth: "Intermediate",
      tags: ["patterns", "arrays"],
    },
    {
      id: "dsa-binary-search-answer",
      q: "What is 'binary search on the answer'?",
      a: "Binary search doesn't need a sorted array — it needs a monotonic predicate. If you can define a boolean function over a candidate answer that is false for every value below some threshold and true for every value at or above it, you can binary search the answer space itself. The classic example is 'minimum capacity to ship all packages in D days': you can't sort your way to it, but you can ask 'is capacity C sufficient?', which is checkable in O(n) with a greedy pass, and which is monotonic — if C works, so does anything larger. So you binary search C between the largest single package and the total sum, giving O(n log(sum)). The same shape solves Koko eating bananas, split-array-largest-sum, and minimum time to complete tasks. The recognition signal is a question phrased as 'minimise the maximum' or 'maximise the minimum'.",
      why: "It's a genuine level-up that many candidates have never encountered, and the 'minimise the maximum' phrasing is a reliable tell.",
      trap: "Only associating binary search with sorted arrays. The requirement is monotonicity of a predicate, not sortedness of data.",
      followUps: ["What's the search range for the shipping problem?", "How do you verify the predicate is monotonic?"],
      depth: "Advanced",
      tags: ["binary-search", "patterns"],
    },
    {
      id: "dsa-dp-recognise",
      q: "How do you recognise a dynamic programming problem, and how do you approach it?",
      a: "Two signals: optimal substructure, meaning the optimal answer is built from optimal answers to subproblems, and overlapping subproblems, meaning a naive recursion recomputes the same states. Phrasings that suggest it are 'number of ways', 'minimum/maximum cost to', 'can you reach', and anything where a greedy choice can be shown to fail. The approach that works under pressure: write the brute-force recursion first, without worrying about efficiency; identify what varies across recursive calls, and those variables are your state; add memoisation keyed by that state, which alone usually takes it from exponential to polynomial; then, if needed, convert to a bottom-up table and observe whether each row depends only on the previous one, which lets you cut space from O(n·m) to O(m). State the recurrence out loud before coding — most DP failures are a wrong recurrence, not a coding error.",
      why: "DP is where most candidates freeze, and having an explicit procedure is the difference between progress and a blank screen.",
      trap: "Jumping straight to a 2D table. Deriving the recursion first is faster, more reliable, and easier to explain.",
      followUps: ["Do 0/1 knapsack and then optimise its space.", "How do you know greedy fails here?"],
      depth: "Advanced",
      tags: ["dp", "patterns"],
    },
    {
      id: "dsa-hashmap-tradeoff",
      q: "Hash maps are O(1) — what's the catch?",
      a: "Three catches. First, O(1) is average, not worst case: all keys can collide into one bucket, degrading to O(n), which matters for adversarial input — hash-flooding DoS attacks are exactly this, and languages mitigate it with randomised seeds or by switching a hot bucket to a tree. Second, you're spending O(n) space to buy that time, which may not be available, and the constant factor is worse than an array because of hashing and pointer chasing, so for small n a linear scan of an array can genuinely be faster thanks to cache locality. Third, there's no ordering: you can't ask for the smallest key, iterate in sorted order, or do range queries, so the moment the problem needs any of that you want a balanced BST or a sorted array instead. Also worth mentioning: keys must be hashable and immutable — mutating a key after insertion makes the entry unreachable.",
      why: "It tests whether someone reaches for a hash map reflexively or actually understands the trade.",
      trap: "Quoting O(1) as a guarantee. It's amortised average with assumptions about the hash function and the keys.",
      followUps: ["What's a hash-flooding attack?", "When would you use a TreeMap instead?"],
      depth: "Intermediate",
      tags: ["hashing", "complexity"],
      topic: "hash-tables",
    },
    {
      id: "dsa-heap",
      q: "What is a heap good for?",
      a: "Maintaining the minimum or maximum of a changing collection cheaply. It's a complete binary tree stored in an array where every parent compares favourably to its children, giving O(1) peek, O(log n) insert and extract, and O(n) to build from an existing array — which is better than the O(n log n) you'd get inserting one at a time. The interview applications are top-k, where you keep a min-heap of size k and get O(n log k) rather than sorting everything; merging k sorted lists, by holding one element from each list; running median, using a max-heap for the lower half and a min-heap for the upper; and task scheduling by priority. Dijkstra and A* use one as their frontier. What a heap does not give you is search — finding an arbitrary element is O(n), because only the root's relationship is guaranteed, not any global ordering.",
      why: "'Top k' is one of the most common question families and the heap answer should be immediate.",
      trap: "Assuming a heap is sorted. Only the root is guaranteed; iterating the array gives no useful order.",
      followUps: ["How do you build a max-heap when the library only gives a min-heap?", "Solve the running-median problem."],
      depth: "Intermediate",
      tags: ["heaps", "patterns"],
      topic: "heaps",
    },
    {
      id: "dsa-graph-representation",
      q: "Adjacency list or adjacency matrix?",
      a: "It depends on density. An adjacency list stores, for each vertex, the vertices it connects to: O(V + E) space, iterating a vertex's neighbours is proportional to its degree, and checking whether a specific edge exists is O(degree). An adjacency matrix is a V×V grid: O(V²) space regardless of edges, O(1) edge lookup, but iterating a vertex's neighbours always costs O(V) even if it has two. Real-world graphs are sparse — social networks, road maps, dependency graphs all have E far closer to V than to V² — so the adjacency list is the default, and it's what BFS and DFS assume when we quote O(V + E). The matrix earns its place for dense graphs, for algorithms that genuinely need constant-time edge queries, and for anything expressed as matrix operations, like Floyd-Warshall or spectral methods.",
      why: "It's a clean space-versus-time trade-off with a definite default and a definite exception.",
      trap: "Choosing a matrix for a large sparse graph. A million vertices means a trillion cells.",
      followUps: ["What does O(V + E) mean for a matrix representation?", "Where is a matrix genuinely better?"],
      depth: "Intermediate",
      tags: ["graphs"],
      topic: "graphs",
    },
    {
      id: "dsa-recursion-iteration",
      q: "When should you convert recursion to iteration?",
      a: "When depth can exceed the stack. Recursion depth is bounded by the stack — roughly a few thousand frames in Python by default, more in JVM or native languages but still finite — so a DFS over a graph with a million nodes, or a linked-list recursion over a long list, will overflow. Converting means maintaining an explicit stack of the state each frame held, which is mechanical for DFS and tree traversals though noticeably less readable. Tail recursion would avoid the problem, but Python and JavaScript engines don't reliably optimise it, so you can't rely on it. The other reason is performance: each call has overhead, and iterative versions avoid it. Against that, recursion is dramatically clearer for tree and divide-and-conquer algorithms, so the right answer in an interview is usually to write the recursive version, then say 'if depth could be large I'd convert this to an explicit stack' — which shows the awareness without sacrificing clarity.",
      why: "Depth limits are a real production concern and mentioning them unprompted is a strong signal.",
      trap: "Assuming tail-call optimisation will save you. Most mainstream runtimes don't do it.",
      followUps: ["Convert an in-order tree traversal to iterative.", "What's the space complexity of a recursive DFS?"],
      depth: "Intermediate",
      tags: ["recursion"],
      topic: "recursion",
    },
    {
      id: "dsa-stability",
      q: "What is a stable sort and when does it matter?",
      a: "A stable sort preserves the relative order of elements that compare equal. It matters whenever you sort by multiple criteria in passes: to order employees by department and then by salary within each department, you sort by salary first and then by department, and stability guarantees the salary ordering survives inside each department group. Without stability you'd need a composite comparator. Concretely, merge sort and Timsort are stable, and Timsort is what Python's `sorted` and Java's `Collections.sort` use; quicksort and heapsort are not, and C's `qsort` and many `sort` implementations for primitives are unstable — which is fine for primitives, since equal primitives are indistinguishable, and is exactly why Java uses a dual-pivot quicksort for primitives and Timsort for objects. It also matters for UI: re-sorting a table by a second column shouldn't scramble rows that tie.",
      why: "It's a detail that only people who've hit the bug tend to know.",
      trap: "Assuming every language's default sort is stable. It's guaranteed in Python and for Java objects, not universally.",
      followUps: ["Why is Java's primitive sort allowed to be unstable?", "How would you sort by two keys without stability?"],
      depth: "Advanced",
      tags: ["sorting"],
    },
    {
      id: "dsa-union-find",
      q: "What is union-find and when do you reach for it?",
      a: "A disjoint-set structure that tracks a partition of elements into groups, supporting two operations: `find`, which returns the representative of an element's group, and `union`, which merges two groups. With both optimisations — path compression, which flattens the tree during `find`, and union by rank or size, which attaches the smaller tree under the larger — the amortised cost is effectively constant, formally the inverse Ackermann function, which is under 5 for any input you'll ever see. Reach for it when the question is about connectivity under incremental merging: counting connected components, detecting a cycle while building an undirected graph, Kruskal's minimum spanning tree, grouping accounts by shared email, or 'number of islands' when cells are added over time. The thing it can't do is deletion — you can merge groups but not split them, so a problem with edge removal usually needs a different approach, often processing the operations in reverse.",
      why: "It's the elegant answer to a family of problems people otherwise solve with repeated BFS, and knowing it stands out.",
      trap: "Implementing it without path compression or union by rank, which degrades to O(n) per operation and loses the entire point.",
      followUps: ["Why can't union-find handle deletions?", "How does Kruskal's use it?"],
      depth: "Advanced",
      tags: ["graphs", "structures"],
    },
    {
      id: "dsa-interview-process",
      q: "You're given a problem you don't recognise. What do you do?",
      a: "Don't code. Restate the problem and walk through a small example out loud — that alone catches misreadings and often reveals the structure. Ask about constraints, because they're a hint: n up to 10⁵ rules out O(n²) and points at O(n log n); n up to 20 suggests exponential with bitmasking is intended; sorted input suggests two pointers or binary search. Then state the brute force and its complexity explicitly, which guarantees you have something working to fall back on and demonstrates you understand the problem. Next, name the bottleneck in the brute force and ask what could remove it — a repeated lookup wants a hash map, a repeated scan wants a window or prefix sums, repeated recomputation wants memoisation. If you're still stuck, solve a simpler version (smaller k, no duplicates, one dimension) and generalise. Keep talking throughout; silence gives the interviewer nothing to help you with, and most will nudge you if they can see where you are.",
      why: "How someone handles being stuck is often weighted more heavily than whether they finish.",
      trap: "Coding in silence for ten minutes. A wrong solution explained well scores better than a silent partial one.",
      followUps: ["What do the constraints tell you about the intended complexity?", "How do you recover if your approach is wrong halfway through?"],
      depth: "Core",
      tags: ["process"],
    },
    {
      id: "dsa-space-time",
      q: "Give an example of trading space for time.",
      a: "Two-sum is the cleanest. The brute force checks every pair for the target, which is O(n²) time and O(1) space. Adding a hash map of value-to-index lets you ask, for each element, whether its complement has already been seen — one pass, O(n) time, O(n) space. You paid memory to remove the inner loop. The same trade recurs everywhere: memoisation in DP stores computed subproblems to avoid recomputation; a prefix-sum array costs O(n) space to answer range-sum queries in O(1) instead of O(n); indexes in a database duplicate data so lookups avoid a full scan; caching stores results to avoid recomputation or a network call. It's worth naming the reverse too, since interviewers sometimes want it: if memory is the binding constraint you can recompute instead of storing, which is why in-place algorithms and streaming approaches exist.",
      why: "It's the central trade-off in the field, and having a crisp example ready shows fluency.",
      trap: "Presenting space as free. On large inputs, O(n) extra space can be the thing that doesn't fit.",
      followUps: ["When would you refuse the space and keep O(n²)?", "How do prefix sums work?"],
      depth: "Core",
      tags: ["complexity", "tradeoffs"],
      topic: "time-space-complexity",
    },
    {
      id: "dsa-monotonic-stack",
      q: "What is a monotonic stack and what does it solve?",
      a: "A stack you maintain in sorted order — increasing or decreasing — by popping elements that violate the order before pushing a new one. It answers 'next greater element' style questions in O(n) instead of O(n²). Walking left to right with a decreasing stack, when you meet an element larger than the stack top, that element is the next greater element for everything you pop, so each element is pushed and popped at most once and the total work is linear. The family it solves is larger than it first appears: next greater or smaller element, daily temperatures, largest rectangle in a histogram, trapping rain water, and the maximal rectangle in a binary matrix all reduce to it. The recognition signal is a question about finding, for each element, the nearest element on one side satisfying a comparison — that's the tell.",
      why: "It's the pattern most candidates haven't internalised, and it converts several otherwise-hard problems into short solutions.",
      trap: "Storing values rather than indices. Most of these problems need the distance or width, which requires the index.",
      followUps: ["Solve 'daily temperatures'.", "How does the histogram problem reduce to this?"],
      depth: "Advanced",
      tags: ["stacks", "patterns"],
      topic: "stacks-queues",
    },
  ],

  pitfalls: [
    "Don't start coding before stating the approach and its complexity — interviewers grade the reasoning.",
    "Don't quote hash map O(1) as a guarantee — it's average case, with a worst case of O(n).",
    "Don't forget the recursion stack when stating space complexity.",
    "Don't say 'this is O(n) because there's one loop' — check what's inside it; a `list.index()` or string concat hides an inner O(n).",
    "Don't use binary search only on sorted arrays — the requirement is a monotonic predicate.",
    "Don't go silent when stuck — state the brute force, name the bottleneck, and think out loud.",
    "Don't assume the interviewer wants the optimal solution immediately — a correct brute force first is the safer path.",
  ],

  numbers: [
    { label: "n ≤ 10–20", value: "O(2ⁿ) / O(n!) ok", note: "Backtracking or bitmask DP is likely intended." },
    { label: "n ≤ 10³", value: "O(n²) ok", note: "Nested loops fine." },
    { label: "n ≤ 10⁵–10⁶", value: "O(n log n) needed", note: "Sort or a single pass with a map." },
    { label: "n ≥ 10⁷", value: "O(n) or O(log n)", note: "Streaming, hashing, or math." },
    { label: "log₂(1,000,000)", value: "≈ 20", note: "Binary search over a million items is 20 steps." },
    { label: "Recursion depth (Python)", value: "~1000 default", note: "Convert to an explicit stack beyond this." },
  ],

  relatedTopics: [
    "big-o-notation",
    "time-space-complexity",
    "amortized-analysis",
    "arrays-strings",
    "hash-tables",
    "binary-trees",
    "graphs",
    "heaps",
    "recursion",
    "stacks-queues",
  ],
};
