import type { Area } from "../types";

export const javascript: Area = {
  slug: "javascript",
  title: "JavaScript",
  icon: "🟨",
  stream: "Language & Runtime",
  blurb:
    "Closures, the event loop, prototypes, and `this` — the four things nearly every JS interview probes, in some disguise.",

  mustKnow: [
    "JavaScript is single-threaded with an event loop: synchronous code runs to completion, then all microtasks (promises), then one macrotask (timer, I/O), then microtasks again.",
    "A closure is a function plus a reference to the scope it was created in — the scope survives because the function still points at it, which is how private state and stale-value bugs both happen.",
    "`var` is function-scoped and hoisted as `undefined`; `let`/`const` are block-scoped and in the temporal dead zone until declared (touching them early throws, it does not give `undefined`).",
    "`this` is decided by HOW a function is called, not where it is defined — except arrow functions, which have no `this` and take it from the enclosing scope at creation time.",
    "`==` coerces types, `===` does not. Use `===` always, except `x == null` which is the idiomatic check for 'null or undefined'.",
    "Objects and arrays are copied by reference. Spread (`{...o}`) is a SHALLOW copy — nested objects are still shared.",
    "`async`/`await` is syntax over promises. `await` in a loop serialises; `Promise.all` parallelises.",
    "Prototypal inheritance: property lookup walks the `__proto__` chain until it hits `null`. `class` is syntax sugar over exactly this.",
    "Event delegation: attach one listener to a parent and read `event.target`, instead of N listeners on N children.",
    "`null` is an intentional absence you assigned; `undefined` is the absence the language gives you (unset variable, missing property, no return).",
  ],

  sheets: [
    {
      title: "Event loop — the exact order",
      points: [
        "Call stack empties → drain the ENTIRE microtask queue → render (in browsers) → take ONE macrotask → repeat.",
        "Microtasks: `Promise.then/catch/finally`, `queueMicrotask`, `MutationObserver`, `await` continuations.",
        "Macrotasks: `setTimeout`, `setInterval`, `setImmediate` (Node), I/O callbacks, UI events.",
        "`setTimeout(fn, 0)` does not run 'immediately' — it runs after ALL pending microtasks.",
        "A microtask that queues another microtask starves the macrotask queue — infinite `Promise.resolve().then(loop)` freezes the page.",
        "Node extra phases: timers → pending → poll → check (`setImmediate`) → close. `process.nextTick` jumps ahead of even promises.",
        "Classic output order: sync log → `Promise.then` log → `setTimeout` log.",
      ],
    },
    {
      title: "`this` — resolution rules, in priority order",
      points: [
        "1. `new Foo()` → `this` is the newly created object.",
        "2. `fn.call/apply/bind(obj)` → `this` is `obj` (a bound function cannot be re-bound).",
        "3. `obj.method()` → `this` is `obj` (the thing left of the final dot).",
        "4. Plain `fn()` → `this` is `undefined` in strict mode / modules, `globalThis` otherwise.",
        "Arrow functions skip all four — they close over `this` lexically and ignore `call/apply/bind`.",
        "The classic bug: `const m = obj.method; m()` loses `this` because the dot is gone.",
        "In a class, methods are NOT auto-bound — that is why React class components needed `this.handleClick = this.handleClick.bind(this)`.",
      ],
    },
    {
      title: "Types & coercion",
      points: [
        "7 primitives: string, number, boolean, null, undefined, symbol, bigint. Everything else is an object.",
        "`typeof null === 'object'` — a 1995 bug that can never be fixed without breaking the web.",
        "`typeof NaN === 'number'`; `NaN !== NaN`; test with `Number.isNaN(x)`.",
        "Falsy values, all of them: `false, 0, -0, 0n, '', null, undefined, NaN`. Everything else is truthy — including `[]` and `{}`.",
        "`[] == false` is `true` (both coerce to 0) but `[] === false` is `false`. This is why `===` is the default.",
        "`0.1 + 0.2 !== 0.3` — IEEE-754 doubles. Compare with an epsilon, or use integers/cents for money.",
        "Use `Array.isArray(x)` for arrays; `typeof` reports `'object'` for both arrays and objects.",
      ],
    },
    {
      title: "Async patterns",
      points: [
        "`Promise.all` — fails fast on the first rejection; use when you need all results.",
        "`Promise.allSettled` — never rejects, returns `{status, value|reason}` per item; use for independent best-effort work.",
        "`Promise.race` — settles on the first settle (reject OR resolve); the standard timeout pattern.",
        "`Promise.any` — first FULFILLMENT; rejects with `AggregateError` only if all reject.",
        "`for (const x of xs) await f(x)` runs serially. `await Promise.all(xs.map(f))` runs concurrently.",
        "A promise `.then` chain flattens: returning a promise from `.then` waits for it.",
        "An unhandled rejection crashes Node by default (since v15). Always `.catch` or wrap in `try/catch`.",
        "`await` only pauses the enclosing async function — it never blocks the thread.",
      ],
    },
    {
      title: "Copying, equality, and memory",
      points: [
        "Shallow copy: `{...obj}`, `Object.assign({}, obj)`, `arr.slice()`, `[...arr]`.",
        "Deep copy: `structuredClone(obj)` (built in, handles Dates/Maps/cycles) — `JSON.parse(JSON.stringify(x))` silently drops `undefined`, functions, `Symbol`, and turns `Date` into a string.",
        "`Object.freeze` is shallow too — nested objects stay mutable.",
        "Common leaks: forgotten `setInterval`, listeners never removed, closures capturing large objects, unbounded caches in module scope.",
        "`WeakMap`/`WeakSet` hold keys weakly — entries vanish when the key is garbage-collected, so they're right for metadata keyed by object.",
      ],
    },
    {
      title: "Modern syntax worth naming",
      points: [
        "Optional chaining `a?.b?.c` — short-circuits to `undefined` instead of throwing.",
        "Nullish coalescing `a ?? b` — falls back only on `null`/`undefined`, unlike `||` which also catches `0` and `''`.",
        "Logical assignment `a ??= b`, `a ||= b`, `a &&= b`.",
        "Destructuring with defaults + rename: `const {a: x = 1, ...rest} = obj`.",
        "`Array.prototype.at(-1)` for the last element.",
        "`Object.groupBy(items, fn)` and `Map.groupBy` for bucketing.",
        "Top-level `await` works in ES modules.",
      ],
    },
  ],

  decisions: [
    {
      title: "`var` vs `let` vs `const`",
      options: [
        {
          name: "const",
          pick: ["Default for everything — signals the binding never gets reassigned.", "Objects/arrays you mutate but never reassign."],
          cost: ["Only freezes the binding, not the value — `const a = []; a.push(1)` is legal and surprises people."],
        },
        {
          name: "let",
          pick: ["Loop counters and values that genuinely get reassigned.", "Values assigned in a branch and read after."],
          cost: ["Reassignment makes code harder to reason about; reach for it only when needed."],
        },
        {
          name: "var",
          pick: ["Essentially never in new code."],
          cost: ["Function-scoped, hoisted as `undefined`, and re-declarable — the source of the classic `for (var i...)` closure bug."],
        },
      ],
      verdict: "`const` by default, `let` when you must reassign, `var` never.",
    },
    {
      title: "`==` vs `===`",
      options: [
        {
          name: "===",
          pick: ["Always, as the default.", "Any comparison where a type mismatch signals a bug."],
          cost: ["Slightly more verbose when you genuinely want to catch both `null` and `undefined`."],
        },
        {
          name: "==",
          pick: ["Exactly one idiom: `x == null` to catch both `null` and `undefined` in one check."],
          cost: ["Coercion rules are a lookup table nobody remembers — `'' == 0`, `'0' == 0`, `[] == ''` are all true."],
        },
      ],
      verdict: "`===` everywhere; `== null` is the one sanctioned exception.",
    },
    {
      title: "Arrow function vs `function`",
      options: [
        {
          name: "Arrow",
          pick: ["Callbacks, `map`/`filter`, and anywhere you want the surrounding `this`.", "Short expressions with implicit return."],
          cost: ["No own `this`, `arguments`, or `prototype`; cannot be a constructor; can't be used as an object method that needs `this`."],
        },
        {
          name: "function",
          pick: ["Object methods that use `this`.", "Constructors and prototype methods.", "When you want hoisting or a named stack frame."],
          cost: ["`this` depends on call site, so it needs binding when passed as a callback."],
        },
      ],
      verdict: "Arrow for callbacks and lexical `this`; `function` for methods and constructors.",
    },
    {
      title: "Debounce vs throttle",
      options: [
        {
          name: "Debounce",
          pick: ["Wait until the burst STOPS, then act once: search-as-you-type, autosave, resize-end, validation."],
          cost: ["Nothing runs during a continuous stream of events — if input never pauses, the callback never fires."],
        },
        {
          name: "Throttle",
          pick: ["Run at most once per interval DURING the burst: scroll position, mousemove, analytics, rate-limited APIs."],
          cost: ["Drops intermediate events; the final event may need a trailing call to avoid a stale end state."],
        },
      ],
      verdict: "Debounce answers 'has it stopped?'; throttle answers 'not more than N times a second'.",
    },
    {
      title: "`Promise.all` vs `allSettled` vs `race` vs `any`",
      options: [
        {
          name: "all",
          pick: ["You need every result and any failure invalidates the whole operation."],
          cost: ["Fails fast — one rejection discards results that already succeeded, and the others keep running unwatched."],
        },
        {
          name: "allSettled",
          pick: ["Independent work where partial success is useful: fan-out to N services, batch notifications."],
          cost: ["You must inspect each `{status}` yourself; never rejects, so errors can pass silently."],
        },
        {
          name: "race",
          pick: ["Timeouts — race the real work against a rejecting timer."],
          cost: ["A fast rejection wins too, which is sometimes not what you meant."],
        },
        {
          name: "any",
          pick: ["Redundant sources where the first success is enough: multiple mirrors or replicas."],
          cost: ["Only rejects when every input rejects, wrapped in `AggregateError`."],
        },
      ],
      verdict: "`all` for all-or-nothing, `allSettled` for best-effort, `race` for timeouts, `any` for first-success.",
    },
    {
      title: "`Map` vs plain object",
      options: [
        {
          name: "Map",
          pick: ["Keys that aren't strings (objects, numbers).", "Frequent add/delete.", "You need `.size` or guaranteed insertion order.", "User-controlled keys — no prototype-pollution risk."],
          cost: ["Not JSON-serialisable directly; slightly more verbose."],
        },
        {
          name: "Object",
          pick: ["Fixed, known, string-keyed records.", "You need JSON serialisation or destructuring."],
          cost: ["Keys are coerced to strings; inherited keys like `__proto__` and `constructor` can collide with user data."],
        },
      ],
      verdict: "Object for records with known shape; `Map` for a real keyed collection, especially with untrusted keys.",
    },
  ],

  qa: [
    {
      id: "js-closure",
      q: "What is a closure, and give a real use for it.",
      a: "A closure is a function bundled with a reference to the lexical scope it was created in. When the outer function returns, its variables normally die — but if an inner function still references them, that scope stays alive, and the inner function keeps reading and writing the same variables. Practical uses: private state (a counter or a module that exposes methods but hides its data), function factories where you bake in configuration once and return a specialised function, and memoisation where the cache lives in the closure rather than a global. React hooks are closures — `useState`'s setter and the values your effect sees are captured from the render in which the closure was created.",
      why: "It is the fastest way to tell whether someone understands scope and lifetime, versus having memorised syntax. Almost every stale-state bug in React is a closure question in disguise.",
      trap: "Saying 'a function inside a function'. That is the shape, not the definition — the point is the captured scope surviving the outer call, and being shared by every closure created in the same call.",
      followUps: [
        "Why does `for (var i = 0; i < 3; i++) setTimeout(() => console.log(i))` print 3, 3, 3?",
        "How does changing `var` to `let` fix it?",
        "How can a closure cause a memory leak?",
      ],
      depth: "Core",
      tags: ["closures", "scope"],
      topic: "functions",
    },
    {
      id: "js-var-loop",
      q: "Why does a `setTimeout` inside a `var` loop log the final value every time?",
      a: "`var` is function-scoped, so all three iterations share one binding of `i`. The timeouts are macrotasks — they run after the synchronous loop finishes, by which point that single `i` is 3, so every callback reads 3. `let` is block-scoped: the spec creates a fresh binding per iteration and copies the value forward, so each closure captures its own `i` and you get 0, 1, 2. Before `let`, the fix was an IIFE per iteration to create a new scope, or passing `i` as a third argument to `setTimeout`.",
      why: "It sits at the intersection of scoping, closures, and the event loop — three topics in one question.",
      trap: "Saying `setTimeout` is 'too slow' or 'asynchronous so it misses the value'. Timing is not the cause; the shared binding is. A zero-delay timeout behaves identically.",
      followUps: ["What exactly does the spec do per iteration for `let`?", "Would `const` work in a `for` loop?"],
      depth: "Core",
      tags: ["closures", "hoisting"],
    },
    {
      id: "js-event-loop",
      q: "Walk me through the event loop.",
      a: "JavaScript has one call stack, so one thing runs at a time. Synchronous code runs to completion. When the stack empties, the runtime drains the entire microtask queue — promise callbacks, `queueMicrotask`, `await` continuations — including microtasks queued by other microtasks. Then the browser may render. Then it takes exactly ONE macrotask (a timer, an I/O callback, a click handler) and repeats the whole cycle. Two consequences matter in practice: `setTimeout(fn, 0)` runs after all pending promise work, not immediately; and a long synchronous function or a microtask that keeps re-queuing itself blocks rendering entirely, because neither can be interrupted.",
      why: "It explains everything about ordering, UI jank, and why 'async' does not mean 'parallel'.",
      trap: "Saying JavaScript is multi-threaded because of async. The language runs on one thread; concurrency comes from the runtime (browser or libuv) doing I/O elsewhere and queuing callbacks back onto that single thread.",
      followUps: [
        "Predict the output of a snippet mixing sync logs, `setTimeout`, and `Promise.then`.",
        "Where does `process.nextTick` fit in Node?",
        "How would you break up a long computation to keep the UI responsive?",
      ],
      depth: "Core",
      tags: ["event-loop", "async"],
      topic: "threads-vs-async",
    },
    {
      id: "js-microtask-order",
      q: "What does this print? `console.log(1); setTimeout(()=>console.log(2)); Promise.resolve().then(()=>console.log(3)); console.log(4);`",
      a: "1, 4, 3, 2. The two synchronous logs run first, in order: 1 then 4. The stack then empties, so the microtask queue drains and prints 3. Only then is one macrotask taken, printing 2. The rule to state out loud: all synchronous code, then all microtasks, then one macrotask.",
      why: "A five-second check that you actually internalised the queue priority rather than reciting it.",
      trap: "Putting 2 before 3 because `setTimeout` was written first. Source order does not matter across queues; queue priority does.",
      followUps: ["Add `queueMicrotask` and `process.nextTick` — where do they land?"],
      depth: "Core",
      tags: ["event-loop"],
    },
    {
      id: "js-this",
      q: "How is `this` determined?",
      a: "By the call site, in this priority: `new Foo()` binds `this` to the new object; an explicit `call`/`apply`/`bind` binds it to what you passed; a method call `obj.fn()` binds it to `obj`; and a bare `fn()` gives `undefined` in strict mode or modules, and `globalThis` otherwise. Arrow functions are outside this system entirely — they have no own `this`, so they use the enclosing scope's `this` fixed at creation, and `call`/`apply`/`bind` cannot change it. The practical consequence is that detaching a method (`const m = obj.method; m()`) loses `this`, which is why callbacks need `bind` or an arrow wrapper.",
      why: "`this` bugs are everywhere in class components, event handlers, and callbacks; the rules are learnable and reveal whether someone reasons or guesses.",
      trap: "Saying `this` refers to the function or to where it was defined. For everything except arrows, definition site is irrelevant.",
      followUps: ["What does `this` mean inside a class method passed to `addEventListener`?", "Why can't you re-bind an already-bound function?"],
      depth: "Core",
      tags: ["this", "binding"],
    },
    {
      id: "js-hoisting-tdz",
      q: "Explain hoisting and the temporal dead zone.",
      a: "During compilation the engine registers declarations before any code runs. `var` declarations are registered and initialised to `undefined`, so reading one early gives `undefined` rather than an error. Function declarations are hoisted whole, so you can call them before their line. `let` and `const` are also hoisted — the binding exists — but they are not initialised, and the region from the top of the block to the declaration is the temporal dead zone: touching the variable there throws a `ReferenceError`. That is deliberate; it turns a silent `undefined` bug into a loud failure. Class declarations behave like `let` in this respect.",
      why: "Tests whether someone knows `let` is hoisted at all — most people wrongly say it isn't.",
      trap: "'`let` is not hoisted.' It is; it just isn't initialised. The observable difference is a throw instead of `undefined`.",
      followUps: ["Is a function expression assigned to `var` callable before its line?", "What about `typeof` on a TDZ variable?"],
      depth: "Intermediate",
      tags: ["hoisting", "scope"],
    },
    {
      id: "js-proto",
      q: "How does prototypal inheritance work?",
      a: "Every object has an internal link to another object, its prototype. When you read a property, the engine checks the object itself, then its prototype, then that object's prototype, until it reaches `null`. Writes are different — they land on the object itself and shadow the prototype's version rather than modifying it. Functions have a `prototype` property that becomes the prototype of objects made with `new`, which is how methods are shared: one function object on the prototype, used by every instance, instead of a copy per instance. `class` syntax compiles to exactly this — `extends` sets up the prototype chain and `super` walks it.",
      why: "It separates people who learned `class` from people who understand what `class` is.",
      trap: "Describing it as classical inheritance with a different keyword. There are no classes at runtime — only objects delegating to other objects, and delegation is live, so patching a prototype affects existing instances.",
      followUps: ["Difference between `__proto__` and `.prototype`?", "What does `Object.create(null)` give you and why would you want it?"],
      depth: "Intermediate",
      tags: ["prototypes", "oop"],
      topic: "inheritance",
    },
    {
      id: "js-shallow-deep",
      q: "Shallow vs deep copy — how do you deep copy correctly?",
      a: "A shallow copy duplicates the top level only; nested objects are still shared references, so mutating `copy.nested.x` changes the original. Spread, `Object.assign`, and `slice` are all shallow. For a deep copy, use `structuredClone(obj)` — it is built into browsers and Node, and it correctly handles `Date`, `Map`, `Set`, `ArrayBuffer`, and cyclic references. The old `JSON.parse(JSON.stringify(x))` trick is lossy: it drops `undefined`, functions, and symbols, converts `Date` to a string, and throws on cycles. Reach for a library only if you need to clone class instances with their prototypes, which `structuredClone` does not preserve.",
      why: "Accidental shared mutation is one of the most common real bugs, especially in state management.",
      trap: "Claiming spread is a deep copy. It is one level deep.",
      followUps: ["What does `structuredClone` NOT handle?", "How does this connect to immutability in Redux?"],
      depth: "Core",
      tags: ["objects", "immutability"],
      topic: "immutability",
    },
    {
      id: "js-debounce-impl",
      q: "Implement debounce.",
      a: "Keep a timer id in a closure. Every call clears the pending timer and schedules a new one, so the wrapped function only runs once the calls stop for `delay` milliseconds. `function debounce(fn, delay) { let t; return function (...args) { clearTimeout(t); t = setTimeout(() => fn.apply(this, args), delay); }; }`. Two details separate a good answer: use a regular function and `fn.apply(this, args)` so the wrapper preserves `this` when used as a method, and consider returning a `cancel` method so callers can tear it down on unmount. If asked for the leading-edge variant, fire immediately when no timer is pending and use the timer purely to suppress the tail.",
      why: "A small, real implementation that exposes closures, `this`, rest args, and timer handling at once.",
      trap: "Using an arrow for the returned wrapper — it captures the wrong `this` and breaks method usage.",
      followUps: ["Now write throttle.", "How do you cancel a pending call on component unmount?"],
      depth: "Intermediate",
      tags: ["closures", "performance"],
    },
    {
      id: "js-event-delegation",
      q: "What is event delegation and why use it?",
      a: "Instead of attaching a listener to every child, attach one to a common ancestor and identify the origin with `event.target`, usually via `event.target.closest('.item')`. This works because events bubble from the target up through its ancestors. The benefits: one listener instead of N, so less memory and faster setup; and it automatically covers elements added later, since you never bound to them in the first place. The main caveats are events that do not bubble (`focus`, `blur` — use `focusin`/`focusout`), and needing to guard against clicks on the container itself.",
      why: "It shows understanding of the DOM event model, and it is the standard fix for lists with thousands of rows.",
      trap: "Confusing `event.target` (what was actually clicked, possibly a nested span) with `event.currentTarget` (the element the listener is on).",
      followUps: ["Capture vs bubble phase?", "How do you stop propagation, and when is that a bad idea?"],
      depth: "Intermediate",
      tags: ["dom", "events"],
    },
    {
      id: "js-null-undefined",
      q: "`null` vs `undefined`.",
      a: "`undefined` is what the language gives you when something was never set: an unassigned variable, a missing object property, a missing argument, or a function with no `return`. `null` is an explicit assignment meaning 'intentionally empty' — you chose it. Practically: `typeof undefined` is `'undefined'` while `typeof null` is `'object'` (a historic bug); `null == undefined` is true but `null === undefined` is false; and `JSON.stringify` keeps `null` but drops `undefined` properties entirely. Default parameters trigger on `undefined` only, not `null`. The clean convention is to let `undefined` mean 'absent' and use `null` when you deliberately model 'known to be empty'.",
      why: "It surfaces coercion knowledge and API design instincts in one question.",
      trap: "Saying they are interchangeable. Their serialisation and default-parameter behaviour differ in ways that cause real bugs.",
      followUps: ["Why does `?? ` treat them the same but `||` doesn't?", "What does a default parameter do when passed `null`?"],
      depth: "Core",
      tags: ["types"],
    },
    {
      id: "js-nullish-vs-or",
      q: "Why use `??` instead of `||` for defaults?",
      a: "`||` falls back whenever the left side is falsy, which includes `0`, `''`, `false`, and `NaN` — all of which are often legitimate values. `??` falls back only on `null` or `undefined`. So `const count = input || 10` wrongly becomes 10 when the user genuinely entered 0, while `input ?? 10` keeps the 0. Use `??` for defaults on values where zero or empty string is meaningful — counts, prices, flags, search strings — and `||` only when you actually want any falsy value replaced.",
      why: "A concrete, high-frequency bug that separates people who write JS from people who copy JS.",
      trap: "Treating them as synonyms. The difference only bites on `0` and `''`, which is exactly when it matters.",
      followUps: ["Why is `a ?? b || c` a syntax error?"],
      depth: "Core",
      tags: ["operators"],
    },
    {
      id: "js-await-loop",
      q: "What's wrong with `await` inside a `for` loop?",
      a: "Nothing, if the iterations genuinely depend on each other — but if they are independent, you have serialised work that could have run concurrently. Ten requests at 200 ms each take 2 seconds serially and about 200 ms with `await Promise.all(items.map(fetchOne))`. The nuance worth adding: `Promise.all` fires all of them at once, which can overwhelm a downstream service or hit rate limits, so for large N you want bounded concurrency — chunk the array, or use a small pool that keeps K requests in flight. And note that `forEach` does not await at all: `items.forEach(async x => await f(x))` returns immediately and silently swallows rejections.",
      why: "Tests whether someone reasons about concurrency and blast radius, not just syntax.",
      trap: "Blanket-replacing every loop with `Promise.all`. Unbounded fan-out against a database or third-party API is its own outage.",
      followUps: ["Implement bounded concurrency with a pool size of 5.", "Why doesn't `forEach` work with async?"],
      depth: "Intermediate",
      tags: ["async", "performance"],
    },
    {
      id: "js-error-async",
      q: "How do you handle errors in async code?",
      a: "With `async/await`, wrap in `try/catch` — it catches rejections just like throws. With raw promises, use `.catch()`, and remember `.then(onOk, onErr)` does NOT catch errors thrown inside `onOk`, whereas a trailing `.catch()` does. Three things that catch people out: an async function always returns a promise, so throwing inside it produces a rejection, not a synchronous throw; `try/catch` around a non-awaited call catches nothing, because the function returned before rejecting; and unhandled rejections terminate Node by default since v15. For robustness, add a process-level `unhandledRejection` handler for logging, but treat it as a bug detector, not a strategy.",
      why: "Error handling is where async understanding either holds up or falls apart.",
      trap: "Wrapping a call in `try/catch` but forgetting `await` — the error escapes entirely.",
      followUps: ["What happens to a rejection inside `setTimeout`?", "How do you add a timeout to a fetch?"],
      depth: "Intermediate",
      tags: ["async", "errors"],
      topic: "error-handling",
    },
    {
      id: "js-currying",
      q: "What is currying, and when is it useful?",
      a: "Currying turns a function of N arguments into a chain of N single-argument functions: `f(a, b, c)` becomes `f(a)(b)(c)`. Each call captures its argument in a closure and returns a function awaiting the next. In practice the useful cousin is partial application — fixing some arguments now and the rest later — which gives you specialised functions from general ones: a `log` curried on level yields `logError` and `logWarn`. It also makes point-free composition possible, since every step takes exactly one value. The cost is indirection and worse stack traces, so it earns its place in pipelines and functional codebases and rarely elsewhere.",
      why: "Checks closure fluency and whether someone can justify a pattern rather than just name it.",
      trap: "Confusing currying with `bind`. `bind` does partial application and also fixes `this`; currying is purely about argument arity.",
      followUps: ["Write a generic `curry` that works for any arity."],
      depth: "Advanced",
      tags: ["functional", "closures"],
      topic: "function-composition",
    },
    {
      id: "js-memo",
      q: "Implement memoisation.",
      a: "Wrap the function and keep a cache in a closure, keyed by the arguments: `function memo(fn) { const cache = new Map(); return (...args) => { const k = JSON.stringify(args); if (cache.has(k)) return cache.get(k); const v = fn(...args); cache.set(k, v); return v; }; }`. The interesting part is the caveats, and mentioning them is what makes the answer senior: `JSON.stringify` is a poor key for objects with unstable key order or non-serialisable values; the cache grows without bound, so a real one needs an LRU limit or a TTL; it is only correct for pure functions, since caching a function that reads mutable state or does I/O returns stale results; and if you key by a single object argument, a `WeakMap` lets entries be garbage-collected with the object.",
      why: "Simple to write, and the follow-up about unbounded growth separates careful engineers from the rest.",
      trap: "Shipping it without a size bound — a memoised function on user input is a memory leak.",
      followUps: ["How would you add an LRU eviction policy?", "When is `WeakMap` the right cache?"],
      depth: "Intermediate",
      tags: ["closures", "performance"],
    },
    {
      id: "js-generators",
      q: "What are generators and where would you use one?",
      a: "A generator function (`function*`) can pause at `yield` and resume later, keeping its local state between resumptions. Calling it returns an iterator; each `.next()` runs until the next `yield`. That makes them good for lazy or infinite sequences (produce values only as consumed), for streaming large datasets without materialising them, and for custom iteration protocols. Because `.next(value)` can send data back in, they can also drive cooperative control flow — which is exactly how `async/await` was originally implemented and how redux-saga models side effects. In modern app code, `async/await` covers most of what generators used to be needed for, so their remaining niche is lazy sequences and fine-grained control.",
      why: "Signals depth beyond everyday syntax and connects to how `await` actually works.",
      trap: "Describing them as 'async functions'. Generators are synchronous unless you combine them with promises; `async function*` is the async variant.",
      followUps: ["How do you consume an async generator?", "Write a generator producing an infinite Fibonacci sequence."],
      depth: "Advanced",
      tags: ["generators", "iterators"],
    },
    {
      id: "js-modules",
      q: "ES modules vs CommonJS.",
      a: "ESM (`import`/`export`) is the standard: statically analysable, so bundlers can tree-shake unused exports; hoisted and resolved before execution; asynchronous; and it gives live bindings, so importing a value and later reassigning it in the source module is visible to importers. CommonJS (`require`/`module.exports`) is Node's original system: synchronous, resolved at runtime, so `require` can be conditional or inside a function, and it copies values at the moment of require. Practical consequences: you can `require` a CJS module from ESM, but importing ESM from CJS needs dynamic `import()`; ESM has top-level `await` and CJS does not; and `__dirname` exists in CJS but needs `import.meta.url` in ESM.",
      why: "Every Node and bundler configuration problem eventually traces back to this distinction.",
      trap: "Saying they are interchangeable. Static vs dynamic resolution is what makes tree-shaking possible and what makes the interop awkward.",
      followUps: ["Why can't you tree-shake CommonJS?", "What is the dual-package hazard?"],
      depth: "Intermediate",
      tags: ["modules", "tooling"],
    },
    {
      id: "js-symbols",
      q: "What are Symbols for?",
      a: "A Symbol is a guaranteed-unique primitive, so it works as a property key that can never collide with another key — useful for attaching metadata to objects you don't own, or for quasi-private fields (they don't appear in `Object.keys` or `JSON.stringify`, though `Object.getOwnPropertySymbols` still finds them, so it is encapsulation by convention, not security). The bigger use is well-known symbols that hook into language protocols: `Symbol.iterator` makes an object work with `for...of` and spread, `Symbol.asyncIterator` powers `for await`, and `Symbol.toPrimitive` controls coercion. `Symbol.for('key')` uses a global registry when you need the same symbol across realms.",
      why: "Rarely used day to day, so it distinguishes people who have read the language from people who have only used it.",
      trap: "Calling symbol properties truly private. Use `#field` for real privacy.",
      followUps: ["Make a custom object iterable with `Symbol.iterator`."],
      depth: "Advanced",
      tags: ["symbols", "protocols"],
    },
    {
      id: "js-weakmap",
      q: "When would you use a `WeakMap`?",
      a: "When you want to associate data with an object without preventing that object from being garbage-collected. `WeakMap` keys must be objects and are held weakly, so once nothing else references the key, both the key and its value become collectable. The canonical uses are caching computed results keyed by an object, storing private per-instance data outside the instance, and tracking metadata for DOM nodes so that removing a node from the page also releases its metadata. A regular `Map` in those positions is a leak: the map keeps a strong reference forever. The trade-off is that `WeakMap` is not enumerable and has no `.size` — by design, since entries can vanish at any time.",
      why: "Memory-leak awareness is a strong senior signal.",
      trap: "Trying to iterate a `WeakMap`. It is deliberately impossible; if you need iteration you need a `Map` plus an eviction strategy.",
      followUps: ["How would you implement private fields with `WeakMap`?", "What does `#private` do differently?"],
      depth: "Advanced",
      tags: ["memory", "collections"],
      topic: "garbage-collection",
    },
    {
      id: "js-immutability-why",
      q: "Why do frameworks insist on immutable updates?",
      a: "Because change detection becomes an O(1) reference comparison instead of a deep walk. If every update produces a new object, `prev !== next` is a reliable signal that something changed, which is exactly what React's `memo`, `useMemo`, and dependency arrays rely on. Mutating in place keeps the same reference, so the check says 'unchanged' and the UI silently fails to update — the single most common React state bug. Immutability also gives you free undo/redo and time-travel debugging, since old versions remain intact, and it removes a class of bugs where two components unknowingly share and mutate the same object. The cost is allocation churn, which structural sharing (Immer, Immutable.js) reduces by reusing untouched subtrees.",
      why: "Connects a language concept to a framework behaviour, which is where real understanding shows.",
      trap: "Saying immutability is 'safer' without explaining the reference-equality mechanism that makes it load-bearing.",
      followUps: ["How does Immer give you mutable syntax with immutable results?", "What is structural sharing?"],
      depth: "Intermediate",
      tags: ["immutability", "react"],
      topic: "immutability",
    },
    {
      id: "js-gc",
      q: "How does garbage collection work in JavaScript, and how do leaks still happen?",
      a: "Modern engines use generational mark-and-sweep: start from roots (globals, the current stack), mark everything reachable, sweep the rest. Objects are allocated in a young generation that is collected frequently and cheaply, and survivors are promoted to an old generation collected less often. Reference counting is not used, because it cannot reclaim cycles. Leaks therefore are not 'unfreed memory' but unintended reachability: a `setInterval` never cleared, an event listener never removed, a closure holding a large object alive, detached DOM nodes still referenced by JS, or an unbounded cache in module scope. The fix is always to drop the reference — clear timers, remove listeners on teardown, bound caches, and use `WeakMap`/`WeakRef` where the association should not keep things alive.",
      why: "Distinguishes people who have debugged a production memory problem from those who haven't.",
      trap: "Saying 'JS has GC so leaks are impossible'. GC frees unreachable memory; leaks are reachable memory you forgot about.",
      followUps: ["How would you find a leak with Chrome DevTools heap snapshots?", "What is a detached DOM node?"],
      depth: "Advanced",
      tags: ["memory", "gc"],
      topic: "garbage-collection",
    },
    {
      id: "js-float",
      q: "Why is `0.1 + 0.2 !== 0.3`?",
      a: "JavaScript numbers are IEEE-754 double-precision binary floats. 0.1 and 0.2 have no exact binary representation, the same way 1/3 has no exact decimal one, so each is stored as the nearest representable value and the sum lands at 0.30000000000000004. This is not a JS quirk — it is true in Java, Python, and C too. For comparisons, test `Math.abs(a - b) < Number.EPSILON`. For money, never use floats: store integer minor units (cents) and divide only for display, or use a decimal library, or `BigInt` if you need arbitrary precision integers. Also worth knowing: integers are exact only up to `Number.MAX_SAFE_INTEGER` (2^53 − 1), beyond which IDs from a backend silently lose precision, which is why large IDs should be transported as strings.",
      why: "The `MAX_SAFE_INTEGER` follow-up is a real bug in almost every system that passes 64-bit IDs as JSON numbers.",
      trap: "Blaming JavaScript specifically. It is binary floating point, and it is universal.",
      followUps: ["How would you represent currency?", "Why must a 64-bit database ID be sent as a string?"],
      depth: "Intermediate",
      tags: ["numbers", "precision"],
    },
    {
      id: "js-optional-chaining",
      q: "What problem does optional chaining solve, and what does it not solve?",
      a: "`a?.b?.c` short-circuits to `undefined` the moment any link is `null` or `undefined`, replacing long `a && a.b && a.b.c` chains. It also works for calls (`fn?.()`, which no-ops if `fn` is nullish) and indexes (`arr?.[0]`). What it does not do is make missing data correct — it converts a loud `TypeError` into a silent `undefined`, which can push the failure further from its cause. So use it where absence is genuinely expected (optional config, partially-loaded data) and validate at the boundary where it is not. Note it only guards `null`/`undefined`: `a?.b` still throws if `a` is a number and you call a method that doesn't exist.",
      why: "Anyone can describe the syntax; the interesting answer is knowing when the silence is harmful.",
      trap: "Sprinkling `?.` everywhere to stop crashes. That hides schema mismatches instead of fixing them.",
      followUps: ["How does it combine with `??`?", "Where should you validate an API response instead?"],
      depth: "Core",
      tags: ["operators", "safety"],
    },
    {
      id: "js-array-methods",
      q: "Which array methods mutate, and why does it matter?",
      a: "Mutating: `push`, `pop`, `shift`, `unshift`, `splice`, `sort`, `reverse`, `fill`, `copyWithin`. Non-mutating: `map`, `filter`, `slice`, `concat`, `flat`, `flatMap`, and the newer `toSorted`, `toReversed`, `toSpliced`, `with`. The trap is `sort` and `reverse` — they look functional and read like they return a new array, but they modify in place and return the same reference. In React that means state appears unchanged to a reference check and the component doesn't re-render, so you write `[...items].sort()` or `items.toSorted()`. Also remember `sort` is lexicographic by default: `[10, 9, 1].sort()` gives `[1, 10, 9]` unless you pass `(a, b) => a - b`.",
      why: "Two of the most common real bugs — mutating state and the default string sort — in one question.",
      trap: "Assuming `sort` returns a copy. It returns the same array, already mutated.",
      followUps: ["How do you sort objects by multiple fields?", "What is `toSorted` and when can you use it?"],
      depth: "Core",
      tags: ["arrays", "immutability"],
    },
    {
      id: "js-cors",
      q: "What is CORS and where is it enforced?",
      a: "CORS is a browser mechanism that relaxes the same-origin policy. By default a page may not read a response from a different origin (scheme + host + port). The server opts in by returning `Access-Control-Allow-Origin` and friends; the browser then permits the read. Two details matter. First, enforcement is entirely in the browser — the request often still reaches the server, and a CORS failure does not mean the server rejected it. That is why `curl` and Postman never see CORS errors. Second, non-simple requests (custom headers, `PUT`/`DELETE`, JSON content type) trigger a preflight `OPTIONS` that must also be answered correctly. To send cookies you need `credentials: 'include'` on the client plus `Access-Control-Allow-Credentials: true` and a specific origin — the wildcard `*` is rejected with credentials.",
      why: "It is the single most misdiagnosed frontend error, and the fix is always server-side.",
      trap: "Trying to 'fix CORS' in frontend code. You cannot; you configure the server, or proxy through your own origin.",
      followUps: ["Why does a preflight happen for `Content-Type: application/json`?", "Why is `*` disallowed with credentials?"],
      depth: "Intermediate",
      tags: ["browser", "security"],
      topic: "http",
    },
    {
      id: "js-storage",
      q: "localStorage vs sessionStorage vs cookies — and where do you put a token?",
      a: "`localStorage` persists until cleared and is shared across tabs of the same origin; `sessionStorage` is scoped to a single tab and dies with it; both are synchronous, string-only, roughly 5–10 MB, and readable by any JavaScript on the page. Cookies are small (~4 KB), sent automatically with every matching request, and can be marked `HttpOnly` so JavaScript cannot read them, `Secure` so they only travel over HTTPS, and `SameSite` to limit cross-site sending. For auth tokens the answer is a cookie with `HttpOnly; Secure; SameSite=Lax` (or `Strict`), because any XSS on your page can read `localStorage` and exfiltrate a token instantly. The cookie approach trades that for CSRF exposure, which `SameSite` plus a CSRF token handles.",
      why: "A security-flavoured question with a definite right answer and a real trade-off behind it.",
      trap: "Defaulting to `localStorage` for JWTs because it is convenient. It makes any XSS a full account takeover.",
      followUps: ["How does `SameSite` mitigate CSRF?", "Where do refresh tokens live?"],
      depth: "Intermediate",
      tags: ["browser", "security", "auth"],
      topic: "sessions-vs-tokens",
    },
    {
      id: "js-perf-render",
      q: "A page feels janky during scroll. How do you diagnose it?",
      a: "Start by naming the budget: 60fps means about 16 ms per frame, so anything long on the main thread drops frames. Record a Performance profile in DevTools and look at what dominates — long JavaScript tasks, style recalculation, layout, or paint. The common causes are layout thrashing (reading a layout property like `offsetHeight` after a write, in a loop, forcing synchronous reflow each time), expensive scroll handlers that aren't throttled, animating properties that trigger layout (`top`, `width`) instead of compositor-only ones (`transform`, `opacity`), and rendering thousands of DOM nodes instead of virtualising. Fixes in order: batch reads then writes, throttle or use `IntersectionObserver`/`content-visibility` instead of scroll math, animate `transform`/`opacity`, virtualise long lists, and move heavy computation to a Web Worker.",
      why: "Performance questions reward a diagnostic method over a list of tips.",
      trap: "Jumping to `will-change` or micro-optimising loops before profiling. Measure first; the bottleneck is usually layout, not arithmetic.",
      followUps: ["What is layout thrashing exactly?", "Why is `transform` cheaper than `top`?", "When is a Web Worker worth it?"],
      depth: "Advanced",
      tags: ["performance", "dom"],
      topic: "profiling",
    },
    {
      id: "js-iife-module",
      q: "What was the module pattern, and why did it exist?",
      a: "Before ES modules, every script shared one global scope, so libraries wrapped themselves in an immediately-invoked function expression to get a private scope and return only a public API. The closure kept internal state hidden while the returned object exposed methods — genuine encapsulation with no language support for it. It also prevented name collisions between scripts, which was a real hazard when everything was a `<script>` tag. ES modules replaced it: each module has its own scope by default, `export` is explicit, and bundlers can analyse the graph statically. The pattern is worth knowing because you still meet it in older code and in UMD builds that must work in both worlds.",
      why: "History that explains why modules are designed the way they are.",
      trap: "Dismissing it as obsolete without being able to say what problem it solved.",
      followUps: ["What does UMD do?", "How do ES modules give you privacy for free?"],
      depth: "Advanced",
      tags: ["modules", "closures"],
    },
    {
      id: "js-tagged-template",
      q: "What are tagged template literals used for?",
      a: "A tag is a function that receives the literal's static string parts as an array plus the interpolated values separately, and returns whatever it likes. Because the values arrive separated from the text, the tag can process them safely — which is exactly how libraries prevent injection: a SQL tag can parameterise every interpolation rather than concatenating it, and an HTML tag can escape values before insertion. Other uses are styled-components (CSS with interpolations), i18n (keying off the static parts), and `String.raw` for un-escaped strings like Windows paths or regex sources. The security angle is the one worth leading with, since it explains why the API separates the two arrays at all.",
      why: "Explains a language feature by the problem it solves, which is the answer interviewers remember.",
      trap: "Describing them as 'template strings with a function in front' without mentioning why the split matters.",
      followUps: ["How would you write a `sql` tag that parameterises safely?"],
      depth: "Advanced",
      tags: ["syntax", "security"],
    },
    {
      id: "js-deep-equal",
      q: "How would you write a deep equality check?",
      a: "Recurse: if both sides are strictly equal, return true (this also handles primitives and identical references); handle `NaN` explicitly since `NaN !== NaN`; if either is `null` or not an object, they are unequal at this point; if their constructors differ, unequal; for arrays compare lengths then each index; for plain objects compare key counts then recurse per key. The parts people miss are the special cases: `Date` needs `getTime()` comparison, `RegExp` needs `source` and `flags`, `Map`/`Set` need their own logic, and cyclic structures need a `WeakMap` of visited pairs or the recursion never terminates. In production, use `structuredClone` for copying and a vetted library for comparison — but being able to name these edge cases is the point of the question.",
      why: "It is really a question about edge-case thinking, not recursion.",
      trap: "Comparing `JSON.stringify` outputs. Key order changes the result, and it throws on cycles.",
      followUps: ["How do you handle cycles?", "Why is `JSON.stringify` comparison unreliable?"],
      depth: "Advanced",
      tags: ["algorithms", "objects"],
    },
    {
      id: "js-strict",
      q: "What does strict mode change?",
      a: "It turns silent failures into errors and removes legacy behaviour: assigning to an undeclared variable throws instead of creating a global; writes to non-writable or non-existent properties throw; duplicate parameter names are a syntax error; `this` is `undefined` in a plain function call rather than the global object; `delete` on a variable is illegal; and `with` and octal literals are banned. It also lets engines optimise more aggressively, since fewer dynamic behaviours are possible. In practice you rarely write `'use strict'` any more, because ES modules and class bodies are strict automatically — which is worth saying, since it explains why `this` is `undefined` in module code that would have given `globalThis` in a script.",
      why: "The module-implies-strict detail explains a `this` behaviour people otherwise find mysterious.",
      trap: "Thinking you must opt in manually. Modules and classes are always strict.",
      followUps: ["Why is `this` `undefined` at the top of a module?"],
      depth: "Intermediate",
      tags: ["language"],
    },
    {
      id: "js-getter-proxy",
      q: "What is a Proxy and when is it worth using?",
      a: "A `Proxy` wraps an object and intercepts fundamental operations through traps — `get`, `set`, `has`, `deleteProperty`, `apply`, and others — letting you run code whenever the object is used. That powers reactivity systems (Vue 3 tracks dependencies in `get` and triggers updates in `set`), validation layers that reject bad writes, negative array indices, logging and mocking in tests, and lazy-loading placeholders that fetch on first access. The costs are real: property access through a proxy is meaningfully slower than direct access, traps are easy to get subtly wrong (forgetting to `Reflect` through to the target breaks invariants), and debugging becomes harder because ordinary-looking code now runs side effects. Reach for it for framework-level infrastructure, not application logic.",
      why: "Explains how modern reactivity actually works, and tests judgement about when metaprogramming is justified.",
      trap: "Using a Proxy where a plain function or class would do. It is powerful and usually unnecessary.",
      followUps: ["Why pair `Proxy` with `Reflect`?", "How does Vue 3 reactivity use it?"],
      depth: "Advanced",
      tags: ["metaprogramming"],
    },
  ],

  pitfalls: [
    "Don't say 'JavaScript is multi-threaded because of async' — say it is single-threaded, and the runtime does I/O off-thread and queues callbacks back.",
    "Don't call spread a deep copy — say it is shallow, and name `structuredClone` as the built-in deep copy.",
    "Don't say '`let` is not hoisted' — say it is hoisted but uninitialised, and the TDZ makes early access throw.",
    "Don't claim `setTimeout(fn, 0)` runs immediately — it runs after every pending microtask.",
    "Don't reach for `localStorage` for auth tokens — say `HttpOnly` cookie, and name XSS as the reason.",
    "Don't answer 'what is a closure' with 'a function inside a function' — lead with the captured scope outliving the call.",
    "Don't say `sort` returns a new array — it mutates and returns the same reference.",
  ],

  numbers: [
    { label: "Frame budget at 60fps", value: "~16.7 ms", note: "Main-thread work beyond this drops frames." },
    { label: "MAX_SAFE_INTEGER", value: "2^53 − 1 ≈ 9.007e15", note: "Larger backend IDs must be strings in JSON." },
    { label: "localStorage quota", value: "~5–10 MB per origin", note: "Synchronous — large writes block the main thread." },
    { label: "Cookie size limit", value: "~4 KB", note: "Sent on every matching request; keep them small." },
    { label: "Number.EPSILON", value: "~2.22e-16", note: "Tolerance for float comparison." },
  ],

  relatedTopics: ["functions", "higher-order-functions", "immutability", "garbage-collection", "threads-vs-async", "error-handling", "http", "type-systems"],
};
