import type { Area } from "../types";

export const llmTransformers: Area = {
  slug: "llm-transformers",
  title: "LLMs & Transformers",
  icon: "🧠",
  stream: "AI Engineering",
  blurb:
    "Attention, tokens, context windows, decoding, and why hallucination is a property of the objective rather than a bug to patch.",

  mustKnow: [
    "A transformer predicts the next token given all previous tokens. Everything an LLM appears to do — reasoning, coding, translation — emerges from that one objective at scale.",
    "Self-attention lets every token attend to every other token, computing weighted relevance. That's what gives long-range context, and it costs O(n²) in sequence length.",
    "Tokens are sub-word pieces, not words: roughly 4 characters or 0.75 words in English, and far more tokens per word for code, non-Latin scripts, and rare names.",
    "The context window is the total budget for system prompt + history + retrieved documents + the response. Exceeding it means truncation, not an error you'd notice.",
    "Temperature controls randomness of sampling. 0 is near-deterministic (not fully — batching and floating point still vary), higher is more diverse and more error-prone.",
    "Hallucination is not a bug in the usual sense: the model is optimised to produce plausible continuations, and it has no built-in notion of truth or of its own uncertainty.",
    "The model is stateless between calls. 'Memory' in a chat product means you're resending the conversation, which is why cost and latency grow with the conversation.",
    "Decoder-only (GPT-style) models generate; encoder-only (BERT-style) models embed and classify; encoder-decoder (T5) models suit translation-shaped tasks.",
    "Inference has two phases: prefill, which processes the prompt in parallel and is compute-bound, and decode, which emits one token at a time and is memory-bandwidth-bound.",
    "Knowledge cutoff means the model has no awareness of events after training. Anything current must come in through the prompt — via retrieval or tools.",
  ],

  sheets: [
    {
      title: "The transformer, in the order it runs",
      points: [
        "Tokenise → integer ids via a learned vocabulary (BPE / SentencePiece).",
        "Embed → each id becomes a dense vector; positional information is added (absolute, learned, or rotary/RoPE).",
        "Per layer: multi-head self-attention → residual + layer norm → feed-forward network → residual + layer norm.",
        "Attention = softmax(QKᵀ / √d)·V. Q, K, V are learned projections; the √d scaling keeps softmax gradients from vanishing.",
        "Multi-head: several attention computations in parallel over different subspaces, so different heads track syntax, coreference, position, etc.",
        "Causal mask in decoder models: a token may not attend to future tokens — that's what makes it autoregressive.",
        "Final layer → logits over the vocabulary → sampling picks the next token → append and repeat.",
        "Modern efficiency work: FlashAttention (IO-aware exact attention), grouped-query attention, sliding-window/sparse attention, mixture-of-experts for sparse capacity.",
      ],
    },
    {
      title: "Decoding parameters",
      points: [
        "temperature — scales logits before softmax. 0–0.3 extraction/classification/code; 0.7–1.0 creative writing.",
        "top_p (nucleus) — sample only from the smallest set of tokens whose cumulative probability ≥ p. Usually tune this OR temperature, not both.",
        "top_k — sample from the k most likely tokens; blunter than top_p.",
        "max_tokens — caps the RESPONSE; it does not extend the context window.",
        "stop sequences — end generation at a marker; essential for structured formats.",
        "frequency/presence penalty — discourage repetition; over-applying degrades coherence.",
        "seed — improves reproducibility but doesn't guarantee it in a batched serving environment.",
      ],
    },
    {
      title: "Cost and latency model",
      points: [
        "Cost is per token, input and output priced differently — output is typically 3–5× input.",
        "Latency ≈ time-to-first-token (prefill, scales with prompt length) + tokens × time-per-token (decode, roughly constant per token).",
        "Streaming doesn't reduce total latency; it reduces PERCEIVED latency by showing the first token quickly.",
        "Prompt caching lets a repeated prefix (system prompt, few-shot examples, a large document) skip prefill — big win for chat and agents.",
        "Long conversations grow quadratically in cost if you resend everything; summarise or window the history.",
        "Batching increases throughput at the cost of per-request latency — the core serving trade-off.",
        "Smaller models are cheaper AND faster; routing easy requests to a small model is the highest-leverage cost lever.",
      ],
    },
    {
      title: "Why models get things wrong",
      points: [
        "Hallucination — trained to produce plausible text; no truth model, no calibrated uncertainty. Mitigate with retrieval, citations, and verification, not with 'don't hallucinate' in the prompt.",
        "Knowledge cutoff — no awareness of anything after training.",
        "Lost in the middle — recall is best at the start and end of a long context, weakest in the middle. Put critical instructions at the edges.",
        "Tokenisation artefacts — character counting, reversing strings, and arithmetic are hard because the model sees tokens, not characters or digits.",
        "Sycophancy — models tend to agree with a confidently-stated premise, including a wrong one.",
        "Prompt sensitivity — reordering or rewording can change the output materially; this is why evals matter more than eyeballing.",
        "Context rot — very long contexts degrade instruction-following even inside the nominal window.",
      ],
    },
    {
      title: "Model selection checklist",
      points: [
        "Task difficulty — start with the cheapest model that passes your eval, not the best model available.",
        "Context window needed — measure your actual p95 prompt, don't guess.",
        "Latency budget — interactive chat vs a batch pipeline are different problems.",
        "Structured output support — native JSON schema / tool calling beats prompt-and-parse.",
        "Multimodality — images, audio, video in or out.",
        "Deployment constraints — data residency, on-prem, and whether an open-weights model is required.",
        "Cost at expected volume — model the monthly bill at p50 and p95 token counts before committing.",
      ],
    },
  ],

  decisions: [
    {
      title: "RAG vs fine-tuning vs long context",
      options: [
        {
          name: "RAG",
          pick: ["The knowledge changes: docs, tickets, policies, product data.", "You need citations and auditability.", "Access control per document matters.", "You want to update knowledge without retraining."],
          cost: ["A retrieval stack to build and maintain; quality is capped by retrieval quality.", "Adds latency and prompt tokens per request."],
        },
        {
          name: "Fine-tuning",
          pick: ["Teaching FORM rather than facts: tone, format, a domain's phrasing, consistent structured output.", "Distilling a large model's behaviour into a smaller, cheaper one.", "Shortening prompts by baking in instructions."],
          cost: ["Needs a curated dataset and a retraining loop for every update.", "Doesn't reliably add facts, and can cause forgetting.", "Harder to audit — you can't point at a source."],
        },
        {
          name: "Long context (stuff everything in)",
          pick: ["The corpus genuinely fits and is small and stable.", "Prototyping, before building retrieval."],
          cost: ["Cost scales with every request; latency grows with prefill.", "Recall degrades in the middle of long contexts.", "Doesn't scale past the window, and gives no access control."],
        },
      ],
      verdict: "Facts that change → RAG. Style, format, or behaviour → fine-tuning. They're complementary: fine-tune for form, retrieve for facts.",
      topic: "fine-tuning",
    },
    {
      title: "Prompt engineering vs fine-tuning — try which first?",
      options: [
        {
          name: "Prompting (+ few-shot)",
          pick: ["Always first. Minutes to iterate, no data collection, no training cost.", "Requirements still changing.", "You can switch models freely."],
          cost: ["Long prompts cost tokens on every call.", "Ceiling on consistency for very specific formats or tone."],
        },
        {
          name: "Fine-tuning",
          pick: ["Prompting has plateaued below your eval bar AFTER real iteration.", "You have hundreds to thousands of high-quality examples.", "You want a smaller model to match a larger one's behaviour, cutting cost and latency."],
          cost: ["Data curation is the real work and the real expense.", "Locks you to a model; migrating means retraining.", "Needs an eval suite or you can't tell whether it helped."],
        },
      ],
      verdict: "Prompt first, always. Fine-tune only when you have evals proving prompting has plateaued, and data to train on.",
    },
    {
      title: "Big model vs small model (or routing)",
      options: [
        {
          name: "Large frontier model",
          pick: ["Hard reasoning, long multi-step tasks, ambiguous instructions.", "Quality dominates cost — low volume, high stakes."],
          cost: ["Highest cost and latency; often overkill for classification or extraction."],
        },
        {
          name: "Small/fast model",
          pick: ["Classification, extraction, routing, summarisation of short text.", "High volume where cost is the constraint.", "Tight latency budgets."],
          cost: ["Degrades on multi-step reasoning and long instructions; needs tighter prompts and more examples."],
        },
        {
          name: "Router / cascade",
          pick: ["Mixed traffic where most requests are easy.", "Try the small model, escalate on low confidence or a failed check."],
          cost: ["Complexity: you need a reliable difficulty signal and a verification step, plus two sets of evals."],
        },
      ],
      verdict: "Start on the strongest model to establish the quality bar, then move down until an eval fails. Routing pays off once volume is high and traffic is mixed.",
    },
    {
      title: "Temperature 0 vs higher",
      options: [
        {
          name: "Low (0–0.3)",
          pick: ["Extraction, classification, structured output, code, tool arguments.", "Anything where you'll compare against an expected answer."],
          cost: ["Repetitive and less creative; can get stuck in a bad phrasing.", "Still not fully deterministic — batching and GPU non-determinism cause drift."],
        },
        {
          name: "Higher (0.7–1.0)",
          pick: ["Brainstorming, copywriting, generating diverse candidates.", "Sampling several answers to vote or rank."],
          cost: ["More factual errors and format violations; harder to test and to reproduce a bug report."],
        },
      ],
      verdict: "Default to low for anything a program consumes; raise it only when diversity is the goal.",
    },
    {
      title: "Hosted API vs self-hosted open-weights",
      options: [
        {
          name: "Hosted API",
          pick: ["Default. No GPUs to run, best models available immediately, scaling handled.", "Small team, uncertain volume."],
          cost: ["Per-token cost at scale; data leaves your perimeter (check the retention terms).", "Vendor dependency — model versions get deprecated.", "Rate limits."],
        },
        {
          name: "Self-hosted",
          pick: ["Strict data residency or regulatory constraints.", "Very high, steady volume where GPU amortisation beats per-token pricing.", "You need weight-level control: custom fine-tunes, quantisation, unusual decoding."],
          cost: ["GPU capacity, serving infrastructure (vLLM/TGI), and the ops burden of both.", "Open-weights models generally trail frontier models on hard reasoning.", "Utilisation risk — idle GPUs still cost."],
        },
      ],
      verdict: "Hosted by default. Self-host for compliance, for genuinely high steady volume, or when you need control of the weights.",
    },
  ],

  qa: [
    {
      id: "llm-attention",
      q: "Explain self-attention.",
      a: "Attention lets each token look at every other token and decide how much each one matters for representing it. Each token is projected into three vectors: a query, a key, and a value. The relevance of token j to token i is the dot product of i's query with j's key; those scores are scaled by the square root of the head dimension, softmaxed into weights summing to one, and used to take a weighted sum of the value vectors. So the output for each position is a blend of the whole sequence, weighted by learned relevance — which is how the model resolves what 'it' refers to twenty words back. Multi-head attention runs several of these in parallel over different learned subspaces, so different heads can specialise. In a decoder, a causal mask sets attention to future positions to negative infinity, so a token can only see what came before, which is what makes generation autoregressive.",
      why: "It's the foundational mechanism; a clear explanation signals real understanding rather than API familiarity.",
      trap: "Skipping the √d scaling. Without it, dot products grow with dimension, softmax saturates, and gradients vanish — it's not a cosmetic detail.",
      followUps: ["Why is attention O(n²)?", "What does the causal mask change?", "What do different heads learn?"],
      depth: "Core",
      tags: ["transformers", "attention"],
      topic: "llm-fundamentals",
    },
    {
      id: "llm-quadratic",
      q: "Why is attention O(n²), and what do people do about it?",
      a: "Because every token attends to every other token, so the attention matrix has n² entries for a sequence of length n — doubling the context quadruples the compute and the memory for that matrix. That's the reason context windows were historically small and why long contexts are expensive. The mitigations fall into three groups. Exact but IO-efficient: FlashAttention doesn't reduce the FLOPs but avoids materialising the full matrix in slow high-bandwidth memory, tiling the computation in on-chip SRAM, which gives large real speedups and memory savings. Approximate: sparse and sliding-window attention have each token attend to a local neighbourhood plus a few global tokens, giving near-linear scaling at some quality cost. And architectural: grouped-query and multi-query attention shrink the KV cache by sharing key/value heads, which matters because at inference the KV cache, not the attention matrix, is usually the memory bottleneck.",
      why: "It connects the architecture to real cost and latency, which is the applied engineer's concern.",
      trap: "Saying FlashAttention makes attention sub-quadratic. It's exact and still O(n²) in compute; the win is memory movement.",
      followUps: ["What is the KV cache and why does it dominate memory?", "What does sliding-window attention give up?"],
      depth: "Advanced",
      tags: ["transformers", "performance"],
    },
    {
      id: "llm-tokens",
      q: "What is a token and why does it matter practically?",
      a: "Tokens are sub-word units produced by a learned vocabulary, usually via byte-pair encoding. Common words are a single token, rare words split into pieces, and the rough English rule is 4 characters or 0.75 words per token. It matters for four practical reasons. Cost and limits are counted in tokens, not characters, so you must count with the model's actual tokeniser rather than estimating. Non-English text and code tokenise far less efficiently — the same meaning in some languages can cost several times more tokens, which is a real fairness and cost issue. Character-level tasks are hard precisely because the model never sees characters: counting letters in a word or reversing a string fails not from lack of intelligence but because the unit of perception is wrong. And arithmetic suffers because numbers split inconsistently into tokens, so digit alignment isn't naturally represented.",
      why: "Tokenisation explains a whole category of surprising model failures and drives cost engineering.",
      trap: "Estimating tokens as words. For code, JSON, or non-Latin scripts you can be off by 2–3×.",
      followUps: ["Why can't models reliably count letters?", "Why does code cost more tokens than prose?"],
      depth: "Core",
      tags: ["tokenisation", "cost"],
      topic: "tokenization-embeddings",
    },
    {
      id: "llm-hallucination",
      q: "Why do LLMs hallucinate, and how do you reduce it?",
      a: "Because the training objective rewards plausible continuations, not true ones. The model has learned a distribution over text; when the prompt asks for something it doesn't know, the most probable continuation is still a fluent, confident-sounding answer, because that's what its training data looks like. It has no separate representation of 'I don't know' and its confidence is poorly calibrated to correctness. So you reduce it architecturally, not by asking nicely. Ground the model with retrieval so the facts are in the context, and require citations to spans of the retrieved text so an unsupported claim is detectable. Give it tools — a calculator, a database, a search API — so factual lookups aren't generated from weights. Explicitly permit and reward 'I don't know' in the prompt and in your evals. Verify afterwards: a second pass checking claims against sources, or schema validation for structured output. And lower temperature for factual tasks. What doesn't work is instructing 'do not hallucinate'.",
      why: "It's the defining reliability problem in applied LLM work and the answer reveals whether someone builds systems or writes prompts.",
      trap: "Treating it as a bug that a better prompt fixes. It's inherent to the objective; you engineer around it.",
      followUps: ["How would you detect an unsupported claim automatically?", "Why doesn't asking the model for its confidence work well?"],
      depth: "Core",
      tags: ["reliability", "hallucination"],
    },
    {
      id: "llm-context-window",
      q: "What is the context window, and what actually happens when you exceed it?",
      a: "It's the maximum number of tokens the model can attend to in one call, and it covers everything: system prompt, conversation history, retrieved documents, tool definitions and results, and the space reserved for the response. The key operational point is that `max_tokens` limits the output and does not extend the window — if your prompt fills the window there's no room to answer. What happens on overflow depends on the layer: the API usually returns an error, but application frameworks commonly truncate silently, dropping the oldest messages or the middle of a document, so you get a degraded answer with no signal that anything was lost. That silent failure is the thing to watch for. Also, a large nominal window doesn't mean uniform quality across it — recall is measurably weaker in the middle, so filling 200k tokens is rarely as good as retrieving the right 5k.",
      why: "Silent truncation is a common production bug, and the 'big window ≠ good recall' point is what separates practitioners.",
      trap: "Assuming a 200k-token window means you should use 200k tokens. Cost, latency, and middle-of-context recall all argue against it.",
      followUps: ["What is 'lost in the middle'?", "How do you manage a long chat history?"],
      depth: "Core",
      tags: ["context", "limits"],
    },
    {
      id: "llm-temperature",
      q: "What do temperature and top_p actually do?",
      a: "The model produces logits over the whole vocabulary at each step; these parameters shape how a token is chosen from that distribution. Temperature divides the logits before the softmax: below 1 it sharpens the distribution toward the most likely tokens, above 1 it flattens it, and at 0 you effectively take the argmax. Top_p is nucleus sampling: sort tokens by probability, keep the smallest set whose cumulative probability reaches p, and sample within it — so the candidate pool adapts to how confident the model is at each step, which is why it's often preferred to a fixed top_k. Conventional advice is to tune one of temperature or top_p, not both, since their effects compound confusingly. One caveat worth stating: temperature 0 is not a determinism guarantee in a hosted setting — batching, GPU non-determinism, and mixed precision all introduce variation, so you should never build a system that requires bit-identical outputs.",
      why: "These are the knobs everyone touches, and few can explain what they do to the distribution.",
      trap: "Believing temperature 0 gives reproducible output. It reduces variance; it doesn't eliminate it.",
      followUps: ["Why prefer top_p over top_k?", "What temperature would you use for JSON extraction?"],
      depth: "Core",
      tags: ["decoding", "sampling"],
    },
    {
      id: "llm-prefill-decode",
      q: "Why is the first token slow but the rest fast?",
      a: "Inference has two phases with different bottlenecks. Prefill processes the entire prompt in one pass; because all positions are known, it parallelises across the sequence and is compute-bound, and its cost grows with prompt length — that's your time-to-first-token. Decode then produces one token at a time, each depending on the last, so it can't be parallelised across the sequence; instead it re-reads the model weights and the KV cache for every single token, making it memory-bandwidth-bound rather than compute-bound. That's why decode speed is roughly constant per token regardless of prompt size, and why the practical levers differ: shortening the prompt or caching its prefix improves time-to-first-token, while shortening the output improves total latency. It also explains why batching helps throughput so much during decode — you amortise the weight reads across many sequences.",
      why: "It's the mental model behind every latency optimisation in LLM serving.",
      trap: "Assuming a bigger prompt slows every token. It mainly hurts the first one.",
      followUps: ["What is the KV cache?", "How does prompt caching change this?", "Why does batching help decode more than prefill?"],
      depth: "Advanced",
      tags: ["inference", "performance"],
      topic: "inference-optimization",
    },
    {
      id: "llm-kv-cache",
      q: "What is the KV cache and why does it matter?",
      a: "During generation, each new token attends to all previous tokens, which requires their key and value vectors. Recomputing those for the whole prefix at every step would be quadratic, so the server caches them and only computes K and V for the newest token — turning per-token work from O(n) into O(1) in the sequence length. The cost is memory: the cache scales with batch size × sequence length × layers × heads × head dimension, and for long contexts and large batches it dominates GPU memory, often more than the weights themselves. That makes it the primary constraint on how many concurrent requests a GPU can serve. The mitigations are architectural — grouped-query and multi-query attention share key/value heads across query heads, shrinking the cache several-fold — and systems-level, like PagedAttention in vLLM, which manages the cache in non-contiguous pages to eliminate fragmentation and enable prefix sharing between requests.",
      why: "It's the concept that connects model architecture to serving economics.",
      trap: "Thinking model weights dominate inference memory. At long context and high batch, the KV cache usually exceeds them.",
      followUps: ["How does grouped-query attention shrink it?", "What problem does PagedAttention solve?"],
      depth: "Advanced",
      tags: ["inference", "memory"],
      topic: "inference-optimization",
    },
    {
      id: "llm-embeddings",
      q: "What are embeddings and how do they differ from what an LLM generates?",
      a: "An embedding is a fixed-length dense vector representing the meaning of a piece of text, such that semantically similar texts land near each other, usually measured by cosine similarity. That's a different job from generation: an embedding model maps text to a point, while a generative model maps a prompt to a continuation. Embeddings power retrieval, semantic search, clustering, deduplication, recommendation, and classification over a fixed label set. Three practical points: you must use the same model for indexing and querying, since vectors from different models are not comparable; embeddings capture semantic similarity, which is not the same as relevance to a question, and that gap is exactly why hybrid search with keyword matching outperforms pure vector search; and dimension is a cost trade-off, with some models supporting Matryoshka truncation so you can shorten vectors and trade a little accuracy for much cheaper storage and search.",
      why: "Embeddings underpin RAG, and the 'similarity ≠ relevance' point is where naive systems fail.",
      trap: "Assuming high cosine similarity means the passage answers the question. A passage about the same topic scores high whether or not it contains the answer.",
      followUps: ["Why does hybrid search beat pure vector search?", "Can you mix embeddings from two models?"],
      depth: "Intermediate",
      tags: ["embeddings", "retrieval"],
      topic: "tokenization-embeddings",
    },
    {
      id: "llm-lost-middle",
      q: "What is 'lost in the middle'?",
      a: "An empirically observed pattern where a model's ability to use information from a long context depends on where that information sits: recall is strongest for content at the very beginning and very end, and noticeably weaker in the middle. It's a U-shaped curve, and it means a 200k-token window doesn't behave like uniform random-access memory. The practical consequences are concrete: put system instructions and the actual question at the edges rather than buried in the middle; when injecting retrieved documents, order them so the highest-scoring ones are at the start and end rather than in ranked order top-to-bottom; keep contexts as short as the task allows, which is one of the strongest arguments for good retrieval over stuffing everything in; and when you need reliability, restate the critical instruction at the end of the prompt. It's also why 'needle in a haystack' benchmarks became a standard way to characterise long-context models.",
      why: "It's a non-obvious, practically important finding that directly shapes prompt construction.",
      trap: "Treating advertised context length as a quality guarantee. Capacity and effective recall are different things.",
      followUps: ["How would you order retrieved chunks given this?", "What does a needle-in-a-haystack eval measure?"],
      depth: "Advanced",
      tags: ["context", "reliability"],
    },
    {
      id: "llm-structured-output",
      q: "How do you get reliable JSON out of a model?",
      a: "Use the platform feature rather than prompting and hoping. Native structured output or tool calling constrains decoding to a JSON schema — the sampler simply cannot emit a token that would violate the grammar — so the output is valid by construction rather than valid most of the time. That's categorically stronger than 'respond only in JSON', which fails on markdown fences, trailing commentary, and truncation. Beyond that: keep the schema flat and simple, since deeply nested schemas degrade quality; use enums instead of free text for anything you'll branch on; give every field a description, because those act as inline instructions; and use temperature near zero. Then still validate with Zod or Pydantic on receipt, because a schema-valid response can be semantically wrong, and handle the truncation case where a `max_tokens` cut produces valid-prefix-but-incomplete output. Include a retry with the validation error fed back, which recovers most residual failures.",
      why: "Structured output is the interface between an LLM and the rest of a system, so its reliability is a systems concern.",
      trap: "Parsing JSON out of a markdown code fence with a regex. That's the workaround from before constrained decoding existed.",
      followUps: ["What's the difference between JSON mode and a strict schema?", "How do you handle a truncated response?"],
      depth: "Intermediate",
      tags: ["structured-output", "reliability"],
      topic: "structured-output",
    },
    {
      id: "llm-finetune-vs-rag",
      q: "Fine-tuning or RAG — how do you choose?",
      a: "The dividing line is form versus facts. Fine-tuning changes how the model behaves: tone, output format, adherence to a house style, domain phrasing, or compressing a long instruction prompt into the weights. It's also the tool for distillation — training a small cheap model to imitate a large one on your task. What it does poorly is inject knowledge: facts learned in fine-tuning are diffuse, unverifiable, can't be attributed to a source, and require a retraining cycle to update. RAG is the opposite: knowledge lives outside the model, so it updates instantly, can be permission-filtered per user, and supports citations, which makes the system auditable. The real answer in production is usually both — retrieve for facts, fine-tune for form — and the ordering matters: exhaust prompting first, then add retrieval, and only fine-tune when you have evals showing you've plateaued and you have the data to train on.",
      why: "It's the single most common applied-AI design question and a clean test of judgement.",
      trap: "Fine-tuning to teach the model your documentation. It'll produce confident, unattributable, stale answers — this is the classic expensive mistake.",
      followUps: ["What is LoRA and why is it the default?", "How would you combine both in one system?"],
      depth: "Core",
      tags: ["fine-tuning", "rag"],
      topic: "fine-tuning",
    },
    {
      id: "llm-lora",
      q: "What is LoRA and why is it used instead of full fine-tuning?",
      a: "Low-Rank Adaptation freezes the base model's weights and injects small trainable low-rank matrices alongside them, on the observation that the weight update needed to adapt a model to a task is itself low-rank. So instead of training billions of parameters you train a few million — often under 1% — which cuts GPU memory dramatically, makes training feasible on modest hardware, and produces adapters of tens of megabytes rather than a full model copy. The operational benefits are as important as the training ones: you can host one base model and swap adapters per customer or per task, and you can roll back by unloading an adapter. QLoRA extends this by quantising the frozen base to 4-bit, letting quite large models be fine-tuned on a single GPU. The trade-offs are that quality on tasks requiring deep behavioural change can trail full fine-tuning, and rank and target-module choices are hyperparameters that matter.",
      why: "LoRA is the default fine-tuning method in practice, so familiarity is expected in any AI engineering role.",
      trap: "Describing it as training a smaller model. The base model is unchanged and full-size; you train a small additive update.",
      followUps: ["What does QLoRA add?", "How do you serve many adapters over one base model?"],
      depth: "Advanced",
      tags: ["fine-tuning", "training"],
      topic: "fine-tuning",
    },
    {
      id: "llm-rlhf",
      q: "How does a base model become a chat assistant?",
      a: "Three stages. Pretraining on a very large text corpus with next-token prediction produces a base model that completes text but doesn't follow instructions — prompt it with a question and it may continue with more questions, because that's what documents look like. Supervised fine-tuning on curated instruction-response pairs teaches the assistant format and the habit of answering. Then a preference-alignment stage tunes it toward outputs humans prefer: classic RLHF trains a reward model on human comparisons between candidate responses and optimises the policy against it with PPO, while DPO achieves similar results by optimising directly on preference pairs without a separate reward model, which is simpler and now widely used. Constitutional AI variants replace some human labels with model-generated critiques against written principles. The alignment stage is what produces helpfulness, refusal behaviour, and tone — and also sycophancy, since agreeing with the user is often preferred by raters.",
      why: "It explains where model behaviour, refusals, and personality actually come from.",
      trap: "Thinking RLHF adds knowledge. Knowledge comes from pretraining; alignment shapes behaviour and style.",
      followUps: ["Why is DPO simpler than PPO-based RLHF?", "Where does sycophancy come from?"],
      depth: "Advanced",
      tags: ["training", "alignment"],
    },
    {
      id: "llm-quantization",
      q: "What is quantisation and what does it cost you?",
      a: "Storing and computing weights at lower numerical precision — 16-bit down to 8-bit or 4-bit — to shrink memory and speed up inference. Because decode is memory-bandwidth-bound, halving the bytes read per token roughly doubles throughput, and a model that needed multiple GPUs at 16-bit may fit on one at 4-bit, which changes the economics entirely. The cost is accuracy: 8-bit is usually near-lossless, 4-bit is typically acceptable with a modest quality drop, and below that degradation becomes obvious, with the loss falling hardest on exactly the hard reasoning and long-context tasks you'd notice. Methods differ in how they protect sensitive weights — GPTQ and AWQ do post-training quantisation with calibration data, while quantisation-aware training bakes it into fine-tuning for better results at more cost. The honest framing is that it's a quality-for-capacity trade, so you should measure it on your own eval rather than trusting a benchmark table.",
      why: "It's the main lever for self-hosting economics and shows the candidate thinks about deployment.",
      trap: "Assuming 4-bit is free. It's usually acceptable, not lossless, and the loss concentrates on the hardest cases.",
      followUps: ["Why does quantisation speed up decode more than prefill?", "What does QAT buy over post-training quantisation?"],
      depth: "Advanced",
      tags: ["inference", "optimisation"],
      topic: "inference-optimization",
    },
    {
      id: "llm-cost-reduction",
      q: "Your LLM feature costs too much. What do you do, in order?",
      a: "Measure first: log tokens in and out per request and find where they concentrate — it's usually a small number of endpoints or an oversized system prompt repeated on every call. Then, roughly in order of leverage: route easy requests to a smaller model and keep the large one for hard cases, which is typically the biggest single win; enable prompt caching so a stable system prompt and few-shot block skip prefill on every call; cut prompt size by retrieving fewer, better chunks rather than stuffing context, and by trimming verbose instructions; cap and shape output, since output tokens cost several times input, and asking for structured output rather than prose often halves it; cache complete responses for repeated identical queries; batch anything that isn't interactive, since batch APIs are substantially cheaper; and truncate or summarise conversation history rather than resending it all. Consider fine-tuning a small model last — it's a real lever but only pays back at volume.",
      why: "Cost engineering is a large part of applied LLM work and this ordering shows practical experience.",
      trap: "Jumping straight to self-hosting. It rarely beats a hosted small model until volume is both high and steady.",
      followUps: ["How does prompt caching actually work?", "How do you decide the routing threshold?"],
      depth: "Advanced",
      tags: ["cost", "operations"],
    },
    {
      id: "llm-eval",
      q: "How do you know a prompt change made things better?",
      a: "You need an eval set, because eyeballing a few outputs is how teams ship regressions. Build a dataset of real inputs — production traffic where possible, including the failure cases that prompted the change — with expected outputs or graded criteria. Then pick a grader appropriate to the task: exact match or F1 for extraction and classification, schema validity for structured output, and an LLM-as-judge with an explicit rubric for open-ended generation, validated against human labels on a sample so you know the judge itself is trustworthy. Run the eval on every prompt or model change in CI, and report per-category scores rather than a single number, since an aggregate can hide a regression in one important slice. Two practical cautions: keep a held-out set you don't iterate against, or you'll overfit the prompt to your eval, and track cost and latency alongside quality so you notice when an improvement tripled the bill.",
      why: "Evaluation discipline is the clearest separator between people who've shipped LLM features and people who've demoed them.",
      trap: "Testing on the same handful of examples you used to write the prompt. That measures memorisation of your examples, not generalisation.",
      followUps: ["When is LLM-as-judge unreliable?", "How do you build an eval set from production traffic?"],
      depth: "Intermediate",
      tags: ["evaluation"],
      topic: "ml-evaluation",
    },
    {
      id: "llm-moe",
      q: "What is a mixture-of-experts model?",
      a: "An architecture where the feed-forward block of each layer is replaced by many parallel 'expert' networks plus a router that sends each token to only a small number of them — often two. The result is that total parameter count can be very large while the parameters actually used per token stay small, so you get the capacity benefits of a big model at roughly the inference compute of a much smaller one. That's why several frontier and open-weights models are MoE. The costs are on the systems side: all experts must be resident in memory even though only a couple are active, so memory footprint tracks total parameters rather than active ones, which makes serving expensive; routing can be unbalanced, leaving some experts overloaded and others idle, so training uses auxiliary load-balancing losses; and distributed serving needs careful expert placement to avoid communication bottlenecks.",
      why: "MoE is now common enough that understanding the compute-versus-memory distinction is expected.",
      trap: "Saying an MoE model is cheaper to run overall. It's cheaper in compute per token, not in memory — you still hold every expert.",
      followUps: ["Why do MoE models need load-balancing losses?", "How does this change GPU sizing?"],
      depth: "Advanced",
      tags: ["architecture"],
    },
  ],

  pitfalls: [
    "Don't call hallucination a bug to be prompted away — explain it as a property of the training objective and describe grounding, tools, and verification.",
    "Don't say temperature 0 is deterministic — say it reduces variance but batching and GPU non-determinism remain.",
    "Don't estimate tokens as words — count with the model's tokeniser, especially for code and non-English text.",
    "Don't claim `max_tokens` extends the context window — it caps the output within it.",
    "Don't propose fine-tuning to add facts — that's what retrieval is for.",
    "Don't treat a large context window as uniform memory — recall degrades in the middle.",
    "Don't say FlashAttention makes attention sub-quadratic — it's exact and IO-efficient.",
    "Don't prompt-and-regex for JSON when constrained decoding or tool calling is available.",
  ],

  numbers: [
    { label: "Tokens per English word", value: "~1.3", note: "≈ 4 characters per token; far higher for code and non-Latin scripts." },
    { label: "Output vs input token price", value: "~3–5× more", note: "Shaping output length is a bigger lever than shortening prompts." },
    { label: "Attention complexity", value: "O(n²)", note: "In sequence length — the reason long context is expensive." },
    { label: "LoRA trainable parameters", value: "< 1% of base", note: "Adapters are tens of MB, not tens of GB." },
    { label: "Typical temperature for extraction", value: "0–0.2", note: "Raise only when diversity is the goal." },
    { label: "Quantisation quality", value: "8-bit ≈ lossless, 4-bit usable", note: "Below 4-bit degrades noticeably on hard tasks." },
  ],

  relatedTopics: [
    "llm-fundamentals",
    "tokenization-embeddings",
    "fine-tuning",
    "inference-optimization",
    "prompting-fundamentals",
    "structured-output",
    "ml-evaluation",
    "rag-fundamentals",
  ],
};
