import type { Area } from "../types";

export const mlFoundations: Area = {
  slug: "ml-foundations",
  title: "ML Foundations",
  icon: "📈",
  stream: "AI Engineering",
  blurb:
    "Bias-variance, the metrics that matter when classes are imbalanced, why accuracy lies, and the leakage bugs that make offline results meaningless.",

  mustKnow: [
    "Supervised learning has labels; unsupervised finds structure without them; reinforcement learning optimises actions against a reward signal.",
    "Overfitting is memorising the training set — low training error, high test error. Underfitting is too simple a model — high error on both.",
    "Bias-variance: high bias means the model is too simple to capture the pattern; high variance means it's too sensitive to the specific training sample.",
    "Never evaluate on data you trained on. Split into train/validation/test, and touch the test set once.",
    "Accuracy is misleading on imbalanced data — 99% accuracy is trivial when 99% of cases are negative.",
    "Precision is 'of what I flagged, how much was right'; recall is 'of what was actually there, how much did I catch'. They trade off.",
    "Data leakage is when information unavailable at prediction time reaches training — it produces excellent offline metrics and a model that fails in production.",
    "Feature scaling matters for distance- and gradient-based models (kNN, SVM, neural nets, linear models with regularisation); tree models don't care.",
    "Cross-validation gives a more reliable estimate than one split, but must respect time order for time-series data.",
    "Correlation is not causation — a model that predicts well does not tell you what to change.",
  ],

  sheets: [
    {
      title: "Classification metrics",
      points: [
        "Confusion matrix: TP, FP, TN, FN — every metric derives from these four.",
        "Precision = TP / (TP + FP) — how trustworthy a positive prediction is. Optimise when false positives are expensive (spam filter blocking real mail).",
        "Recall = TP / (TP + FN) — how much of the real thing you catch. Optimise when false negatives are expensive (cancer screening, fraud).",
        "F1 = harmonic mean of precision and recall — a single number when both matter and classes are imbalanced.",
        "ROC-AUC — ranking quality across all thresholds; over-optimistic on heavily imbalanced data.",
        "PR-AUC — better than ROC-AUC when positives are rare.",
        "Accuracy — only meaningful when classes are roughly balanced AND errors cost the same.",
        "The threshold is a business decision, not a model property — pick it from the cost of each error type.",
      ],
    },
    {
      title: "Regression metrics",
      points: [
        "MAE — mean absolute error; same units as the target, robust to outliers.",
        "MSE / RMSE — squares errors, so it punishes large mistakes disproportionately. RMSE is in target units.",
        "R² — proportion of variance explained; can be negative for a model worse than predicting the mean.",
        "MAPE — percentage error; breaks when actual values approach zero.",
        "Choose by what the error costs: if one big miss is much worse than several small ones, use RMSE; otherwise MAE.",
      ],
    },
    {
      title: "Data leakage — where it hides",
      points: [
        "Scaling or imputing using statistics computed over the full dataset before splitting — the test set influenced the transform.",
        "A feature that is a proxy for the label ('account_closed_date' predicting churn).",
        "Time travel: using future information for a past prediction; any time-series split must be chronological.",
        "Duplicate or near-duplicate rows spanning train and test.",
        "Target encoding computed on the full dataset rather than inside each fold.",
        "Group leakage: the same patient/user appearing in both train and test in different rows — split by group.",
        "The tell: suspiciously high offline performance, and a large drop in production.",
      ],
    },
    {
      title: "Fixing over- and underfitting",
      points: [
        "Overfitting → more data; simpler model; regularisation (L1/L2, dropout, early stopping); data augmentation; fewer features; cross-validation to detect it.",
        "Underfitting → more expressive model; better features; less regularisation; train longer.",
        "L1 (Lasso) drives coefficients to zero — implicit feature selection. L2 (Ridge) shrinks them smoothly.",
        "Learning curves diagnose which you have: a large train/validation gap means variance; both high and converged means bias.",
        "More data reliably helps variance; it does not help bias.",
      ],
    },
    {
      title: "Imbalanced data",
      points: [
        "Don't use accuracy. Use precision/recall, F1, or PR-AUC.",
        "Resampling: oversample the minority (SMOTE) or undersample the majority — apply only to the training fold, never to validation or test.",
        "Class weights in the loss function — usually simpler and safer than resampling.",
        "Adjust the decision threshold rather than the data; the model's ranking may already be fine.",
        "Consider whether it's really an anomaly-detection problem rather than classification.",
        "Always report the base rate so the metric can be judged in context.",
      ],
    },
  ],

  decisions: [
    {
      title: "Precision vs recall — which do you optimise?",
      options: [
        {
          name: "Precision",
          pick: ["A false positive is costly or damaging: blocking a legitimate transaction, flagging a real email as spam, auto-rejecting a good applicant.", "Human review capacity is limited, so flagged items must be worth reviewing."],
          cost: ["You miss true cases — lower recall."],
        },
        {
          name: "Recall",
          pick: ["A false negative is costly: missed disease, missed fraud, missed safety issue.", "There's a cheap second stage (human review) that filters false positives."],
          cost: ["More false alarms, which cause alert fatigue and erode trust in the system."],
        },
      ],
      verdict: "Decide from the cost of each error type, then set the threshold to match. Reporting both plus the threshold is the complete answer.",
      topic: "ml-evaluation",
    },
    {
      title: "Simple model vs deep learning",
      options: [
        {
          name: "Classical (logistic regression, gradient-boosted trees)",
          pick: ["Tabular data — gradient boosting still generally beats deep learning here.", "Limited data.", "You need interpretability or regulatory explainability.", "Fast to train, cheap to serve, easy to debug."],
          cost: ["Needs feature engineering.", "Doesn't handle raw images, audio, or long text well."],
        },
        {
          name: "Deep learning",
          pick: ["Unstructured data: images, audio, text.", "Very large datasets where representation learning pays off.", "Transfer learning from a pretrained model."],
          cost: ["Data- and compute-hungry.", "Harder to interpret, debug, and serve.", "More hyperparameters and more ways to fail silently."],
        },
      ],
      verdict: "Start with a simple baseline always — it sets the bar and often wins on tabular data. Deep learning earns its cost on unstructured inputs.",
      topic: "ml-basics",
    },
    {
      title: "Batch vs real-time inference",
      options: [
        {
          name: "Batch",
          pick: ["Predictions can be precomputed: daily churn scores, nightly recommendations, risk segmentation.", "Cheapest and simplest — no serving latency budget, easy to backfill and re-run."],
          cost: ["Predictions are stale between runs.", "Can't react to fresh signals within a session."],
        },
        {
          name: "Real-time",
          pick: ["The input only exists at request time: fraud on this transaction, ranking for this query, personalisation on this session."],
          cost: ["Latency budget constrains model size and feature lookups.", "Needs a feature store and online/offline consistency, or training-serving skew appears.", "More infrastructure and more failure modes."],
        },
      ],
      verdict: "Batch unless the prediction genuinely depends on request-time input. Many 'real-time' requirements are satisfied by precomputed scores refreshed hourly.",
      topic: "model-serving",
    },
  ],

  qa: [
    {
      id: "ml-bias-variance",
      q: "Explain the bias-variance tradeoff.",
      a: "Prediction error decomposes into bias, variance, and irreducible noise. Bias is error from wrong assumptions — the model is too simple to represent the true relationship, so it's consistently off regardless of the data it sees, like fitting a straight line to a curve. Variance is error from sensitivity to the particular training sample — the model is expressive enough to fit noise, so it gives very different answers when trained on different samples of the same population. The tradeoff is that increasing model complexity reduces bias and increases variance, so there's a sweet spot. You diagnose which you have from learning curves: a large gap between training and validation error means variance, while both being high and close together means bias. The fixes differ, which is why the diagnosis matters — more data reduces variance and does nothing for bias, so throwing data at an underfitting model is wasted effort. Worth noting that very large modern models complicate the classic U-shaped picture, with double descent showing test error falling again past the interpolation threshold.",
      why: "It's the framework for diagnosing why a model underperforms, rather than randomly changing hyperparameters.",
      trap: "Describing it as 'a balance between simple and complex' without saying how you'd tell which side you're on.",
      followUps: ["How do learning curves distinguish them?", "Why doesn't more data fix bias?"],
      depth: "Core",
      tags: ["fundamentals"],
      topic: "ml-basics",
    },
    {
      id: "ml-accuracy-trap",
      q: "Your fraud model has 99.5% accuracy. Is it good?",
      a: "Almost certainly not — that number is meaningless without the base rate. If 0.5% of transactions are fraudulent, a model that predicts 'not fraud' for everything achieves 99.5% accuracy while catching zero fraud, which is worse than useless because it also gives false confidence. On imbalanced problems you need metrics that look at the minority class: precision, which tells you how many flagged transactions were genuinely fraudulent and therefore whether your review team's time is being wasted; recall, which tells you what fraction of actual fraud you caught and therefore your exposure; and PR-AUC, which summarises the tradeoff across thresholds and is more informative than ROC-AUC when positives are rare, because ROC-AUC's false positive rate has a huge denominator and stays flatteringly low. Beyond metrics, the right framing is monetary: a missed fraud costs the transaction value, while a false positive costs a blocked customer and a support contact, so you set the threshold where the expected costs balance rather than where some metric peaks.",
      why: "The imbalance trap is the most common ML evaluation mistake and this question surfaces it immediately.",
      trap: "Answering yes. The question is designed to see whether you ask for the base rate.",
      followUps: ["Why is ROC-AUC optimistic here?", "How would you choose the threshold?"],
      depth: "Core",
      tags: ["metrics", "evaluation"],
      topic: "ml-evaluation",
    },
    {
      id: "ml-leakage",
      q: "What is data leakage and how do you catch it?",
      a: "Leakage is when information that wouldn't be available at prediction time influences training, so the model learns from something it won't have in production. The result is excellent offline metrics and a model that collapses on deployment, which is why it's so damaging — it passes every check you were running. Common forms: fitting a scaler or imputer on the full dataset before splitting, so the test set's statistics influenced the transform; a feature that's a proxy for the label, like an `account_closed_date` when predicting churn; time travel, using information from after the prediction point; duplicate rows spanning train and test; target encoding computed globally rather than within each fold; and group leakage, where the same user or patient appears in both splits. You catch it by being suspicious of unusually good results, by checking feature importance for anything implausibly predictive, by splitting before doing any transformation and putting all preprocessing inside a pipeline fitted per fold, and by splitting chronologically for anything time-dependent. The strongest check is asking, for each feature, whether you'd genuinely have it at prediction time.",
      why: "It's the single most common reason an offline-good model fails in production.",
      trap: "Only thinking of the obvious label-proxy case. Preprocessing before splitting is far more common and much subtler.",
      followUps: ["Why must scaling happen inside the CV fold?", "How do you split time-series data?"],
      depth: "Intermediate",
      tags: ["evaluation", "pitfalls"],
      topic: "ml-evaluation",
    },
    {
      id: "ml-overfitting",
      q: "How do you know a model is overfitting, and what do you do?",
      a: "The signature is a large and growing gap between training and validation performance — training error keeps falling while validation error plateaus and then rises. Plotting both across epochs or model complexity makes it obvious, which is why learning curves are the first diagnostic. The remedies come in three families. Reduce effective capacity: a simpler model, fewer features, or regularisation, where L2 shrinks coefficients smoothly and L1 drives some to exactly zero and so performs feature selection; for neural networks, dropout and early stopping, where you stop at the validation minimum rather than the training minimum. Increase effective data: more examples if you can get them, or data augmentation, which is why image models rotate and crop. And improve the evaluation so you can trust the signal: k-fold cross-validation gives a more stable estimate than a single split, especially on small datasets. The important discipline around all of this is that the test set is used once, at the end — if you tune against it you've made it a validation set and your final number is optimistic.",
      why: "It's the core practical skill and the 'test set is used once' point is a discipline many candidates lack.",
      trap: "Tuning hyperparameters against the test set. Every decision you make from it leaks into your reported performance.",
      followUps: ["L1 or L2, and why?", "Why does early stopping regularise?"],
      depth: "Core",
      tags: ["training"],
      topic: "ml-basics",
    },
    {
      id: "ml-cross-validation",
      q: "Why cross-validate instead of using one train/test split?",
      a: "Because a single split gives one estimate whose value depends heavily on which rows happened to land in the test set, and on a small dataset that variance can be large enough to make model comparison meaningless. K-fold cross-validation partitions the data into k parts, trains k times holding out each part in turn, and averages — so every row is used for both training and evaluation, and you get a mean plus a standard deviation, which tells you whether a 2% difference between two models is real or noise. Stratified k-fold preserves class proportions in each fold, which matters for imbalanced data. Two important caveats. For time-series you cannot shuffle, because training on future data to predict the past is leakage; you use forward-chaining splits where each fold trains on everything before a cut point. And when rows are grouped — multiple records per user or patient — you need GroupKFold so the same entity doesn't appear in both training and validation, or you'll measure memorisation rather than generalisation. The cost is k times the training compute, so on very large datasets a single large held-out set is often sufficient.",
      why: "The time-series and grouping caveats are what separate someone who's applied it from someone who's read about it.",
      trap: "Using standard k-fold on time-series data. Shuffling destroys temporal order and produces leakage.",
      followUps: ["How do you cross-validate a forecasting model?", "When is a single split good enough?"],
      depth: "Intermediate",
      tags: ["evaluation"],
      topic: "ml-evaluation",
    },
    {
      id: "ml-feature-engineering",
      q: "What does feature engineering involve, and does it still matter?",
      a: "It's transforming raw data into representations that expose the signal to the model, and it still matters a great deal for tabular problems — which is most business ML. Typical work: encoding categoricals, where one-hot suits low cardinality and target or embedding encoding suits high cardinality; scaling numeric features for distance- and gradient-based models, though tree models are invariant to monotonic transforms and don't need it; extracting components from timestamps, since a raw epoch is useless while hour-of-day and day-of-week are often strongly predictive; creating ratios and interactions that encode domain knowledge the model would otherwise have to discover; and handling missing values, where the fact of missingness is often itself informative and worth its own indicator feature. Deep learning reduced the need for it on unstructured data — CNNs learn visual features and transformers learn text representations — but on tabular data, gradient-boosted trees with good features still typically beat neural networks. The critical operational point is that every transformation must be reproducible at serving time with identical logic, or you get training-serving skew.",
      why: "It's where most of the practical gain on real business problems comes from.",
      trap: "Saying deep learning made it obsolete. That's true for images and text, not for the tabular data most companies actually have.",
      followUps: ["How do you handle a high-cardinality categorical?", "What is training-serving skew?"],
      depth: "Intermediate",
      tags: ["features"],
      topic: "ml-basics",
    },
    {
      id: "ml-drift",
      q: "A model that performed well is getting worse. Why?",
      a: "Most likely drift, and it's worth distinguishing the kinds because they need different responses. Data drift means the input distribution has shifted — a new customer segment, a new device type, a changed upstream schema — so the model is now extrapolating outside what it saw. Concept drift means the relationship between inputs and the target has changed: user behaviour shifted, a competitor changed pricing, or a fraud ring adapted to your detection, so yesterday's mapping is simply wrong now. There's also the self-inflicted case where the model influences its own inputs — a recommender that only shows certain items stops receiving data about the others, creating a feedback loop. Before assuming drift, though, rule out plainer causes: an upstream pipeline change silently altering a feature, a broken join producing nulls, or training-serving skew from a transformation implemented differently in the two paths. The response is monitoring you should have had in place — track feature distributions and prediction distributions, not just accuracy, since ground-truth labels usually arrive late — plus scheduled retraining and alerting on distribution shift.",
      why: "Models degrade in production, and the answer shows whether someone has operated one rather than only trained one.",
      trap: "Jumping to retraining. If the cause is a broken feature pipeline, retraining bakes the bug into the model.",
      followUps: ["How do you monitor when labels arrive weeks later?", "What is a feedback loop and why is it dangerous?"],
      depth: "Advanced",
      tags: ["production", "monitoring"],
      topic: "ml-evaluation",
    },
    {
      id: "ml-train-serve-skew",
      q: "What is training-serving skew?",
      a: "When the features a model sees in production differ from those it was trained on, so the model is effectively being asked a different question than the one it learned. The most common cause is having two implementations of the same transformation — a pandas pipeline for training and hand-written service code for inference — which inevitably diverge in edge cases: different null handling, a different default category, a timezone difference, a rounding difference. Another cause is time-based: a training feature computed with a full day's aggregate that at serving time is only partially available. And a subtle one is when the serving path reads from a different source than the training path, so definitions drift independently. The fixes are structural rather than vigilant. Share one implementation between training and serving, either by packaging the transformation pipeline with the model or by using a feature store that computes a feature once and serves both paths. Log the actual feature values used at inference and compare their distributions to training. And validate by scoring the same records through both paths and asserting the outputs match.",
      why: "It's the production ML bug that's hardest to detect, because both halves look correct in isolation.",
      trap: "Assuming the same logic reimplemented in two places will stay in sync. It won't, and the divergence is silent.",
      followUps: ["How does a feature store prevent this?", "How would you detect it in production?"],
      depth: "Advanced",
      tags: ["production", "mlops"],
      topic: "model-serving",
    },
    {
      id: "ml-explainability",
      q: "How do you explain a model's prediction?",
      a: "Distinguish global from local explanations. Global means understanding the model overall — feature importance from a tree model, coefficients from a linear model, partial dependence plots showing how a prediction changes as one feature varies. Local means explaining one prediction, which is what a regulator or a rejected customer actually wants, and the standard tools are SHAP, which attributes the prediction to each feature with a game-theoretic grounding and desirable consistency properties, and LIME, which fits a simple local surrogate around the point. The caveats matter and are what senior candidates add. Tree-based impurity importance is biased toward high-cardinality features, so permutation importance or SHAP is more trustworthy. Correlated features split their attributed credit arbitrarily, so you can't read importance as causal. And an explanation describes what the model did, not why the world works that way — a model may rely on a proxy for a protected attribute and SHAP will faithfully report the proxy. Where explainability is a hard requirement, an intrinsically interpretable model like logistic regression or a shallow tree is often the better answer than explaining a black box after the fact.",
      why: "Explainability is now a regulatory and product requirement in many domains, and the caveats show real understanding.",
      trap: "Presenting SHAP values as causal. They explain the model's behaviour, not the underlying mechanism.",
      followUps: ["Why is impurity-based importance misleading?", "When would you choose an interpretable model instead?"],
      depth: "Advanced",
      tags: ["interpretability"],
      topic: "ml-evaluation",
    },
    {
      id: "ml-baseline",
      q: "What's the first thing you do on a new ML problem?",
      a: "Establish a baseline, and before that, establish whether ML is the right tool at all — a rules engine or a SQL query is often sufficient, cheaper, and easier to explain. Assuming ML fits, the first steps are to define the target precisely, decide the metric from the business cost of each error type, and build the simplest possible model end to end: for classification, predicting the majority class, then logistic regression or gradient-boosted trees on the obvious features. That baseline does three things. It sets a bar, so you know whether your sophisticated model is actually adding anything — a surprising amount of published improvement disappears against a well-tuned simple baseline. It exercises the whole pipeline, surfacing data quality problems, leakage, and label issues while they're still cheap to fix. And it gives you something deployable early, so you learn from real traffic rather than from your assumptions. Only then do you invest in better features and more complex models, measuring each step against the baseline.",
      why: "Baseline-first is the practice that most distinguishes people who ship ML from people who experiment with it.",
      trap: "Starting with the most sophisticated model. You then have no idea whether the complexity is buying anything.",
      followUps: ["When is ML the wrong tool?", "How do you choose the metric?"],
      depth: "Intermediate",
      tags: ["process"],
      topic: "ml-basics",
    },
  ],

  pitfalls: [
    "Don't quote accuracy without the base rate — on imbalanced data it's meaningless.",
    "Don't scale or impute before splitting — fit the transform inside each fold.",
    "Don't shuffle time-series data for cross-validation — split chronologically.",
    "Don't tune against the test set — that makes your final number optimistic.",
    "Don't say deep learning made feature engineering obsolete — not for tabular data.",
    "Don't retrain in response to degradation before ruling out a broken feature pipeline.",
    "Don't present SHAP or feature importance as causal.",
    "Don't skip the simple baseline — without it you can't tell whether complexity helped.",
  ],

  numbers: [
    { label: "Typical split", value: "60/20/20 or 80/10/10", note: "Larger test sets matter more on small data." },
    { label: "k in k-fold", value: "5 or 10", note: "Higher k costs more compute for a modestly better estimate." },
    { label: "Test set usage", value: "Once", note: "Every additional look leaks information into your reported result." },
    { label: "Tabular winner", value: "Gradient-boosted trees", note: "Still generally beats deep learning on tabular data." },
  ],

  relatedTopics: [
    "ml-basics",
    "ml-evaluation",
    "model-serving",
    "statistics-basics",
    "probability-basics",
    "bayes-theorem",
    "vectors-matrices",
    "pipelines",
  ],
};
