import type { Area } from "../types";

export const networking: Area = {
  slug: "networking",
  title: "Networking & HTTP",
  icon: "🌐",
  stream: "CS Core",
  blurb:
    "What happens when you type a URL, TCP vs UDP, TLS, and the HTTP semantics that every backend interview eventually reaches.",

  mustKnow: [
    "TCP is connection-oriented, ordered, and reliable via acknowledgements and retransmission. UDP is fire-and-forget: no handshake, no ordering, no retransmission.",
    "The TCP handshake is three packets (SYN, SYN-ACK, ACK) — one round trip before any data. TLS 1.3 adds one more; TLS 1.2 adds two.",
    "DNS resolves a name to an IP, walking resolver → root → TLD → authoritative, with caching at every layer governed by TTL.",
    "HTTP is stateless: every request carries everything needed. Cookies and tokens are how state is simulated.",
    "HTTP/1.1 has head-of-line blocking per connection; HTTP/2 multiplexes streams over one connection; HTTP/3 runs over QUIC/UDP to remove TCP-level head-of-line blocking.",
    "TLS gives confidentiality, integrity, and authentication of the server — via a certificate chain your client verifies against trusted roots.",
    "Latency is bounded by physics: a cross-continent round trip is tens of milliseconds and no amount of bandwidth fixes it.",
    "An idle TCP connection is cheap; establishing one is not — which is why connection reuse and keep-alive matter so much.",
    "A load balancer at L4 routes by IP/port; at L7 it can route on path, header, or cookie and terminate TLS.",
    "Timeouts are mandatory on every network call — the default in most clients is 'wait forever', which is how one slow dependency takes down a fleet.",
  ],

  sheets: [
    {
      title: "What happens when you type a URL",
      points: [
        "1. Browser cache / HSTS check → may upgrade to HTTPS immediately.",
        "2. DNS resolution: browser cache → OS cache → resolver → root → TLD → authoritative.",
        "3. TCP handshake (SYN, SYN-ACK, ACK) — one RTT.",
        "4. TLS handshake — 1 RTT in TLS 1.3, 2 in 1.2; certificate chain verified against trusted roots; session resumption can make it 0-RTT.",
        "5. HTTP request sent; server processes; response returns.",
        "6. Browser parses HTML, discovers subresources, and fetches them (often over the same connection with HTTP/2).",
        "7. Render: DOM + CSSOM → render tree → layout → paint → composite.",
        "8. JS executes; hydration if server-rendered.",
      ],
    },
    {
      title: "TCP vs UDP",
      points: [
        "TCP: handshake, ordering, acknowledgement, retransmission, flow control, congestion control.",
        "UDP: a datagram with a checksum. No connection, no ordering, no retransmission, no congestion control.",
        "TCP head-of-line blocking: one lost packet stalls everything behind it, even for independent streams.",
        "UDP is right when late data is worthless: live audio/video, gaming, DNS queries, telemetry.",
        "QUIC (HTTP/3) is built on UDP and re-implements reliability per stream, so one lost packet doesn't stall other streams.",
        "TCP slow start means a new connection doesn't reach full throughput immediately — another reason to reuse connections.",
      ],
    },
    {
      title: "HTTP versions",
      points: [
        "HTTP/1.0 — one request per connection.",
        "HTTP/1.1 — keep-alive, pipelining (rarely usable), chunked transfer. Browsers open ~6 connections per host to work around head-of-line blocking.",
        "HTTP/2 — binary framing, multiplexed streams over ONE connection, header compression (HPACK), server push (now largely deprecated).",
        "HTTP/2 still suffers TCP-level head-of-line blocking: a lost packet stalls all streams.",
        "HTTP/3 — QUIC over UDP; per-stream reliability, faster handshake (often 0-RTT resumption), connection migration across network changes.",
        "Practical consequence: domain sharding and asset concatenation were HTTP/1.1 workarounds and are counterproductive on HTTP/2+.",
      ],
    },
    {
      title: "TLS essentials",
      points: [
        "Handshake: negotiate version and cipher, server presents its certificate chain, key exchange (ECDHE) establishes a shared secret, then symmetric encryption for the session.",
        "Certificate verification: signature chain up to a trusted root, hostname match, validity dates, revocation.",
        "Forward secrecy (ECDHE): compromising the server's private key later does not decrypt past sessions.",
        "TLS 1.3 removed legacy ciphers, cut the handshake to 1 RTT, and supports 0-RTT resumption (which has replay caveats — never for non-idempotent requests).",
        "mTLS: both sides present certificates — common for service-to-service authentication in a mesh.",
        "TLS terminates somewhere: at the CDN, the load balancer, or the app. Know where, because that's where plaintext begins.",
      ],
    },
    {
      title: "Latency numbers that shape design",
      points: [
        "Same datacenter round trip: ~0.5 ms.",
        "Same continent: ~10–30 ms. Cross-continent: ~70–150 ms.",
        "TCP + TLS 1.3 handshake: ~2 RTT before the first byte of the request.",
        "So a cold cross-continent HTTPS request costs ~300 ms before your server sees anything.",
        "Bandwidth improves; RTT is bounded by the speed of light. This is why CDNs and connection reuse matter more than pipe size.",
        "A 100 ms delay is perceptible; 1 s breaks flow; 10 s loses the user.",
      ],
    },
  ],

  decisions: [
    {
      title: "TCP vs UDP",
      options: [
        {
          name: "TCP",
          pick: ["The data must arrive, complete and in order: APIs, file transfer, databases, anything transactional."],
          cost: ["Handshake latency before any data.", "Head-of-line blocking — one lost packet stalls the stream.", "Slow start means a new connection is initially slow."],
        },
        {
          name: "UDP",
          pick: ["Late data is worthless: live voice/video, gaming, real-time telemetry.", "Small single-shot exchanges like DNS.", "You want to implement your own reliability (QUIC)."],
          cost: ["You handle loss, ordering, and congestion yourself — or accept them.", "Often blocked or rate-limited by middleboxes."],
        },
      ],
      verdict: "Correctness and completeness → TCP. Timeliness over completeness → UDP. QUIC gets both by rebuilding reliability per stream on UDP.",
      topic: "tcp-udp",
    },
    {
      title: "Polling vs long polling vs SSE vs WebSocket",
      options: [
        {
          name: "Polling",
          pick: ["Low update frequency, simplest possible client.", "Works everywhere, through every proxy."],
          cost: ["Wasteful — most requests return nothing.", "Latency up to the poll interval."],
        },
        {
          name: "Server-Sent Events",
          pick: ["Server → client updates only: notifications, live feeds, streaming LLM tokens.", "Plain HTTP, auto-reconnect built in, works with existing infrastructure."],
          cost: ["One direction only.", "HTTP/1.1 connection limits per host (much less of an issue on HTTP/2)."],
        },
        {
          name: "WebSocket",
          pick: ["Genuine bidirectional, low-latency traffic: chat, collaborative editing, multiplayer."],
          cost: ["Stateful connections complicate load balancing and scaling — you need a connection registry or sticky routing.", "You reimplement reconnection, heartbeats, and backpressure.", "Some proxies and corporate networks interfere."],
        },
      ],
      verdict: "Server-push only → SSE, and it's underused. Truly bidirectional → WebSocket. Infrequent updates → just poll.",
    },
    {
      title: "L4 vs L7 load balancing",
      options: [
        {
          name: "L4 (transport)",
          pick: ["Maximum throughput with minimal processing.", "Non-HTTP protocols.", "TLS passthrough where the backend must terminate."],
          cost: ["Can't route on path, header, or cookie.", "No HTTP-aware retries, health checks, or observability."],
        },
        {
          name: "L7 (application)",
          pick: ["Route by path or host to different services.", "TLS termination, header manipulation, request-level retries.", "Rate limiting, auth, and observability at the edge."],
          cost: ["More CPU per request and higher latency.", "Terminating TLS means it sees plaintext — a security boundary to reason about."],
        },
      ],
      verdict: "L7 for HTTP services — routing and observability are worth the cost. L4 for raw throughput or non-HTTP traffic.",
      topic: "load-balancing",
    },
  ],

  qa: [
    {
      id: "net-url",
      q: "What happens when you type a URL and press enter?",
      a: "The browser first checks its own caches and HSTS list, which may upgrade the scheme to HTTPS before anything leaves the machine. Then DNS resolution: browser cache, OS cache, then the configured resolver, which recursively queries root, TLD, and authoritative nameservers unless it has a cached answer — every layer honouring TTLs. With an IP, the browser opens a TCP connection via the three-way handshake, one round trip, then performs a TLS handshake, one more round trip on TLS 1.3, during which it verifies the server's certificate chain against trusted roots and checks the hostname and validity. Then it sends the HTTP request; the server routes it through a load balancer, possibly a CDN edge, to an application, which may hit caches and databases before responding. The browser parses the HTML, discovers subresources and fetches them, builds the DOM and CSSOM into a render tree, lays out, paints, and composites. The valuable part of this answer is naming which steps you'd optimise: DNS prefetch, connection reuse, CDN, and caching headers all target specific steps here.",
      why: "It's the classic breadth question — the interviewer picks any step and drills in, so it maps your knowledge quickly.",
      trap: "Reciting the steps without depth. Pick one or two — TLS, or caching — and show you can go deeper, and let them steer.",
      followUps: ["Where would you add caching?", "What does HSTS prevent?", "Why is the first request to a domain slower?"],
      depth: "Core",
      tags: ["http", "dns"],
      topic: "request-lifecycle",
    },
    {
      id: "net-tcp-udp",
      q: "TCP or UDP — and where does QUIC fit?",
      a: "TCP gives you a connection with ordering, acknowledgement, retransmission, flow control, and congestion control, so the application sees a reliable byte stream. UDP gives you a datagram and nothing else. You choose UDP when late data is worthless: in a voice call, a packet that arrives 400 ms late is worse than useless, because retransmitting it delays everything behind it, and a brief glitch is preferable to a growing lag. The subtlety worth raising is TCP's head-of-line blocking — because it guarantees ordering over the whole connection, a single lost packet stalls delivery of everything behind it, even data belonging to logically independent streams. That's exactly what HTTP/2 hit: it multiplexes many streams over one TCP connection, so one lost packet stalls all of them. QUIC fixes this by running over UDP and implementing reliability and ordering per stream, so loss affects only the stream it belongs to, and it folds the transport and TLS handshakes together to cut setup to one round trip or zero on resumption.",
      why: "The head-of-line blocking thread ties TCP, HTTP/2, and HTTP/3 into one coherent story.",
      trap: "Saying UDP is 'unreliable so it's worse'. It's a deliberate trade of completeness for timeliness, and QUIC shows you can rebuild reliability where you want it.",
      followUps: ["Why didn't HTTP/2 solve head-of-line blocking?", "What is connection migration in QUIC?"],
      depth: "Intermediate",
      tags: ["tcp", "udp", "quic"],
      topic: "tcp-udp",
    },
    {
      id: "net-tls",
      q: "How does TLS work, and what does it actually guarantee?",
      a: "The handshake negotiates a protocol version and cipher suite, the server presents its certificate chain, the client verifies that chain up to a root it trusts while checking the hostname and validity dates, and both sides perform an ephemeral Diffie-Hellman key exchange to derive a shared secret. From then on the session is encrypted symmetrically, because asymmetric crypto is far too slow for bulk data — so the handshake is asymmetric and the session is symmetric. What it guarantees is confidentiality, so an observer sees ciphertext; integrity, so tampering is detected; and authentication of the server, so you're talking to who the certificate says. What it does not guarantee is that the server is trustworthy, only that it controls the domain, nor does it authenticate the client unless you use mTLS, nor does it hide metadata — the destination IP and, unless encrypted client hello is in use, the SNI hostname are visible. Using ephemeral keys gives forward secrecy, meaning a later compromise of the server's private key can't decrypt recorded past sessions.",
      why: "It's a security fundamental and the 'what it doesn't guarantee' half is what distinguishes a real answer.",
      trap: "Saying TLS means the site is safe. It authenticates domain control and encrypts transport; a phishing site can have a perfectly valid certificate.",
      followUps: ["What is forward secrecy and why does it matter?", "What does mTLS add?", "What is still visible to an observer?"],
      depth: "Intermediate",
      tags: ["tls", "security"],
      topic: "tls-ssl",
    },
    {
      id: "net-dns",
      q: "How does DNS resolution work, and why does a change take time to propagate?",
      a: "Your resolver walks the hierarchy: it asks a root server which nameservers handle `.com`, asks those which handle `example.com`, and asks the authoritative server for the record — unless any step is already cached, which it usually is. Every record carries a TTL, and every cache along the path is entitled to serve the cached answer until it expires. That's the propagation answer: nothing is 'propagating' in a push sense, it's that caches hold the old value until their TTL runs out, and some resolvers ignore short TTLs. So the practical technique before a migration is to lower the TTL well in advance — hours or days ahead, so the low value itself has time to reach caches — then make the change, then raise it again. Other things worth knowing: A and AAAA map names to IPv4 and IPv6, CNAME aliases one name to another and can't coexist with other records at the apex (hence provider-specific ALIAS records), and DNS is also a load-balancing and failover mechanism, though a blunt one because of caching.",
      why: "The 'lower the TTL before, not during' insight is practical operational knowledge.",
      trap: "Describing propagation as a push. It's cache expiry, which is why you can't accelerate it after the fact.",
      followUps: ["Why can't you CNAME the apex of a domain?", "How would you plan a zero-downtime DNS migration?"],
      depth: "Intermediate",
      tags: ["dns"],
      topic: "dns",
    },
    {
      id: "net-http2",
      q: "What did HTTP/2 change, and what practices did it obsolete?",
      a: "It replaced HTTP/1.1's text protocol with binary framing and, crucially, multiplexed many concurrent streams over a single TCP connection, so requests no longer queue behind each other at the application layer. It also added header compression, which matters more than it sounds because HTTP/1.1 resent the same verbose headers and cookies on every request. The practical consequence is that several optimisation practices became counterproductive: domain sharding, which existed to work around the roughly six-connection-per-host limit, now fragments connections and defeats multiplexing and compression; concatenating all JavaScript into one bundle prevents fine-grained caching when small files are no longer expensive; and image spriting is similarly obsolete. Server push was part of the spec but proved hard to use well — it frequently pushed resources the client already had — and has been effectively deprecated in favour of `103 Early Hints` with preload. What HTTP/2 did not fix is TCP-level head-of-line blocking, which is what HTTP/3 addresses.",
      why: "It's a good test of whether someone's performance advice is current or a decade old.",
      trap: "Still recommending domain sharding and mega-bundles. On HTTP/2 those actively hurt.",
      followUps: ["Why is server push deprecated?", "What does HTTP/3 fix that HTTP/2 didn't?"],
      depth: "Intermediate",
      tags: ["http"],
      topic: "http",
    },
    {
      id: "net-timeouts",
      q: "Why are timeouts on network calls so important?",
      a: "Because the default in most HTTP clients is to wait indefinitely, and a dependency that is slow rather than down is more dangerous than one that has failed. If a downstream service starts taking thirty seconds instead of fifty milliseconds, every request to it holds a thread, a connection, and memory for that whole period; your pool fills, new requests queue, and your service — which is perfectly healthy — stops responding. That's how one component's degradation cascades into a full outage. So every outbound call needs an explicit timeout, and you should set several: a connection timeout, a read timeout, and an overall deadline for the operation. The budget should be derived from your own SLA — if you must respond in 500 ms and you make two sequential calls, neither can be allowed 400 ms. Timeouts pair with retries using exponential backoff and jitter, a circuit breaker so you stop calling a failing dependency, and bulkheads so each dependency has its own pool and cannot consume all your capacity. Propagating a deadline downstream is the mature version, so work is abandoned rather than completed for a caller who has already given up.",
      why: "Missing timeouts are the single most common cause of cascading failure in production.",
      trap: "Setting a generous timeout to 'be safe'. A long timeout is what converts a slow dependency into your outage.",
      followUps: ["How do you choose the timeout value?", "What is deadline propagation?"],
      depth: "Advanced",
      tags: ["reliability"],
      topic: "resilience-patterns",
    },
    {
      id: "net-idempotent-retry",
      q: "When is it safe to retry a failed request?",
      a: "When the operation is idempotent, or when you've made it so. A connection failure or a timeout is ambiguous — the request may have been processed and only the response lost — so retrying a non-idempotent operation like 'create order' or 'charge card' risks doing it twice. GET, PUT, and DELETE are idempotent by definition, so retrying them is safe; POST and PATCH are not, and need an idempotency key so the server can recognise the retry and return the original result rather than re-executing. Beyond safety, retries need discipline: exponential backoff so you don't hammer a struggling service, jitter so many clients don't retry in lockstep and create a synchronised thundering herd, a bounded attempt count, and a circuit breaker so you stop entirely when the dependency is clearly down. It's also worth distinguishing which failures are worth retrying — a 503 or a connection reset, yes; a 400 or a 422, never, since the same request will fail identically.",
      why: "It connects HTTP semantics to distributed-systems reliability and shows judgement about amplification.",
      trap: "Retrying on all errors. Retrying a 400 wastes capacity, and retrying without jitter turns recovery into a stampede.",
      followUps: ["Why does jitter matter?", "How does an idempotency key work?"],
      depth: "Advanced",
      tags: ["reliability", "http"],
      topic: "idempotency",
    },
    {
      id: "net-cors-preflight",
      q: "Why does a preflight request happen, and what triggers it?",
      a: "The browser sends an `OPTIONS` preflight before certain cross-origin requests to ask the server whether the actual request is permitted, and it exists for backward compatibility: before CORS, a cross-origin request could only be something a form could already make, so those 'simple' requests were always possible and can't be newly dangerous. Anything beyond that could have side effects the server never expected to receive cross-origin, so the browser asks first. Triggers are a method other than GET, HEAD, or POST; a `Content-Type` other than the three form-ish types, which is why `application/json` preflights; and any custom header such as `Authorization` or `X-Request-Id`. The server responds with the allowed origin, methods, and headers, plus `Access-Control-Max-Age` to let the browser cache that answer and skip preflights for subsequent calls — which is the main performance lever, since otherwise you double the request count. Note preflight is a browser behaviour: server-to-server calls and curl never do it.",
      why: "It's a daily frontend/backend friction point that's usually misdiagnosed as a client bug.",
      trap: "Trying to avoid preflight by changing frontend code. You configure the server, and cache the preflight with `Max-Age`.",
      followUps: ["How do credentials change the rules?", "Why is `*` disallowed with credentials?"],
      depth: "Intermediate",
      tags: ["cors", "browser"],
      topic: "http",
    },
    {
      id: "net-websocket-scale",
      q: "What's hard about scaling WebSockets?",
      a: "They're stateful, which breaks the assumption every other part of a web stack is built on. With stateless HTTP any instance can serve any request, so scaling is just adding instances behind a load balancer. With WebSockets a user's connection lives on one specific instance, so when another user sends them a message, the instance handling that send probably isn't the one holding the recipient's socket. You need a connection registry — typically user id to node id in Redis — and a way to forward the message to the right node, usually a pub/sub channel per node or a broadcast that each node filters. Deployment is harder too: rolling out a new version drops every connection, so clients need reconnection with backoff and jitter, and the server needs to resume state or replay missed messages. Add heartbeats to detect half-open connections, which TCP won't tell you about; enforce per-connection limits so one client can't exhaust memory; and think about backpressure, because a slow consumer with a fast producer grows an unbounded buffer.",
      why: "It's where a design that looked simple meets distributed-systems reality, and the connection registry is the piece candidates miss.",
      trap: "Assuming a load balancer handles it. Sticky sessions keep a client on one node but don't solve routing a message to a different user's node.",
      followUps: ["How do you deploy without dropping every connection?", "Why do you need heartbeats?"],
      depth: "Advanced",
      tags: ["websockets", "scaling"],
    },
    {
      id: "net-latency-vs-bandwidth",
      q: "Latency or bandwidth — which do you optimise?",
      a: "Usually latency, because bandwidth has improved by orders of magnitude while latency is bounded by the speed of light and hasn't. A round trip from London to Sydney can't go below roughly a hundred milliseconds no matter what you pay, and most web performance is dominated by the number of round trips rather than the bytes moved. That reframes optimisation: reduce round trips by reusing connections rather than reopening them, since a new HTTPS connection costs two round trips before the request is even sent; move content physically closer with a CDN, which is the only way to actually reduce propagation delay; avoid chains of dependent requests, where each must complete before the next begins, because those serialise round trips; and use HTTP/2 or 3 so many requests share one connection. Bandwidth still matters for large payloads — video, images, big bundles — where compression, modern image formats, and code splitting pay off. The diagnostic question is whether time is going into waiting or into transferring, which a waterfall chart answers immediately.",
      why: "It's the framing that makes web performance work make sense rather than being a list of tips.",
      trap: "Optimising payload size when the problem is a chain of sequential requests. Halving the bytes doesn't help if you're paying eight round trips.",
      followUps: ["Why does connection reuse matter so much?", "How does a CDN reduce latency specifically?"],
      depth: "Intermediate",
      tags: ["performance"],
      topic: "latency-throughput",
    },
  ],

  pitfalls: [
    "Don't say UDP is 'worse than TCP' — it trades completeness for timeliness, deliberately.",
    "Don't claim HTTP/2 fixed head-of-line blocking — it fixed it at the application layer only; TCP still blocks.",
    "Don't recommend domain sharding or mega-bundles — those are HTTP/1.1 workarounds.",
    "Don't describe DNS propagation as a push — it's cache expiry, so lower TTLs before a migration.",
    "Don't say TLS means a site is trustworthy — it authenticates domain control, not intent.",
    "Don't leave network calls without an explicit timeout.",
    "Don't retry non-idempotent requests without an idempotency key, or retry without jitter.",
    "Don't assume sticky sessions solve WebSocket scaling — you still need cross-node message routing.",
  ],

  numbers: [
    { label: "Same-DC round trip", value: "~0.5 ms", note: "Cross-continent ~70–150 ms." },
    { label: "TCP + TLS 1.3 setup", value: "2 RTT", note: "TLS 1.2 needs 3; resumption can reach 0-RTT." },
    { label: "HTTP/1.1 connections per host", value: "~6", note: "The reason domain sharding existed." },
    { label: "Perceptible delay", value: "~100 ms", note: "1 s breaks flow; 10 s loses the user." },
    { label: "Ports", value: "80 HTTP, 443 HTTPS, 53 DNS, 22 SSH", note: "5432 Postgres, 3306 MySQL, 6379 Redis." },
  ],

  relatedTopics: [
    "osi-tcpip-model",
    "tcp-udp",
    "tcp-handshake",
    "dns",
    "http",
    "tls-ssl",
    "load-balancing",
    "latency-throughput",
    "request-lifecycle",
    "resilience-patterns",
  ],
};
