import type { Area } from "../types";

export const nodejs: Area = {
  slug: "nodejs",
  title: "Node.js & Backend",
  icon: "🟢",
  stream: "Language & Runtime",
  blurb:
    "The event loop under load, streams, clustering, and why one slow synchronous function stalls every request on the process.",

  mustKnow: [
    "Node runs your JavaScript on ONE thread. Concurrency comes from libuv doing I/O elsewhere and queuing callbacks back — it is concurrency, not parallelism.",
    "Any CPU-heavy synchronous work blocks the event loop, and therefore every other in-flight request on that process. This is the defining operational property of Node.",
    "Node is excellent for I/O-bound work (APIs, proxies, streaming, real-time) and poor for CPU-bound work unless you offload to worker threads or a separate service.",
    "libuv keeps a thread pool (default 4) used for file system operations, DNS lookups via `getaddrinfo`, and some crypto/zlib — network I/O uses the OS event notification mechanism instead, not the pool.",
    "`process.nextTick` runs before promise microtasks; both run between every event loop phase, so a recursive `nextTick` can starve the loop entirely.",
    "Streams process data in chunks with backpressure, so memory stays flat regardless of file or response size — the reason to prefer them over buffering everything.",
    "One Node process uses one core. `cluster` or a process manager forks one worker per core; containers usually scale horizontally instead.",
    "An unhandled promise rejection terminates the process by default since Node 15.",
    "Middleware is a chain: each function either responds or calls `next()`. Error-handling middleware is identified by taking four arguments.",
    "Never block on `JSON.parse` of untrusted large bodies, synchronous `fs` calls, or unbounded loops in a request handler.",
  ],

  sheets: [
    {
      title: "Event loop phases (in order, each tick)",
      points: [
        "timers — `setTimeout` / `setInterval` callbacks whose threshold elapsed.",
        "pending callbacks — some system operations, e.g. certain TCP errors.",
        "idle/prepare — internal.",
        "poll — retrieve new I/O events and run their callbacks; this is where the loop blocks when idle.",
        "check — `setImmediate` callbacks.",
        "close callbacks — `socket.on('close')` and friends.",
        "BETWEEN every phase: drain `process.nextTick` queue, then the promise microtask queue.",
        "`setImmediate` vs `setTimeout(fn, 0)`: inside an I/O callback `setImmediate` always wins; at the top level the order is non-deterministic.",
      ],
    },
    {
      title: "Blocking the loop — causes and fixes",
      points: [
        "Causes: JSON parse/stringify of huge payloads, synchronous `fs` (`readFileSync`), `crypto.pbkdf2Sync`, big loops, complex regex (ReDoS), synchronous template rendering.",
        "Symptom: p99 latency spikes across ALL endpoints, not just the slow one; health checks time out.",
        "Diagnose: event loop lag metric (`perf_hooks` monitorEventLoopDelay), `--prof`, `clinic doctor`, or a flame graph via `0x`.",
        "Fix — offload: `worker_threads` for CPU work in-process; a separate service or queue for heavy jobs.",
        "Fix — chunk: break the work and yield with `setImmediate` so other callbacks interleave.",
        "Fix — stream: process incrementally instead of materialising the whole payload.",
        "Guard: body size limits, regex timeouts / safe regex, and input validation before expensive work.",
      ],
    },
    {
      title: "Streams",
      points: [
        "Four types: Readable, Writable, Duplex (both), Transform (Duplex that modifies).",
        "Backpressure: `write()` returns false when the internal buffer is full; respect it or memory grows unbounded.",
        "`pipeline()` (from `stream/promises`) over `.pipe()` — it propagates errors and destroys all streams on failure; `.pipe()` leaks on error.",
        "Memory stays flat: streaming a 5 GB file uses the highWaterMark (64 KB default for streams), not 5 GB.",
        "Async iteration: `for await (const chunk of readable)` is often the clearest consumer.",
        "Use for: file upload/download, CSV/log processing, proxying, server-sent events, large query results.",
      ],
    },
    {
      title: "Scaling a Node service",
      points: [
        "Vertical first: one process per core via `cluster` / PM2 — a single process cannot use a second core.",
        "In containers, prefer one process per container and let the orchestrator scale replicas — simpler failure and resource accounting.",
        "Stateless processes: no in-memory sessions or caches that must be shared; put them in Redis so any replica can serve any request.",
        "Sticky sessions are a smell except for WebSockets, where you either use sticky routing or a Redis pub/sub adapter.",
        "Graceful shutdown: stop accepting new connections, finish in-flight requests, close DB pools, then exit — otherwise deploys drop requests.",
        "Set `NODE_ENV=production`; many libraries (Express included) skip development-only work based on it.",
      ],
    },
    {
      title: "Security checklist for a Node API",
      points: [
        "Validate every input at the boundary with a schema (Zod/Joi) — body, params, query, headers.",
        "Parameterise every query; never build SQL by concatenation.",
        "`helmet` for security headers; explicit CORS allowlist, never reflect the Origin blindly.",
        "Rate limit by IP and by user; add stricter limits on auth endpoints.",
        "Hash passwords with bcrypt/argon2 — never a fast hash like SHA-256.",
        "Body size limits to prevent memory exhaustion; timeouts on all outbound calls.",
        "Secrets from environment or a secret manager, never in the repo; `npm audit` / Dependabot in CI.",
        "Don't leak stack traces to clients — log them, return a generic message plus a correlation id.",
      ],
    },
  ],

  decisions: [
    {
      title: "`worker_threads` vs `cluster` vs child process",
      options: [
        {
          name: "worker_threads",
          pick: ["CPU-bound work inside one service: image processing, parsing, compression, crypto.", "You want shared memory via `SharedArrayBuffer` and cheap message passing."],
          cost: ["Shares the process, so a crash can take everything down; no isolation between workers."],
        },
        {
          name: "cluster",
          pick: ["Using all cores for the SAME HTTP server — the master forks workers that share a listening socket."],
          cost: ["Does not help a single slow request; state can't be shared in memory across workers."],
        },
        {
          name: "child_process / separate service",
          pick: ["Running a different binary, or isolating genuinely heavy or untrusted work.", "Long-running jobs that should survive independent of the API."],
          cost: ["Highest overhead, IPC serialisation cost, and its own deployment story."],
        },
      ],
      verdict: "CPU work in-process → worker threads. Use all cores for HTTP → cluster (or replicas). Heavy/independent work → a queue and a separate worker service.",
      topic: "concurrency-models-backend",
    },
    {
      title: "Streaming vs buffering a response",
      options: [
        {
          name: "Stream",
          pick: ["Large or unbounded payloads: file downloads, exports, log tailing, LLM token output.", "You want time-to-first-byte low and memory flat."],
          cost: ["Harder error handling once headers are sent — you can't switch to a 500 mid-body.", "Compression/caching layers need to support it."],
        },
        {
          name: "Buffer",
          pick: ["Small, bounded responses — ordinary JSON APIs.", "You need to set headers or status based on the full result, or transform the whole payload."],
          cost: ["Memory proportional to payload size × concurrent requests — the classic OOM under load."],
        },
      ],
      verdict: "Bounded and small → buffer. Large, unbounded, or latency-sensitive first byte → stream, and use `pipeline()` so errors clean up.",
    },
    {
      title: "REST framework choice: Express vs Fastify vs NestJS",
      options: [
        {
          name: "Express",
          pick: ["Maximum ecosystem and familiarity; every tutorial and middleware targets it.", "Small services where you want no opinions."],
          cost: ["No built-in validation, typing, or structure — large codebases drift.", "Slower than Fastify; async error handling needs care in v4."],
        },
        {
          name: "Fastify",
          pick: ["Throughput matters.", "You want JSON schema validation and serialisation built in, which also speeds up responses."],
          cost: ["Smaller ecosystem; some Express middleware needs adapters."],
        },
        {
          name: "NestJS",
          pick: ["Large teams wanting enforced structure: modules, DI, decorators, testable layers.", "Coming from Spring/Angular conventions."],
          cost: ["Heavy abstraction and boilerplate; steep learning curve for a small service."],
        },
      ],
      verdict: "Small/simple → Express. Performance and built-in validation → Fastify. Large team needing enforced architecture → NestJS.",
    },
    {
      title: "In-process cache vs Redis",
      options: [
        {
          name: "In-process (Map / LRU)",
          pick: ["Tiny, read-heavy, tolerant of staleness: config, feature flags, reference data.", "Zero network latency matters."],
          cost: ["Duplicated per replica and inconsistent between them; lost on restart; competes with the heap and can trigger GC pressure."],
        },
        {
          name: "Redis",
          pick: ["Shared state across replicas: sessions, rate limit counters, real-time fan-out.", "You need TTLs, atomic operations, or pub/sub."],
          cost: ["A network hop per access and another component to run, secure, and monitor.", "A new failure mode — decide up front whether a Redis outage fails open or closed."],
        },
      ],
      verdict: "Shared or must-be-consistent → Redis. Small, static, per-process → in-memory with a bounded LRU.",
      topic: "distributed-caching",
    },
  ],

  qa: [
    {
      id: "node-single-thread",
      q: "Node is single-threaded — how does it handle thousands of concurrent connections?",
      a: "Your JavaScript runs on one thread, but Node doesn't wait on I/O. When you make a database call, Node hands it to libuv, which uses the OS's event notification mechanism — epoll on Linux, kqueue on BSD, IOCP on Windows — and immediately returns to run other code. When the response arrives, the callback is queued and runs when the stack is clear. So one thread can have ten thousand connections in flight, because nearly all of them are waiting on something else at any moment. The cost of a connection is a small amount of memory, not a thread with its own stack, which is why this scales far better than thread-per-request for I/O-bound work. The flip side is that it only works while no callback occupies the thread for long — one slow synchronous function stalls all ten thousand.",
      why: "It's the foundational question, and the follow-up about CPU work is where the real understanding shows.",
      trap: "Saying Node is multi-threaded because of libuv's thread pool. The pool handles file I/O, DNS, and some crypto — network I/O uses OS event notification, and your code is always one thread.",
      followUps: ["What is the libuv thread pool actually used for?", "What happens when a request needs 2 seconds of CPU?"],
      depth: "Core",
      tags: ["event-loop", "concurrency"],
      topic: "threads-vs-async",
    },
    {
      id: "node-blocking",
      q: "What happens when a request handler does heavy CPU work, and how do you fix it?",
      a: "Every other request on that process stalls. There's one thread, so a 2-second synchronous computation means 2 seconds during which no callback runs — health checks time out, unrelated endpoints spike, and to an observer the whole service looks down. The distinctive symptom is that p99 latency rises across all endpoints at once, not just the expensive one. To diagnose, measure event loop lag with `monitorEventLoopDelay` from `perf_hooks` and alert on it; a flame graph from `0x` or `clinic` will show the offending frame. To fix, in order of preference: offload to `worker_threads` if it belongs in this service; push it to a queue and a separate worker process if it's a long job; chunk the work and yield with `setImmediate` so other callbacks interleave; or use a native/streaming implementation that doesn't materialise everything at once.",
      why: "It's the single most important operational property of Node and a real production failure mode.",
      trap: "Wrapping the CPU work in a promise or `async` and thinking that helps. `async` doesn't move work off the thread — only a worker or another process does.",
      followUps: ["How do you measure event loop lag?", "Why doesn't `async` help here?"],
      depth: "Core",
      tags: ["performance", "event-loop"],
    },
    {
      id: "node-nexttick",
      q: "`process.nextTick` vs `setImmediate` vs `Promise.then`.",
      a: "`process.nextTick` callbacks run at the end of the current operation, before the event loop continues — and crucially before promise microtasks. Promise callbacks run next, in the microtask queue. Both queues are fully drained between every event loop phase. `setImmediate` is different: it's a macrotask scheduled in the check phase, so it runs once per loop iteration after poll. The practical rule: `nextTick` for 'run this before anything else, right now', promises for ordinary async continuation, and `setImmediate` for 'yield to the event loop, then continue' — which is what you want when chunking CPU work. The danger with `nextTick` is starvation: because the queue is drained completely before the loop proceeds, a callback that recursively queues another `nextTick` blocks I/O forever, whereas the same pattern with `setImmediate` lets the loop breathe.",
      why: "It's the standard depth-check on Node's scheduling, and the starvation point is the part that matters.",
      trap: "Assuming `setImmediate` means 'immediately'. It's later than `nextTick` and later than promises.",
      followUps: ["Why is `setImmediate` safer for chunking work?", "Why is `setTimeout(fn,0)` vs `setImmediate` non-deterministic at the top level?"],
      depth: "Intermediate",
      tags: ["event-loop"],
    },
    {
      id: "node-streams",
      q: "Why use streams, and what is backpressure?",
      a: "Streams let you process data in chunks instead of loading it all into memory, so memory use stays flat regardless of size — reading a 5 GB file with `readFile` needs 5 GB of heap and will crash, while a stream needs only the buffer size. They also improve time-to-first-byte, since you can start sending before you've finished producing. Backpressure is the flow-control mechanism that makes this safe: `writable.write()` returns false when its internal buffer exceeds the highWaterMark, signalling the producer to pause until the `drain` event. If you ignore that return value and keep writing — reading from a fast disk into a slow network socket, say — the buffer grows without bound and you're back to holding everything in memory. `pipe()` and `pipeline()` handle backpressure for you, which is the main reason to use them rather than manual writes.",
      why: "Backpressure is the concept that distinguishes people who've used streams from people who've read about them.",
      trap: "Using `.pipe()` and assuming errors are handled. `.pipe()` doesn't forward errors or destroy the source on failure, which leaks file descriptors — use `pipeline()`.",
      followUps: ["Why `pipeline()` over `.pipe()`?", "How would you stream a CSV transform?"],
      depth: "Intermediate",
      tags: ["streams", "memory"],
      topic: "backpressure",
    },
    {
      id: "node-cluster",
      q: "How do you use all the CPU cores on a machine?",
      a: "One Node process uses one core, so you run several. The `cluster` module forks a worker per core; the master creates the listening socket and the OS or the master distributes connections, so all workers share one port. In practice most people use a process manager like PM2 or the framework's own clustering rather than hand-rolling it. In containerised deployments the more common answer is one process per container and let Kubernetes run N replicas, because it makes CPU and memory limits meaningful per process, keeps crash isolation clean, and reuses the same scaling mechanism you already have. Either way the constraint is that workers share nothing in memory: sessions, caches, rate-limit counters, and WebSocket connection maps must move to Redis, or requests will behave differently depending on which worker they land on.",
      why: "The 'workers share nothing' consequence is what actually breaks applications when they scale out.",
      trap: "Clustering while keeping sessions or rate-limit counters in process memory. Behaviour becomes randomly inconsistent per request.",
      followUps: ["What breaks when you go from one process to four?", "Cluster or container replicas — which and why?"],
      depth: "Intermediate",
      tags: ["scaling"],
      topic: "horizontal-vertical",
    },
    {
      id: "node-error-handling",
      q: "How do you handle errors properly in a Node service?",
      a: "Distinguish operational errors from programmer errors. Operational errors — a failed database call, a timeout, invalid input — are expected and should be handled: catch, log with context, return an appropriate status. Programmer errors — a `TypeError` from a bug — should crash the process, because the state is now unknown and continuing risks corrupting data; a process manager restarts it cleanly. Concretely: `try/catch` around awaited calls, and in Express 4 remember that async handler rejections are NOT caught by the framework, so you need a wrapper or `express-async-errors`; Express 5 handles them. Add a single error-handling middleware (four arguments) as the last one to format responses consistently. Register `unhandledRejection` and `uncaughtException` handlers to log and then exit, never to swallow. And never send stack traces to clients — return a generic message with a correlation id you can look up in logs.",
      why: "The operational-vs-programmer distinction is the framing that separates senior answers.",
      trap: "Catching `uncaughtException` and continuing. The process is in an undefined state; log and exit.",
      followUps: ["Why do async errors escape Express 4 middleware?", "What should the client see versus the log?"],
      depth: "Intermediate",
      tags: ["errors", "reliability"],
      topic: "error-handling",
    },
    {
      id: "node-graceful-shutdown",
      q: "What does graceful shutdown involve and why does it matter?",
      a: "When an orchestrator deploys a new version it sends SIGTERM and then kills the process after a grace period. If you exit immediately, in-flight requests are dropped and users see errors on every deploy. Graceful shutdown means: stop accepting new connections with `server.close()`, which lets existing requests finish; stop consuming from queues so no new work starts; wait for in-flight work with a bounded timeout, then force-exit if it overruns; and close resources — database pools, Redis clients, file handles — so connections aren't left dangling. Two details people miss: your readiness probe should start failing before you stop accepting connections, so the load balancer removes you from rotation first, otherwise it keeps sending requests to a closing process; and keep-alive connections need `server.closeIdleConnections()` or they hold the server open until the timeout.",
      why: "It's the difference between zero-downtime deploys and error spikes on every release.",
      trap: "Calling `process.exit()` in the SIGTERM handler. That's the ungraceful shutdown you're trying to avoid.",
      followUps: ["Why fail the readiness probe first?", "What happens to in-flight queue messages?"],
      depth: "Advanced",
      tags: ["operations", "deployment"],
      topic: "release-strategies",
    },
    {
      id: "node-memory-leak",
      q: "A Node service's memory grows until it OOMs. How do you find the leak?",
      a: "First confirm it's a leak and not just a large heap: watch RSS and heap used over time, and check whether it plateaus after GC or grows monotonically across GC cycles. Then take heap snapshots at intervals with `--inspect` and Chrome DevTools, and use the comparison view to see which object types grew between snapshots — that usually names the culprit directly. The common causes in Node are an unbounded cache or `Map` in module scope, event listeners added per request to a long-lived emitter (you'll often see the MaxListenersExceeded warning first), closures capturing large buffers, timers never cleared, promises that never settle holding their scopes, and accumulating entries in a global array for metrics or logs. The fixes are bounding caches with an LRU and TTL, removing listeners in cleanup, and being careful about what module-scope structures accumulate.",
      why: "It's a realistic production scenario where the method matters more than the specific cause.",
      trap: "Raising `--max-old-space-size` and calling it fixed. That buys time and makes the eventual crash bigger.",
      followUps: ["Why is a module-scope `Map` dangerous?", "How does an LRU with TTL fix it?"],
      depth: "Advanced",
      tags: ["memory", "debugging"],
      topic: "garbage-collection",
    },
    {
      id: "node-middleware",
      q: "How does Express middleware work?",
      a: "Middleware is an ordered chain of functions with the signature `(req, res, next)`. Each one can inspect or mutate `req`/`res`, then either end the request by sending a response or call `next()` to pass control on. Order is everything: a body parser must come before handlers that read `req.body`, authentication before the routes it protects, and the 404 handler after all routes. Error-handling middleware is distinguished purely by taking four arguments `(err, req, res, next)`, and Express skips to the next error handler when you call `next(err)` or when a synchronous handler throws — but in Express 4, a rejected promise in an async handler is not caught, which silently hangs the request until timeout. Mounting with a path (`app.use('/api', router)`) scopes middleware to a subtree, which is how you apply auth to one section only.",
      why: "It's the core mental model for every Node HTTP framework, and the async-error gap is a real bug.",
      trap: "Forgetting to call `next()` — the request hangs with no error, which is much harder to debug than a crash.",
      followUps: ["Why does an async throw hang in Express 4?", "How do you scope middleware to one route group?"],
      depth: "Core",
      tags: ["express", "http"],
      topic: "request-lifecycle",
    },
    {
      id: "node-esm-cjs",
      q: "What problems come up with ESM and CommonJS in Node?",
      a: "They're different module systems with different resolution and timing. CommonJS is synchronous — `require` executes and returns immediately, so it can be conditional or inside a function — while ESM is asynchronous and statically resolved before execution. You can `require` a CommonJS module from ESM, and you can `import()` ESM dynamically from CommonJS, but you cannot statically `import` ESM from CommonJS. Node decides which mode a file is by the nearest `package.json` `'type'` field, or by the `.mjs`/`.cjs` extension. Things that break: `__dirname` and `__filename` don't exist in ESM (use `import.meta.url` with `fileURLToPath`); ESM requires file extensions in relative imports; `require` isn't defined in ESM; and a library shipping both formats can be loaded twice, giving two copies of its state — the dual-package hazard. Jest historically needed extra configuration for ESM, which is why many projects stayed on CommonJS longer than they wanted.",
      why: "Every Node project eventually hits this, and the answer shows breadth of practical experience.",
      trap: "Assuming `'type': 'module'` is a flip-the-switch change. Extensions, `__dirname`, and tooling all need attention.",
      followUps: ["What is the dual-package hazard?", "How do you get `__dirname` in ESM?"],
      depth: "Intermediate",
      tags: ["modules", "tooling"],
    },
    {
      id: "node-caching-strategy",
      q: "Where would you add caching in a Node API, and what would you invalidate on?",
      a: "Work outward from the data. Start with the database's own query plan and indexes, since a cache over a bad query hides the real problem. Then an application-level cache in Redis for expensive reads — key by the query parameters, set a TTL that matches how stale the data may acceptably be, and use cache-aside: check Redis, miss, read the database, populate. Above that, HTTP caching with `Cache-Control` and `ETag` lets browsers and CDNs skip the request entirely, which is the cheapest cache of all. Invalidation is where it goes wrong: prefer short TTLs for data you can't reliably invalidate, and explicit deletion on write for data you can. Watch for stampede — when a hot key expires, many requests miss at once and hit the database together — which you handle with a short lock, a single-flight pattern, or staggered TTLs.",
      why: "It tests layered thinking and whether the candidate treats invalidation as the hard part.",
      trap: "Adding a cache before checking indexes and query plans. You end up with two problems and stale data.",
      followUps: ["How do you prevent a cache stampede?", "When is a short TTL better than explicit invalidation?"],
      depth: "Advanced",
      tags: ["caching", "performance"],
      topic: "cache-strategies",
    },
    {
      id: "node-async-patterns",
      q: "How do you run 1,000 async operations without overwhelming the downstream service?",
      a: "Bounded concurrency. `Promise.all` on 1,000 promises fires all 1,000 immediately, which will exhaust connection pools, trip rate limits, or take down the service you're calling — and a serial `for await` loop is correct but 1,000× slower than necessary. The middle ground is a pool that keeps K requests in flight: process the array with K workers each pulling the next item, or use a library like `p-limit` or `p-map` with a `concurrency` option. Choose K from the downstream constraint — the database pool size, the API's documented rate limit — not from what feels fast. Add per-request timeouts so one hung call doesn't hold a slot forever, retries with exponential backoff and jitter for transient failures, and decide whether one failure should abort everything (`Promise.all`) or be collected (`allSettled`).",
      why: "It's a realistic backend problem and the answer reveals whether someone thinks about blast radius.",
      trap: "Reaching for `Promise.all` on an unbounded array. It's the standard way to accidentally DoS your own database.",
      followUps: ["How do you pick the concurrency limit?", "Why add jitter to backoff?"],
      depth: "Advanced",
      tags: ["async", "reliability"],
      topic: "resilience-patterns",
    },
    {
      id: "node-worker-threads",
      q: "When would you reach for `worker_threads`?",
      a: "When you have CPU-bound work that must happen inside this service and would otherwise block the event loop — image resizing, PDF generation, parsing a large file, compression, or expensive crypto. A worker runs on its own thread with its own V8 isolate and event loop, so the main thread stays responsive; you communicate by structured-cloned messages, or share memory explicitly with `SharedArrayBuffer` when copying is too expensive. The cost is that spawning a worker isn't free — around tens of milliseconds — so you use a pool rather than creating one per task, and there's no isolation, so an unhandled error in a worker can affect the process. The alternative, and often the better one for genuinely heavy or long-running jobs, is to push the work to a queue and have a separate service consume it, which gives you retries, independent scaling, and durability across deploys.",
      why: "The 'worker vs queue' judgement is the interesting part, not the API.",
      trap: "Using worker threads for I/O. I/O is already non-blocking; workers only help with CPU.",
      followUps: ["Why pool workers instead of creating per task?", "When is a job queue better than a worker thread?"],
      depth: "Advanced",
      tags: ["concurrency", "performance"],
      topic: "concurrency-models-backend",
    },
    {
      id: "node-observability",
      q: "What would you instrument in a Node service?",
      a: "Three signals, plus one Node-specific one. Metrics: request rate, error rate, and latency percentiles per endpoint (p50/p95/p99 — averages hide the problem), plus saturation signals like connection pool usage and queue depth. Logs: structured JSON, one line per request with method, path, status, duration, and a correlation id propagated from an incoming header so a single user journey can be traced across services. Traces: distributed tracing via OpenTelemetry so you can see where time actually goes across service hops — usually revealing that the slow endpoint is waiting on something three hops away. The Node-specific one is event loop lag, which is the earliest warning that the process is CPU-saturated, along with heap usage and GC pause time. Alert on symptoms users feel — error rate and latency SLOs — not on CPU percentage.",
      why: "It shows whether someone has actually operated a service rather than only written one.",
      trap: "Reporting average latency. The average is fine while a tenth of your users are timing out.",
      followUps: ["Why percentiles over averages?", "How does a correlation id flow between services?"],
      depth: "Advanced",
      tags: ["observability"],
      topic: "metrics",
    },
    {
      id: "node-file-upload",
      q: "How do you handle a large file upload?",
      a: "Stream it, and preferably don't route it through your API at all. Buffering a multi-gigabyte upload into memory or even onto local disk puts a hard ceiling on concurrency and couples file size to instance memory. The standard pattern is a presigned URL: the client asks your API for a short-lived signed URL, then uploads directly to object storage, and your API only records metadata when the upload completes — so the bytes never touch your service. When you must proxy them, use a streaming parser like Busboy and pipe straight to the storage SDK, never accumulating the whole body. Either way, enforce a size limit before you start (an unbounded upload is a memory-exhaustion DoS), validate the content type by inspecting magic bytes rather than trusting the extension or client-supplied MIME type, and scan untrusted files before making them available.",
      why: "The presigned-URL answer signals real backend experience; buffering answers signal the opposite.",
      trap: "Reading the upload into a Buffer to validate it. That's exactly the memory-exhaustion vector.",
      followUps: ["How does a presigned URL stay secure?", "Why not trust the client's content type?"],
      depth: "Advanced",
      tags: ["streams", "storage", "security"],
    },
  ],

  pitfalls: [
    "Don't say Node is multi-threaded — say your JS is one thread and libuv handles I/O, with a small pool for file/DNS/crypto.",
    "Don't claim `async` moves CPU work off the main thread — only workers or another process do that.",
    "Don't use `.pipe()` in production code without error handling — `pipeline()` propagates errors and cleans up.",
    "Don't keep sessions or rate-limit counters in process memory once you run more than one process.",
    "Don't swallow `uncaughtException` and keep running — log and exit; let the supervisor restart.",
    "Don't `Promise.all` an unbounded array of requests — bound the concurrency.",
    "Don't buffer large uploads or downloads — stream, or use presigned URLs.",
  ],

  numbers: [
    { label: "libuv thread pool (default)", value: "4", note: "`UV_THREADPOOL_SIZE`, max 1024. Used for fs, DNS, some crypto/zlib." },
    { label: "Default stream highWaterMark", value: "64 KB", note: "16 KB for object-mode / older defaults; tune for throughput." },
    { label: "Default V8 old-space heap", value: "~4 GB (64-bit, modern Node)", note: "Raise with `--max-old-space-size`; a leak will still win." },
    { label: "Event loop lag alert threshold", value: "> 100 ms p99", note: "Early warning of CPU saturation." },
    { label: "Processes per machine", value: "= CPU cores", note: "One Node process saturates exactly one core." },
  ],

  relatedTopics: ["threads-vs-async", "concurrency-models-backend", "backpressure", "error-handling", "request-lifecycle", "cache-strategies", "horizontal-vertical", "metrics"],
};
