import type { Area } from "../types";

export const oopDesign: Area = {
  slug: "oop-design",
  title: "OOP, SOLID & Patterns",
  icon: "🧩",
  stream: "CS Core",
  blurb:
    "The four pillars, SOLID without the recitation, the patterns that actually appear in code, and why composition keeps beating inheritance.",

  mustKnow: [
    "Encapsulation: hide internal state behind an interface so invariants can be enforced in one place. It's the pillar the others depend on.",
    "Abstraction: expose what something does, hide how. Interfaces are the contract; implementations are swappable.",
    "Inheritance: reuse by 'is-a'. Powerful and over-used — it couples subclass to superclass internals permanently.",
    "Polymorphism: one interface, many implementations, selected at runtime. It's what removes conditional branching on type.",
    "Composition over inheritance: prefer 'has-a'. It's more flexible, avoids fragile base classes, and can change at runtime.",
    "Single Responsibility: one reason to change. If you describe a class with 'and', it's probably two classes.",
    "Open/Closed: extend behaviour by adding code, not by editing existing code — usually via an interface plus a new implementation.",
    "Liskov Substitution: a subclass must be usable anywhere its parent is, without surprising the caller. Violating it is the deepest inheritance bug.",
    "Interface Segregation: many small interfaces beat one large one; clients shouldn't depend on methods they don't call.",
    "Dependency Inversion: depend on abstractions, not concretions — this is what makes code testable without a test framework hack.",
  ],

  sheets: [
    {
      title: "SOLID, stated as what goes wrong without it",
      points: [
        "S — a class doing report generation AND email sending changes for two unrelated reasons; a formatting change risks breaking delivery.",
        "O — adding a payment method means editing a switch statement in five files, and every edit risks the existing methods.",
        "L — `Square extends Rectangle` overrides `setWidth` to also set height; code that sets width then height gets a wrong area. The subclass broke the parent's contract.",
        "I — a `Worker` interface with `eat()` forces a `RobotWorker` to implement or throw on a method it has no business having.",
        "D — a service that constructs its own `PostgresRepository` cannot be tested without a database and cannot be reused with another store.",
        "SOLID is a set of smells to recognise, not rules to apply pre-emptively. Applying them all to a 50-line script produces worse code.",
      ],
    },
    {
      title: "Patterns you'll actually be asked about",
      points: [
        "Strategy — swap an algorithm at runtime behind one interface. The honest replacement for most `switch` statements on type.",
        "Factory — centralise object creation when the concrete type depends on input or config.",
        "Observer — publish/subscribe within a process; the basis of event emitters and reactive UIs.",
        "Decorator — wrap an object to add behaviour without changing it; how middleware, retry wrappers, and caching layers work.",
        "Adapter — make an incompatible interface fit; the standard way to isolate a third-party API.",
        "Singleton — one instance globally. Usually a smell: it's global state, it hides dependencies, and it breaks tests. Prefer DI with one registered instance.",
        "Repository — abstract data access so the domain doesn't know about SQL.",
        "Builder — construct an object with many optional parts without a telescoping constructor.",
      ],
    },
    {
      title: "Composition vs inheritance",
      points: [
        "Inheritance is compile-time and permanent; composition is runtime and swappable.",
        "Inheritance exposes the parent's internals to the child — a change to the parent can silently break subclasses (the fragile base class problem).",
        "Deep hierarchies become impossible to reason about; behaviour is spread across five files.",
        "Multiple behaviours combine badly with single inheritance — the class explosion problem (FlyingSwimmingDuck).",
        "Composition + interfaces gives the same polymorphism with none of the coupling.",
        "Use inheritance when the relationship is genuinely 'is-a' AND the subclass never violates the parent's contract.",
        "Frameworks often require inheritance (extending a base component); that's a constraint, not a recommendation.",
      ],
    },
    {
      title: "LLD interview process",
      points: [
        "1. Clarify requirements and scope — what's in, what's explicitly out.",
        "2. Identify the nouns → candidate entities; the verbs → behaviours.",
        "3. Define interfaces before implementations; state the contracts.",
        "4. Draw relationships: composition, aggregation, inheritance — and justify each inheritance.",
        "5. Walk one core use case end-to-end through your design.",
        "6. Name the extension points: 'a new payment method is a new class, no existing code changes'.",
        "7. Mention concurrency, error handling, and persistence boundaries even if you don't implement them.",
        "Classic problems: parking lot, elevator, vending machine, library, chess, rate limiter, logger, cache with LRU.",
      ],
    },
  ],

  decisions: [
    {
      title: "Composition vs inheritance",
      options: [
        {
          name: "Composition",
          pick: ["Default. Behaviour can be swapped at runtime and combined freely.", "You want to share behaviour across unrelated types.", "You need to test a part in isolation."],
          cost: ["More explicit wiring — you pass collaborators in.", "Slightly more code for simple cases."],
        },
        {
          name: "Inheritance",
          pick: ["A genuine 'is-a' relationship where the subtype honours every parent contract.", "A framework requires it.", "Shared implementation across a closed, stable set of types."],
          cost: ["Permanent compile-time coupling to the parent's internals.", "Fragile base class: a parent change breaks subclasses silently.", "Single inheritance forces awkward hierarchies when behaviours cross-cut."],
        },
      ],
      verdict: "Compose by default. Reach for inheritance only when 'is-a' holds AND Liskov holds — and be able to say why both do.",
      topic: "composition-vs-inheritance",
    },
    {
      title: "Interface vs abstract class",
      options: [
        {
          name: "Interface",
          pick: ["Defining a contract with no shared implementation.", "A type needs to satisfy several contracts (multiple interfaces are fine, multiple inheritance usually isn't).", "You want maximum decoupling and easy test doubles."],
          cost: ["No shared code — duplication if several implementers need the same helper (default methods mitigate this)."],
        },
        {
          name: "Abstract class",
          pick: ["Genuine shared implementation plus abstract hooks (the Template Method pattern).", "You need protected state or constructor logic common to all subtypes."],
          cost: ["Uses up the single inheritance slot.", "Couples every subclass to the base's implementation details."],
        },
      ],
      verdict: "Interface for the contract; abstract class only when there's real shared implementation. Many designs want an interface plus an optional abstract base.",
      topic: "interfaces-abstract-classes",
    },
    {
      title: "Singleton vs dependency injection",
      options: [
        {
          name: "Dependency injection",
          pick: ["Almost always. Dependencies are explicit in the constructor, so the class is honest about what it needs.", "Trivially testable — pass a fake.", "One instance is still achievable: register it once in the container."],
          cost: ["Wiring code, or a DI container to learn.", "Constructor signatures grow (which is useful feedback about coupling)."],
        },
        {
          name: "Singleton",
          pick: ["Genuinely process-wide resources with no alternative: a logger root, a metrics registry.", "Small scripts where DI is overkill."],
          cost: ["Global mutable state — the thing everyone agrees is bad, wearing a pattern name.", "Hidden dependencies: you can't tell what a class uses from its signature.", "Tests share state and leak between each other; parallel tests break.", "Thread-safe lazy initialisation is easy to get wrong."],
        },
      ],
      verdict: "Use DI and register a single instance. 'Singleton' as a pattern mostly survives because people conflate 'one instance' with 'globally reachable' — you only want the first.",
      topic: "singleton",
    },
  ],

  qa: [
    {
      id: "oop-pillars",
      q: "What are the four pillars of OOP, and which matters most?",
      a: "Encapsulation, abstraction, inheritance, and polymorphism. Encapsulation is hiding internal state behind a controlled interface so invariants are enforced in one place rather than at every call site — a `BankAccount` that exposes `deposit` and `withdraw` rather than a public `balance` field can guarantee the balance never goes negative. Abstraction is exposing what a thing does while hiding how, so callers depend on a contract they can rely on rather than an implementation that will change. Polymorphism lets one interface have many implementations chosen at runtime, which is what lets you add a new payment method without touching the code that processes payments. Inheritance is reuse through an 'is-a' relationship, and it's the one to be most careful with. If pressed on which matters most, encapsulation — the others build on having a stable boundary. And the honest addition is that polymorphism plus composition delivers most of OOP's practical value, while inheritance delivers most of its practical pain.",
      why: "Everyone can list them; the differentiator is explaining what each buys you and being critical about inheritance.",
      trap: "Defining them by mechanism ('inheritance is `extends`') rather than by the problem they solve.",
      followUps: ["Why is encapsulation foundational to the others?", "Can you have polymorphism without inheritance?"],
      depth: "Core",
      tags: ["fundamentals"],
      topic: "encapsulation",
    },
    {
      id: "oop-liskov",
      q: "Explain the Liskov Substitution Principle with a concrete violation.",
      a: "A subclass must be substitutable for its parent without breaking any caller's expectations. The canonical violation is `Square extends Rectangle`: mathematically a square is a rectangle, so it looks correct. But `Rectangle` has independent `setWidth` and `setHeight`, and `Square` must override them to keep the sides equal. Now any code written against `Rectangle` — set width to 5, set height to 4, assert area is 20 — silently produces 16 when handed a `Square`. Nothing crashes, nothing is obviously wrong, and the caller was written entirely reasonably. The lesson is that inheritance must preserve behavioural contracts, not just structural shape: a subclass may not strengthen preconditions, weaken postconditions, or throw exceptions the parent's contract didn't permit. Other common violations are overriding a method to throw `NotSupportedException`, or a `ReadOnlyList` extending `List`. The fix here is usually to stop inheriting — make `Shape` an interface with an `area()` method and let both implement it independently.",
      why: "It's the SOLID principle with real teeth, and the square/rectangle example makes it concrete rather than abstract.",
      trap: "Explaining LSP as 'a subclass should behave like its parent' without an example. The example is what proves you understand it.",
      followUps: ["How would you redesign shapes correctly?", "Why is throwing `NotSupported` in an override a violation?"],
      depth: "Intermediate",
      tags: ["solid"],
      topic: "liskov-substitution",
    },
    {
      id: "oop-composition",
      q: "Why 'composition over inheritance'?",
      a: "Because inheritance creates the tightest coupling the language offers, and it's permanent. A subclass depends on its parent's implementation details, not just its interface, so a change in the parent can break subclasses that never mentioned the changed method — the fragile base class problem. It's also fixed at compile time: an object can't change what it inherits, whereas a composed collaborator can be swapped at runtime or in a test. And single inheritance forces bad hierarchies when behaviours cross-cut — if you have flying, swimming, and singing behaviours, inheritance gives you a combinatorial explosion of classes, while composition lets an object simply hold the behaviours it has. The classic illustration is a `Duck` hierarchy where adding a rubber duck that can't fly forces you to override `fly()` to do nothing, which is also an LSP violation. Composing a `FlyBehavior` fixes both problems and lets you change it at runtime. The nuance worth adding is that inheritance isn't forbidden — it's right for a genuine, stable 'is-a' where the subclass honours every parent contract.",
      why: "It's the most practically consequential OOP guideline and the reasoning is more useful than the slogan.",
      trap: "Stating it as a rule without the fragile-base-class and runtime-flexibility reasons behind it.",
      followUps: ["When is inheritance genuinely the right choice?", "How does the Strategy pattern apply here?"],
      depth: "Core",
      tags: ["design"],
      topic: "composition-vs-inheritance",
    },
    {
      id: "oop-dip",
      q: "What does Dependency Inversion actually mean in code?",
      a: "That high-level policy shouldn't depend on low-level detail — both should depend on an abstraction. Concretely, if `OrderService` constructs its own `new PostgresOrderRepository()`, then the business logic depends on Postgres: you can't test it without a database, you can't reuse it with another store, and changing the persistence layer means editing the service. Inverting it means `OrderService` accepts an `OrderRepository` interface through its constructor, and something at the composition root — your DI container or `main` — decides which implementation to supply. The 'inversion' is in who owns the interface: it belongs to the high-level module, expressed in its language, and the low-level module implements it, so the dependency arrow points from detail toward policy rather than the reverse. The practical payoffs are that unit tests pass a fake with no infrastructure, implementations are swappable, and the constructor signature honestly documents everything the class needs — which also makes over-coupling visible, because a constructor with nine dependencies is telling you the class does too much.",
      why: "It's the principle that most directly determines whether a codebase is testable.",
      trap: "Equating it with 'use a DI framework'. The principle is about which direction dependencies point; the framework is just wiring.",
      followUps: ["Who should own the interface, and why?", "What does a nine-parameter constructor tell you?"],
      depth: "Intermediate",
      tags: ["solid", "testing"],
      topic: "dependency-inversion",
    },
    {
      id: "oop-strategy",
      q: "When would you use the Strategy pattern?",
      a: "When you have several interchangeable ways of doing one thing and the choice is made at runtime. The tell is a `switch` or `if/else` chain branching on a type or mode — payment methods, pricing rules, compression algorithms, export formats, sorting criteria. Each branch becomes a class implementing a common interface, and the caller holds a reference to one of them, so selecting behaviour becomes selecting an object. What you gain is Open/Closed: adding a new payment method is a new class plus a registration, with no edits to the code that processes payments, so you can't break the existing methods while adding one. You also gain testability, since each strategy is independently testable, and the ability to change behaviour at runtime per customer or per request. The cost is more classes and a level of indirection, so it's not worth it for two stable branches that will never grow — the pattern earns its keep when the set of variants is open-ended.",
      why: "It's the pattern with the widest real-world applicability, and recognising the switch-statement smell is the useful skill.",
      trap: "Applying it to a two-branch conditional that will never change. That's ceremony without benefit.",
      followUps: ["How does this relate to Open/Closed?", "How do you choose which strategy at runtime?"],
      depth: "Intermediate",
      tags: ["patterns"],
      topic: "strategy",
    },
    {
      id: "oop-singleton-problems",
      q: "What's wrong with the Singleton pattern?",
      a: "It's global mutable state with a respectable name. Three concrete problems. It hides dependencies: a class that calls `Database.getInstance()` internally has a dependency you cannot see in its signature, so you can't tell what it needs without reading the body, and you can't substitute it. It breaks tests: state persists between test cases, so tests become order-dependent and can't run in parallel, and you end up adding a `reset()` method purely for tests, which is an admission the design is wrong. And it's often wrong about lifetime — 'one instance' turns out to mean one per tenant, or per request, or per thread, and retrofitting that is painful. There are also implementation hazards around thread-safe lazy initialisation. The important distinction is that wanting a single instance is entirely reasonable; what causes the damage is making it globally reachable. Dependency injection gives you exactly one instance, registered in the container and passed explicitly, with none of the drawbacks — which is why most modern frameworks make it the default.",
      why: "It's the standard 'do you think critically about patterns' probe, and the one-instance-versus-globally-reachable distinction is the insight.",
      trap: "Defending it as thread-safe lazy initialisation. Thread safety was never the main objection.",
      followUps: ["How does DI give you one instance without the downsides?", "When is a singleton genuinely acceptable?"],
      depth: "Intermediate",
      tags: ["patterns", "antipatterns"],
      topic: "singleton",
    },
    {
      id: "oop-lld-parking",
      q: "Design a parking lot.",
      a: "Start by scoping: multiple levels with spots of different sizes, vehicles of different types, ticketing on entry, fee calculation on exit — and explicitly exclude reservations and number-plate recognition unless asked. The entities fall out of the nouns: `ParkingLot` containing `Level`s containing `ParkingSpot`s; `Vehicle` as an abstraction with `Car`, `Motorcycle`, `Truck`; `Ticket` recording spot, vehicle, and entry time; and a `FeeCalculator`. The design decisions worth voicing are where I'd use polymorphism and where I'd resist inheritance. Spot allocation is a `SpotAssignmentStrategy` interface, so 'nearest available' and 'level-balanced' are separate implementations rather than branches. Fee calculation is likewise a strategy, since hourly, flat-rate, and weekend pricing are exactly the kind of thing that changes. Vehicle type is better modelled as an enum plus a size than as an inheritance hierarchy, because the subclasses would add no behaviour. Then I'd walk one flow end to end — vehicle arrives, strategy finds a compatible free spot, spot is marked occupied atomically, ticket issued — and flag concurrency as the real issue, since two entrances assigning the same spot needs a lock or an atomic compare-and-set.",
      why: "It's the most common LLD prompt, and mentioning concurrency and strategy interfaces unprompted is what distinguishes a strong answer.",
      trap: "Building a deep `Vehicle` inheritance tree. The subclasses have no differing behaviour, so an enum and a size attribute are simpler and more honest.",
      followUps: ["How do you stop two entrances assigning the same spot?", "How would you add a new pricing scheme?"],
      depth: "Advanced",
      tags: ["lld", "case-study"],
      topic: "lld-case-studies",
    },
    {
      id: "oop-solid-overuse",
      q: "Can SOLID be over-applied?",
      a: "Yes, and it commonly is. Each principle is a response to a specific pain, so applying it where that pain doesn't exist adds cost without benefit. Splitting every class until each has one method produces a codebase where following a single request means opening fifteen files, which is harder to understand than the 'violation' it replaced. Introducing an interface for every class when there's exactly one implementation and no test seam adds indirection with no substitution. Building extension points for variation that never arrives is speculative generality — you pay for flexibility you don't use, and you usually guessed the wrong axis anyway. The better framing is that SOLID describes smells to recognise once code starts hurting: when a class keeps changing for unrelated reasons, split it; when adding a variant means editing a switch in five places, invert it behind an interface; when a test needs a real database, inject the dependency. Let the second or third instance of a change drive the abstraction rather than the first.",
      why: "It's a maturity signal — junior engineers apply principles, senior engineers know what they cost.",
      trap: "Treating SOLID as a checklist to satisfy. Over-abstraction is as expensive as under-abstraction and harder to unwind.",
      followUps: ["What is speculative generality?", "When do you actually introduce the abstraction?"],
      depth: "Advanced",
      tags: ["design", "judgement"],
      topic: "dry-kiss-yagni",
    },
    {
      id: "oop-coupling-cohesion",
      q: "What are coupling and cohesion, and how do you use them?",
      a: "Cohesion is how related the things inside a module are; coupling is how dependent modules are on each other. You want high cohesion and low coupling, and they're a better everyday guide than the SOLID acronym because they're directly observable. Low cohesion looks like a `Utils` class holding date formatting, string parsing, and HTTP retries — nothing belongs together, so nobody knows where to add the next thing and it becomes a dumping ground. High coupling looks like a change to one module forcing edits in four others, or a class reaching through several objects to get what it needs (`order.getCustomer().getAddress().getCountry().getCode()`), which is the Law of Demeter violation and means you're coupled to a whole object graph rather than to one neighbour. The diagnostic questions are practical: if I change this, what else must change? Can I test this without constructing half the system? Can I describe what this module does without saying 'and'? Those tell you more than checking principles off a list.",
      why: "They're the underlying properties SOLID is trying to produce, and they're easier to assess in real code.",
      trap: "Treating low coupling as an absolute good. Zero coupling means nothing talks to anything; you want the dependencies to be few, deliberate, and pointed in one direction.",
      followUps: ["What does the Law of Demeter guard against?", "How do you spot a low-cohesion module in review?"],
      depth: "Intermediate",
      tags: ["design"],
      topic: "coupling-cohesion",
    },
    {
      id: "oop-decorator",
      q: "Where does the Decorator pattern show up in real systems?",
      a: "Anywhere behaviour is layered around a core operation without changing it. A decorator implements the same interface as the thing it wraps and delegates to it, adding behaviour before or after — which means decorators stack in any combination and the wrapped object never knows. HTTP middleware is exactly this: logging wraps authentication wraps rate limiting wraps the handler, each conforming to the same request-handler shape. So are retry and circuit-breaker wrappers around a client, caching layers that check a store before delegating, and instrumentation that times a call. Java's IO library is the textbook case, with `BufferedReader` wrapping `FileReader`. The advantage over inheritance is combinatorial: with three optional behaviours you'd need seven subclasses to cover the combinations, while decorators compose at runtime. The costs are that a deep stack makes stack traces long and debugging indirect, and order can matter in non-obvious ways — putting caching outside authentication would serve cached responses to unauthorised callers.",
      why: "It connects a textbook pattern to middleware, which candidates use daily without naming it.",
      trap: "Confusing it with Proxy. Both wrap, but a proxy controls access to the same interface, while a decorator adds behaviour and is designed to stack.",
      followUps: ["Why does decorator order matter?", "How does this differ from Proxy?"],
      depth: "Intermediate",
      tags: ["patterns"],
      topic: "decorator",
    },
  ],

  pitfalls: [
    "Don't define the pillars by keyword — define them by the problem each solves.",
    "Don't explain Liskov without a concrete violation; the example is the answer.",
    "Don't state 'composition over inheritance' as a rule — give the fragile-base-class and runtime-swappability reasons.",
    "Don't equate Dependency Inversion with using a DI framework.",
    "Don't defend Singleton on thread safety — the objection is hidden global state.",
    "Don't build a deep inheritance hierarchy in an LLD answer when the subclasses add no behaviour.",
    "Don't apply every SOLID principle to every class — over-abstraction is a real cost.",
    "Don't forget concurrency in an LLD design; it's usually the hardest part and it's usually skipped.",
  ],

  relatedTopics: [
    "encapsulation",
    "abstraction",
    "inheritance",
    "polymorphism",
    "composition-vs-inheritance",
    "single-responsibility",
    "open-closed",
    "liskov-substitution",
    "interface-segregation",
    "dependency-inversion",
    "coupling-cohesion",
    "strategy",
    "decorator",
    "singleton",
    "lld-fundamentals",
    "lld-case-studies",
  ],
};
