import type { Area } from "../types";

export const osConcurrency: Area = {
  slug: "os-concurrency",
  title: "OS & Concurrency",
  icon: "⚙️",
  stream: "CS Core",
  blurb:
    "Processes vs threads, locks and deadlocks, virtual memory, and why concurrency and parallelism are not the same word.",

  mustKnow: [
    "A process has its own address space; threads within a process share one. That single fact explains isolation, communication cost, and every data race.",
    "Concurrency is dealing with many things at once (structure); parallelism is doing many things at once (execution). Single-core systems are concurrent, not parallel.",
    "A race condition is when the result depends on timing. A data race — unsynchronised concurrent access with at least one write — is the most common cause.",
    "Deadlock needs all four Coffman conditions simultaneously: mutual exclusion, hold-and-wait, no pre-emption, circular wait. Break any one and it cannot occur.",
    "The standard deadlock prevention in application code is lock ordering: always acquire locks in the same global order.",
    "A context switch costs microseconds and flushes cache locality — cheap individually, ruinous when threads thrash.",
    "Virtual memory gives each process a private address space, translated to physical frames by the MMU using page tables and cached in the TLB.",
    "A page fault fetches a page from disk; excessive faulting is thrashing, where the system spends more time paging than working.",
    "Blocking I/O ties up a thread per operation; non-blocking/async I/O multiplexes many operations onto few threads — the core scalability difference.",
    "Prefer message passing or immutable data to shared mutable state. Most concurrency bugs are shared-state bugs.",
  ],

  sheets: [
    {
      title: "Process vs thread",
      points: [
        "Process — own address space, own file descriptors, isolated. Crash affects only itself.",
        "Thread — shares address space, heap, and file descriptors with its siblings; has its own stack and registers.",
        "Creating a process is expensive (page tables, address space); creating a thread is cheap.",
        "IPC between processes needs pipes, sockets, shared memory, or a queue — explicit and serialised.",
        "Threads communicate by shared memory — fast, and exactly why they need synchronisation.",
        "One thread crashing (segfault) usually takes the whole process with it.",
        "Rule of thumb: processes for isolation and fault tolerance, threads for cheap shared-memory concurrency.",
      ],
    },
    {
      title: "Synchronisation primitives",
      points: [
        "Mutex — mutual exclusion; one holder at a time. The default.",
        "Semaphore — counter permitting N concurrent holders; use for resource pools and rate limits.",
        "Read-write lock — many readers OR one writer; wins when reads vastly outnumber writes, but risks writer starvation.",
        "Condition variable — wait until a predicate holds; always re-check the predicate in a `while` loop (spurious wakeups).",
        "Atomic operations — lock-free single-word updates (compare-and-swap); the basis of lock-free structures.",
        "Spinlock — busy-waits instead of sleeping; only worth it for very short critical sections on multicore.",
        "Barrier — all participants wait until everyone arrives.",
        "Hold locks for the shortest possible time, and NEVER across a network call or user interaction.",
      ],
    },
    {
      title: "Deadlock, livelock, starvation",
      points: [
        "Deadlock — everyone blocked forever waiting on each other. Needs all four Coffman conditions.",
        "Prevention: global lock ordering (simplest and most used), lock timeouts with retry, `tryLock`, or acquiring all locks atomically.",
        "Livelock — threads are active but making no progress, each politely backing off in sync. Fix with randomised backoff.",
        "Starvation — a thread never gets scheduled or never acquires the lock. Fix with fair locks or priority ageing.",
        "Priority inversion — a low-priority thread holds a lock a high-priority thread needs. Fix with priority inheritance.",
        "Detection: thread dumps showing a cycle of `BLOCKED` threads; database deadlock logs naming the victim transaction.",
        "Databases usually DETECT and abort a victim rather than prevent — so application code must retry.",
      ],
    },
    {
      title: "Memory hierarchy and why locality matters",
      points: [
        "Register ~1 ns → L1 ~1 ns → L2 ~4 ns → L3 ~15 ns → RAM ~100 ns → NVMe ~100 µs → network ~0.5 ms.",
        "Cache line is typically 64 bytes — you always fetch a whole line, so adjacent data comes free.",
        "Sequential array access is far faster than pointer chasing, even at the same complexity class.",
        "False sharing: two threads writing different variables on the SAME cache line thrash it between cores. Pad to fix.",
        "TLB caches virtual→physical translations; a miss costs a page-table walk.",
        "This is why an O(n) array scan often beats an O(1) hash lookup for small n.",
      ],
    },
    {
      title: "Virtual memory",
      points: [
        "Each process sees a contiguous private address space; the MMU maps pages (usually 4 KB) to physical frames.",
        "Page table per process; the TLB caches recent translations.",
        "Page fault — the page isn't resident; the OS loads it (minor fault: already in memory elsewhere; major fault: from disk).",
        "Demand paging means memory is allocated lazily — `malloc` succeeding doesn't mean the memory exists yet.",
        "Copy-on-write: `fork` shares pages read-only and copies only on write — why forking is cheap.",
        "Swapping to disk is ~1000× slower than RAM; sustained swapping means the machine is effectively down.",
        "The OOM killer picks a victim when memory is exhausted — in containers, cgroup limits trigger it per container.",
      ],
    },
  ],

  decisions: [
    {
      title: "Threads vs async I/O",
      options: [
        {
          name: "Threads (blocking I/O)",
          pick: ["Simple, familiar control flow — code reads top to bottom.", "CPU-bound work in languages with real parallelism.", "Libraries that only offer blocking APIs."],
          cost: ["Each thread costs stack memory (often ~1 MB) — tens of thousands is impractical.", "Context switches under high concurrency.", "Shared state means locks, and locks mean races and deadlocks."],
        },
        {
          name: "Async / event loop",
          pick: ["Very high concurrency of I/O-bound work: tens of thousands of connections.", "Memory efficiency matters.", "Cooperative scheduling makes switch points explicit and easier to reason about."],
          cost: ["One blocking call stalls everything on the loop.", "Async colours the whole call stack.", "No CPU parallelism from the loop alone."],
        },
      ],
      verdict: "I/O-bound at high concurrency → async. CPU-bound or moderate concurrency with blocking libraries → threads. Many runtimes combine both.",
      topic: "threads-vs-async",
    },
    {
      title: "Mutex vs read-write lock vs lock-free",
      options: [
        {
          name: "Mutex",
          pick: ["Default. Simple, predictable, correct."],
          cost: ["Serialises all access, including reads that could have run concurrently."],
        },
        {
          name: "Read-write lock",
          pick: ["Reads vastly outnumber writes and the critical section is long enough to matter."],
          cost: ["More overhead than a mutex on short sections — often slower in practice.", "Writer starvation unless the implementation is fair."],
        },
        {
          name: "Lock-free (CAS)",
          pick: ["Extreme contention on a simple structure like a counter or queue.", "You cannot tolerate a thread being pre-empted while holding a lock."],
          cost: ["Very hard to get right; the ABA problem and memory-ordering subtleties are real.", "Retry loops can waste CPU under contention.", "Almost always the wrong first choice."],
        },
      ],
      verdict: "Start with a mutex. Measure before reaching for an RW lock, and only go lock-free with strong evidence and a library.",
      topic: "lock-free-programming",
    },
    {
      title: "Shared memory vs message passing",
      options: [
        {
          name: "Shared mutable state + locks",
          pick: ["Performance-critical paths where copying is too expensive.", "Existing codebases built this way."],
          cost: ["Every access needs discipline; a single missed lock is a heisenbug.", "Deadlocks, races, and non-reproducible failures."],
        },
        {
          name: "Message passing (channels, actors, queues)",
          pick: ["Default for new concurrent code.", "State is owned by one component and mutated only by it.", "Naturally extends across processes and machines."],
          cost: ["Copying/serialisation overhead.", "Can hide backpressure problems if the queue is unbounded."],
        },
      ],
      verdict: "Prefer message passing or immutability. Reach for shared mutable state only when profiling shows copying is the bottleneck.",
      topic: "actor-model",
    },
  ],

  qa: [
    {
      id: "os-process-thread",
      q: "Process vs thread — and when do you use each?",
      a: "A process is an instance of a program with its own virtual address space, file descriptors, and resources; a thread is an execution context within a process, with its own stack and registers but sharing the process's heap and address space with its siblings. That sharing is the whole story. Threads communicate by writing to shared memory, which is essentially free but requires synchronisation, and one thread corrupting memory or segfaulting takes the entire process down. Processes are isolated, so a crash is contained and memory corruption can't spread, but communicating means explicit IPC — pipes, sockets, or shared-memory regions — with serialisation cost. Creation cost differs too: a thread is cheap, a process requires setting up an address space, though copy-on-write makes `fork` much cheaper than it sounds. So the rule is processes for fault isolation and for sidestepping runtime limits like Python's GIL, threads for cheap concurrency where shared state is genuinely wanted.",
      why: "It underpins every concurrency decision, from Node clustering to Python multiprocessing to container design.",
      trap: "Saying threads are 'lighter processes'. The defining difference is the shared address space, not the weight.",
      followUps: ["Why does Python use processes for CPU parallelism?", "What does copy-on-write do for `fork`?"],
      depth: "Core",
      tags: ["processes", "threads"],
      topic: "processes-vs-threads",
    },
    {
      id: "os-concurrency-parallelism",
      q: "Concurrency vs parallelism.",
      a: "Concurrency is a property of the program's structure: it deals with multiple tasks whose lifetimes overlap, interleaving progress on them. Parallelism is a property of execution: multiple things literally happening at the same instant, which requires multiple cores. A single-core machine can be highly concurrent and not parallel at all — it interleaves, giving the appearance of simultaneity. Conversely you can have parallelism without meaningful concurrency, as in a data-parallel numeric kernel where one task is split across cores. Rob Pike's framing is useful: concurrency is about dealing with many things at once, parallelism is about doing many things at once. It matters practically because it tells you what a design buys you — Node's event loop and Python's threads give concurrency, so they help when tasks spend their time waiting on I/O, but neither gives parallelism, so neither speeds up arithmetic. For that you need processes, worker threads, or a native library that releases the interpreter lock.",
      why: "Conflating the two leads directly to choosing the wrong concurrency model.",
      trap: "Using them interchangeably. It's the reason people expect Node threads or Python threads to speed up CPU work.",
      followUps: ["Is Node concurrent, parallel, or both?", "What does a GIL prevent exactly?"],
      depth: "Core",
      tags: ["fundamentals"],
      topic: "concurrency-vs-parallelism",
    },
    {
      id: "os-race-condition",
      q: "What is a race condition? Give an example.",
      a: "A race condition exists when the correctness of a program depends on the relative timing of concurrent operations. The classic instance is a non-atomic read-modify-write: two threads both execute `counter++`, which compiles to load, increment, store. Both load 5, both increment to 6, both store 6 — one increment is lost, and nothing in the code looks wrong. It's insidious because it's timing-dependent: it may pass a thousand test runs and fail in production under load, and adding logging can change the timing enough to hide it. Related is check-then-act, where you test a condition and then act on it, but the condition changed in between — checking a file exists then opening it, or checking stock then decrementing it. The fixes are to make the operation atomic (an atomic increment, a compare-and-swap, or a database `UPDATE x = x + 1`), to guard it with a mutex, or to remove the sharing entirely by giving each thread its own state and combining at the end.",
      why: "It's the most common concurrency bug and the example makes the mechanism concrete rather than abstract.",
      trap: "Saying `counter++` is atomic because it's one line of source. It's three machine operations.",
      followUps: ["What's the difference between a race condition and a data race?", "How does compare-and-swap fix this?"],
      depth: "Core",
      tags: ["races", "bugs"],
      topic: "race-conditions",
    },
    {
      id: "os-deadlock",
      q: "What causes deadlock and how do you prevent it?",
      a: "Deadlock requires four conditions simultaneously — mutual exclusion, so a resource is held exclusively; hold-and-wait, so a thread holding one resource waits for another; no pre-emption, so resources can't be forcibly taken; and circular wait, so there's a cycle of threads each waiting on the next. Because all four are necessary, breaking any one prevents it, and in application code the practical lever is circular wait: impose a global ordering on locks and always acquire them in that order, so no cycle can form. If two threads both need locks A and B, and both always take A first, one simply waits. Other approaches are `tryLock` with a timeout and backoff, which turns deadlock into a retryable failure; acquiring all needed locks in one atomic step; or avoiding multiple locks entirely by restructuring around single ownership or message passing. Databases generally don't prevent deadlock — they detect the cycle, abort one transaction as the victim, and expect your application to retry, which is why retry logic on serialisation failures is mandatory.",
      why: "The four conditions give a framework rather than a list of tips, and lock ordering is the answer that gets used in practice.",
      trap: "Suggesting 'use fewer locks' as the fix. The actionable rule is consistent ordering.",
      followUps: ["How would you diagnose a deadlock in production?", "Why do databases detect rather than prevent?"],
      depth: "Intermediate",
      tags: ["deadlock", "locks"],
      topic: "deadlocks",
    },
    {
      id: "os-context-switch",
      q: "What happens during a context switch, and why does it cost?",
      a: "The kernel saves the current thread's registers, program counter, and stack pointer into its control block, selects another thread, and restores that thread's state. For a switch between processes it must also switch the address space, which means loading a new page-table base and, historically, flushing the TLB — modern CPUs mitigate this with address-space identifiers, but the effect remains. The direct cost is on the order of a microsecond, which sounds trivial. The indirect cost usually dominates: the new thread's working set isn't in cache, so it runs slowly until the caches refill, and the evicted thread will pay the same price when it resumes. That's why a system with far more runnable threads than cores can spend a large fraction of its time switching and cache-missing rather than working, and why thread pools sized to roughly the core count outperform unbounded thread creation. It's also the main argument for async I/O at high concurrency: ten thousand connections on an event loop involve no thread switching at all.",
      why: "It explains why thread pools are sized the way they are and why async scales differently.",
      trap: "Quoting only the direct microsecond cost. Cache pollution is usually the bigger effect.",
      followUps: ["Why is a process switch more expensive than a thread switch?", "How should you size a thread pool?"],
      depth: "Intermediate",
      tags: ["scheduling", "performance"],
      topic: "context-switching",
    },
    {
      id: "os-virtual-memory",
      q: "What is virtual memory and what does it buy you?",
      a: "Every process gets its own contiguous-looking address space, and the MMU translates those virtual addresses to physical frames through page tables, with recent translations cached in the TLB. It buys four things. Isolation: a process literally cannot name another's memory, so a bug can't corrupt a neighbour, which is the foundation of multi-user systems. Simplicity for the programmer: you get a flat address space regardless of how fragmented physical memory is. Overcommit and demand paging: pages are allocated lazily on first touch and can be backed by disk, so processes can address more memory than physically exists — which is why `malloc` succeeding doesn't guarantee the memory is there, and why the OOM killer exists. And efficient sharing: copy-on-write lets `fork` share pages until one side writes, and shared libraries map one physical copy into many processes. The cost is a translation on every access, mitigated by the TLB, plus page faults when a page isn't resident.",
      why: "It's the mechanism behind isolation, `fork` performance, OOM behaviour, and container memory limits.",
      trap: "Describing it as just 'using disk as extra RAM'. Swapping is one consequence; isolation and sharing are the primary purposes.",
      followUps: ["What is a page fault, and minor vs major?", "Why does `malloc` succeed when memory is exhausted?"],
      depth: "Intermediate",
      tags: ["memory"],
      topic: "virtual-memory",
    },
    {
      id: "os-false-sharing",
      q: "What is false sharing?",
      a: "Two threads on different cores writing to different variables that happen to occupy the same 64-byte cache line. Nothing is logically shared, so no synchronisation is needed for correctness, but the hardware's cache coherence protocol works at cache-line granularity: when core A writes, the line is invalidated in core B's cache, so B's next access must re-fetch it, and vice versa. The line ping-pongs between cores and performance collapses — a parallel loop that should scale linearly can end up slower than single-threaded. The classic manifestation is an array of per-thread counters, `counts[threadId]++`, where adjacent counters share a line. The fixes are to pad each element so it occupies its own cache line, to have each thread accumulate into a local variable and combine once at the end, which is usually better anyway, or to use language-level alignment attributes. It's worth knowing because it's invisible in the source — the code looks perfectly parallel.",
      why: "It's a hardware-level effect that explains otherwise-inexplicable parallel performance, and few candidates know it.",
      trap: "Assuming that avoiding shared variables avoids all sharing costs. Physical layout matters, not just logical ownership.",
      followUps: ["How would you detect it?", "Why is thread-local accumulation better than padding?"],
      depth: "Advanced",
      tags: ["performance", "caching"],
      topic: "memory-hierarchy",
    },
    {
      id: "os-thread-pool-size",
      q: "How do you size a thread pool?",
      a: "It depends entirely on what the threads do. For CPU-bound work, the answer is roughly the number of cores — more threads don't create more CPU, they just add context switching and cache pressure, so cores or cores plus one is the standard. For I/O-bound work, threads spend most of their time blocked, so you can profitably run many more; the classic formula is cores × (1 + wait time / compute time), which for a thread waiting 90% of the time suggests around ten times the core count. In practice you measure rather than compute, because the real constraint is usually downstream: if every task hits a database with a 20-connection pool, a 200-thread pool just queues 180 threads on the pool and adds latency without throughput. That's the important framing — the pool should be sized to the bottleneck resource, not to the machine. Separate pools per dependency (the bulkhead pattern) stop one slow downstream from consuming all threads, and a bounded queue with a rejection policy is essential so overload sheds load rather than exhausting memory.",
      why: "It's a practical tuning question where the reasoning matters far more than the formula.",
      trap: "Setting a large pool to 'handle more load'. Beyond the bottleneck's capacity you add latency and memory, not throughput.",
      followUps: ["Why separate pools per dependency?", "What should happen when the queue is full?"],
      depth: "Advanced",
      tags: ["performance", "tuning"],
    },
    {
      id: "os-memory-barrier",
      q: "Why do you need memory barriers or volatile?",
      a: "Because neither the compiler nor the CPU executes your code in the order you wrote it. Compilers reorder and cache values in registers; CPUs execute out of order and buffer writes. On a single thread this is invisible because the hardware preserves the appearance of sequential execution for that thread. Across threads it is very visible: thread A sets `data = 42` then `ready = true`, and thread B sees `ready` become true while still reading a stale `data`, because the two writes became visible in the other order. A memory barrier constrains that reordering, and language-level tools express it — Java's `volatile` guarantees visibility and ordering around the access, C++ has explicit memory orderings on atomics, and higher-level primitives like mutexes include the necessary barriers, which is why correctly-locked code doesn't need explicit ones. The practical advice is to use language-provided synchronisation rather than hand-rolling with barriers, because getting the orderings right is genuinely difficult and the failures are rare and non-reproducible.",
      why: "It's the depth question for concurrency and separates people who've written lock-free code from those who haven't.",
      trap: "Thinking `volatile` in Java means the same as in C. In C/C++ it's about memory-mapped I/O and gives no thread-safety guarantees.",
      followUps: ["What does a mutex guarantee beyond mutual exclusion?", "What is the happens-before relationship?"],
      depth: "Advanced",
      tags: ["memory-model"],
      topic: "memory-models",
    },
    {
      id: "os-blocking-io",
      q: "Why doesn't thread-per-connection scale?",
      a: "Because a thread is expensive in a way a connection isn't. Each thread reserves stack space — commonly around a megabyte of virtual address space, with physical pages committed as used — so ten thousand connections means gigabytes reserved and a real memory footprint even though almost every thread is idle waiting on a socket. Beyond memory, the scheduler now has ten thousand runnable-ish entities, so context switching and cache pollution consume a growing share of CPU, and the switching cost rises faster than the useful work. The alternative is to decouple connections from threads: use non-blocking sockets and an event notification mechanism — epoll, kqueue, IOCP — so a small number of threads can watch many sockets and act only on the ones that are ready. Then a connection costs a file descriptor and a small buffer rather than a thread, which is what makes hundreds of thousands of concurrent connections practical. That's exactly the architecture behind Node, nginx, and Go's runtime, though Go hides it behind cheap goroutines that look like threads.",
      why: "It's the C10K problem, and it explains the design of every modern high-concurrency server.",
      trap: "Blaming context switching alone. Memory per thread is usually the first wall you hit.",
      followUps: ["What does epoll do differently from select?", "How do goroutines get the best of both?"],
      depth: "Advanced",
      tags: ["io", "scaling"],
      topic: "threads-vs-async",
    },
    {
      id: "os-cpu-scheduling",
      q: "How does the OS decide which thread runs next?",
      a: "A scheduler picks from the runnable threads according to a policy balancing fairness, throughput, and latency. Linux's default, CFS and now EEVDF, is fair-share: it tracks how much CPU time each thread has received relative to its weight and runs the one that's furthest behind, which approximates giving every thread an equal slice without fixed time quanta. Priorities and nice values adjust the weights, and real-time classes exist for threads that need bounded latency. Threads leave the CPU either voluntarily, by blocking on I/O or a lock, or involuntarily, by being pre-empted when their fair share is exhausted or a higher-priority thread becomes runnable. Two practical consequences: an I/O-bound thread tends to get scheduled promptly because it uses little CPU and is always behind, which is why interactive work stays responsive alongside batch work; and in containers, CPU limits are enforced by cgroup quotas, so a container exceeding its quota is throttled for the rest of the period — which shows up as latency spikes that look like GC pauses but aren't.",
      why: "The cgroup throttling connection is a real production debugging insight.",
      trap: "Describing scheduling as simple round-robin. Modern schedulers are weighted fair-share, which is why priorities behave the way they do.",
      followUps: ["What is CPU throttling in Kubernetes and how do you spot it?", "Why do I/O-bound threads feel responsive?"],
      depth: "Advanced",
      tags: ["scheduling"],
      topic: "cpu-scheduling",
    },
  ],

  pitfalls: [
    "Don't use concurrency and parallelism interchangeably — structure versus simultaneous execution.",
    "Don't call threads 'lightweight processes' — the shared address space is the defining difference.",
    "Don't say `counter++` is atomic — it's load, increment, store.",
    "Don't answer deadlock prevention with 'use fewer locks' — say consistent global lock ordering.",
    "Don't hold a lock across a network call or user think-time.",
    "Don't size a thread pool to the machine — size it to the bottleneck resource downstream.",
    "Don't assume avoiding shared variables avoids sharing costs — false sharing is about cache lines.",
    "Don't reach for lock-free algorithms before profiling; a mutex is almost always the right first answer.",
  ],

  numbers: [
    { label: "L1 cache / RAM / SSD", value: "~1 ns / ~100 ns / ~100 µs", note: "Each step is roughly 100×." },
    { label: "Context switch", value: "~1–5 µs direct", note: "Cache pollution usually costs more than the switch." },
    { label: "Thread stack (default)", value: "~1 MB", note: "Why thread-per-connection hits a memory wall." },
    { label: "Cache line", value: "64 bytes", note: "The unit of false sharing." },
    { label: "Page size", value: "4 KB", note: "Huge pages of 2 MB reduce TLB pressure." },
    { label: "CPU-bound pool size", value: "≈ cores", note: "I/O-bound: cores × (1 + wait/compute), capped by the downstream bottleneck." },
  ],

  relatedTopics: ["processes-vs-threads", "concurrency-vs-parallelism", "race-conditions", "deadlocks", "locks-and-atomics", "synchronization-primitives", "context-switching", "virtual-memory", "memory-hierarchy", "threads-vs-async", "cpu-scheduling"],
};
