import type { Area } from "../types";

export const python: Area = {
  slug: "python",
  title: "Python",
  icon: "🐍",
  stream: "Language & Runtime",
  blurb:
    "The GIL, mutable defaults, generators, and the concurrency model — plus the idioms interviewers expect from anyone doing backend or ML work.",

  mustKnow: [
    "Everything is an object with a reference. Assignment binds a name to an object; it never copies. `b = a` on a list gives two names for one list.",
    "Mutable vs immutable: `list`, `dict`, `set` mutate in place; `int`, `str`, `tuple`, `frozenset` do not. This decides argument behaviour, dict keys, and hashability.",
    "The GIL lets only one thread execute Python bytecode at a time, so threads give concurrency for I/O but no parallelism for CPU. Use `multiprocessing` or native extensions for CPU parallelism.",
    "A default argument is evaluated ONCE at function definition. `def f(x=[])` shares one list across all calls — use `None` as the sentinel.",
    "Generators produce values lazily and hold constant memory; a list comprehension materialises everything.",
    "List/dict/set comprehensions are the idiomatic transform; a `for` loop that only appends is a comprehension written the long way.",
    "`is` compares identity, `==` compares value. Use `is` only for `None`, `True`, `False`.",
    "`__init__` initialises an already-created instance; `__new__` creates it. You almost always want `__init__`.",
    "Decorators are functions returning functions — they wrap behaviour without touching the wrapped code. `@property`, `@staticmethod`, `@classmethod`, `@lru_cache`, `@dataclass` are the ones to know cold.",
    "Context managers (`with`) guarantee cleanup via `__enter__`/`__exit__`, even on exception — the right way to handle files, locks, transactions, and connections.",
  ],

  sheets: [
    {
      title: "Data structure complexity",
      points: [
        "`list` — index O(1), append O(1) amortised, insert/delete at front O(n), `in` O(n).",
        "`dict` / `set` — insert, lookup, delete O(1) average, O(n) worst case; `dict` preserves insertion order since 3.7 (guaranteed).",
        "`collections.deque` — O(1) append and pop at BOTH ends; use for queues and sliding windows instead of `list.pop(0)`.",
        "`heapq` — min-heap on a list; push/pop O(log n), `heapify` O(n). For a max-heap, negate the values.",
        "`collections.Counter` — frequency counting plus `most_common(k)`.",
        "`collections.defaultdict` — avoids the `if key not in d` dance.",
        "`bisect` — binary search into a sorted list, O(log n) search, O(n) insert.",
        "`str` is immutable — building with `+=` in a loop is O(n²); use `''.join(parts)`.",
      ],
    },
    {
      title: "Concurrency model — what to use when",
      points: [
        "`asyncio` — thousands of concurrent I/O operations in one thread; needs async-native libraries (`httpx`, `asyncpg`). One blocking call stalls the whole loop.",
        "`threading` — I/O-bound work with blocking libraries. The GIL is released during I/O, so threads genuinely overlap there.",
        "`multiprocessing` — CPU-bound work. Separate processes, separate GILs, real parallelism; costs process startup and pickling data across the boundary.",
        "`concurrent.futures` — one uniform API over both pools: `ThreadPoolExecutor` for I/O, `ProcessPoolExecutor` for CPU.",
        "Native extensions (NumPy, Polars, PyTorch) release the GIL internally, so CPU work in them already parallelises.",
        "Python 3.13+ has an experimental free-threaded (no-GIL) build; not yet the default.",
        "`asyncio.run(main())` is the entry point; `await asyncio.gather(*tasks)` runs coroutines concurrently.",
      ],
    },
    {
      title: "Common gotchas",
      points: [
        "Mutable default argument — evaluated once at def time; use `def f(x=None): x = x or []`.",
        "Late binding in closures: `[lambda: i for i in range(3)]` all return 2. Fix with `lambda i=i: i`.",
        "`list * n` on nested lists copies the REFERENCE: `[[0]*3]*3` gives three aliases of one row.",
        "Modifying a list while iterating over it skips elements — iterate over a copy or build a new list.",
        "`copy.copy` is shallow; `copy.deepcopy` is deep and slow.",
        "Integer caching means `a is b` may be True for small ints and False for large ones — never use `is` for numbers.",
        "Bare `except:` catches `KeyboardInterrupt` and `SystemExit` too — catch `Exception` at minimum, specific types ideally.",
        "Class attributes are shared across instances; assigning `self.x` creates an instance attribute that shadows it.",
      ],
    },
    {
      title: "Idioms interviewers look for",
      points: [
        "`enumerate(xs)` instead of `range(len(xs))`; `zip(a, b)` to walk in parallel.",
        "Unpacking: `a, b = b, a`; `first, *rest = xs`.",
        "`with open(path) as f:` — never a bare `open` without cleanup.",
        "f-strings for formatting; `f'{x=}'` for quick debugging.",
        "`dict.get(k, default)` and `dict.setdefault`; `collections.defaultdict` for accumulation.",
        "`any()` / `all()` with a generator instead of a loop with a flag.",
        "`sorted(xs, key=lambda o: (o.a, o.b))` for multi-key sorts; `functools.cmp_to_key` only when unavoidable.",
        "`pathlib.Path` over `os.path` string juggling.",
        "Type hints on public functions, checked with mypy/pyright — increasingly expected in backend and ML code.",
      ],
    },
    {
      title: "Memory and the object model",
      points: [
        "CPython uses reference counting plus a cycle-detecting generational GC.",
        "Reference cycles need the GC; `__del__` on objects in a cycle used to be problematic (fine since 3.4).",
        "`__slots__` removes the per-instance `__dict__`, cutting memory substantially for many small objects.",
        "Generators and `itertools` keep memory constant over large inputs.",
        "Everything is boxed — a Python `int` is far larger than a machine word; use NumPy arrays for numeric bulk data.",
        "`sys.getsizeof` measures the object only, not what it references.",
      ],
    },
  ],

  decisions: [
    {
      title: "`asyncio` vs `threading` vs `multiprocessing`",
      options: [
        {
          name: "asyncio",
          pick: ["High-concurrency I/O: API gateways, web scrapers, chat servers, LLM calls.", "Thousands of concurrent waits with tiny per-task overhead."],
          cost: ["Requires async-native libraries top to bottom; one blocking call freezes everything.", "Async colours your whole call stack — `async` propagates upward."],
        },
        {
          name: "threading",
          pick: ["I/O-bound work using blocking libraries you can't replace.", "Modest concurrency where simplicity matters."],
          cost: ["No CPU parallelism because of the GIL.", "Shared mutable state means locks, and locks mean deadlocks and races."],
        },
        {
          name: "multiprocessing",
          pick: ["CPU-bound work: data transforms, image processing, simulations.", "You need real parallelism across cores."],
          cost: ["Process startup cost and memory per process; arguments and results are pickled, so large data is expensive to move.", "No shared memory by default."],
        },
      ],
      verdict: "I/O-bound with async libraries → asyncio. I/O-bound with blocking libraries → threads. CPU-bound → processes (or a native library that releases the GIL).",
      topic: "concurrency-models-backend",
    },
    {
      title: "List comprehension vs generator expression",
      options: [
        {
          name: "List comprehension `[...]`",
          pick: ["You need the result more than once, or need `len`, indexing, or slicing.", "The collection is small and you want it materialised."],
          cost: ["Allocates the whole result — memory proportional to size, and a 10 GB file becomes 10 GB of RAM."],
        },
        {
          name: "Generator `(...)`",
          pick: ["Iterating once, especially over something large or unbounded.", "Chaining transforms — memory stays constant through the pipeline.", "Feeding `sum`, `any`, `all`, `max`."],
          cost: ["Single-use — exhausted after one pass. No `len` or indexing.", "Harder to debug, since values don't exist until pulled."],
        },
      ],
      verdict: "Iterate once over something big → generator. Need it repeatedly or need random access → list.",
    },
    {
      title: "`dataclass` vs `NamedTuple` vs Pydantic vs plain class",
      options: [
        {
          name: "@dataclass",
          pick: ["Internal data containers — free `__init__`, `__repr__`, `__eq__`.", "`frozen=True` for immutability and hashability."],
          cost: ["Type hints are NOT enforced at runtime; you can pass a string where an int is declared."],
        },
        {
          name: "NamedTuple",
          pick: ["Small immutable records where tuple behaviour (unpacking, indexing) is useful.", "Lightest memory footprint."],
          cost: ["Immutable by design; awkward when you need to evolve the shape."],
        },
        {
          name: "Pydantic model",
          pick: ["Any external boundary: API request/response, config, env vars, LLM structured output.", "You want validation, coercion, and JSON schema generation."],
          cost: ["A dependency plus per-instance validation cost — real but usually trivial next to I/O."],
        },
      ],
      verdict: "Internal container → dataclass. External/untrusted data → Pydantic. Tiny immutable record → NamedTuple.",
    },
    {
      title: "Python vs a compiled language for a service",
      options: [
        {
          name: "Python",
          pick: ["ML/AI work — the entire ecosystem lives here.", "Speed of development, data processing, glue code, scripting.", "I/O-bound services where runtime speed isn't the bottleneck."],
          cost: ["10–100× slower than compiled languages for pure CPU work.", "The GIL blocks in-process CPU parallelism.", "Dynamic typing needs discipline and tooling to scale to large teams."],
        },
        {
          name: "Go / Rust / Java",
          pick: ["CPU-bound or latency-critical services.", "High-throughput infrastructure where per-request cost matters.", "Large teams wanting compile-time guarantees."],
          cost: ["Slower to write; far weaker ML ecosystem; more ceremony for simple work."],
        },
      ],
      verdict: "Python for ML and I/O-bound services; compiled languages for CPU-bound or latency-critical paths. Mixing them — Python orchestration with hot paths in Rust/C — is common and correct.",
    },
  ],

  qa: [
    {
      id: "py-gil",
      q: "What is the GIL and what does it mean for your code?",
      a: "The Global Interpreter Lock is a mutex in CPython allowing only one thread to execute Python bytecode at a time. It exists because CPython's memory management uses non-atomic reference counting, and the GIL makes that safe without fine-grained locking everywhere. The consequence is that threads give you no CPU parallelism — four threads doing arithmetic run about as fast as one, sometimes slower because of contention. But threads still help for I/O, because the GIL is released while waiting on the network or disk, so other threads run during the wait. For CPU parallelism you use `multiprocessing`, which gives each process its own interpreter and GIL, or native libraries like NumPy and PyTorch that release the GIL while executing C code. Python 3.13 ships an experimental free-threaded build without the GIL, but it isn't the default and carries a single-thread performance cost.",
      why: "It's the defining constraint of Python's concurrency model and drives every architectural decision around it.",
      trap: "Saying threads are useless in Python. They're the right tool for I/O-bound work with blocking libraries.",
      followUps: ["Why does NumPy parallelise despite the GIL?", "When would you use threads over asyncio?"],
      depth: "Core",
      tags: ["concurrency", "gil"],
      topic: "concurrency-vs-parallelism",
    },
    {
      id: "py-mutable-default",
      q: "What's wrong with `def f(items=[])`?",
      a: "The default is evaluated once, when the function is defined, not on each call. So every call that doesn't pass `items` shares the same list object, and appends accumulate across calls — call it three times and the third sees everything from the first two. The same applies to `{}`, and to any mutable or expensive expression like `datetime.now()`, which would freeze the import-time value forever. The fix is a `None` sentinel: `def f(items=None): items = [] if items is None else items`. This trips people up because it looks like a per-call default, and because the bug only appears on the second call, which unit tests that call once will never catch.",
      why: "It's the classic Python gotcha and a quick check on whether someone understands when code executes.",
      trap: "Thinking it's a linting nitpick. It's a real shared-state bug that produces wrong results silently.",
      followUps: ["Why does `def f(t=datetime.now())` have the same problem?", "How would you write a default that IS re-evaluated?"],
      depth: "Core",
      tags: ["gotchas", "functions"],
    },
    {
      id: "py-generator",
      q: "What's the difference between a generator and a list, and when does it matter?",
      a: "A list computes and stores every element up front; a generator computes each one on demand and holds only the current state. For a million rows that's the difference between hundreds of megabytes and a few hundred bytes. Generators are created with a `yield` in a function or a parenthesised comprehension, and they're lazy — nothing runs until you iterate. They compose beautifully: chaining generators builds a pipeline where each element flows through all stages without any intermediate collection existing, which is how you process a file larger than RAM. The limitations are that they're single-use, exhausted after one pass, and support no `len` or indexing. So the rule is: iterating once over something large, use a generator; needing the data repeatedly or randomly, use a list.",
      why: "Memory-conscious data processing is core to both backend and ML work.",
      trap: "Iterating a generator twice and getting nothing the second time — it's exhausted, not empty.",
      followUps: ["How does `yield from` help?", "What does `itertools.islice` give you here?"],
      depth: "Core",
      tags: ["generators", "memory"],
    },
    {
      id: "py-mutable-args",
      q: "Is Python pass-by-value or pass-by-reference?",
      a: "Neither, precisely — it's pass-by-object-reference (sometimes called pass-by-assignment). The function receives a reference to the same object the caller has, so mutating it is visible to the caller: appending to a list argument changes the caller's list. But rebinding the parameter name inside the function only changes the local name, leaving the caller's binding untouched — so `def f(x): x = [1]` has no external effect while `def f(x): x.append(1)` does. The distinction lands on mutability: immutable objects like `int`, `str`, and `tuple` can't be changed in place, so they behave as if passed by value, while lists, dicts, and sets can. This is why accepting a mutable argument and modifying it is a design decision worth making explicitly, and why returning a new object is usually clearer.",
      why: "It explains a whole class of surprising side-effect bugs.",
      trap: "Saying 'immutable types are passed by value'. The mechanism is identical; immutability just makes mutation impossible.",
      followUps: ["Why does `x += [1]` differ from `x = x + [1]` for a list parameter?"],
      depth: "Intermediate",
      tags: ["semantics"],
    },
    {
      id: "py-decorator",
      q: "How does a decorator work? Write one.",
      a: "A decorator is a function taking a function and returning a replacement; `@dec` above `def f` is just `f = dec(f)`. A timing decorator: define `def timer(fn)`, inside it `@functools.wraps(fn)` on a `def wrapper(*args, **kwargs)` that records the start time, calls `fn(*args, **kwargs)`, logs the elapsed time, and returns the result; then return `wrapper`. Two details matter. `*args, **kwargs` keeps it usable on any signature. And `functools.wraps` copies over `__name__`, `__doc__`, and the signature — without it the decorated function reports itself as `wrapper`, which breaks introspection, documentation tools, and some frameworks that inspect signatures. For a decorator that takes arguments you need a third layer: a function returning the decorator returning the wrapper.",
      why: "Decorators are everywhere in Flask, FastAPI, pytest, and Django, so being able to write one is expected.",
      trap: "Omitting `functools.wraps`. It works until something introspects the function, then breaks confusingly.",
      followUps: ["Write a decorator that takes an argument, like `@retry(times=3)`.", "How does `@property` work?"],
      depth: "Intermediate",
      tags: ["decorators", "functions"],
    },
    {
      id: "py-context-manager",
      q: "What is a context manager and why use one?",
      a: "An object defining `__enter__` and `__exit__` so that `with` guarantees setup and teardown, including when an exception is raised or the block returns early. That guarantee is the point: `f = open(path)` followed by `f.close()` leaks the descriptor if anything in between throws, while `with open(path) as f:` cannot. The pattern generalises well beyond files — acquiring and releasing a lock, opening and committing or rolling back a database transaction, temporarily changing a setting and restoring it, timing a block. Writing one is easiest with `contextlib.contextmanager`: a generator that yields once, with the setup before the `yield` and the teardown in a `finally`. `__exit__` receives the exception details and can suppress the exception by returning True, which you should do sparingly.",
      why: "It's the idiomatic Python answer to resource safety, equivalent to RAII elsewhere.",
      trap: "Doing cleanup in a `finally` by hand everywhere. It works, but it's the manual version of a language feature.",
      followUps: ["Write a context manager that times a block.", "How does `__exit__` suppress an exception?"],
      depth: "Intermediate",
      tags: ["context-managers", "resources"],
    },
    {
      id: "py-asyncio",
      q: "How does `asyncio` differ from threading?",
      a: "Both give concurrency for I/O, but the switching model differs. Threads are pre-emptive — the OS can switch at any bytecode boundary, so shared state needs locks and races are possible anywhere. `asyncio` is cooperative and single-threaded: a coroutine runs until it hits an `await`, then explicitly yields control to the event loop. That makes reasoning easier, since you know exactly where a switch can happen, and it's far cheaper — coroutines cost bytes, threads cost megabytes of stack, so tens of thousands of concurrent connections are practical. The costs are real too: everything in the path must be async-aware, because a single blocking call — a synchronous database driver, `time.sleep`, or a CPU-heavy loop — freezes the entire loop and all its tasks. When you must call blocking code, wrap it in `asyncio.to_thread` or a thread pool executor.",
      why: "It's the standard Python concurrency question and the blocking-call failure mode is what actually bites in production.",
      trap: "Using `time.sleep` or a blocking `requests` call inside a coroutine. That stalls every other task on the loop.",
      followUps: ["How do you call blocking code from async?", "What does `asyncio.gather` do versus a loop of awaits?"],
      depth: "Intermediate",
      tags: ["asyncio", "concurrency"],
      topic: "threads-vs-async",
    },
    {
      id: "py-mro",
      q: "How does Python resolve methods with multiple inheritance?",
      a: "Through the MRO — the method resolution order — computed by the C3 linearisation algorithm, which produces a single ordering that preserves each parent's own order and ensures a class always precedes its ancestors. You can inspect it with `Class.__mro__`. `super()` doesn't mean 'my parent'; it means 'the next class in the MRO of the actual instance's type', which is why cooperative multiple inheritance works: each class calls `super().__init__()` and the chain walks the whole diamond exactly once, rather than calling a shared base twice. The practical rules are to always call `super()` rather than naming a parent class explicitly, and to accept `**kwargs` in cooperative `__init__` methods so arguments can flow through. If C3 can't produce a consistent order, Python raises a `TypeError` at class definition time.",
      why: "It's the depth question for OOP in Python and shows whether someone understands `super()` properly.",
      trap: "Thinking `super()` calls the immediate parent class. It follows the MRO of the runtime type, which may not be the class you wrote.",
      followUps: ["What is the diamond problem and how does C3 solve it?", "Why prefer composition here?"],
      depth: "Advanced",
      tags: ["oop", "inheritance"],
      topic: "inheritance",
    },
    {
      id: "py-memory",
      q: "How does Python manage memory?",
      a: "CPython uses reference counting as the primary mechanism: every object tracks how many references point at it, and it's freed immediately when that count hits zero. That's deterministic and prompt, which is nice, but it can't reclaim reference cycles — two objects pointing at each other keep each other alive even when nothing else references them. So there's also a generational cycle-detecting garbage collector, running periodically over three generations on the theory that most objects die young. Practical implications: cycles are collected but not immediately, so `__del__`-based cleanup shouldn't be relied on for timing; large objects freed inside a function are reclaimed at once thanks to refcounting; and memory returned to the allocator isn't always returned to the OS, so RSS may not drop after a spike. For many small objects, `__slots__` removes the per-instance dict and cuts memory substantially.",
      why: "It's a good discriminator between people who've profiled a Python service and those who haven't.",
      trap: "Saying Python 'just has a garbage collector' like Java. Refcounting is the primary mechanism; the GC exists specifically for cycles.",
      followUps: ["Why can't refcounting collect cycles?", "What does `__slots__` save?"],
      depth: "Advanced",
      tags: ["memory", "gc"],
      topic: "garbage-collection",
    },
    {
      id: "py-shallow-deep",
      q: "Shallow vs deep copy in Python.",
      a: "`copy.copy(x)` creates a new outer object whose elements are the same references as the original's, so mutating a nested list is visible through both. `copy.deepcopy(x)` recursively copies everything, producing a fully independent structure — and it correctly handles cycles by memoising objects it has already copied. Slicing (`xs[:]`), `list(xs)`, and `dict(d)` are all shallow. The classic bug is `grid = [[0] * 3] * 3`, which doesn't even shallow-copy — the multiplication repeats the same inner list reference three times, so `grid[0][0] = 1` changes all three rows; you want `[[0] * 3 for _ in range(3)]`. Deep copy is slow and can be surprising with objects holding file handles or database connections, so for configuration and data transfer it's often better to reconstruct from a serialised form or to design for immutability instead.",
      why: "Aliasing bugs are common, and the `[[0]*3]*3` case is a memorable, concrete test.",
      trap: "Believing `[:]` deep-copies a nested list. It copies the outer list only.",
      followUps: ["Why does `[[0]*3]*3` alias?", "When is deepcopy a bad idea?"],
      depth: "Intermediate",
      tags: ["gotchas", "objects"],
    },
    {
      id: "py-dunder",
      q: "Which dunder methods matter, and what do they enable?",
      a: "`__init__` initialises an instance and `__new__` creates it — you override `__new__` only for immutable types or metaclass tricks. `__repr__` should give an unambiguous developer-facing string, ideally one that could recreate the object, and `__str__` a friendly one; if you define only one, define `__repr__`, since it's the fallback. `__eq__` and `__hash__` travel together: define `__eq__` and Python sets `__hash__` to None, making the object unhashable, so you must define both to use it in a set or as a dict key, and both must be consistent. `__iter__` and `__next__` make it iterable; `__len__` and `__getitem__` make it sequence-like; `__enter__`/`__exit__` make it a context manager; `__call__` makes an instance callable. These are the protocol hooks that make custom classes work with built-in syntax, which is what 'Pythonic' means in practice.",
      why: "It shows whether someone can write classes that integrate with the language rather than just hold data.",
      trap: "Defining `__eq__` without `__hash__` and then being confused when the object can't go in a set.",
      followUps: ["Why must `__eq__` and `__hash__` agree?", "When would you override `__new__`?"],
      depth: "Intermediate",
      tags: ["oop", "protocols"],
    },
    {
      id: "py-typing",
      q: "Do type hints do anything at runtime?",
      a: "Essentially nothing — the interpreter stores them in `__annotations__` and otherwise ignores them, so passing a string where `int` is annotated runs happily until something else breaks. Their value is in tooling: mypy or pyright check them in CI and in your editor, giving you the refactoring safety and autocomplete that dynamic typing otherwise costs you. Some libraries do read them at runtime and act on them — Pydantic validates and coerces based on annotations, FastAPI derives request parsing, validation, and OpenAPI docs from them, and `dataclasses` uses them to generate `__init__` — but that's those libraries choosing to introspect, not the language enforcing. So the practical stance is: annotate public functions, run a type checker in CI, and validate external data with Pydantic rather than assuming an annotation protects you.",
      why: "The 'hints aren't enforcement' point is important and frequently misunderstood in ML codebases.",
      trap: "Assuming a `-> int` annotation guarantees an int comes back. Nothing checks it unless you run a checker.",
      followUps: ["How does FastAPI use annotations?", "What does `from __future__ import annotations` change?"],
      depth: "Intermediate",
      tags: ["typing"],
      topic: "type-systems",
    },
    {
      id: "py-slow-loop",
      q: "A Python data-processing script is too slow. What do you do?",
      a: "Profile first — `cProfile` for function-level costs, `line_profiler` for line-level, and check whether you're actually CPU-bound or waiting on I/O, because the fixes are entirely different. If it's I/O, add concurrency: threads or asyncio, and batch the requests or queries; an N+1 query pattern is the usual culprit. If it's CPU, the biggest wins usually come from vectorising rather than micro-optimising: replacing a Python loop over a million rows with a NumPy or Polars operation moves the work into C and typically gives one to two orders of magnitude. Then check algorithmic complexity — an accidental O(n²) from a `list` membership test inside a loop is fixed by switching to a `set`. After that: `multiprocessing` to use all cores, `functools.lru_cache` for repeated pure calls, and only then reach for Cython, Numba, or a Rust extension for the genuinely hot inner loop.",
      why: "The ordering — profile, then vectorise, then parallelise, then rewrite — is what distinguishes a systematic engineer.",
      trap: "Jumping to multiprocessing before checking for an accidental O(n²) or an unvectorised loop.",
      followUps: ["Why is `x in list` inside a loop dangerous?", "When is Numba worth it over NumPy?"],
      depth: "Advanced",
      tags: ["performance"],
      topic: "profiling",
    },
    {
      id: "py-packaging",
      q: "How do you manage dependencies and environments?",
      a: "Isolate per project — never install into the system Python. A virtual environment (`venv`) plus `pip` is the baseline, but modern practice is a tool that manages the lockfile too: `uv` (very fast, now the common default), Poetry, or PDM. The key distinction is between the declared dependencies in `pyproject.toml`, which express what you need, and the lockfile, which pins exact transitive versions so every machine and CI run installs identical bytes. Without a lock, a transitive dependency releasing a new version breaks a build that changed nothing. For deployment, install from the lockfile in a Docker image using a multi-stage build so build tools don't ship to production, and pin the base image by digest. `requirements.txt` still works, but it conflates declarations and pins unless you split it into a `.in` and a compiled output.",
      why: "Dependency handling is where Python projects rot, and this shows operational maturity.",
      trap: "Committing only `requirements.txt` from `pip freeze`. It pins everything including your own transitive tree, but expresses no intent, so upgrades become guesswork.",
      followUps: ["Why does a lockfile matter for reproducibility?", "How would you structure a Dockerfile for a Python service?"],
      depth: "Advanced",
      tags: ["tooling", "deployment"],
      topic: "config-management",
    },
    {
      id: "py-exceptions",
      q: "How should you handle exceptions in Python?",
      a: "Catch narrowly and only what you can act on. A bare `except:` also swallows `KeyboardInterrupt` and `SystemExit`, so at minimum catch `Exception`, and preferably the specific types you expect. Use `else` for the code that should run only if no exception occurred, and `finally` — or better, a context manager — for cleanup that must always happen. When re-raising after adding context, use `raise NewError(...) from err` so the original traceback is preserved in the chain; a bare `raise` re-raises the current exception unchanged. Define your own exception hierarchy rooted at a project base class so callers can catch broadly or narrowly as they choose. And the cultural point: Python favours EAFP — try the operation and handle the failure — over LBYL's pre-checks, because pre-checks are racy and often duplicate work the operation does anyway.",
      why: "Exception discipline is visible in every code review and separates careful engineers.",
      trap: "`except Exception: pass`. It converts a loud failure into silent wrong behaviour.",
      followUps: ["What does `raise ... from err` preserve?", "When is LBYL better than EAFP?"],
      depth: "Intermediate",
      tags: ["errors"],
      topic: "error-handling",
    },
    {
      id: "py-lru-cache",
      q: "When would you use `functools.lru_cache`?",
      a: "For a pure function whose calls repeat with the same arguments and whose computation is more expensive than a dict lookup — recursive algorithms, parsing, expensive derivations from a fixed input. It memoises by argument tuple, which brings three requirements worth stating: the arguments must be hashable, so lists and dicts can't be passed directly; the function must be genuinely pure, since caching one that reads mutable state or does I/O returns stale results; and you should set `maxsize` rather than accepting unbounded growth, because caching on user-supplied input with no bound is a memory leak. It's also a lifetime trap on methods — decorating an instance method caches `self` too, keeping every instance alive forever. `functools.cache` is the unbounded shorthand, appropriate only for a small fixed key space.",
      why: "It's easy to use and easy to misuse; the caveats are what matter.",
      trap: "Putting it on a method or on a function that hits a database. The first leaks instances, the second serves stale data.",
      followUps: ["Why does it leak when used on a method?", "How would you cache on an unhashable argument?"],
      depth: "Intermediate",
      tags: ["caching", "functions"],
    },
  ],

  pitfalls: [
    "Don't say threads are useless in Python — they're right for I/O-bound work; the GIL only blocks CPU parallelism.",
    "Don't use a mutable default argument — it's evaluated once at definition and shared across calls.",
    "Don't say Python is pass-by-reference — it's pass-by-object-reference; rebinding a parameter doesn't affect the caller.",
    "Don't claim type hints are enforced — nothing checks them at runtime unless a library chooses to introspect.",
    "Don't use `is` to compare numbers or strings — small-integer and string interning make it unreliable.",
    "Don't write bare `except:` — it swallows `KeyboardInterrupt` and `SystemExit`.",
    "Don't build strings with `+=` in a loop — it's O(n²); use `''.join()`.",
    "Don't reach for multiprocessing before checking for an accidental O(n²) or an unvectorised loop.",
  ],

  numbers: [
    { label: "dict/set lookup", value: "O(1) average", note: "O(n) worst case on hash collisions." },
    { label: "`list.pop(0)`", value: "O(n)", note: "Use `collections.deque` for O(1) at both ends." },
    { label: "NumPy vs Python loop", value: "10–100×", note: "Typical speedup from vectorising a numeric loop." },
    { label: "dict ordered by insertion", value: "3.7+", note: "Implementation detail in 3.6, guaranteed from 3.7." },
    { label: "Free-threaded (no-GIL) build", value: "3.13+, experimental", note: "Not the default; costs single-thread performance." },
  ],

  relatedTopics: [
    "concurrency-vs-parallelism",
    "threads-vs-async",
    "concurrency-models-backend",
    "garbage-collection",
    "inheritance",
    "error-handling",
    "type-systems",
    "profiling",
  ],
};
