import type { Area } from "../types";

export const rag: Area = {
  slug: "rag",
  title: "RAG & Vector Search",
  icon: "📚",
  stream: "AI Engineering",
  blurb:
    "Chunking, hybrid retrieval, reranking, and the uncomfortable truth that most RAG failures are retrieval failures, not model failures.",

  mustKnow: [
    "RAG = retrieve relevant context at query time, put it in the prompt, generate an answer grounded in it. The model's weights are untouched.",
    "It exists to solve four things at once: knowledge the model never saw, knowledge that changes, citations for auditability, and per-user access control.",
    "The quality ceiling is retrieval. If the right chunk isn't retrieved, no prompt or model fixes it — so debug retrieval first, always.",
    "Chunking is the highest-leverage decision. Too small loses context, too large dilutes the embedding and wastes tokens.",
    "Hybrid search — dense vectors plus keyword/BM25 — beats either alone, because vectors miss exact terms (error codes, names, SKUs) and keywords miss paraphrase.",
    "A reranker (cross-encoder) applied to the top ~50 candidates is usually the single biggest quality win per unit of effort.",
    "Embeddings capture semantic SIMILARITY, which is not the same as answering the question — that gap is why reranking exists.",
    "You must use the same embedding model for indexing and querying; vectors from different models are not comparable.",
    "Always return citations to the retrieved spans, and evaluate whether the answer is actually supported by them.",
    "Evaluate retrieval and generation separately, or you can't tell which half is broken.",
  ],

  sheets: [
    {
      title: "The pipeline, stage by stage",
      points: [
        "Ingest → parse (PDF/HTML/DOCX), clean boilerplate, keep structure (headings, tables).",
        "Chunk → split with overlap; attach metadata (source, section, date, permissions, URL).",
        "Embed → one vector per chunk, using the SAME model you'll use at query time.",
        "Index → vector store (HNSW/IVF) + a keyword index for hybrid.",
        "Query → optionally rewrite/expand the question; embed it.",
        "Retrieve → top-k dense + top-k sparse, fused (Reciprocal Rank Fusion is the standard, and needs no score calibration).",
        "Rerank → cross-encoder over ~50 candidates, keep the top 3–8.",
        "Assemble → order chunks with the strongest at the start and end; include source labels for citation.",
        "Generate → instruct the model to answer ONLY from context and to say when it can't.",
        "Verify → check claims are supported; log the retrieved set for debugging.",
      ],
    },
    {
      title: "Chunking strategies",
      points: [
        "Fixed-size with overlap — 200–800 tokens, 10–20% overlap. Simple, robust baseline; start here.",
        "Recursive/structural — split on headings, then paragraphs, then sentences, so a chunk is a coherent unit.",
        "Document-aware — one chunk per section, FAQ entry, function, or table row, when the document has natural units.",
        "Semantic chunking — split where embedding similarity between adjacent sentences drops. Better boundaries, much slower to build.",
        "Small-to-big — embed small precise chunks for retrieval, but return the surrounding parent section to the model.",
        "Contextual retrieval — prepend a short LLM-generated summary of the document to each chunk before embedding; a large measured win.",
        "Always keep metadata with the chunk: it powers filtering, citation, and permission checks.",
        "Tables and code are usually destroyed by naive splitting — handle them separately.",
      ],
    },
    {
      title: "Retrieval failure modes and their fixes",
      points: [
        "Right document, wrong chunk → adjust chunk size/overlap; try small-to-big.",
        "Exact term missed (error code, product name) → add BM25/keyword; pure vectors are bad at rare literals.",
        "Question phrased differently from the source → query rewriting, HyDE (embed a hypothetical answer), or multi-query expansion.",
        "Retrieved topically-similar but non-answering text → add a reranker; this is the classic similarity-vs-relevance gap.",
        "Answer spans multiple documents → retrieve more, then rerank; consider multi-hop or query decomposition.",
        "Stale answers → track document versions and re-index on change; put dates in metadata and filter.",
        "Model ignores context and uses its own knowledge → instruct explicitly, lower temperature, require citations, and eval for groundedness.",
        "Conflicting sources → include dates/authority in metadata and instruct the model how to resolve.",
      ],
    },
    {
      title: "Vector index types",
      points: [
        "Flat (exact) — brute-force cosine over everything. Perfect recall, fine up to ~100k vectors. Always the correctness baseline.",
        "HNSW — graph-based ANN. Fast, high recall, high memory. The default for most workloads.",
        "IVF (+PQ) — cluster then search a few clusters; product quantisation compresses vectors. Lower memory, needs training, some recall loss.",
        "ANN is APPROXIMATE — you trade recall for speed. Measure recall@k against a flat index before shipping.",
        "Metric must match the embedding model's training: cosine for most text models; dot product only for normalised vectors.",
        "Filtering + ANN is subtle: post-filtering can return fewer than k results; pre-filtering needs index support.",
      ],
    },
    {
      title: "Evaluating RAG",
      points: [
        "Retrieval: recall@k (is the answer-bearing chunk in the top k — the metric that matters most), precision@k, MRR, NDCG.",
        "Generation given perfect context: does the model answer correctly when handed the right chunk? Isolates model from retrieval.",
        "Groundedness/faithfulness: is every claim supported by the retrieved context? Catches hallucination.",
        "Answer relevance: does it actually address the question asked?",
        "End-to-end: correctness on a golden question/answer set drawn from real user queries.",
        "Build the eval set from real questions, including ones the system currently fails.",
        "Track cost and latency per query alongside quality — reranking and multi-query both add both.",
      ],
    },
  ],

  decisions: [
    {
      title: "Vector search vs keyword vs hybrid",
      options: [
        {
          name: "Dense vectors",
          pick: ["Paraphrase and conceptual matching — 'how do I cancel' finding 'subscription termination'.", "Cross-lingual retrieval.", "Users don't know the document's vocabulary."],
          cost: ["Bad at rare literals: error codes, SKUs, person names, version numbers.", "Opaque — hard to explain why something ranked high.", "Needs an embedding model and re-indexing when you change it."],
        },
        {
          name: "Keyword / BM25",
          pick: ["Exact terms, identifiers, code, quoted phrases.", "Explainable ranking.", "Cheap, mature, no GPU."],
          cost: ["No semantic understanding — misses synonyms and paraphrase entirely.", "Vocabulary mismatch between question and document kills it."],
        },
        {
          name: "Hybrid",
          pick: ["Almost always. Run both, fuse with Reciprocal Rank Fusion, then rerank."],
          cost: ["Two indexes to maintain and keep in sync; slightly more latency and complexity."],
        },
      ],
      verdict: "Hybrid is the default. Pure vector search silently fails on exact identifiers, which is exactly what users paste in.",
      topic: "retrieval-strategies",
    },
    {
      title: "RAG vs fine-tuning vs long context",
      options: [
        {
          name: "RAG",
          pick: ["Knowledge changes.", "You need citations.", "Per-user permissions on documents.", "Corpus is larger than any context window."],
          cost: ["A pipeline to build, evaluate, and operate.", "Latency and token cost per query.", "Quality capped by retrieval."],
        },
        {
          name: "Fine-tuning",
          pick: ["Teaching format, tone, or domain style.", "Compressing a long system prompt into weights.", "Distilling a big model into a small one."],
          cost: ["Doesn't reliably add facts; no citations; retraining to update."],
        },
        {
          name: "Long context",
          pick: ["Small, stable corpus that genuinely fits.", "Prototyping before investing in retrieval."],
          cost: ["Pays for the whole corpus on every request; recall degrades mid-context; no access control; doesn't scale."],
        },
      ],
      verdict: "Changing facts → RAG. Style and format → fine-tuning. Small stable corpus → just use context. Most production systems combine RAG with a fine-tuned or well-prompted generator.",
      topic: "rag-fundamentals",
    },
    {
      title: "Dedicated vector DB vs pgvector vs a search engine",
      options: [
        {
          name: "pgvector (Postgres)",
          pick: ["You already run Postgres — one database, real transactions, joins against your relational data.", "Under ~10M vectors.", "Metadata filtering with SQL is a first-class need."],
          cost: ["ANN performance trails specialised stores at very large scale.", "Index builds compete with your OLTP workload."],
        },
        {
          name: "Dedicated vector DB (Pinecone, Qdrant, Weaviate, Milvus)",
          pick: ["Hundreds of millions of vectors.", "You want managed scaling, sharding, and replication for vectors specifically.", "Advanced features: multi-tenancy, sparse+dense in one index."],
          cost: ["Another datastore to operate, secure, and pay for.", "A second source of truth to keep in sync with your primary database."],
        },
        {
          name: "Elasticsearch / OpenSearch",
          pick: ["You already run it for keyword search.", "Hybrid in one system, with mature filtering, aggregation, and ops tooling."],
          cost: ["Heavier to operate; vector performance trails purpose-built stores."],
        },
      ],
      verdict: "Start with pgvector if you have Postgres — it removes a whole sync problem. Move to a dedicated store when scale or features force it.",
      topic: "graph-databases",
    },
    {
      title: "Rerank or not?",
      options: [
        {
          name: "With a reranker",
          pick: ["Almost always worth it. Retrieve ~50 cheaply, rerank to the top 5.", "Precision matters and context budget is limited."],
          cost: ["An extra model call — typically 50–200 ms and some cost.", "Another component to host or a vendor dependency."],
        },
        {
          name: "Retrieval only",
          pick: ["Very tight latency budget.", "The corpus is small and homogeneous so top-k is already precise.", "Prototype stage."],
          cost: ["You'll pass topically-similar but non-answering chunks to the model, diluting context and inviting hallucination."],
        },
      ],
      verdict: "Add a reranker. Bi-encoders optimise for similarity; cross-encoders judge relevance to the actual question, which is what you need.",
    },
  ],

  qa: [
    {
      id: "rag-what",
      q: "Explain RAG and why it exists.",
      a: "Retrieval-Augmented Generation means fetching relevant text at query time and putting it into the prompt so the model answers from that material rather than from its weights. Mechanically: embed and index your corpus, embed the incoming question, retrieve the most relevant chunks, assemble them into a prompt with instructions to answer only from the provided context, and generate with citations. It exists because a model's weights have four limitations that retrieval fixes simultaneously — the model never saw your private data, its knowledge has a cutoff, you can't attribute its claims to a source, and you can't apply per-user permissions to what it knows. Retrieval addresses all four without touching the model: update a document and the next query reflects it, filter the index by the user's permissions and they can only ever see what they're allowed to, and cite the chunk so a human can verify.",
      why: "It's the foundational question, and the four-reasons framing shows you understand why it's an architecture rather than a trick.",
      trap: "Describing it as 'giving the model more information'. The distinguishing properties are freshness, attribution, and access control.",
      followUps: ["Why not just fine-tune on the documents?", "How do permissions work in a RAG system?"],
      depth: "Core",
      tags: ["fundamentals"],
      topic: "rag-fundamentals",
    },
    {
      id: "rag-chunking",
      q: "How do you decide chunk size?",
      a: "It's a trade-off between precision and completeness. Small chunks give a focused embedding that matches a specific question well, but may cut an answer in half or strip the context needed to interpret it — a chunk saying 'it must be renewed annually' is useless without knowing what 'it' is. Large chunks preserve context but their embedding averages several topics, so it matches everything weakly and nothing strongly, and they consume context budget with mostly-irrelevant text. A reasonable default is 300–500 tokens with 10–20% overlap, then tune against a retrieval eval rather than intuition. Better than tuning size alone: split on structure so chunks are coherent units — headings, sections, FAQ entries, functions — and use small-to-big, where you embed a small precise chunk but return its parent section to the model, which gets you both precise matching and full context. Contextual retrieval, prepending a short document-level summary to each chunk before embedding, is another measured improvement.",
      why: "Chunking is where most RAG quality is won or lost, and the answer shows whether someone has tuned a real system.",
      trap: "Picking a number because a tutorial used it. The right size depends on your documents and question types, and it's measurable.",
      followUps: ["What is small-to-big retrieval?", "How do you chunk a document with tables?"],
      depth: "Core",
      tags: ["chunking", "ingestion"],
      topic: "chunking-embeddings",
    },
    {
      id: "rag-hybrid",
      q: "Why is hybrid search better than pure vector search?",
      a: "Because the two methods fail in opposite directions. Dense embeddings capture meaning, so they handle paraphrase and synonymy — a question about 'cancelling my plan' finds a document titled 'subscription termination'. But they're weak on rare literal tokens: error codes, SKUs, version numbers, and person names get smeared into a semantic neighbourhood, so searching `ERR_4021` may return documents about errors generally rather than that one. BM25 is the mirror image — it nails exact terms and gives explainable rankings, but a question worded differently from the document simply doesn't match. Since users paste exact identifiers constantly, pure vector search fails visibly on the queries where users are most confident there's an answer. The standard combination is to run both and fuse with Reciprocal Rank Fusion, which merges by rank position rather than score, so you don't have to calibrate two incomparable scoring scales.",
      why: "It's a concrete, defensible design decision with a clear failure mode behind it.",
      trap: "Assuming embeddings subsume keyword search. They're complementary, and the gap shows up on exactly the highest-intent queries.",
      followUps: ["Why use RRF instead of a weighted score blend?", "Give a query where each method alone fails."],
      depth: "Intermediate",
      tags: ["retrieval", "hybrid"],
      topic: "retrieval-strategies",
    },
    {
      id: "rag-reranker",
      q: "What does a reranker do, and why does it help so much?",
      a: "It re-scores the retrieved candidates by judging the question and each document together. The distinction is architectural: retrieval uses a bi-encoder, which embeds the question and each document independently so their vectors can be precomputed and searched fast — but that means the document's representation was made without knowing the question. A reranker is a cross-encoder, feeding question and document through the model jointly with full attention between them, which is far more accurate at judging relevance but far too slow to run over a whole corpus. So you use them in sequence: retrieve maybe 50 candidates cheaply, rerank those to pick the best 5. It helps disproportionately because it closes exactly the similarity-versus-relevance gap — a passage on the same topic as the question scores high on cosine similarity whether or not it contains the answer, and only a cross-encoder can tell the difference.",
      why: "It's usually the highest quality-per-effort improvement available, and explaining bi- versus cross-encoder shows real depth.",
      trap: "Calling a reranker 'a second embedding search'. It's a fundamentally different computation — joint encoding, not independent.",
      followUps: ["Why can't you use a cross-encoder for initial retrieval?", "How many candidates should you rerank?"],
      depth: "Intermediate",
      tags: ["reranking", "retrieval"],
    },
    {
      id: "rag-debug",
      q: "Your RAG system gives a wrong answer. How do you debug it?",
      a: "Split the pipeline and test the halves independently, because the two failure modes need opposite fixes. First, look at what was actually retrieved — always log it. If the answer-bearing chunk isn't in the retrieved set, it's a retrieval failure and the model was never given a chance; work on chunking, hybrid search, query rewriting, or reranking. If the right chunk WAS retrieved but the answer is still wrong, hand that chunk to the model in isolation and see if it answers correctly. If it does, the problem is context assembly — too many distracting chunks, bad ordering, or the useful content sitting in the middle where recall is weakest. If it doesn't, it's a generation problem — prompt instructions, model capability, or temperature. In practice the large majority of RAG failures are retrieval failures, which is why 'improve the prompt' is usually the wrong first move.",
      why: "It's the most practically useful RAG question, and the systematic split is what interviewers are listening for.",
      trap: "Tuning the prompt first. If the context doesn't contain the answer, no prompt can produce it.",
      followUps: ["What would you log per query to make this debuggable?", "How do you measure retrieval separately?"],
      depth: "Intermediate",
      tags: ["debugging", "evaluation"],
    },
    {
      id: "rag-eval",
      q: "How do you evaluate a RAG system?",
      a: "In layers, because a single end-to-end number tells you nothing about what to fix. Retrieval is measured with recall@k — is the chunk containing the answer among the top k — which is the metric that matters most, since it's a hard ceiling on everything downstream; precision@k, MRR, and NDCG add ranking quality. Generation is measured two ways: correctness given perfect context, which isolates the model, and groundedness or faithfulness, which asks whether every claim in the answer is supported by the retrieved text and is how you detect hallucination. Answer relevance checks it actually addresses the question. Then end-to-end correctness on a golden set built from real user questions, deliberately including current failures. Frameworks like Ragas or DeepEval implement these, often using an LLM as judge — which you should validate against human labels on a sample before trusting. Track cost and latency alongside, since reranking and multi-query improve quality and increase both.",
      why: "Layered evaluation is the difference between systematically improving a system and guessing.",
      trap: "Only measuring end-to-end answer quality. When it drops you have no idea which stage regressed.",
      followUps: ["Why is recall@k the most important retrieval metric?", "How do you validate an LLM judge?"],
      depth: "Advanced",
      tags: ["evaluation"],
      topic: "ml-evaluation",
    },
    {
      id: "rag-permissions",
      q: "How do you enforce per-user permissions in RAG?",
      a: "Filter at retrieval time, never after generation. Store the access-control metadata on each chunk at ingestion — owning team, document ACL, tenant id, sensitivity label — and apply it as a filter in the vector query so the user's results only ever contain documents they're entitled to see. Filtering after retrieval is dangerous because it can leave you with fewer than k results and, worse, filtering after generation is useless: once forbidden text is in the prompt it can leak into the answer regardless of instructions. Two implementation details matter. Pre-filtering versus post-filtering in ANN indexes is a real distinction — post-filtering searches then discards, which can return too few results, so you want an index supporting filtered search natively. And permissions change: if a document is revoked or reclassified, the index must reflect that promptly, so you need re-indexing on ACL changes, or you check permissions against the source of truth at retrieval time rather than trusting a stale copy.",
      why: "It's the question that separates people who've deployed RAG in an enterprise from people who've built a demo.",
      trap: "Retrieving everything and instructing the model not to use unauthorised documents. Prompt instructions are not an access-control mechanism.",
      followUps: ["Pre-filtering vs post-filtering in an ANN index?", "How do you handle a document whose ACL just changed?"],
      depth: "Advanced",
      tags: ["security", "multi-tenancy"],
      topic: "rbac-abac",
    },
    {
      id: "rag-query-rewriting",
      q: "What is query rewriting and when do you need it?",
      a: "Transforming the user's question before retrieval, because the raw question is often a poor search key. Several cases need it. In a conversation, a follow-up like 'what about the enterprise plan?' is meaningless standalone, so you rewrite it against the history into a self-contained query — this is essential for any chat interface. When a question is broad or multi-part, decomposing it into sub-questions and retrieving for each covers more ground than one blended query. Multi-query expansion generates several paraphrases and unions the results, improving recall when vocabulary might mismatch. And HyDE — Hypothetical Document Embeddings — has the model write a plausible answer first and embeds THAT instead of the question, on the reasoning that an answer resembles the document you're looking for more than a question does. All of these cost an extra model call and latency, so they earn their place when recall is measurably the bottleneck, not by default.",
      why: "Conversational rewriting in particular is a non-obvious requirement that breaks naive chat-over-docs systems.",
      trap: "Embedding a follow-up question verbatim in a multi-turn chat. 'What about pricing?' retrieves nothing useful without the earlier context folded in.",
      followUps: ["Why does HyDE work?", "What does query decomposition cost you?"],
      depth: "Advanced",
      tags: ["retrieval", "queries"],
      topic: "advanced-rag",
    },
    {
      id: "rag-ann",
      q: "What is approximate nearest neighbour search and what do you give up?",
      a: "Exact search compares the query vector against every vector, which is O(n) per query and fine up to maybe a hundred thousand vectors but not millions. ANN indexes trade a little recall for a large speedup. HNSW builds a multi-layer navigable small-world graph — you enter at a sparse top layer, greedily walk toward the query, and descend, giving logarithmic-ish search with high recall, at the cost of substantial memory and slower index builds. IVF partitions vectors into clusters and searches only the nearest few, often combined with product quantisation to compress vectors, which cuts memory a lot in exchange for some accuracy. What you give up is exactness: the returned neighbours are usually but not always the true nearest. That matters because it's silent — you never see the result you missed. So you should measure recall@k against a flat exact index on a sample before shipping, and tune the parameters (efSearch for HNSW, nprobe for IVF) to hit your recall target rather than accepting defaults.",
      why: "Understanding that ANN can silently drop the right answer is important, and few candidates think to measure it.",
      trap: "Treating the vector store as exact. Default parameters often sit well below the recall you'd assume.",
      followUps: ["How would you measure recall@k in production?", "HNSW or IVF for 50M vectors — and why?"],
      depth: "Advanced",
      tags: ["vector-search", "indexing"],
      topic: "indexing",
    },
    {
      id: "rag-freshness",
      q: "How do you keep the index fresh?",
      a: "Treat ingestion as a pipeline with change detection rather than a one-off batch. Track a content hash and version per source document so you only re-process what actually changed, since re-embedding an entire corpus nightly is expensive and slow to converge. When a document changes you must delete its old chunks before inserting new ones — chunk boundaries shift, so a naive upsert by chunk id leaves orphaned stale chunks that keep getting retrieved, which is a common and confusing bug. Deletions need to propagate too, or the system confidently cites a document that no longer exists. For near-real-time needs, drive ingestion from change events — a webhook, a CDC stream, a queue — rather than polling. Put timestamps in metadata so you can filter or down-weight stale content and so the model can say how current its answer is. And keep the pipeline idempotent and re-runnable, because you will need to re-index everything when you change chunking or the embedding model.",
      why: "Freshness and deletion handling are where RAG systems quietly rot after launch.",
      trap: "Upserting new chunks without deleting the old ones. Stale chunks linger in the index and surface as contradictory answers.",
      followUps: ["What has to happen when you change embedding models?", "How do you handle a deleted document?"],
      depth: "Advanced",
      tags: ["operations", "ingestion"],
    },
    {
      id: "rag-similarity-relevance",
      q: "Why isn't high cosine similarity enough?",
      a: "Because similarity measures topical closeness, not whether the passage answers the question. A question like 'what is the refund window for enterprise customers?' will score high against any paragraph discussing refunds and enterprise plans, including one that says refunds are handled by a separate team and gives no window at all. Embeddings were trained to place related text nearby, and a question and its answer aren't necessarily the most similar pair — a question is often more similar to other questions than to its answer, which is exactly the insight behind HyDE. There's also no notion of specificity, recency, or authority in a cosine score. The practical consequences are the standard RAG architecture: rerank with a cross-encoder that judges the pair jointly, combine with keyword matching so exact terms carry weight, and use metadata filters for recency and source authority rather than hoping the vector captures them.",
      why: "It's the conceptual reason reranking and hybrid search exist; understanding it means you can debug retrieval rather than tweak randomly.",
      trap: "Using a similarity threshold as a relevance filter. The right cutoff varies per query and per corpus, and a confident-looking 0.85 can be a non-answer.",
      followUps: ["Why is a question sometimes more similar to another question than to its answer?", "How do you incorporate recency?"],
      depth: "Intermediate",
      tags: ["embeddings", "retrieval"],
    },
    {
      id: "rag-graphrag",
      q: "When would you use GraphRAG or a knowledge graph instead of plain vector RAG?",
      a: "When the questions require connecting facts that live in different documents, which chunk-level retrieval handles badly. Vector RAG retrieves the k chunks most similar to the question, so it's excellent at 'what does the policy say about X' and poor at 'which suppliers are affected if this factory shuts down', because that answer isn't stated anywhere — it has to be assembled from relationships. GraphRAG extracts entities and relations at ingestion, builds a graph, and can then traverse it, as well as summarise communities within the graph to answer global questions like 'what are the main themes across these documents', which no top-k retrieval can do since the answer requires the whole corpus. The costs are real and worth stating: entity and relation extraction over a corpus is expensive in LLM calls, the graph needs maintenance as documents change, and extraction errors propagate. So it's justified for multi-hop and global-summary questions, and overkill for straightforward lookup.",
      why: "It shows awareness of where the standard architecture genuinely runs out, without over-reaching for complexity.",
      trap: "Proposing a knowledge graph for ordinary document Q&A. It multiplies cost and maintenance for questions plain RAG already answers.",
      followUps: ["What's a multi-hop question vector RAG can't answer?", "What does community summarisation give you?"],
      depth: "Advanced",
      tags: ["architecture", "graphs"],
      topic: "advanced-rag",
    },
    {
      id: "rag-citations",
      q: "How do you make a RAG system produce trustworthy citations?",
      a: "Design for it end to end rather than asking the model to cite. Give each retrieved chunk a stable identifier and include it in the prompt alongside the text, instruct the model to attach the identifier to each claim, and use structured output so citations come back as fields rather than being parsed from prose. Then verify: check that every cited id was actually in the retrieved set, since models will occasionally invent plausible identifiers, and ideally run a support check asking whether the cited span entails the claim. Keep the mapping from chunk id back to source document, section, and character offsets so the UI can deep-link and highlight — a citation the user can't inspect provides confidence without accountability, which is worse than none. Finally, evaluate groundedness as a metric, not a hope: sample outputs and measure the proportion of claims genuinely supported by their citations.",
      why: "Citations are what make RAG auditable, and 'the model cites but the citation is wrong' is a real and damaging failure.",
      trap: "Trusting the citations because they look plausible. Verify the ids exist in the retrieved set and that the span supports the claim.",
      followUps: ["How would you automatically check a claim is supported?", "What do you show the user when nothing supports the answer?"],
      depth: "Advanced",
      tags: ["reliability", "citations"],
    },
    {
      id: "rag-no-answer",
      q: "How do you make the system say 'I don't know'?",
      a: "You have to build it in at several points, because the default behaviour is to answer anyway. Instruct explicitly that if the context doesn't contain the answer it must say so, and give an example of that response in the prompt — models follow demonstrated behaviour more reliably than described behaviour. Add a retrieval gate: if the top reranked score falls below a threshold calibrated on your own data, don't call the generator at all, and respond that nothing relevant was found. Include abstention cases in your eval set with 'I don't know' as the expected answer, otherwise every optimisation pushes toward answering. Post-generation, run a groundedness check and suppress or flag answers whose claims aren't supported. And design the UI to make abstention useful rather than a dead end — show the closest documents found, offer to search differently, or route to a human. The organisational point is that a system which never abstains isn't more capable, it's less honest.",
      why: "Knowing that abstention must be engineered — and evaluated — is a strong applied-AI signal.",
      trap: "Adding 'say I don't know if unsure' to the prompt and considering it handled. Without a retrieval gate and abstention examples in the eval, it rarely fires.",
      followUps: ["How do you pick the score threshold?", "Why include abstention cases in the eval set?"],
      depth: "Advanced",
      tags: ["reliability", "ux"],
    },
  ],

  pitfalls: [
    "Don't debug RAG by tuning the prompt first — log and inspect what was retrieved.",
    "Don't use pure vector search — it silently fails on error codes, SKUs, and names that users paste in.",
    "Don't enforce permissions after retrieval or after generation — filter in the query.",
    "Don't treat cosine similarity as relevance — that's what a reranker is for.",
    "Don't upsert changed documents without deleting their old chunks — boundaries shift and stale chunks linger.",
    "Don't assume ANN returns the true nearest neighbours — measure recall against exact search.",
    "Don't embed a conversational follow-up verbatim — rewrite it into a standalone query.",
    "Don't report one end-to-end score — evaluate retrieval and generation separately.",
  ],

  numbers: [
    { label: "Typical chunk size", value: "300–500 tokens", note: "With 10–20% overlap. Tune against a retrieval eval." },
    { label: "Retrieve then rerank", value: "~50 → 3–8", note: "Cheap wide recall, expensive precise ranking." },
    { label: "Exact search viable up to", value: "~100k vectors", note: "Beyond that, ANN. Keep a flat index for recall measurement." },
    { label: "Reranker latency", value: "~50–200 ms", note: "For ~50 candidates; usually worth it." },
    { label: "Key retrieval metric", value: "recall@k", note: "A hard ceiling on end-to-end quality." },
  ],

  relatedTopics: [
    "rag-fundamentals",
    "advanced-rag",
    "chunking-embeddings",
    "retrieval-strategies",
    "tokenization-embeddings",
    "inverted-index",
    "indexing",
    "ml-evaluation",
    "rbac-abac",
  ],
};
