import type { Area } from "../types";

export const react: Area = {
  slug: "react",
  title: "React",
  icon: "⚛️",
  stream: "Language & Runtime",
  blurb:
    "Rendering, reconciliation, hooks, and the stale-closure family of bugs — plus knowing when NOT to reach for a `useEffect`.",

  mustKnow: [
    "React re-renders a component when its state changes, its parent re-renders, or its context value changes. Props changing is not itself a trigger — the parent re-rendering is.",
    "Re-render ≠ DOM update. React re-runs the function, diffs the new element tree against the old, and touches only the DOM nodes that actually differ.",
    "State updates are asynchronous and batched. Reading state right after `setState` gives the old value; use the updater form `setX(prev => ...)` when the next value depends on the previous one.",
    "`key` tells React which item is which across renders. Using an array index as a key breaks state and animations whenever the list is reordered, filtered, or has items inserted.",
    "`useEffect` is for synchronising with something OUTSIDE React — subscriptions, timers, the DOM, network. It is not for deriving state from props; compute that during render.",
    "The dependency array is a correctness contract, not an optimisation. Lying about it produces stale closures that read old props and state.",
    "The effect cleanup function runs before the next effect and on unmount. Without it you leak subscriptions and race obsolete responses.",
    "Every hook must be called unconditionally, in the same order, every render — React matches hooks to state by call index, not by name.",
    "`useMemo`/`useCallback` cache values across renders; they cost memory and comparison, so they pay only for genuinely expensive work or for referential stability that a memoised child depends on.",
    "Controlled input = value comes from state; uncontrolled = the DOM owns it and you read it with a ref. Mixing them (value without onChange) makes the field read-only.",
  ],

  sheets: [
    {
      title: "What causes a re-render",
      points: [
        "`useState`/`useReducer` setter called with a value that is not `Object.is`-equal to the current one.",
        "Parent re-renders → all children re-render by default, regardless of whether props changed.",
        "A consumed context's value changes (by reference — a new object literal every render defeats it).",
        "A subscribed external store changes (`useSyncExternalStore`).",
        "NOT a trigger: mutating state in place, or a ref changing (`ref.current = x` never re-renders).",
        "`React.memo` stops the parent-cascade only if the props are referentially stable.",
        "Setting state to the same value bails out — React may still re-render once, then stop.",
      ],
    },
    {
      title: "Hooks rules and why they exist",
      points: [
        "Call hooks only at the top level — never in conditions, loops, or nested functions.",
        "Call hooks only from components or other hooks.",
        "React stores hook state in a linked list per component, matched by call ORDER; a conditional hook shifts every subsequent index onto the wrong state.",
        "Custom hooks are just functions starting with `use` that call other hooks — they share logic, never state. Two components using the same hook get independent state.",
        "`useRef` gives a stable mutable box that survives renders and never triggers one — for DOM nodes, timer ids, and 'previous value' tracking.",
        "`useLayoutEffect` fires synchronously after DOM mutation but before paint — use it only to measure or to prevent a visible flicker.",
      ],
    },
    {
      title: "`useEffect` — when you should NOT use it",
      points: [
        "Deriving state from props/state → compute during render, or `useMemo` if expensive. An effect adds a wasted second render.",
        "Responding to a user event → put the logic in the event handler, not an effect watching the state it set.",
        "Resetting state when a prop changes → pass a `key` to the component instead and let React remount it.",
        "Fetching on mount in real apps → prefer a data library (TanStack Query, RTK Query) or the framework's loader; hand-rolled effects miss caching, dedup, and race handling.",
        "Legitimate uses: subscriptions, event listeners, timers, imperative DOM/third-party widgets, logging/analytics, syncing to localStorage.",
        "Every fetch effect needs cleanup — an `AbortController` or an `ignore` flag — or a slow first response can overwrite a fast second one.",
      ],
    },
    {
      title: "Performance checklist, in order",
      points: [
        "1. Profile first with the React DevTools Profiler — find what actually re-renders and what it costs.",
        "2. Fix the structure: move state DOWN to the component that uses it, or lift content UP as `children` so it isn't re-created.",
        "3. `React.memo` the expensive child, then make its props referentially stable with `useCallback`/`useMemo`.",
        "4. Virtualise long lists (react-window / TanStack Virtual) — nothing beats not rendering 10,000 rows.",
        "5. Code-split routes with `lazy` + `Suspense` to cut the initial bundle.",
        "6. `useTransition` / `useDeferredValue` to keep typing responsive while an expensive list filters.",
        "Memoising everything is itself a cost — comparison plus memory on every render.",
      ],
    },
    {
      title: "State: where should it live?",
      points: [
        "Local `useState` — used by one component. The default; do not skip it.",
        "Lifted to the nearest common parent — needed by two siblings.",
        "`useReducer` — several fields that change together with defined transitions; makes invalid states unrepresentable.",
        "Context — genuinely global and rarely-changing: theme, locale, current user. Bad for high-frequency updates, since every consumer re-renders.",
        "External store (Zustand, Redux, Jotai) — cross-cutting, frequently-updated client state that needs selective subscription.",
        "Server cache (TanStack Query, SWR) — anything that came from the server. It is not really 'state', it is a cache with staleness rules.",
        "URL — filters, tabs, pagination. Free sharing, back-button support, and no sync bug.",
      ],
    },
    {
      title: "Keys, lists, and reconciliation",
      points: [
        "React diffs children of the same type positionally, using `key` to match items across renders.",
        "Same key + same type → update in place. Different key → unmount old, mount new (state is lost).",
        "Index keys are safe ONLY for a static, never-reordered, append-only-at-the-end list.",
        "The classic index-key bug: delete row 2, and row 3's input value appears in row 2, because the key still matched.",
        "Keys must be unique among siblings only, not globally.",
        "Changing a component's `key` is the documented way to force a remount and reset all its state.",
      ],
    },
  ],

  decisions: [
    {
      title: "`useState` vs `useReducer`",
      options: [
        {
          name: "useState",
          pick: ["One or two independent values.", "Simple set-and-read, no transition rules.", "Fastest to write and read."],
          cost: ["Several related `useState` calls drift out of sync and allow impossible combinations (loading AND error AND data)."],
        },
        {
          name: "useReducer",
          pick: ["Multiple fields that change together.", "Next state depends on previous in non-trivial ways.", "You want transitions testable as a pure function.", "Deep updates you'd otherwise pass many callbacks down for — pass `dispatch` instead."],
          cost: ["More ceremony; overkill for a boolean toggle."],
        },
      ],
      verdict: "One value → `useState`. A state machine with rules → `useReducer`.",
    },
    {
      title: "Context vs a state library (Zustand/Redux)",
      options: [
        {
          name: "Context",
          pick: ["Low-frequency, genuinely global values: theme, locale, auth user.", "You want zero dependencies.", "Dependency injection for a subtree."],
          cost: ["EVERY consumer re-renders when the value changes — there is no selector. A frequently-updating context is a performance bug that spreads.", "Splitting into many contexts to avoid that gets unwieldy fast."],
        },
        {
          name: "State library",
          pick: ["Frequently-updated shared state.", "Consumers must subscribe to a SLICE and ignore the rest.", "You want devtools, middleware, or persistence."],
          cost: ["A dependency and its conventions; Redux specifically adds meaningful boilerplate."],
        },
      ],
      verdict: "Context is dependency injection, not a state manager. The moment you want selectors, use a store.",
      topic: "state",
    },
    {
      title: "Server state (TanStack Query) vs client state (Redux/Zustand)",
      options: [
        {
          name: "Server-state library",
          pick: ["Anything owned by the server: lists, entities, search results.", "You need caching, dedup, background refetch, retries, pagination, optimistic updates."],
          cost: ["Another mental model; not meant for purely local UI state."],
        },
        {
          name: "Client-state store",
          pick: ["State the server never sees: open modals, wizard steps, selections, drafts, theme."],
          cost: ["Re-implementing caching, staleness, and race handling by hand if you use it for server data — this is the single most common React architecture mistake."],
        },
      ],
      verdict: "Server data is a cache, not state. Use a query library for it, and a store only for genuinely client-owned state.",
    },
    {
      title: "Controlled vs uncontrolled inputs",
      options: [
        {
          name: "Controlled",
          pick: ["You need validation as the user types, formatting, or to disable submit conditionally.", "The value must be read or driven by other components."],
          cost: ["A re-render per keystroke; on a large form that needs care, or a form library."],
        },
        {
          name: "Uncontrolled (refs / FormData)",
          pick: ["Large simple forms where you only need values at submit.", "File inputs, which are always uncontrolled.", "Wrapping a non-React widget."],
          cost: ["No live validation without extra work; the value lives outside React so it is harder to test and share."],
        },
      ],
      verdict: "Controlled when React needs the value continuously; uncontrolled when you only need it at submit.",
    },
    {
      title: "`useMemo`/`useCallback` — memoise or not?",
      options: [
        {
          name: "Memoise",
          pick: ["The computation is genuinely expensive (big sort/filter/parse).", "The value is a dependency of an effect and must be referentially stable.", "It is a prop to a `React.memo` child that would otherwise re-render."],
          cost: ["Memory per cached value plus a dependency comparison every render; wrong deps produce stale values, which is a correctness bug, not a slow one."],
        },
        {
          name: "Don't memoise",
          pick: ["Cheap computation — an object literal, a small map, string concatenation.", "The child isn't memoised anyway, so stability buys nothing."],
          cost: ["Occasional avoidable re-render, usually far cheaper than the memo machinery."],
        },
      ],
      verdict: "Memoise for referential stability or measured expense. Blanket memoisation adds cost and stale-closure risk.",
    },
    {
      title: "CSR vs SSR vs SSG vs ISR",
      options: [
        {
          name: "CSR",
          pick: ["Authenticated dashboards and internal tools where SEO is irrelevant and every view is user-specific."],
          cost: ["Slow first paint, poor SEO, and a large JS bundle before anything is interactive."],
        },
        {
          name: "SSR",
          pick: ["Per-request personalised pages that must still be indexable and fast to first paint."],
          cost: ["Server cost and latency on every request; needs caching to scale."],
        },
        {
          name: "SSG",
          pick: ["Content that is the same for everyone: marketing, docs, blogs. Serve from a CDN, effectively free and instant."],
          cost: ["Content is only as fresh as the last build; a big site means long builds."],
        },
        {
          name: "ISR",
          pick: ["Mostly-static content that changes occasionally: product pages, catalogues."],
          cost: ["Some users see stale content until revalidation; the mental model is more complex."],
        },
      ],
      verdict: "Same for everyone → SSG. Personalised but indexable → SSR. Behind a login → CSR. Mostly static, occasionally updated → ISR.",
    },
  ],

  qa: [
    {
      id: "react-rerender",
      q: "What exactly causes a component to re-render?",
      a: "Three things: its own state changed via a `useState`/`useReducer` setter with a value that isn't `Object.is`-equal to the current one; its parent re-rendered, which by default re-renders all children whether or not their props changed; or a context it consumes got a new value. A subscribed external store updating also counts. Note what is NOT on the list: mutating an object in place, and changing `ref.current` — neither notifies React. The critical distinction is that re-rendering means React calls your function again and diffs the result; it does not mean the DOM was touched. If the output is identical, the diff finds nothing and no DOM operation happens, which is why 'extra renders' are usually cheap and rarely worth optimising blindly.",
      why: "Most React performance and correctness confusion traces back to conflating re-render with DOM update.",
      trap: "Saying 'when props change'. Props changing is a consequence of the parent re-rendering — a child re-renders on a parent render even with identical props, unless it is wrapped in `React.memo`.",
      followUps: ["How does `React.memo` change this?", "Why doesn't mutating state re-render?", "Is an extra render actually expensive?"],
      depth: "Core",
      tags: ["rendering"],
    },
    {
      id: "react-key",
      q: "Why shouldn't you use array index as a `key`?",
      a: "Keys tell React which element in a list corresponds to which element from the previous render. With index keys, the key describes a position rather than an identity, so if you delete, insert, or reorder, the same key now points at different data. React thinks the item at index 1 is unchanged and just updates its props — but any state INSIDE that item stays put. The classic symptom is deleting the second row of a list of inputs and finding the third row's typed text now sitting in the second row. It also breaks CSS transitions and can cause wrong focus. Index keys are fine only when the list is static, never reordered, and only appended to at the end. Otherwise use a stable id from the data; if you truly have none, generate one when the item is created, not during render.",
      why: "It is the most common React bug that reviewers can spot instantly in a diff.",
      trap: "Thinking keys are only about silencing the console warning. They drive the reconciliation algorithm's identity matching.",
      followUps: ["How can you use `key` deliberately to reset a component's state?", "Do keys need to be globally unique?"],
      depth: "Core",
      tags: ["lists", "reconciliation"],
    },
    {
      id: "react-stale-closure",
      q: "What is a stale closure in React, and how do you avoid it?",
      a: "Every render creates fresh functions that close over that render's props and state. If a function outlives the render that made it — inside a `setInterval`, an event listener, or an effect with an incomplete dependency array — it keeps reading the old values. The classic case is `useEffect(() => { const id = setInterval(() => setCount(count + 1), 1000); return () => clearInterval(id); }, [])`: the interval captures `count` as 0 forever, so the counter sticks at 1. Three fixes, in order of preference: use the functional updater `setCount(c => c + 1)` so you never read the captured value; put the value in the dependency array and let the effect re-subscribe; or, when re-subscribing is too expensive, keep the latest value in a ref that the callback reads at call time.",
      why: "It is the single most common source of 'React is behaving weirdly' bugs, and the fix reveals whether someone understands closures.",
      trap: "Adding an eslint-disable to silence the exhaustive-deps warning. The warning was correct; disabling it is how the bug ships.",
      followUps: ["Why does the functional updater fix it?", "When is the ref pattern the right answer?"],
      depth: "Intermediate",
      tags: ["hooks", "closures"],
    },
    {
      id: "react-effect-misuse",
      q: "When should you NOT use `useEffect`?",
      a: "Most of the time people reach for it. If you can compute a value from existing props or state, compute it during render — an effect that sets derived state costs an extra render and can go out of sync. If something should happen because the user did something, put it in the event handler, not in an effect watching the resulting state; the handler knows the intent, the effect only sees the consequence. If you need to reset state when a prop changes, give the component a `key` and let React remount it. And for data fetching, a hand-rolled effect misses caching, request dedup, retries, and race handling, so a query library or the framework's loader is better. What genuinely belongs in an effect is synchronising with something outside React: subscriptions, event listeners, timers, imperative DOM or third-party widgets, and analytics.",
      why: "'You Might Not Need an Effect' is the biggest single lever on React code quality, and it separates people who learned React recently and properly from people running on 2019 habits.",
      trap: "Using an effect to keep two pieces of state in sync. That is a design smell — one of them should be derived, not stored.",
      followUps: ["How would you reset a form when the `userId` prop changes?", "Why is fetching in an effect race-prone?"],
      depth: "Intermediate",
      tags: ["hooks", "effects"],
    },
    {
      id: "react-effect-cleanup",
      q: "What does the effect cleanup function do, and why do fetches need one?",
      a: "Cleanup runs before the effect re-runs and once more on unmount. Its job is to undo whatever the effect set up: clear timers, remove listeners, close sockets, cancel subscriptions. For fetches it prevents two real bugs. First, setting state on an unmounted component, which used to warn and still means wasted work. Second, and more importantly, a race: if the user types quickly and you fire a request per keystroke, responses can arrive out of order, so a slow request for 'ab' can land after a fast one for 'abc' and overwrite it with the wrong results. The fixes are an `AbortController` you abort in cleanup, or an `let ignore = false` flag set to true in cleanup and checked before calling `setState`.",
      why: "The out-of-order response race is a real production bug that most candidates have never considered.",
      trap: "Thinking cleanup only runs on unmount. It runs before every re-run of the effect too.",
      followUps: ["Write a search-as-you-type effect that can't race.", "Why does StrictMode run effects twice in development?"],
      depth: "Intermediate",
      tags: ["hooks", "effects", "async"],
    },
    {
      id: "react-strictmode",
      q: "Why does StrictMode mount components twice in development?",
      a: "In development, StrictMode deliberately mounts, unmounts, and remounts each component, running effects twice, to surface effects that are not resilient to being re-run. Real React features — Fast Refresh today, and offscreen/reusable state in future — can mount and remount components, so an effect that leaks or double-registers is a latent bug. If your effect subscribes without cleaning up, you now get two subscriptions and can see it immediately. The correct response is never to disable StrictMode or add an `didMount` ref guard; it is to write a cleanup that makes the effect idempotent. It only happens in development, never in production builds.",
      why: "The reaction to this question tells you whether someone fixes causes or symptoms.",
      trap: "Adding a `useRef` guard so the effect only runs once. That hides the design flaw and breaks under real remounts.",
      followUps: ["What would break if a subscription effect had no cleanup?"],
      depth: "Intermediate",
      tags: ["effects", "tooling"],
    },
    {
      id: "react-batching",
      q: "Are state updates synchronous? What is batching?",
      a: "No. Calling a setter schedules an update; reading the state variable immediately after still gives the value from the current render, because that variable is a `const` captured in this render's closure. React batches multiple updates in the same tick into a single re-render, so calling `setCount(count + 1)` three times with `count` at 0 sets it to 1, not 3 — each call read the same captured 0. Using `setCount(c => c + 1)` three times gives 3, because each updater receives the latest pending value. Since React 18, automatic batching applies everywhere — including promises, `setTimeout`, and native event handlers — whereas React 17 only batched inside React event handlers. If you truly need the DOM updated synchronously, `flushSync` forces it, at the cost of the performance batching was buying.",
      why: "It combines closures, the render model, and a real React 18 behaviour change.",
      trap: "Saying 'setState is async so use a timeout to read the new value'. The value isn't late — this render's variable is simply immutable.",
      followUps: ["What changed about batching in React 18?", "When would you use `flushSync`?"],
      depth: "Core",
      tags: ["state", "rendering"],
    },
    {
      id: "react-memo-when",
      q: "When does `React.memo` actually help — and when does it not?",
      a: "`React.memo` skips re-rendering a component when its props are shallowly equal to last time. It helps when the component is genuinely expensive to render — a big list, a chart, a heavy tree — and its parent re-renders often for unrelated reasons. It does nothing useful in three common cases: when the props include a new object, array, or inline function every render, since shallow comparison always fails and you've added a comparison cost for no benefit; when the component is cheap, where the comparison can cost more than the render; and when the re-render is caused by context or internal state rather than the parent, which `memo` cannot stop. So `memo` almost always has to come with `useCallback`/`useMemo` on the props feeding it, which is why 'lift content into `children`' or 'move state down' is often the better fix — it removes the re-render instead of guarding against it.",
      why: "It tests whether someone optimises by measurement or by ritual.",
      trap: "Wrapping everything in `memo` as a default. Without stable props it is pure overhead.",
      followUps: ["Why does passing `children` avoid re-rendering a subtree?", "What is the custom comparison function argument for?"],
      depth: "Intermediate",
      tags: ["performance"],
    },
    {
      id: "react-context-perf",
      q: "Why can Context hurt performance, and what do you do about it?",
      a: "Because there are no selectors: when the context value changes, every consumer re-renders, even ones that only use an unrelated field of it. Two things make this worse in practice. Passing an object literal as the value creates a new reference every render, so consumers re-render even when nothing meaningfully changed — fix with `useMemo` around the value. And bundling frequently-changing state with rarely-changing state in one context drags every consumer along with the fast-changing part. Remedies, in order: split into multiple contexts by change frequency (a common pattern is separate state and dispatch contexts, since dispatch is stable); memoise the value; and if you actually need per-field subscription, use a store like Zustand where components subscribe to a selected slice.",
      why: "The 'context is a state manager' misconception causes real, hard-to-diagnose slowdowns.",
      trap: "Putting the whole app's state in one context and then blaming React for being slow.",
      followUps: ["Why split state and dispatch into two contexts?", "How does `useSyncExternalStore` enable selectors?"],
      depth: "Advanced",
      tags: ["context", "performance"],
    },
    {
      id: "react-reconciliation",
      q: "How does reconciliation work?",
      a: "When a component re-renders, React builds a new tree of elements — plain objects describing what the UI should be — and compares it with the previous tree, then applies the minimal set of DOM operations. The diff uses two heuristics to stay O(n) rather than O(n³). First, elements of different types produce entirely different trees, so if a `<div>` becomes a `<span>`, React tears down the old subtree, destroying its state, rather than trying to match it. Second, for lists of children, it uses `key` to match items across renders; without keys it falls back to matching by position. Same type plus same key means update in place, keeping component state; a changed key means unmount and remount. Fiber, the current implementation, additionally splits this work into interruptible units so high-priority updates like typing can pre-empt a big render.",
      why: "It explains keys, state loss on conditional rendering, and why moving a component in the tree resets it.",
      trap: "Describing it as 'React compares the virtual DOM to the real DOM'. It compares the new element tree to the previous element tree; the real DOM is only written to at the end.",
      followUps: ["What happens to state when an element's type changes?", "What did Fiber change?"],
      depth: "Advanced",
      tags: ["rendering", "internals"],
    },
    {
      id: "react-custom-hook",
      q: "What do custom hooks share, and what don't they?",
      a: "They share logic, never state. A custom hook is just a function whose name begins with `use` and which calls other hooks; each component that calls it gets its own independent state, because the hooks inside run in that component's context. So two components using `useCounter()` have two separate counters — if you want them to share a value, the state has to live somewhere common, like a lifted parent, a context, or an external store. This is the single most misunderstood point about custom hooks. Their real value is packaging a piece of stateful behaviour with its own effects and cleanup — `useDebounce`, `useLocalStorage`, `useOnScreen` — so the component stays declarative and the logic becomes independently testable.",
      why: "The 'hooks share state' misconception leads people to build broken pseudo-global state.",
      trap: "Assuming a custom hook is a singleton. Every call site gets fresh state.",
      followUps: ["How would you make two components share the state from one hook?", "Why must the name start with `use`?"],
      depth: "Intermediate",
      tags: ["hooks"],
    },
    {
      id: "react-useref",
      q: "What is `useRef` for, beyond DOM access?",
      a: "A ref is a stable, mutable box that survives re-renders and never triggers one when you write to it. DOM access is the obvious use — `<input ref={inputRef} />` then `inputRef.current.focus()`. The less obvious uses matter more in interviews: storing a timer or interval id so cleanup can clear it; holding the previous value of a prop or state to compare against; keeping a mutable 'latest value' that a long-lived callback can read to escape a stale closure; and tracking whether something has already happened without causing a render. The rule that separates it from state is exactly that last property: if changing the value should update the UI, it is state; if it is bookkeeping the UI does not display, it is a ref.",
      why: "The state-vs-ref decision is a daily one and the reasoning is crisp.",
      trap: "Reading or writing `ref.current` during render. That makes render impure and breaks under concurrent rendering — do it in effects or handlers.",
      followUps: ["How do you build a `usePrevious` hook?", "What does `useImperativeHandle` add?"],
      depth: "Intermediate",
      tags: ["hooks", "refs"],
    },
    {
      id: "react-layout-effect",
      q: "`useEffect` vs `useLayoutEffect`.",
      a: "Both run after render, but at different moments. `useEffect` is deferred: React commits to the DOM, the browser paints, and then the effect runs — so it never blocks visual updates, which is why it is the default. `useLayoutEffect` runs synchronously after the DOM mutation but BEFORE the browser paints, so anything you do there is visible in the same frame. You need it when you must measure the DOM and immediately adjust based on the measurement — positioning a tooltip against a trigger, syncing scroll position, measuring text to avoid a layout shift. If you did that in `useEffect`, the user would briefly see the un-adjusted position, producing a flicker. The cost is that it blocks paint, so heavy work there directly delays the frame.",
      why: "The 'flicker' explanation shows the candidate has actually hit the problem.",
      trap: "Reaching for `useLayoutEffect` by default 'to be safe'. It blocks painting and is measurably worse for most work.",
      followUps: ["Why does `useLayoutEffect` warn during SSR?"],
      depth: "Advanced",
      tags: ["hooks", "rendering"],
    },
    {
      id: "react-lists-virtual",
      q: "How do you render a list of 50,000 rows?",
      a: "You don't — you virtualise. Rendering 50,000 DOM nodes is slow to create, expensive in memory, and makes every subsequent re-render and layout worse. Virtualisation renders only the rows currently in the viewport plus a small overscan buffer, using absolute positioning inside a container whose height is the total row count times row height, so the scrollbar behaves correctly. `react-window` or TanStack Virtual do this; variable-height rows need measurement, which those libraries support. Complementary moves: paginate or use infinite scroll so you don't fetch 50,000 records at once, memoise the row component so scrolling doesn't re-render every visible row, and keep the row itself cheap. If it's a data grid with sorting and filtering, do that work outside render and feed the virtualiser a prepared array.",
      why: "A concrete performance question where the right answer is architectural rather than a micro-optimisation.",
      trap: "Suggesting `React.memo` on rows as the primary fix. It helps, but it doesn't address the 50,000 DOM nodes.",
      followUps: ["How does virtualisation preserve the scrollbar?", "What breaks with variable row heights?"],
      depth: "Advanced",
      tags: ["performance", "lists"],
    },
    {
      id: "react-error-boundary",
      q: "What is an error boundary, and what does it not catch?",
      a: "An error boundary is a component that implements `componentDidCatch` or `getDerivedStateFromError` and renders a fallback UI when a render error occurs anywhere in its subtree, instead of letting the whole app unmount — which is React's default since v16. It catches errors thrown during rendering, in lifecycle methods, and in constructors of the tree below it. It does NOT catch errors in event handlers (use `try/catch` there — they're outside the render flow), in asynchronous code such as `setTimeout` or promise callbacks, during server-side rendering, or thrown in the boundary itself. There is still no hook version, so you either write a class component or use `react-error-boundary`. Place them per route and around risky widgets, so one broken chart doesn't take down the page.",
      why: "Knowing the gaps matters more than knowing the API, because the gaps are where production incidents come from.",
      trap: "Assuming boundaries catch everything. Async and handler errors escape entirely.",
      followUps: ["How do you catch errors in an event handler?", "How does Suspense interact with error boundaries?"],
      depth: "Intermediate",
      tags: ["errors"],
      topic: "error-handling",
    },
    {
      id: "react-suspense",
      q: "What does Suspense actually do?",
      a: "Suspense lets a component tell React 'I'm not ready yet' by throwing a promise, and React renders the nearest `<Suspense fallback={...}>` above it until that promise resolves. The original use was code splitting with `React.lazy`, where the component itself is being downloaded. With React 18 and frameworks, it also covers data: a component can suspend while its data loads, letting you declare loading states positionally in the tree rather than threading `isLoading` booleans through props. That enables streaming SSR — the server sends the shell immediately and streams in slower sections as they resolve — and selective hydration, where React hydrates the parts the user interacts with first. The important limitation is that you cannot suspend on an arbitrary promise in a plain `useEffect` fetch; it needs an integrated data source such as a framework loader or a Suspense-enabled query library.",
      why: "Distinguishes people tracking modern React from those anchored in the class era.",
      trap: "Believing Suspense catches errors. Errors need an error boundary; Suspense only handles the pending state.",
      followUps: ["How does streaming SSR use it?", "Why can't you suspend on any promise?"],
      depth: "Advanced",
      tags: ["suspense", "async"],
    },
    {
      id: "react-server-components",
      q: "What are React Server Components and what do they change?",
      a: "Server Components render only on the server and send a serialised description of the UI to the client — never their code. That means their dependencies stay out of the bundle entirely, so a component using a large markdown or date library adds zero kilobytes to the client. They can access server resources directly, awaiting a database query inside the component rather than round-tripping through an API. The trade-off is that they have no state, no effects, and no event handlers, since none of that exists on the server; anything interactive must be a Client Component marked with `'use client'`. The practical model is a tree of server components for data and layout with interactive islands beneath them, and the props crossing that boundary must be serialisable — you cannot pass a function to a client component from a server one.",
      why: "It is the biggest shift in React's model in a decade, and it comes up for anyone touching Next.js.",
      trap: "Confusing them with SSR. SSR renders your client components to HTML and then ships and hydrates their JS; server components never ship their JS at all.",
      followUps: ["What can't cross the server/client boundary?", "How do server actions fit in?"],
      depth: "Advanced",
      tags: ["rsc", "architecture"],
    },
    {
      id: "react-transition",
      q: "What problem do `useTransition` and `useDeferredValue` solve?",
      a: "They let you mark some updates as low priority so urgent ones stay responsive. The canonical case is a search box filtering a large list: typing updates the input (urgent) and re-filters thousands of rows (expensive). Without prioritisation, every keystroke waits for the filter and typing feels laggy. `useTransition` gives you a `startTransition` wrapper — you put the expensive state update inside it, and React can interrupt that work when a newer keystroke arrives, plus an `isPending` flag to show a subtle indicator. `useDeferredValue` is the value-level equivalent: you pass it the fast-changing value and get back one that lags behind, and you feed the lagging one to the expensive component. Use the transition when you own the state update, and the deferred value when you only receive a prop.",
      why: "Shows awareness of concurrent React and, more importantly, of the difference between urgent and non-urgent work.",
      trap: "Treating it as a debounce. Debounce delays by a fixed time; a transition starts immediately and is interruptible, so it stays responsive without adding fixed latency.",
      followUps: ["How is this different from debouncing?", "What does `isPending` let you build?"],
      depth: "Advanced",
      tags: ["concurrent", "performance"],
    },
    {
      id: "react-derived-state",
      q: "How do you handle state derived from props?",
      a: "In almost every case, don't store it — compute it during render. If you have `items` and a `filter` prop, `const visible = items.filter(...)` on every render is correct by construction and can never go stale; wrap it in `useMemo` only if profiling shows the computation is expensive. Copying a prop into state with `useState(props.value)` captures the initial value and silently ignores later changes, which is the classic 'why doesn't my component update' bug. When you genuinely need to reset internal state because the entity changed — a form switching between users — the idiomatic answer is to give the component a `key={userId}` in the parent, so React unmounts and remounts it with fresh state. Adjusting state during render by comparing to a previous-value ref is the escape hatch, and it is rarely needed.",
      why: "Derived state is one of the top sources of stale-UI bugs, and the `key` trick is the answer few candidates know.",
      trap: "Using `useEffect` to sync a prop into state. It works, but it renders twice and can be momentarily inconsistent.",
      followUps: ["Why is `key` better than an effect for resetting?", "When is `useMemo` justified here?"],
      depth: "Intermediate",
      tags: ["state", "props"],
    },
    {
      id: "react-testing",
      q: "How do you test a React component?",
      a: "With React Testing Library, driving the component the way a user would rather than reaching into internals. Query by accessible role and label — `getByRole('button', { name: /save/i })` — because that both survives refactors and implicitly checks accessibility; avoid test ids except as a last resort. Interact with `userEvent` rather than `fireEvent`, since it simulates real sequences like focus, keydown, and input. Assert on what the user can observe: visible text, ARIA state, whether a request was made. Mock the network at the boundary with MSW, not by stubbing `fetch` per test, so the tests exercise your real data layer. And use `findBy*` queries for anything asynchronous, since they retry until the element appears. The guiding principle is that testing state or props directly gives you tests that break on every refactor and still miss real breakage.",
      why: "Testing philosophy reveals whether someone has maintained a test suite over time.",
      trap: "Testing implementation details — asserting on state values or calling instance methods. Those tests fail on refactors and pass on regressions.",
      followUps: ["Why prefer `userEvent` over `fireEvent`?", "How do you test a hook in isolation?"],
      depth: "Intermediate",
      tags: ["testing"],
      topic: "unit-testing",
    },
    {
      id: "react-a11y",
      q: "What accessibility issues do React apps commonly introduce?",
      a: "Mostly from replacing semantic elements with `div`s wired up by hand. A clickable `div` is not a button: it has no role, no keyboard focus, no Enter/Space activation, and screen readers announce nothing — using `<button>` gives all of that free. Custom modals often fail to trap focus, don't return focus to the trigger on close, and don't close on Escape. Client-side route changes don't move focus or announce the new page, so screen-reader users stay where they were. Form inputs get a visual label that isn't associated via `htmlFor`/`id`. Errors are rendered visually but not announced, needing `aria-live` or `role='alert'`. And `outline: none` on focus styles removes keyboard users' only indication of where they are. The rule: reach for the semantic element first, and add ARIA only when no element fits.",
      why: "Accessibility is increasingly a hard requirement, and this question shows whether someone builds with semantics or with divs.",
      trap: "Adding `role='button'` to a div and calling it fixed. You still need `tabIndex`, key handlers, and disabled semantics.",
      followUps: ["How do you implement a focus trap?", "What should happen to focus on route change?"],
      depth: "Intermediate",
      tags: ["accessibility"],
    },
    {
      id: "react-form-perf",
      q: "A large form re-renders on every keystroke. How do you fix it?",
      a: "First, work out whether it matters — a re-render of a moderate form is cheap, and the fix has costs. If it does matter, the causes are that all field values sit in one state object at the top, so every keystroke re-renders the whole form. Options, roughly in order: isolate each field into its own component holding its own state so a keystroke only re-renders that field; go uncontrolled and read values at submit via `FormData` or refs, which is what react-hook-form does through subscriptions so the parent never re-renders per keystroke; or keep the state central but memoise the expensive children and stabilise their callbacks. If the expense is downstream — a live preview or validation over the whole document — wrap that update in `useDeferredValue` so typing stays smooth while the preview lags slightly.",
      why: "It's a realistic scenario with several defensible answers, which shows how the candidate weighs trade-offs.",
      trap: "Debouncing the controlled input's `onChange`, which makes the field itself feel laggy. Debounce the expensive consequence, not the input.",
      followUps: ["How does react-hook-form avoid re-renders?", "When is uncontrolled the better default?"],
      depth: "Advanced",
      tags: ["performance", "forms"],
    },
    {
      id: "react-portal",
      q: "What are portals for?",
      a: "A portal renders children into a different DOM node while keeping them in the same React tree. The reason you need it is CSS: a modal or tooltip rendered inside a container with `overflow: hidden`, a `transform`, or a stacking context gets clipped or mis-layered, and no amount of `z-index` fixes it reliably. Rendering into `document.body` escapes that. Crucially, the React tree is unchanged — context still flows in, and events still bubble through the React tree rather than the DOM tree, so a click inside a portaled modal will fire a handler on the React parent that rendered it, which surprises people implementing click-outside logic. That behaviour is usually what you want, since it keeps the component model intact.",
      why: "The event-bubbling-follows-the-React-tree detail is the part that separates a memorised answer from an understood one.",
      trap: "Assuming events bubble through the DOM parent. They follow the React tree.",
      followUps: ["Why does this break naive click-outside detection?", "How do you manage focus in a portaled modal?"],
      depth: "Intermediate",
      tags: ["dom", "portals"],
    },
    {
      id: "react-hydration",
      q: "What is a hydration mismatch and what causes it?",
      a: "With SSR, the server sends HTML and the client then attaches React to it, expecting the first client render to produce exactly the same tree. When it doesn't, React warns and, since 18, discards the server HTML for that subtree and re-renders it on the client — costing performance and sometimes flashing content. The usual causes are non-deterministic values: `Date.now()` or `new Date()` rendering a timestamp, `Math.random()`, locale- or timezone-dependent formatting where server and client differ, and reading `window`, `localStorage`, or a media query during render, since those don't exist on the server. Browser extensions injecting DOM can also trigger it. The standard fixes are to render the server-safe value first and update in an effect, gate genuinely client-only content behind a mounted flag, or use `suppressHydrationWarning` for the narrow case of an intentionally differing timestamp.",
      why: "Anyone doing Next.js hits this, and the causes are a fixed, learnable list.",
      trap: "Blanket `suppressHydrationWarning` to silence it. That hides real mismatches elsewhere in the subtree.",
      followUps: ["Why is `new Date()` in render dangerous?", "How do you render client-only content safely?"],
      depth: "Advanced",
      tags: ["ssr", "hydration"],
    },
    {
      id: "react-class-vs-hooks",
      q: "Why did React move from classes to hooks?",
      a: "Three problems with classes. Reusing stateful logic required render props or higher-order components, which produced deeply nested 'wrapper hell' and made data flow hard to trace; hooks let you extract that logic into a plain function. Related code was split across lifecycle methods — a subscription set up in `componentDidMount`, updated in `componentDidUpdate`, and torn down in `componentWillUnmount` — while unrelated concerns were jammed together in the same method; a single `useEffect` with its cleanup keeps one concern in one place. And classes carried real friction: `this` binding, constructors, and confusion about when to use them, plus they minify worse and are harder for compilers to optimise. Hooks also compose naturally, since a custom hook is just a function calling other hooks.",
      why: "It checks whether someone understands the motivation behind the API rather than just its surface.",
      trap: "Saying 'classes are deprecated'. They still work and error boundaries still require one.",
      followUps: ["What can classes still do that hooks can't?", "How does `useEffect` unify three lifecycle methods?"],
      depth: "Core",
      tags: ["history", "hooks"],
    },
    {
      id: "react-prop-drilling",
      q: "How do you deal with prop drilling?",
      a: "First check whether it's actually a problem — passing a prop through two levels is fine and keeps data flow explicit. When it is genuinely deep, the options in escalating order are: restructure by composition, passing the rendered element as `children` so the intermediate layers never see the data at all, which solves a surprising share of cases and also avoids re-rendering those layers; use context for values that are genuinely ambient to a subtree, like theme or current user; or move to a store when many components across the tree need selective access to frequently-changing state. The reason to prefer composition first is that context and stores both make data flow implicit, which trades a visible annoyance for an invisible coupling.",
      why: "The composition answer is the one most candidates miss, and it's usually the best one.",
      trap: "Jumping straight to Redux for a three-level prop pass.",
      followUps: ["Show how `children` avoids drilling.", "When does context become the wrong tool?"],
      depth: "Intermediate",
      tags: ["architecture", "context"],
    },
    {
      id: "react-fiber",
      q: "What is Fiber?",
      a: "Fiber is React's reconciliation engine since v16, a rewrite that made rendering interruptible. Before it, reconciliation was a synchronous recursive walk that could not be paused, so a large update blocked the main thread and dropped frames. Fiber restructures the work into a linked list of units, each a 'fiber' node holding a component's state and its relationship to its neighbours, and processes them in a loop that can yield back to the browser between units. That enables the concurrent features: React can start rendering, pause for a higher-priority update like a keystroke, and resume or discard the in-progress work. Rendering is split into a render phase, which is interruptible and must be side-effect free — that's why StrictMode double-invokes to catch impurity — and a commit phase, which applies DOM changes synchronously and cannot be interrupted.",
      why: "It explains why render must be pure and where the concurrent features come from.",
      trap: "Describing Fiber as a performance optimisation that makes rendering faster. It doesn't make the work smaller; it makes it schedulable.",
      followUps: ["Why must the render phase be pure?", "What is double buffering in Fiber?"],
      depth: "Advanced",
      tags: ["internals"],
    },
    {
      id: "react-optimistic",
      q: "How do you implement optimistic UI updates?",
      a: "Apply the expected result to local state immediately, fire the request, and reconcile when it returns — rolling back if it fails. Concretely: snapshot the current state, apply the change so the UI responds instantly, send the mutation, and on error restore the snapshot and surface a message; on success, replace the optimistic value with the server's canonical response, which matters because the server may assign an id, timestamp, or normalised values. TanStack Query formalises this with `onMutate` to apply and cancel in-flight queries, `onError` to roll back, and `onSettled` to invalidate and refetch; React 19 adds `useOptimistic` for the local case. The trade-off is honesty: it's right for high-success-rate, low-stakes actions like a like button or reordering a list, and wrong for payments or anything where showing a success that later reverses is worse than a spinner.",
      why: "It's a design question as much as a technical one, and the 'when not to' half is what senior candidates add.",
      trap: "Forgetting rollback, or forgetting to cancel in-flight refetches that would overwrite the optimistic state.",
      followUps: ["How do you avoid a refetch clobbering the optimistic value?", "When is optimistic UI inappropriate?"],
      depth: "Advanced",
      tags: ["ux", "data"],
    },
    {
      id: "react-bundle",
      q: "The initial bundle is too big. What do you do?",
      a: "Measure first with a bundle analyser to see what's actually large — the answer is usually two or three dependencies, not your code. Then: code-split by route with `React.lazy` and `Suspense` so users download only the page they're on, and split heavy below-the-fold or modal-only components the same way. Replace oversized dependencies with smaller ones (moment → date-fns or `Intl`, lodash → individual imports or native methods). Make sure tree-shaking can work, which means ESM imports and avoiding `import * as`. Lazy-load genuinely optional things like charting and rich text editors on demand. Then check the loading path itself: preload critical chunks, ensure compression is on, and serve modern syntax to modern browsers rather than shipping ES5 polyfills to everyone. With Server Components, moving a component to the server removes its dependencies from the bundle entirely.",
      why: "A practical question where the method — measure, then act — matters more than the list.",
      trap: "Code-splitting aggressively at component level. Too many small chunks add request overhead and can make things slower.",
      followUps: ["What is tree-shaking and what defeats it?", "How do Server Components change bundle size?"],
      depth: "Advanced",
      tags: ["performance", "bundling"],
    },
  ],

  pitfalls: [
    "Don't say a component re-renders 'when props change' — say when its parent re-renders, its state changes, or its context changes.",
    "Don't say re-render means the DOM updated — say React diffs and touches only what differs.",
    "Don't reach for `useEffect` to derive state from props — compute during render, or reset with a `key`.",
    "Don't silence the exhaustive-deps lint rule — the warning is pointing at a stale closure.",
    "Don't use index as a key for any list that can reorder, filter, or insert.",
    "Don't call Context a state manager — it has no selectors, so every consumer re-renders.",
    "Don't claim `React.memo` fixes re-renders caused by context or internal state — it only blocks the parent cascade.",
    "Don't confuse Server Components with SSR — RSC never ships the component's JS at all.",
  ],

  numbers: [
    { label: "Frame budget", value: "~16.7 ms", note: "Render work beyond this drops frames." },
    { label: "Rows before virtualising", value: "~100–200", note: "Rough threshold; measure with the Profiler." },
    { label: "React 18 batching", value: "Everywhere", note: "React 17 batched only inside React event handlers." },
    { label: "INP 'good' threshold", value: "< 200 ms", note: "Core Web Vital that replaced FID in 2024." },
  ],

  relatedTopics: ["state", "immutability", "functions", "higher-order-functions", "unit-testing", "error-handling"],
};
