import type { Area } from "../types";

export const security: Area = {
  slug: "security",
  title: "Security & Auth",
  icon: "🔐",
  stream: "Backend & Data",
  blurb:
    "Authentication vs authorisation, the injection family, OWASP in practice, and the password-hashing answer that must be immediate.",

  mustKnow: [
    "Authentication is who you are; authorisation is what you may do. 401 vs 403.",
    "Never build SQL by string concatenation. Parameterised queries are the only reliable defence against SQL injection.",
    "Hash passwords with bcrypt, scrypt, or Argon2 — deliberately slow, salted algorithms. Never SHA-256 or MD5, which are fast by design and therefore wrong here.",
    "XSS is executing attacker-controlled script in a user's browser; the defences are contextual output encoding, a Content Security Policy, and never using `innerHTML` with untrusted data.",
    "CSRF makes a user's authenticated browser perform an action they didn't intend; `SameSite` cookies plus a CSRF token is the standard defence.",
    "Auth tokens belong in `HttpOnly; Secure; SameSite` cookies, not `localStorage`, because any XSS can read `localStorage` instantly.",
    "Authorise per object, not per route — checking that the caller owns the specific resource is what prevents IDOR.",
    "Validate and allowlist input at the boundary; never trust anything from a client, including hidden fields, prices, roles, and ids.",
    "Least privilege everywhere: database users, cloud IAM roles, service accounts, and API tokens should have the narrowest scope that works.",
    "Secrets belong in a secret manager or environment, never in the repository, and must be rotatable.",
  ],

  sheets: [
    {
      title: "OWASP Top 10, in practical terms",
      points: [
        "Broken access control — the most common. Missing object-level authorisation, IDOR, privilege escalation via a client-supplied role.",
        "Cryptographic failures — plaintext or weakly-hashed secrets, missing TLS, homemade crypto.",
        "Injection — SQL, NoSQL, OS command, LDAP, and template injection. Parameterise; never interpolate.",
        "Insecure design — missing rate limits, no account lockout, business logic that can be replayed.",
        "Security misconfiguration — default credentials, debug mode in production, permissive CORS, public storage buckets.",
        "Vulnerable components — outdated dependencies; automate scanning and patching.",
        "Identification and authentication failures — weak password rules, no MFA, session fixation, tokens that never expire.",
        "Software/data integrity failures — unsigned updates, untrusted CI plugins, deserialising untrusted data.",
        "Logging and monitoring failures — no audit trail, so a breach goes undetected for months.",
        "SSRF — the server fetches an attacker-supplied URL and reaches internal services or cloud metadata.",
      ],
    },
    {
      title: "Password handling",
      points: [
        "Use Argon2id (preferred), scrypt, or bcrypt. Never a general-purpose fast hash.",
        "The algorithm salts automatically and stores the salt with the hash — you don't manage it yourself.",
        "Slowness is the feature: it makes offline brute force expensive. Tune the work factor so hashing takes ~100–250 ms on your hardware.",
        "Never encrypt passwords (reversible) — hash them.",
        "Rate limit and lock out on failed attempts; use a generic 'invalid credentials' message so you don't confirm which accounts exist.",
        "Compare hashes in constant time to avoid timing side channels.",
        "Enforce length over composition rules; check against known-breached password lists.",
        "MFA is worth more than any password policy.",
      ],
    },
    {
      title: "XSS types and defences",
      points: [
        "Stored — attacker content saved server-side and served to others. Highest impact.",
        "Reflected — payload in the URL echoed into the response.",
        "DOM-based — client JS writes untrusted data into the DOM; the server never sees the payload.",
        "Defence 1: contextual output encoding — HTML, attribute, JS, URL, and CSS contexts each need different escaping.",
        "Defence 2: framework auto-escaping (React, Vue) — but `dangerouslySetInnerHTML` and `v-html` opt out of it.",
        "Defence 3: Content Security Policy — blocks inline scripts and unknown sources; a strong second line of defence.",
        "Defence 4: sanitise HTML with a vetted library (DOMPurify) when you must accept rich text.",
        "`HttpOnly` cookies limit the damage: script can't read the session token.",
      ],
    },
    {
      title: "Tokens and sessions",
      points: [
        "Session cookie — server holds state; revocation is instant (delete the session). Needs shared session storage.",
        "JWT — self-contained and signed; the server verifies without a lookup. Cannot be revoked before expiry without a blocklist.",
        "Standard pattern: short-lived access token (5–15 min) + long-lived, revocable, rotating refresh token.",
        "Always verify the signature, the algorithm (reject `none` and algorithm confusion), the issuer, the audience, and the expiry.",
        "A JWT is signed, not encrypted — anyone can read the payload. Never put secrets in it.",
        "OAuth 2.0 is delegated authorisation; OIDC adds authentication (an ID token) on top.",
        "Use the authorisation code flow with PKCE for web and mobile; the implicit flow is deprecated.",
        "Rotate refresh tokens and detect reuse — reuse of an already-exchanged token means it was stolen.",
      ],
    },
    {
      title: "Defence in depth checklist for a service",
      points: [
        "TLS everywhere, HSTS, no mixed content.",
        "Schema-validate all input; reject unknown fields on writes to stop mass assignment.",
        "Parameterise every query; use an ORM's safe API and audit any raw SQL.",
        "Object-level authorisation enforced in a shared layer, not per endpoint.",
        "Rate limit globally and per user, with tighter limits on auth and expensive endpoints.",
        "Security headers: CSP, X-Content-Type-Options, Referrer-Policy, frame-ancestors.",
        "Least-privilege credentials for the database, cloud roles, and service accounts.",
        "Audit log security-relevant events; alert on anomalies; never log secrets or PII.",
        "Dependency scanning in CI; patch on a schedule, not on incident.",
      ],
    },
  ],

  decisions: [
    {
      title: "Where to store an auth token in a browser",
      options: [
        {
          name: "HttpOnly cookie",
          pick: ["Default. JavaScript cannot read it, so XSS cannot exfiltrate it.", "Sent automatically; add `Secure` and `SameSite`."],
          cost: ["Automatic sending is what enables CSRF — needs `SameSite` plus a CSRF token for state-changing requests.", "Cross-domain API calls need explicit CORS credentials configuration."],
        },
        {
          name: "localStorage",
          pick: ["Genuinely nothing. It's convenient for cross-domain calls, and that's the only argument."],
          cost: ["Any XSS anywhere on the page — including in a third-party script — reads the token and takes over the account.", "No automatic expiry or scoping."],
        },
        {
          name: "In-memory only",
          pick: ["Highest security for the access token: it dies with the tab and XSS has a much smaller window.", "Paired with a refresh token in an HttpOnly cookie."],
          cost: ["Lost on refresh, so you need a silent refresh flow.", "More implementation complexity."],
        },
      ],
      verdict: "HttpOnly cookie for the refresh token; access token in memory or in the same cookie. `localStorage` turns any XSS into full account takeover.",
      topic: "sessions-vs-tokens",
    },
    {
      title: "Session vs JWT",
      options: [
        {
          name: "Server session",
          pick: ["You need instant revocation — logout, ban, password change must take effect now.", "Traditional web app on one domain.", "You want minimal client-side state."],
          cost: ["A shared session store every instance must reach.", "A lookup per request (usually trivial against Redis)."],
        },
        {
          name: "JWT",
          pick: ["Stateless services across domains or organisations.", "Third-party API access.", "You want to avoid a session store dependency."],
          cost: ["No revocation before expiry without a blocklist — which reintroduces the state you avoided.", "Larger, sent on every request.", "Easy to misconfigure: `alg: none`, unverified audience, no expiry check."],
        },
      ],
      verdict: "Same-origin app → sessions, because revocation matters more than statelessness. Distributed or cross-org → short-lived JWTs plus revocable refresh tokens.",
      topic: "jwt",
    },
    {
      title: "RBAC vs ABAC",
      options: [
        {
          name: "RBAC (roles)",
          pick: ["Permissions cluster naturally into job functions: admin, editor, viewer.", "Simple to reason about, audit, and explain to non-engineers."],
          cost: ["Role explosion when rules depend on context ('editor, but only for their own department, during business hours').", "Coarse-grained — often over-grants."],
        },
        {
          name: "ABAC (attributes/policies)",
          pick: ["Decisions depend on attributes of the user, the resource, and the environment.", "Multi-tenant systems, data residency, time- or location-based rules."],
          cost: ["Policies are harder to audit — 'who can access X?' becomes a query, not a lookup.", "Needs a policy engine and careful testing.", "Easier to write a policy that's subtly too permissive."],
        },
      ],
      verdict: "Start with RBAC. Move to ABAC (or RBAC plus attribute conditions) when you find yourself inventing roles like `editor_dept_finance_readonly`.",
      topic: "rbac-abac",
    },
  ],

  qa: [
    {
      id: "sec-sql-injection",
      q: "How do you prevent SQL injection?",
      a: "Parameterised queries — send the SQL and the values separately, so the database parses the query structure first and then binds the values as data that can never be reinterpreted as syntax. `SELECT * FROM users WHERE email = ?` with the value bound is safe no matter what the value contains, whereas string concatenation means an input of `' OR '1'='1` becomes part of the query. Escaping input is the wrong mental model: it's a blocklist approach, it's character-set and context dependent, and people forget it exactly once. ORMs parameterise by default, which is a large part of their security value, but their raw-query escape hatches don't, so those need auditing. Two things people miss: identifiers such as table and column names cannot be parameterised, so if a sort column comes from user input you must validate it against an allowlist; and the same reasoning applies beyond SQL — NoSQL query injection, OS command injection, LDAP, and template injection are all the same failure of mixing code and data. Layer on least privilege so the application's database user can't drop tables even if something slips through.",
      why: "It's the most-asked security question, and the answer must be immediate and correct.",
      trap: "Saying you escape or sanitise input. Parameterisation is the answer; escaping is what people do just before a breach.",
      followUps: ["How do you safely handle a user-supplied ORDER BY column?", "What's the equivalent risk in MongoDB?"],
      depth: "Core",
      tags: ["injection"],
      topic: "injection-attacks",
    },
    {
      id: "sec-password-hash",
      q: "How do you store passwords?",
      a: "Hash them with a slow, salted, purpose-built algorithm: Argon2id preferably, or scrypt or bcrypt. The essential point is that speed is a vulnerability here. SHA-256 and MD5 are designed to be fast, so an attacker with a leaked database can try billions of candidates per second on a GPU; bcrypt and Argon2 have a tunable work factor deliberately making each attempt expensive, so you tune it until hashing takes roughly a couple of hundred milliseconds on your hardware — imperceptible for a login, ruinous for brute force. Salting is handled by these algorithms automatically and stored alongside the hash; its purpose is to ensure identical passwords produce different hashes, defeating rainbow tables and preventing an attacker from seeing which users share a password. Never encrypt passwords, because encryption is reversible and there's no reason to ever recover the original. Around that, compare in constant time, rate limit and lock out on failed attempts, return a generic failure message so you don't reveal which accounts exist, and offer MFA, which does more for account security than any password composition rule.",
      why: "It's a question with a definite right answer, so getting it wrong is disqualifying.",
      trap: "Proposing SHA-256 with a salt. Salting fixes rainbow tables but not brute force; the slowness is the point.",
      followUps: ["Why is a fast hash bad here?", "What does the salt actually prevent?", "How do you pick the work factor?"],
      depth: "Core",
      tags: ["passwords", "crypto"],
      topic: "hashing-passwords",
    },
    {
      id: "sec-xss",
      q: "What is XSS and how do you prevent it?",
      a: "Cross-site scripting is getting attacker-controlled JavaScript to execute in another user's browser in the context of your origin — which means it can read the DOM, make authenticated requests as that user, and steal anything JavaScript can reach. Stored XSS, where the payload is persisted and served to everyone, is the most damaging; reflected XSS bounces off a URL parameter; DOM-based XSS never touches the server at all, arising when client code writes untrusted data into the DOM. The primary defence is contextual output encoding: escape data for the context it lands in, since HTML body, attribute, JavaScript, URL, and CSS contexts each need different treatment. Modern frameworks escape by default, which is why React apps rarely have XSS unless someone reaches for `dangerouslySetInnerHTML` or `v-html`, so those are the places to audit. If you must accept rich text, sanitise with a vetted library like DOMPurify rather than a regex. Then add defence in depth: a Content Security Policy that blocks inline scripts and unknown sources, and `HttpOnly` cookies so a successful XSS still can't read the session token.",
      why: "It's the most common client-side vulnerability, and the layered answer shows security thinking rather than a single trick.",
      trap: "Saying you sanitise input on the way in. Encoding must happen on output, because the correct encoding depends on where the value is used.",
      followUps: ["Why encode on output rather than input?", "What does CSP buy you if you already escape correctly?"],
      depth: "Core",
      tags: ["xss", "browser"],
      topic: "owasp-top-10",
    },
    {
      id: "sec-csrf",
      q: "What is CSRF and how is it different from XSS?",
      a: "CSRF abuses the fact that browsers attach cookies automatically. An attacker's page causes the victim's browser to issue a request to your site — a form auto-submitting to `POST /transfer` — and because the victim is logged in, the cookie rides along and your server sees an authenticated request the user never intended. The attacker cannot read the response, so CSRF is about causing actions, not stealing data. That's the key difference from XSS: XSS runs script in your origin and can therefore do anything the user can, including reading data, whereas CSRF is a blind, forged action from outside. The defences are `SameSite` cookies, which stop the browser sending your cookie on cross-site requests and now default to `Lax` in major browsers, plus a CSRF token — an unpredictable value tied to the session that must accompany state-changing requests, which the attacker cannot obtain because of the same-origin policy. Checking Origin or Referer headers is a useful supplement. Note that an API using an `Authorization` header rather than cookies isn't CSRF-vulnerable, since nothing is attached automatically.",
      why: "The distinction from XSS is frequently muddled and the mechanism explains why the defences work.",
      trap: "Thinking HTTPS or authentication prevents CSRF. The request is authenticated — that's the whole problem.",
      followUps: ["Why does `SameSite=Lax` mitigate this?", "Why is a bearer-token API not CSRF-prone?"],
      depth: "Intermediate",
      tags: ["csrf", "browser"],
      topic: "owasp-top-10",
    },
    {
      id: "sec-jwt-pitfalls",
      q: "What can go wrong with JWTs?",
      a: "Several things, and most are configuration rather than cryptography. The historically famous one is the `alg: none` attack, where a server trusted the algorithm declared in the token's own header and accepted an unsigned token; the related algorithm-confusion attack passes an RS256 public key as an HS256 secret. Both are fixed by pinning the expected algorithm server-side rather than reading it from the token. Then there's revocation: a JWT is valid until it expires, so logging out, banning a user, or changing a password doesn't invalidate outstanding tokens unless you maintain a blocklist — which reintroduces the server state statelessness was meant to avoid. This is why access tokens should be short-lived, minutes rather than days, with a revocable refresh token doing the long-lived work. People also forget that a JWT is signed but not encrypted, so the payload is readable by anyone who has it and must not contain secrets. And validation is frequently incomplete: you must check expiry, issuer, and audience, not just the signature, or a token minted for a different service will be accepted.",
      why: "JWTs are used everywhere and misconfigured often, so this separates users from implementers.",
      trap: "Treating a JWT as encrypted or as instantly revocable. It's neither.",
      followUps: ["How do you implement logout with JWTs?", "Why check the audience claim?"],
      depth: "Advanced",
      tags: ["jwt", "auth"],
      topic: "jwt",
    },
    {
      id: "sec-oauth",
      q: "Explain OAuth 2.0 and how OIDC relates to it.",
      a: "OAuth 2.0 is delegated authorisation: it lets a user grant an application limited access to their resources on another service without handing over their password. The flow you should describe is authorisation code with PKCE: the app redirects the user to the provider, the user authenticates and consents, the provider redirects back with a short-lived authorisation code, and the app exchanges that code — along with a secret or a PKCE verifier — for an access token at the token endpoint. The redirect-then-exchange structure exists so the token never travels through the browser's URL, and PKCE binds the exchange to the client that started it, preventing an intercepted code from being used. OIDC sits on top and adds authentication: an ID token, a signed JWT containing verified claims about who the user is, plus a standard userinfo endpoint. The distinction matters because OAuth alone tells you an app may access something, not who the user is — using an access token as proof of identity is a known mistake, since a token issued for another application can be replayed unless you validate the audience.",
      why: "OAuth is ubiquitous and widely half-understood; the authorisation-versus-authentication split is the key insight.",
      trap: "Calling OAuth a login protocol. That's OIDC; OAuth on its own is about access delegation.",
      followUps: ["What attack does PKCE prevent?", "Why is the implicit flow deprecated?"],
      depth: "Advanced",
      tags: ["oauth", "auth"],
      topic: "oauth-oidc",
    },
    {
      id: "sec-ssrf",
      q: "What is SSRF and why is it dangerous in the cloud?",
      a: "Server-Side Request Forgery is when an application fetches a URL supplied by the user — a webhook target, an image importer, a PDF renderer following links — and an attacker points it somewhere internal. The danger is that your server sits inside a trusted network, so it can reach services that are firewalled from the internet: internal admin panels, databases, and, most damagingly in cloud environments, the instance metadata endpoint at 169.254.169.254, which historically returned temporary IAM credentials to anything that asked. That turns a seemingly harmless 'fetch this image' feature into cloud account compromise, which is exactly what happened in the Capital One breach. The defences are layered: allowlist the destinations you actually need rather than blocklisting internal ranges, since blocklists are defeated by DNS rebinding, redirects, and alternate IP encodings; resolve the hostname and validate the resulting IP, then connect to that IP to avoid a time-of-check/time-of-use gap; disable redirect following or re-validate each hop; and at the infrastructure level require IMDSv2, which needs a session token and blocks the naive fetch entirely.",
      why: "It's risen up the OWASP list precisely because cloud metadata makes it catastrophic.",
      trap: "Blocklisting `127.0.0.1` and `169.254.169.254`. Attackers bypass it with DNS names resolving to those addresses, redirects, or decimal IP encodings.",
      followUps: ["How does DNS rebinding defeat a blocklist?", "What does IMDSv2 change?"],
      depth: "Advanced",
      tags: ["ssrf", "cloud"],
      topic: "owasp-top-10",
    },
    {
      id: "sec-least-privilege",
      q: "What does least privilege mean in practice?",
      a: "Every identity gets only the permissions it needs, scoped as narrowly as possible, and nothing more — so that a compromise is contained rather than total. Concretely: the application's database user should have `SELECT`, `INSERT`, `UPDATE` on the tables it uses and no `DROP`, no schema modification, and no access to other schemas, so SQL injection that slips through can't destroy data. Cloud IAM roles should be per-service with specific resource ARNs rather than a shared role with wildcards, and should use short-lived assumed roles rather than long-lived access keys. Service accounts in Kubernetes shouldn't mount tokens they don't use. API tokens should be scoped to specific operations and expire. Containers shouldn't run as root or with unnecessary capabilities. The practical difficulty is that least privilege is easy to state and tedious to maintain, so it needs process: start from deny-all and add what fails, use access analyzers to find unused permissions, review periodically, and make short-lived credentials the default so that a leaked one has a small window.",
      why: "It's the principle that determines blast radius, which is what actually decides how bad an incident is.",
      trap: "Treating it as an infrastructure concern only. The database grant for your application user is the most impactful and most commonly ignored instance.",
      followUps: ["What should your app's database user NOT be able to do?", "Why prefer assumed roles over static keys?"],
      depth: "Intermediate",
      tags: ["principles", "cloud"],
      topic: "aws-iam",
    },
    {
      id: "sec-secrets",
      q: "How do you handle secrets?",
      a: "Keep them out of the repository entirely — including the history, since deleting a committed secret in a later commit doesn't remove it, and any clone still has it. In practice that means a secret manager (AWS Secrets Manager, Vault, or the platform's equivalent) or injected environment variables, with the manager preferred because it gives you access control, audit logging, and rotation. Rotation is the part people skip: a secret you cannot rotate quickly is a secret you cannot respond to a leak with, so the application should re-read credentials rather than caching them for the process lifetime. Prefer short-lived, automatically-rotated credentials where the platform offers them — IAM roles for service accounts, workload identity, database IAM auth — because that removes the long-lived secret altogether, which is strictly better than managing it well. Around that: secret scanning in CI and as a pre-commit hook to catch mistakes before they land, distinct secrets per environment so a staging leak isn't a production incident, and never logging them, which includes being careful that a request-logging middleware doesn't dump an `Authorization` header.",
      why: "Leaked credentials are one of the most common real breach vectors, and rotation readiness is the mature part of the answer.",
      trap: "Saying 'use environment variables' and stopping. That answers where they live at runtime, not how they're stored, distributed, rotated, or audited.",
      followUps: ["What do you do the moment a secret leaks?", "Why are short-lived credentials better than well-managed static ones?"],
      depth: "Intermediate",
      tags: ["secrets", "operations"],
    },
    {
      id: "sec-threat-model",
      q: "How would you threat model a new feature?",
      a: "Start by drawing the data flow: what enters the system, from whom, where it's stored, who can read it, and what leaves. Then identify the trust boundaries — the points where data crosses from less-trusted to more-trusted, which is where controls belong. Then enumerate what could go wrong at each boundary, and STRIDE gives a usable checklist: spoofing, tampering, repudiation, information disclosure, denial of service, and elevation of privilege. For each realistic threat, decide whether to mitigate, accept, or transfer, and record the decision so it's revisitable. The practical shortcuts that make this fast rather than ceremonial: ask who the attacker is — an anonymous internet user, a logged-in customer attacking another customer, or an insider — because the answers differ; ask what the worst outcome is and work backwards from it; and pay special attention to anything handling money, personal data, authentication, or file uploads. The output should be a short list of concrete controls tied to specific risks, not a document nobody reads.",
      why: "It shows security as a design activity rather than a scanning step at the end.",
      trap: "Treating a penetration test or a scanner as a threat model. Those find known bug classes; they don't tell you what an attacker would want from this feature.",
      followUps: ["What does STRIDE stand for?", "Where are the trust boundaries in a typical web app?"],
      depth: "Advanced",
      tags: ["process", "design"],
      topic: "secure-coding",
    },
  ],

  pitfalls: [
    "Don't say you escape or sanitise SQL input — say parameterised queries.",
    "Don't propose SHA-256 for passwords, even salted — use bcrypt, scrypt, or Argon2.",
    "Don't store auth tokens in `localStorage` — any XSS becomes account takeover.",
    "Don't sanitise for XSS on input — encode on output, for the specific context.",
    "Don't claim a JWT is encrypted or revocable — it's signed, and valid until it expires.",
    "Don't call OAuth an authentication protocol — that's OIDC.",
    "Don't defend SSRF with a blocklist of internal IPs — allowlist destinations.",
    "Don't authorise per route only — check ownership of the specific object.",
  ],

  numbers: [
    { label: "Password hash target time", value: "~100–250 ms", note: "Tune the work factor to your hardware." },
    { label: "Access token TTL", value: "5–15 min", note: "Because you can't revoke it; pair with a rotating refresh token." },
    { label: "Cloud metadata endpoint", value: "169.254.169.254", note: "The SSRF target that turns a bug into account compromise." },
    { label: "Top OWASP risk", value: "Broken access control", note: "Object-level authorisation is where most real bugs are." },
  ],

  relatedTopics: [
    "owasp-top-10",
    "injection-attacks",
    "hashing-passwords",
    "authn-vs-authz",
    "jwt",
    "oauth-oidc",
    "sessions-vs-tokens",
    "rbac-abac",
    "secure-coding",
    "tls-ssl",
    "crypto-basics",
    "aws-iam",
  ],
};
