import type { Area } from "../types";

export const systemDesign: Area = {
  slug: "system-design",
  title: "System Design",
  icon: "🏗️",
  stream: "System Design",
  blurb:
    "A framework that stops you freezing, the handful of building blocks every design reuses, and the trade-off language interviewers are listening for.",

  mustKnow: [
    "Drive the interview with a framework: requirements → scale estimates → API → data model → high-level design → deep dive → bottlenecks and trade-offs. Never start drawing boxes immediately.",
    "Separate functional requirements (what it does) from non-functional (how many users, how fast, how consistent, how available). The non-functional ones determine the architecture.",
    "State assumptions out loud and write them down. Interviewers correct wrong assumptions; they cannot correct unstated ones.",
    "Read-heavy and write-heavy systems look completely different. Establish the ratio early — it's the first thing that shapes the design.",
    "Every design is caching, replication, partitioning, queuing, and load balancing recombined. Learn the five well rather than memorising architectures.",
    "There is no 'correct' design — you are graded on whether you name trade-offs and justify choices against the stated requirements.",
    "Stateless services scale horizontally; state is the hard part, so push it into datastores, caches, and queues that are designed for it.",
    "Asynchronous processing via a queue is the standard answer to slow work, traffic spikes, and third-party dependencies.",
    "Design for failure explicitly: what happens when this component is down, slow, or returns garbage? Timeouts, retries with backoff and jitter, circuit breakers, and idempotency.",
    "Single points of failure, hot partitions, and unbounded growth are the three things to hunt for in your own design before the interviewer does.",
  ],

  sheets: [
    {
      title: "The framework (and the clock)",
      points: [
        "1. Requirements — 5 min. Functional: the 3–5 core features, scope aggressively. Non-functional: scale, latency, availability, consistency.",
        "2. Estimation — 5 min. DAU, requests/sec, read:write ratio, storage per year, bandwidth. Round hard; the order of magnitude is what matters.",
        "3. API — 5 min. A handful of endpoints with their key parameters. This forces clarity about what the system actually does.",
        "4. Data model — 5 min. Core entities, the access patterns, then SQL vs NoSQL justified by those patterns.",
        "5. High-level design — 10 min. Client → LB → service → cache → database, plus queues and workers. Draw the happy path first.",
        "6. Deep dive — 15 min. The interviewer picks, or you offer the most interesting part: the hot path, the consistency question, the scaling bottleneck.",
        "7. Bottlenecks and trade-offs — 5 min. Name your single points of failure, hot spots, and what you'd change at 10× scale.",
      ],
    },
    {
      title: "Estimation shortcuts",
      points: [
        "1 million DAU with 10 requests/day ≈ 10M requests/day ≈ 115 req/s average. Peak ≈ 2–3× average.",
        "86,400 seconds in a day — round to 100,000 for mental arithmetic.",
        "1 KB per record × 1M records/day ≈ 1 GB/day ≈ 365 GB/year. Add replication factor and index overhead.",
        "Read:write of 100:1 is typical for social; 1:1 for messaging; write-heavy for logging and IoT.",
        "A modern server handles thousands of req/s for simple work; a database handles low thousands of simple queries/s.",
        "Cache hit ratios of 80–95% are normal for a well-chosen hot set — state your assumption.",
        "Round to powers of ten and say you're rounding. Precision here is a trap, not a virtue.",
      ],
    },
    {
      title: "The building blocks",
      points: [
        "Load balancer — L4 (fast, TCP) or L7 (routes on path/header, terminates TLS). Health checks and connection draining.",
        "CDN — static assets and cacheable API responses at the edge; the cheapest latency win available.",
        "Cache — Redis for shared state; cache-aside is the default pattern; TTL plus explicit invalidation.",
        "Queue/stream — Kafka for high-throughput ordered logs and replay; SQS/RabbitMQ for task distribution.",
        "Object storage — S3 for blobs; never store files in a relational database.",
        "Search index — Elasticsearch/OpenSearch for full-text; kept in sync asynchronously.",
        "Database — relational by default; add read replicas, then partitioning, then sharding.",
        "API gateway — auth, rate limiting, routing; keeps cross-cutting concerns out of every service.",
      ],
    },
    {
      title: "Reliability patterns",
      points: [
        "Timeouts on every network call — an unbounded call is how one slow dependency takes down a fleet.",
        "Retries with exponential backoff AND jitter — without jitter, retries synchronise into a thundering herd.",
        "Circuit breaker — stop calling a failing dependency, fail fast, probe periodically.",
        "Bulkhead — separate connection pools/thread pools per dependency so one failure can't consume all capacity.",
        "Idempotency keys — retries are inevitable, so make repeated delivery safe.",
        "Graceful degradation — serve stale cache, hide a non-critical feature, queue instead of rejecting.",
        "Rate limiting and load shedding — protect the system by rejecting excess early rather than collapsing.",
        "Backpressure — signal upstream to slow down rather than buffering without bound.",
      ],
    },
    {
      title: "Consistency choices",
      points: [
        "Strong consistency — reads see the latest write. Needed for money, inventory, and uniqueness. Costs latency and availability.",
        "Eventual consistency — replicas converge. Fine for feeds, counts, likes, and search indexes.",
        "Read-your-own-writes — the user must see their own change; route their reads to the primary or a sticky replica for a window.",
        "Monotonic reads — never show older data than you already showed; sticky routing solves it.",
        "Idempotency + at-least-once delivery is usually the pragmatic replacement for exactly-once.",
        "Say WHICH data needs which guarantee — most systems need strong consistency for a small subset and eventual for the rest.",
      ],
    },
  ],

  decisions: [
    {
      title: "Monolith vs microservices",
      options: [
        {
          name: "Monolith (modular)",
          pick: ["Default for a new product or a small team.", "Domain boundaries aren't yet clear — and they usually aren't.", "You want simple local transactions, one deploy, and easy refactoring across boundaries."],
          cost: ["Scaling is all-or-nothing.", "One team's bad deploy affects everything.", "Without discipline, module boundaries erode into a big ball of mud."],
        },
        {
          name: "Microservices",
          pick: ["Many teams needing independent deploy cadence — this is the real driver, and it's organisational.", "Components with genuinely different scaling or reliability profiles.", "You need technology diversity for a specific reason."],
          cost: ["Distributed transactions become sagas; every call can fail partially.", "Operational burden: service discovery, tracing, versioning, per-service datastores.", "A refactor across service boundaries is a project, not a commit."],
        },
      ],
      verdict: "Start with a well-modularised monolith and extract services when a specific team or scaling pressure demands it. Microservices solve an organisational problem, and buy it with distributed-systems complexity.",
      topic: "microservices",
    },
    {
      title: "SQL vs NoSQL in a design interview",
      options: [
        {
          name: "Relational",
          pick: ["Relationships, transactions, and queries you can't fully predict.", "Anything involving money or inventory.", "Default — and say it's the default."],
          cost: ["Write scaling beyond one machine needs sharding.", "Schema migrations at scale need care."],
        },
        {
          name: "NoSQL",
          pick: ["A single, well-known access pattern at very large scale.", "Time-series and event data (wide-column).", "Massive write throughput with a natural partition key.", "Flexible or deeply nested documents."],
          cost: ["Joins and ad-hoc queries are expensive or absent.", "You own consistency across denormalised copies."],
        },
      ],
      verdict: "Justify from access patterns, not from scale alone. 'Postgres until the access pattern or write volume forces otherwise' is a strong, defensible answer.",
      topic: "cap-and-nosql",
    },
    {
      title: "Synchronous call vs message queue",
      options: [
        {
          name: "Synchronous",
          pick: ["The caller needs the result to proceed.", "The work is fast and the failure should be visible immediately.", "Simple request/response semantics with clear errors."],
          cost: ["Caller is coupled to callee availability and latency.", "A slow dependency propagates back as user-facing latency.", "Traffic spikes hit the downstream service directly."],
        },
        {
          name: "Queue / async",
          pick: ["Slow work: video encoding, emails, report generation, third-party calls.", "Absorbing spikes — the queue buffers.", "Fan-out to multiple consumers.", "The caller only needs an acknowledgement."],
          cost: ["Eventual consistency — the user doesn't see the result yet.", "You need dead-letter queues, retries, idempotency, and monitoring of queue depth.", "Debugging spans a broker."],
        },
      ],
      verdict: "If the user needs the answer now, go synchronous. If they need an acknowledgement now and the result later, queue it — and make consumers idempotent.",
      topic: "queues-vs-pubsub",
    },
    {
      title: "Cache-aside vs write-through vs write-behind",
      options: [
        {
          name: "Cache-aside (lazy)",
          pick: ["Default. Application checks cache, misses, reads the database, populates.", "Read-heavy workloads with an unpredictable hot set."],
          cost: ["Every miss pays full latency; cold start is slow.", "Stampede risk when a hot key expires.", "Cache and database can drift — mitigate with TTL plus explicit invalidation."],
        },
        {
          name: "Write-through",
          pick: ["Reads must be fresh immediately after a write.", "You can accept slower writes for cache consistency."],
          cost: ["Every write pays cache latency too.", "Caches data that may never be read."],
        },
        {
          name: "Write-behind",
          pick: ["Very write-heavy workloads where you can batch to the database: counters, metrics, analytics."],
          cost: ["Data loss window if the cache dies before flushing — unacceptable for anything durable."],
        },
      ],
      verdict: "Cache-aside unless you have a specific reason. Write-behind only for data you can afford to lose.",
      topic: "cache-strategies",
    },
    {
      title: "Consistent hashing vs modulo sharding",
      options: [
        {
          name: "Consistent hashing",
          pick: ["The number of nodes changes: caches, distributed stores, autoscaling clusters.", "You need minimal data movement when adding or removing a node."],
          cost: ["More complex; needs virtual nodes to avoid uneven distribution.", "Doesn't by itself solve a hot key — one popular key still lands on one node."],
        },
        {
          name: "hash(key) % N",
          pick: ["N is genuinely fixed and will not change.", "Simplicity matters more than elasticity."],
          cost: ["Changing N remaps almost every key — for a cache that's a total miss storm, for a datastore it's a migration."],
        },
      ],
      verdict: "Any cluster that resizes needs consistent hashing with virtual nodes. Modulo is fine only when N never changes.",
      topic: "sharding",
    },
  ],

  qa: [
    {
      id: "sd-framework",
      q: "How do you approach a system design question you've never seen?",
      a: "Structure buys you time and demonstrates seniority. Spend the first five minutes on requirements, separating functional from non-functional and scoping aggressively — a design interview for 'design Twitter' cannot cover the whole product, so agree on three or four core features. Then estimate: daily active users, requests per second, read-to-write ratio, storage growth. That step isn't arithmetic for its own sake; it tells you whether this is a single-database problem or a distributed one. Then sketch the API, which forces precision about what the system does, and the data model with its access patterns. Only then draw the high-level design, starting with the happy path. Reserve the second half for a deep dive on whichever part is genuinely hard, and finish by naming your own bottlenecks, single points of failure, and what you'd change at ten times the scale. Throughout, state assumptions aloud so the interviewer can redirect you early rather than at the end.",
      why: "Most candidates fail on process, not knowledge — they draw boxes for forty minutes without establishing what they're building.",
      trap: "Jumping straight to architecture. Without requirements and scale you have no basis for any decision you make, and you'll be unable to justify anything.",
      followUps: ["What questions would you ask about requirements?", "How do you decide what to scope out?"],
      depth: "Core",
      tags: ["process"],
      topic: "system-design-framework",
    },
    {
      id: "sd-estimation",
      q: "Why do estimates matter, and how do you do them quickly?",
      a: "They determine the architecture. A system at 100 requests per second and 50 GB of data runs on one Postgres instance and a cache; the same design at 500,000 requests per second and petabytes is a completely different conversation. Doing the estimate early stops you over-engineering a simple problem or under-engineering a hard one. The method is deliberately rough: start from daily active users, multiply by actions per user per day to get daily requests, divide by roughly 100,000 seconds to get average requests per second, and multiply by two or three for peak. For storage, multiply records per day by bytes per record, then by retention, then add replication and index overhead — a factor of two or three. Round everything to powers of ten and say you're rounding. The number itself is less important than the conclusion you draw from it, so always finish an estimate with what it implies: 'that's about 300 GB a year, which fits comfortably on one machine, so I won't shard'.",
      why: "It's the step that justifies every subsequent decision, and skipping it makes the rest of the interview unanchored.",
      trap: "Computing numbers and then never referring to them again. The estimate must visibly drive a decision.",
      followUps: ["What's a reasonable peak-to-average ratio?", "What would change if the read:write ratio inverted?"],
      depth: "Core",
      tags: ["estimation"],
      topic: "estimation",
    },
    {
      id: "sd-url-shortener",
      q: "Design a URL shortener.",
      a: "Functionally: create a short code for a long URL, and redirect on access; optionally custom aliases, expiry, and click analytics. The defining characteristic is the read:write ratio, typically 100:1 or higher, so this is a read-optimised design. For the code, a counter encoded in base62 gives short, collision-free codes but needs a distributed counter — a ticket server or ranges pre-allocated per instance avoids a bottleneck; hashing the URL and taking a prefix is simpler but needs collision handling. Seven base62 characters give about 3.5 trillion codes, which is ample. Storage is a simple key-value mapping, so a key-value store or a well-indexed relational table both work, and the row is tiny. The read path is the interesting part: put a cache in front keyed by short code, expect a very high hit rate since access follows a power law, and use a CDN or edge redirect for the hottest links. Return 301 for permanent redirects if you don't need analytics, or 302 if you do, since a 301 is cached by the browser and you stop seeing the traffic. Analytics should be asynchronous — publish a click event to a queue rather than writing synchronously on the redirect path.",
      why: "It's the canonical warm-up and rewards clean reasoning about encoding, read-heaviness, and caching.",
      trap: "Writing an analytics row synchronously on every redirect. That turns a cache-served read into a database write and destroys your latency and scale story.",
      followUps: ["How do you generate codes without a central counter?", "Why does the 301 vs 302 choice matter?"],
      depth: "Intermediate",
      tags: ["case-study"],
      topic: "design-url-shortener",
    },
    {
      id: "sd-rate-limiter",
      q: "Design a rate limiter.",
      a: "Decide first what you're limiting — per user, per IP, per API key, per endpoint — and where it sits, which is normally the API gateway so every service is protected without duplicating logic. The algorithm choice is the substance. A fixed window counter is trivial but allows a burst of double the limit across a window boundary. A sliding window log stores timestamps and is exact but memory-heavy. A sliding window counter interpolates between the previous and current window, which is a good accuracy-to-cost compromise and what most production limiters use. A token bucket allows controlled bursts while limiting the sustained rate, which usually matches what you actually want from an API. In a distributed setting the state must be shared, so Redis with an atomic Lua script or `INCR` plus `EXPIRE` is standard — doing it in process memory means the effective limit multiplies by the number of instances. Return 429 with `Retry-After`, and decide the failure mode deliberately: if Redis is down, do you fail open and risk overload, or fail closed and reject legitimate traffic?",
      why: "It combines algorithm choice, distributed state, and an explicit failure-mode decision in one compact problem.",
      trap: "Keeping counters in application memory. With ten instances the user gets ten times the limit.",
      followUps: ["Why does a fixed window allow a 2× burst?", "Fail open or fail closed when Redis is unavailable?"],
      depth: "Intermediate",
      tags: ["case-study"],
      topic: "design-rate-limiter",
    },
    {
      id: "sd-newsfeed",
      q: "Design a news feed. Fan-out on write or on read?",
      a: "Fan-out on write means that when someone posts, you push the post id into every follower's precomputed feed list, usually in Redis. Reads are then trivially fast — just read your list — which suits a read-heavy product. The problem is celebrities: a user with fifty million followers triggers fifty million writes for one post, which is a write storm and a latency spike. Fan-out on read means you compute the feed at request time by querying the posts of everyone you follow and merging. Writes are cheap, but reads are expensive and slow, and they get worse as follow counts grow. The production answer is hybrid: fan out on write for ordinary users, and for accounts above a follower threshold skip the fan-out and merge their posts in at read time. That keeps the common path fast while bounding the worst case. Worth adding: the feed list should be capped at a few hundred entries with older content fetched on demand, ranking is a separate concern layered on top of retrieval, and the fan-out itself should run through a queue so a burst doesn't block the write path.",
      why: "It's the classic trade-off question, and the hybrid answer with a named threshold is exactly what's being looked for.",
      trap: "Picking one strategy and defending it absolutely. The interviewer is testing whether you notice the celebrity problem.",
      followUps: ["Where would you set the follower threshold?", "How do you handle a user following 5,000 accounts?"],
      depth: "Advanced",
      tags: ["case-study", "scaling"],
      topic: "design-news-feed",
    },
    {
      id: "sd-idempotency",
      q: "Why does idempotency matter, and how do you implement it?",
      a: "Because networks fail ambiguously. When a client times out waiting for a payment response it cannot tell whether the request succeeded, so it retries — and without idempotency the customer is charged twice. Since at-least-once delivery is what you actually get from retries, queues, and load balancers, idempotency is what makes it safe. The standard implementation is an idempotency key: the client generates a unique key per logical operation and sends it as a header; the server, inside a transaction, attempts to insert that key into a table with a unique constraint, and if the insert succeeds it performs the work and stores the response against the key, while if it conflicts it returns the stored response instead of re-executing. Details that matter: the key must be scoped to the caller so keys can't collide across tenants, you need a TTL so the table doesn't grow forever, and you must handle the in-flight case where a retry arrives before the first request finished — usually by returning 409 and asking the client to retry. Note that some operations are naturally idempotent, like setting a value, while increments are not.",
      why: "It's the practical foundation of reliable distributed systems and shows the candidate thinks about partial failure.",
      trap: "Assuming exactly-once delivery exists. It doesn't at the messaging layer; you get at-least-once plus idempotent processing.",
      followUps: ["What happens when a retry arrives while the original is still running?", "Which HTTP methods are idempotent by definition?"],
      depth: "Advanced",
      tags: ["reliability", "distributed"],
      topic: "idempotency",
    },
    {
      id: "sd-cache-stampede",
      q: "What is a cache stampede and how do you prevent it?",
      a: "When a popular cached key expires, every concurrent request misses simultaneously and they all hit the database at once — so a key serving ten thousand requests per second suddenly sends ten thousand identical queries to a database that can handle a few hundred, which can take it down and then keep it down as retries pile up. It's a self-inflicted thundering herd, and it's most dangerous precisely for your hottest keys. Three mitigations, usually combined. Locking or single-flight: the first request to miss takes a short distributed lock and repopulates while the others either wait briefly or serve the stale value. Probabilistic early expiry: as a key approaches its TTL, each request has a small and growing chance of refreshing it, so one request refreshes early and the rest keep hitting a warm cache. And jittered TTLs, so keys populated together don't expire together — this also fixes the related problem of a cold cache after a deploy or restart, where everything expires at once.",
      why: "It's a real outage pattern and a good test of whether someone has operated a cache under load.",
      trap: "Adding a cache and treating it as pure upside. A cache changes your failure modes; a stampede or a cold start can be worse than no cache.",
      followUps: ["How does the single-flight pattern work?", "What happens to your database when the cache restarts?"],
      depth: "Advanced",
      tags: ["caching", "reliability"],
      topic: "cache-invalidation",
    },
    {
      id: "sd-hot-partition",
      q: "What is a hot partition and how do you fix it?",
      a: "When one shard or partition receives disproportionate traffic, so it saturates while the rest of the cluster idles — your effective capacity becomes that of a single node no matter how many you have. It comes from a partition key with skew: sharding by tenant when one tenant is a thousand times larger, by date when everything writes to today's partition, or by a celebrity user id. The fixes depend on the cause. For write skew on a sequential key, add a salt or a random suffix so writes spread across partitions, accepting that reads must now query all the buckets and merge. For a genuinely hot single entity, replicate it specially — cache it separately, or give a celebrity account dedicated handling as in the feed fan-out problem. For a large tenant, shard within that tenant on a secondary dimension. The broader lesson is that choosing a partition key is one of the least reversible decisions in a design, so you should explicitly examine its distribution — and its worst case — before committing.",
      why: "It's the failure mode that makes a horizontally-scaled design fail to scale, and noticing it unprompted is a strong signal.",
      trap: "Claiming a design scales because it's sharded, without examining whether the key distributes evenly.",
      followUps: ["How would you shard a multi-tenant system with one enormous tenant?", "What does salting cost you on reads?"],
      depth: "Advanced",
      tags: ["scaling", "sharding"],
      topic: "sharding",
    },
    {
      id: "sd-circuit-breaker",
      q: "What is a circuit breaker and why not just retry?",
      a: "A circuit breaker tracks failures to a dependency and, once they cross a threshold, opens — failing subsequent calls immediately without attempting them — then after a cooling period allows a trial request through, closing again if it succeeds. The reason retrying alone is insufficient is that retries make an overloaded dependency worse: if a service is failing because it's saturated, every caller retrying triples its load and guarantees it stays down, and meanwhile your own threads or connections are all blocked waiting on timeouts, so your service fails too. That cascade is how one component's degradation becomes a full outage. The breaker converts slow failure into fast failure, which frees your resources and gives the dependency room to recover. It pairs with three other things: timeouts, because a breaker cannot trip on calls that never return; a fallback for what to serve when open, such as stale cache or a reduced feature; and bulkheads, so each dependency has its own pool and one saturated dependency cannot consume all your capacity.",
      why: "It shows understanding of cascading failure, which is what actually causes large outages.",
      trap: "Adding retries without a breaker or a timeout. That amplifies load precisely when the system can least afford it.",
      followUps: ["Why is jitter important in backoff?", "What do you serve while the circuit is open?"],
      depth: "Advanced",
      tags: ["reliability", "patterns"],
      topic: "resilience-patterns",
    },
    {
      id: "sd-chat",
      q: "Design a chat system.",
      a: "The core requirements are one-to-one and group messaging, delivery and read receipts, online presence, and message history. Unlike a feed, this is roughly balanced between reads and writes and it's latency-sensitive, so the transport matters: WebSockets give a persistent bidirectional connection, which is what you want, with long-polling as a fallback. That creates the central architectural problem — connections are stateful, so you need a registry mapping user id to the gateway node holding their connection, typically in Redis, and when A sends to B the receiving service looks up B's node and forwards the message there, often over a pub/sub channel so the sending node doesn't need a direct path. For storage, messages are append-only, ordered within a conversation, and queried by recent-first, which suits a wide-column store partitioned by conversation id with a time-based clustering key; a relational database works fine at moderate scale. Ordering should use a sequence per conversation rather than client timestamps, since clocks disagree. Offline delivery needs a queue per user and a push notification path. And group chat forces the same fan-out decision as a feed: fine to fan out for small groups, but a large channel needs read-time merging.",
      why: "It exercises stateful connections, which most designs avoid, and the connection registry is the piece candidates miss.",
      trap: "Designing it as stateless HTTP request/response. Real-time delivery needs persistent connections and therefore connection-to-node routing.",
      followUps: ["How does a message reach a user connected to a different gateway node?", "How do you order messages when clocks disagree?"],
      depth: "Advanced",
      tags: ["case-study", "realtime"],
      topic: "design-chat-system",
    },
    {
      id: "sd-consistency-choice",
      q: "How do you decide between strong and eventual consistency?",
      a: "Per data type, not per system — the mistake is treating it as one global setting. Ask what happens if a read returns data a few seconds stale. For a like count, a follower count, or a search index, nothing meaningful: the user won't notice and no invariant breaks, so eventual consistency buys you availability and latency for free. For account balances, inventory decrements, uniqueness constraints, and permission checks, stale data means double-spending, overselling, duplicate usernames, or a security hole, so those need strong consistency and are worth the cost. Most systems are mostly the second category by volume and mostly the first category by importance, which is why the right answer partitions them. There's also a middle tier worth naming: read-your-own-writes, where the user must see their own change even if others see it late, which you get by routing that user's reads to the primary for a short window rather than making the whole system strongly consistent. Saying which data needs which guarantee is what distinguishes a considered design.",
      why: "It's the trade-off interviewers most want to hear reasoned rather than asserted.",
      trap: "Declaring the whole system strongly consistent 'to be safe'. That's an availability and latency cost you're paying for data that doesn't need it.",
      followUps: ["How do you implement read-your-own-writes?", "Where does eventual consistency become user-visible and confusing?"],
      depth: "Advanced",
      tags: ["consistency", "distributed"],
      topic: "consistency-models",
    },
    {
      id: "sd-queue-guarantees",
      q: "What delivery guarantees can a queue give you?",
      a: "At-most-once means a message may be lost but never duplicated — you acknowledge before processing, so a crash loses the work. At-least-once means it's never lost but may be delivered more than once — you acknowledge after processing, so a crash before the ack causes redelivery. Exactly-once is what everyone wants and is not achievable end to end in a distributed system in the general case: the acknowledgement itself can be lost, so the sender genuinely cannot know. What systems like Kafka call exactly-once is exactly-once processing within their own transactional boundary, using idempotent producers and transactional offset commits, which is real but does not extend to side effects in an external system such as sending an email or charging a card. So the practical architecture is at-least-once delivery plus idempotent consumers, which gives you the observable behaviour of exactly-once without needing the impossible guarantee. Alongside that you need dead-letter queues for poison messages, a retry policy with backoff, and monitoring on queue depth and consumer lag.",
      why: "The 'exactly-once doesn't exist, use at-least-once plus idempotency' answer is a clear seniority marker.",
      trap: "Claiming a broker gives you exactly-once and stopping there. Ask what happens to an external side effect on redelivery.",
      followUps: ["What is a dead-letter queue for?", "How does Kafka's transactional processing work?"],
      depth: "Advanced",
      tags: ["messaging", "reliability"],
      topic: "delivery-guarantees",
    },
    {
      id: "sd-single-point",
      q: "How do you find single points of failure in your own design?",
      a: "Walk each component and ask what happens if it dies, and separately what happens if it becomes slow rather than dead — slow is usually worse, because dead fails fast while slow ties up callers' resources. The usual culprits are a single database primary, which needs replication with automated failover and a tested promotion path; a load balancer, which needs redundancy and DNS or anycast failover; a cache, where the question is whether the database survives the resulting miss storm; a message broker, which needs clustering and replicated partitions; and anything with a single leader, which needs an election protocol. Then look beyond infrastructure: a shared configuration service, a single certificate, a DNS provider, and a cloud region are all single points people forget. It's also worth naming the ones you're accepting deliberately — 'this is single-region, so a region outage is total, and I'd address that with multi-region active-passive if the availability target demanded it' is a stronger answer than pretending there are none.",
      why: "Volunteering your own design's weaknesses is one of the strongest signals available in a design interview.",
      trap: "Waiting for the interviewer to find the weakness. Naming it first shows judgement and controls the conversation.",
      followUps: ["Why is a slow dependency worse than a dead one?", "What's your failover plan for the database primary?"],
      depth: "Advanced",
      tags: ["reliability"],
      topic: "fault-tolerance",
    },
    {
      id: "sd-cdn",
      q: "When and why would you put a CDN in your design?",
      a: "For anything cacheable that's served to many users from far away — static assets first, but also images, video segments, and increasingly cacheable API responses. The gains are threefold. Latency drops because content is served from a point of presence physically near the user, and since round-trip time is bounded by the speed of light, this is a class of improvement you cannot achieve any other way. Origin load drops, often dramatically, because a high cache hit ratio means your servers see a small fraction of requests. And bandwidth costs usually fall, since CDN egress is typically cheaper than origin egress. The details worth mentioning are cache keys and `Cache-Control` headers, since caching a personalised response by URL alone leaks one user's data to another and is a genuine incident pattern; using content hashes in asset filenames so you can cache immutably and never need invalidation; and having a purge path for the cases where you do. For dynamic content, edge compute lets you do routing, auth checks, or personalisation near the user while still caching the shared part.",
      why: "It's the cheapest latency win available and candidates often skip it entirely.",
      trap: "Caching a personalised response at the edge without varying the cache key. That's a data-leak incident, not just a bug.",
      followUps: ["How do you invalidate CDN content?", "Why hash asset filenames?"],
      depth: "Intermediate",
      tags: ["caching", "latency"],
      topic: "design-cdn",
    },
    {
      id: "sd-tradeoffs",
      q: "The interviewer says 'what are the trade-offs of your design?' — what do they want?",
      a: "Evidence that you chose rather than defaulted. A strong answer names three or four specific decisions, what you gained, what you gave up, and under what conditions you'd choose differently — for example, 'I used cache-aside, which means a cold cache after deploy sends a burst to the database; I'd add jittered TTLs and consider warming the top keys, and if the data were small enough I'd switch to write-through instead'. It also identifies where the design will break first as load grows, which is usually a specific component and a specific number, and what the next step would be. And it should acknowledge what you deliberately did not build: no multi-region, no exactly-once, no full-text search, because the requirements didn't call for them. What weakens an answer here is generic trade-off vocabulary — saying you traded consistency for availability without saying which data, or listing CAP without applying it. The underlying signal is whether you can reason about your own work critically, which is exactly what a senior engineer does in a design review.",
      why: "This question is often where the level decision is made, and it's entirely predictable — so it should be prepared.",
      trap: "Answering with textbook trade-offs in the abstract. Tie every one to a specific decision you made in this design.",
      followUps: ["What breaks first at 10× traffic?", "What did you deliberately leave out and why?"],
      depth: "Core",
      tags: ["process", "communication"],
      topic: "tradeoff-analysis",
    },
  ],

  pitfalls: [
    "Don't start drawing the architecture before establishing requirements and scale.",
    "Don't compute estimates and then ignore them — every number should justify a decision.",
    "Don't propose microservices for a small team; say the driver is organisational, not technical.",
    "Don't claim exactly-once delivery — say at-least-once plus idempotent consumers.",
    "Don't declare the whole system strongly consistent — say which data needs which guarantee.",
    "Don't add a cache without addressing invalidation, stampede, and cold start.",
    "Don't say 'we'll shard it' without naming the shard key and checking its distribution.",
    "Don't wait for the interviewer to find your single point of failure — name it yourself.",
  ],

  numbers: [
    { label: "1M DAU × 10 req/day", value: "~115 req/s avg", note: "Peak 2–3×. Use 100,000 s/day for mental maths." },
    { label: "Memory read", value: "~100 ns", note: "vs ~100 µs SSD, ~0.5 ms same-DC round trip." },
    { label: "Cross-region round trip", value: "~50–150 ms", note: "Speed of light — why a CDN is irreplaceable." },
    { label: "Typical cache hit ratio", value: "80–95%", note: "State your assumption; it drives the origin load estimate." },
    { label: "1 KB × 1M rows/day", value: "~365 GB/year", note: "Then multiply for replication and indexes." },
    { label: "Availability: 99.9% / 99.99%", value: "~8.8 h / ~53 min per year", note: "Each nine costs roughly an order of magnitude more." },
  ],

  relatedTopics: [
    "system-design-framework",
    "estimation",
    "tradeoff-analysis",
    "hld-fundamentals",
    "load-balancing",
    "cache-strategies",
    "sharding",
    "consistency-models",
    "resilience-patterns",
    "idempotency",
    "queues-vs-pubsub",
    "microservices",
  ],
};
