import type { Area } from "../types";

export const testingDevops: Area = {
  slug: "testing-devops",
  title: "Testing, Git & Delivery",
  icon: "🚀",
  stream: "Platform & Delivery",
  blurb:
    "The test pyramid, what to mock and what not to, Git questions that actually get asked, containers, and deploying without downtime.",

  mustKnow: [
    "Test pyramid: many fast unit tests, fewer integration tests, very few end-to-end tests. Inverted, it's slow and flaky.",
    "Test behaviour through the public interface, not implementation details — tests coupled to internals break on every refactor and still miss regressions.",
    "Mock at the boundary you don't own (network, clock, filesystem). Mocking your own code heavily means the tests verify your mocks.",
    "A flaky test is worse than no test: it trains the team to ignore failures. Fix it or delete it.",
    "Coverage measures which lines ran, not whether behaviour is correct. 100% coverage with no assertions is possible.",
    "CI runs on every push — build, lint, type-check, test. If it isn't blocking merges it isn't doing its job.",
    "A container image should be reproducible, minimal, non-root, and pinned by digest.",
    "Deploys should be zero-downtime by default: rolling, blue-green, or canary — with a tested rollback.",
    "Separate deploy from release with feature flags, so shipping code and enabling behaviour are different decisions.",
    "`git rebase` rewrites history and `git merge` preserves it. Never rebase a branch others have pulled.",
  ],

  sheets: [
    {
      title: "What each test level is for",
      points: [
        "Unit — one function or class, no I/O, milliseconds. Catches logic errors; the bulk of your suite.",
        "Integration — several components together, real database or real HTTP against a test server. Catches wiring, SQL, and serialisation errors.",
        "Contract — verifies a consumer's expectations against a provider's API without running both. Catches cross-service breakage in CI.",
        "End-to-end — the whole system through the UI. Catches what nothing else does; slow, flaky, expensive. Keep a handful covering critical journeys.",
        "Smoke tests post-deploy — is it actually up and serving?",
        "Property-based — generate inputs and assert invariants; finds edge cases you'd never enumerate.",
        "Rule: push each test down the pyramid as far as it can go while still catching the bug.",
      ],
    },
    {
      title: "Test quality",
      points: [
        "Arrange–Act–Assert; one behaviour per test; the name should state the behaviour and the expectation.",
        "Tests must be independent and order-independent — shared mutable state is the top cause of flakiness.",
        "Deterministic: inject the clock, seed randomness, never depend on real network or `sleep`.",
        "Prefer real objects to mocks where cheap; use fakes (in-memory implementations) over mocks where possible.",
        "Test doubles: dummy (unused), stub (canned answers), spy (records calls), mock (asserts interactions), fake (working lightweight implementation).",
        "Assert on outcomes, not on how many times an internal method was called.",
        "If a test needs extensive setup, that's feedback about the design, not just the test.",
      ],
    },
    {
      title: "Git commands you'll be asked about",
      points: [
        "`git merge` — creates a merge commit, preserves true history, safe on shared branches.",
        "`git rebase` — replays your commits on a new base; linear history, but rewrites commit ids.",
        "`git rebase -i` — squash, reword, reorder before opening a PR.",
        "`git revert` — creates a new commit undoing an old one. The safe way to undo on a shared branch.",
        "`git reset --soft/--mixed/--hard` — moves the branch pointer; `--hard` discards working changes irrecoverably.",
        "`git cherry-pick` — apply one commit elsewhere; useful for hotfixes onto a release branch.",
        "`git stash` — park uncommitted work.",
        "`git bisect` — binary search history to find the commit that introduced a bug.",
        "`git reflog` — the safety net; recovers 'lost' commits after a bad reset or rebase.",
      ],
    },
    {
      title: "Containers",
      points: [
        "An image is layers; a container is a running instance. Layers are cached, so order Dockerfile steps least- to most-frequently-changing.",
        "Copy dependency manifests and install BEFORE copying source, so a code change doesn't invalidate the dependency layer.",
        "Multi-stage builds: compile in a builder stage, copy only the artefact into a slim runtime image.",
        "Run as a non-root user; use a minimal base (distroless, alpine, slim); pin the base by digest.",
        "`.dockerignore` matters — without it you copy `node_modules`, `.git`, and secrets into the build context.",
        "One process per container; let the orchestrator handle restarts and scaling.",
        "Secrets via environment or a mounted secret store, never baked into a layer — layers are permanent and inspectable.",
        "Containers share the host kernel — that's why they're light, and why isolation is weaker than a VM.",
      ],
    },
    {
      title: "Deployment strategies",
      points: [
        "Rolling — replace instances gradually. Default in Kubernetes; needs both versions to coexist safely.",
        "Blue-green — run two full environments, switch traffic at once. Instant rollback, double the infrastructure.",
        "Canary — send a small percentage to the new version, watch metrics, then ramp. Best risk/cost balance; needs good observability.",
        "Feature flags — deploy dark, enable per cohort, kill instantly without redeploying. Separates deploy from release.",
        "Always: readiness and liveness probes, graceful shutdown, and a tested rollback path.",
        "Backward-compatible database migrations (expand → migrate → contract), because old and new code run simultaneously.",
        "Post-deploy smoke tests and automatic rollback on error-rate SLO breach.",
      ],
    },
  ],

  decisions: [
    {
      title: "Mock vs real dependency in tests",
      options: [
        {
          name: "Mock / stub",
          pick: ["Third-party APIs you don't control.", "Non-determinism: the clock, randomness, network failure injection.", "Slow or costly dependencies.", "Simulating error paths that are hard to trigger for real."],
          cost: ["Mocks encode your ASSUMPTION about the dependency; when it changes, tests still pass and production breaks.", "Over-mocking produces tests that verify the mocks, not the code."],
        },
        {
          name: "Real (or a fake)",
          pick: ["Your own database — use a container or an in-memory equivalent.", "Anything where the integration is the risk: SQL, serialisation, migrations.", "In-memory fakes give realism without the latency."],
          cost: ["Slower tests, more setup, and data cleanup between tests."],
        },
      ],
      verdict: "Mock what you don't own and what's non-deterministic; use the real thing (or a fake) for what you do own. Contract tests cover the gap left by mocking a third party.",
      topic: "test-doubles",
    },
    {
      title: "Merge vs rebase",
      options: [
        {
          name: "Merge",
          pick: ["Shared/public branches — never rewrite history others have.", "You want the true history of when work integrated.", "Simpler and safer for a team that isn't fluent with Git."],
          cost: ["Noisy history with many merge commits.", "Harder to bisect and read a tangled graph."],
        },
        {
          name: "Rebase",
          pick: ["Your own local feature branch, before opening or updating a PR.", "You want a clean, linear history that bisects well.", "Squashing WIP commits into meaningful ones."],
          cost: ["Rewrites commit ids — destructive if others have based work on the branch.", "Conflicts can resurface per replayed commit.", "Loses the true chronology of integration."],
        },
      ],
      verdict: "Rebase your own unpushed work to tidy it; merge to integrate into shared branches. The rule that prevents disasters: never rebase anything someone else may have pulled.",
      topic: "rebasing",
    },
    {
      title: "Blue-green vs canary vs rolling",
      options: [
        {
          name: "Rolling",
          pick: ["Default. No extra infrastructure, gradual replacement."],
          cost: ["Both versions run simultaneously, so schema and API changes must be backward-compatible.", "Rollback is another rolling deploy — not instant."],
        },
        {
          name: "Blue-green",
          pick: ["You need instant, complete rollback.", "You want to smoke-test the new environment with real infrastructure before any user traffic."],
          cost: ["Double the infrastructure during the switch.", "Shared state (database, cache) still needs compatibility across both.", "Cutover is all-or-nothing — a bad release hits everyone at once."],
        },
        {
          name: "Canary",
          pick: ["Highest-risk changes.", "You have the observability to compare error rate and latency between cohorts.", "Best risk-per-cost of the three."],
          cost: ["Needs traffic splitting and per-version metrics.", "Slower rollout; a subtle regression may not show at 5% traffic."],
        },
      ],
      verdict: "Rolling as the default, canary for risky changes, blue-green when instant rollback is worth the duplicated infrastructure. Feature flags complement all three.",
      topic: "release-strategies",
    },
  ],

  qa: [
    {
      id: "test-pyramid",
      q: "What is the test pyramid and why that shape?",
      a: "Many unit tests at the base, fewer integration tests in the middle, very few end-to-end tests at the top — and the shape follows from cost and feedback speed. Unit tests run in milliseconds, pinpoint the failure to a single function, and are cheap to write, so you can afford thousands and run them on every save. End-to-end tests exercise the real system through the UI, so they catch integration problems nothing else does, but they're slow, expensive to maintain, and inherently flaky because of timing, network, and environment variation, and when one fails it tells you something broke somewhere. Inverting the pyramid — the 'ice cream cone' — gives a suite that takes an hour, fails intermittently, and gets ignored, which is worse than having fewer tests. The practical rule is to push every test as far down as it can go while still catching the bug you care about, and to reserve end-to-end coverage for a handful of critical user journeys like signup and checkout. Contract tests deserve a mention as the middle-ground answer for microservices, catching cross-service breakage in CI without running everything together.",
      why: "It's the framework for deciding where a test belongs, which is a daily judgement call.",
      trap: "Aiming for high end-to-end coverage because it's 'most realistic'. Realism costs you speed and reliability, and a flaky suite gets ignored.",
      followUps: ["Where do contract tests fit?", "What belongs in your handful of E2E tests?"],
      depth: "Core",
      tags: ["testing"],
      topic: "test-pyramid",
    },
    {
      id: "test-what-to-mock",
      q: "What should you mock, and what shouldn't you?",
      a: "Mock what you don't own and what you can't control: third-party APIs, the clock, randomness, and failure conditions that are hard to trigger for real. Don't mock what you do own, and especially don't mock your own database — the SQL, the migrations, and the serialisation are exactly where bugs live, and mocking them means testing that your code calls a fake in the order you expected. The deeper problem with heavy mocking is that a mock encodes your assumption about the dependency's behaviour, so when the real dependency changes, your tests still pass and production breaks, which is the opposite of what a test is for. Where you must mock a third party, pair it with a contract test that verifies your assumption against the real provider, so the assumption is checked somewhere. Prefer fakes over mocks in general — an in-memory implementation of a repository behaves like the real thing rather than replaying canned answers — and prefer testcontainers or a real test database for integration tests, which is fast enough now that the old excuse doesn't hold.",
      why: "Over-mocking is the most common cause of test suites that are green and worthless.",
      trap: "Mocking the repository layer and asserting it was called with certain arguments. That tests your mock's configuration, not your behaviour.",
      followUps: ["What's the difference between a mock and a fake?", "How does a contract test cover the gap?"],
      depth: "Intermediate",
      tags: ["testing", "mocking"],
      topic: "test-doubles",
    },
    {
      id: "test-flaky",
      q: "How do you deal with a flaky test?",
      a: "Treat it as a priority bug, because the real damage isn't the failing run — it's that the team learns to re-run CI instead of reading failures, and once that habit forms a genuine regression gets ignored too. Diagnose the cause rather than adding a retry: the usual sources are shared mutable state between tests, so run order changes the result; timing assumptions, where a `sleep` or a fixed wait races with real work; dependence on the real clock, timezone, or date; unseeded randomness; a real network call; and parallel tests contending for the same database rows or ports. The fixes are correspondingly specific — isolate state and reset it per test, wait for a condition rather than a duration, inject the clock, seed the random source, stub the network, and namespace test data per worker. If you genuinely can't fix it now, quarantine it out of the blocking suite with an owner and a deadline rather than leaving it to erode trust. And deleting it is a legitimate option: a test nobody believes provides negative value.",
      why: "How someone handles flakiness reveals whether they treat the test suite as an asset or an obstacle.",
      trap: "Adding an automatic retry. That hides the nondeterminism, and sometimes the flakiness reflects a real race in the production code.",
      followUps: ["Why is `sleep` in a test a smell?", "When is deleting a test the right call?"],
      depth: "Intermediate",
      tags: ["testing", "ci"],
      topic: "unit-testing",
    },
    {
      id: "test-coverage",
      q: "Is 100% test coverage a good goal?",
      a: "No, and treating it as one produces worse tests. Coverage measures which lines executed during the suite, not whether the behaviour was correct — you can execute every line with no assertions at all and report full coverage. Chasing the last percentage points pushes people to write tests for trivial getters, generated code, and error branches that can't occur, which adds maintenance cost without adding confidence, and it encourages assertions on implementation details because those are the easiest way to touch a line. What coverage is genuinely useful for is the inverse: finding untested areas. A critical payment module at 20% is a real signal worth acting on. So a sensible policy is a floor rather than a target — say 70–80% overall, with a higher bar on core business logic and no requirement on generated or boilerplate code — plus a rule that coverage must not decrease on a PR. Branch coverage is more informative than line coverage, and mutation testing is the honest measure if you want one: it changes the code and checks whether tests fail, which directly tests whether your assertions have teeth.",
      why: "It's a good judgement question — the metric is useful in one direction and harmful as a target.",
      trap: "Mandating 100%. It reliably produces assertion-free tests written to satisfy the tool.",
      followUps: ["What does mutation testing measure?", "Where would you set a higher bar?"],
      depth: "Intermediate",
      tags: ["testing", "metrics"],
    },
    {
      id: "git-merge-rebase",
      q: "Merge or rebase?",
      a: "Merge creates a commit joining two histories, preserving exactly what happened and when; rebase replays your commits on top of a new base, producing a linear history but new commit ids for every replayed commit. The workflow most teams settle on is to rebase your own feature branch onto the updated main before opening or updating a PR — which gives a clean, readable series of commits and makes `git bisect` far more useful — and then merge into main to integrate. The rule that prevents disasters is never to rebase a branch that others may have pulled: because rebasing rewrites commit ids, anyone who has the old commits gets a divergent history and has to recover manually, and a force-push onto a shared branch can destroy work. If you need to undo something on a shared branch, `git revert` is the safe tool, since it adds a new commit rather than rewriting the past. Worth mentioning that interactive rebase is also how you clean up WIP commits into meaningful ones before review, which is a courtesy to reviewers.",
      why: "It's the most common Git interview question and the shared-branch rule is the part that matters operationally.",
      trap: "Saying one is universally better. They serve different purposes, and the failure mode is rebasing shared history.",
      followUps: ["What does `git reflog` recover?", "How would you undo a bad commit on main?"],
      depth: "Core",
      tags: ["git"],
      topic: "rebasing",
    },
    {
      id: "git-recover",
      q: "You ran `git reset --hard` and lost commits. What now?",
      a: "Use `git reflog`, which records every position HEAD has occupied — commits, checkouts, resets, rebases, merges — regardless of whether those commits are still reachable from any branch. Find the entry from before the reset, note its hash, and either `git checkout -b recovery <hash>` to inspect it safely or `git reset --hard <hash>` to move the branch back. The reason this works is that `git reset` moves a pointer; it doesn't immediately delete objects, which remain in the object database until garbage collection runs, typically after 30 days for unreachable objects. This also recovers from a botched rebase, a deleted branch, or an amended commit whose original you needed. The important caveat is that reflog is local and per-clone, so it can't recover work that only ever existed on someone else's machine, and `--hard` does discard uncommitted working-tree changes permanently, since those were never objects in the first place. That's the argument for committing or stashing before any destructive operation.",
      why: "It's a practical question, and knowing reflog exists is the difference between a five-minute fix and lost work.",
      trap: "Believing `reset --hard` is irreversible. Committed work is recoverable; only uncommitted changes are truly gone.",
      followUps: ["What can reflog NOT recover?", "How would you recover a deleted branch?"],
      depth: "Intermediate",
      tags: ["git"],
      topic: "git-fundamentals",
    },
    {
      id: "devops-docker-layers",
      q: "How do you make a Docker build fast and the image small?",
      a: "Both come from understanding layers. Each instruction creates a layer, layers are cached, and a change invalidates that layer and everything after it — so order the Dockerfile from least- to most-frequently-changing. Concretely, copy the dependency manifest and install dependencies before copying application source, because source changes on every commit while dependencies change rarely, and inverting that order means reinstalling everything every build. For size, use a multi-stage build: compile or install build-time dependencies in a builder stage and copy only the resulting artefact into a slim runtime image, so compilers, headers, and dev dependencies never ship. Choose a minimal base — slim or distroless rather than a full distribution — and pin it by digest for reproducibility. Add a `.dockerignore`, since without one the build context includes `node_modules`, `.git`, and possibly secrets, which is both slow and a leak risk. And never `COPY` a secret into a layer even if you delete it later, because layers are immutable and inspectable; use build secrets or inject at runtime.",
      why: "It's a daily-practice question where the answer directly maps to CI time and image size.",
      trap: "Copying the whole source before installing dependencies. Every code change then busts the dependency cache.",
      followUps: ["Why doesn't deleting a file in a later layer shrink the image?", "What does distroless give up?"],
      depth: "Intermediate",
      tags: ["docker"],
      topic: "images-layers",
    },
    {
      id: "devops-zero-downtime",
      q: "How do you deploy without downtime?",
      a: "The core requirement is that old and new versions must be able to run simultaneously, because every gradual strategy has an overlap window. That makes backward compatibility the real work: database migrations follow expand-migrate-contract, adding a nullable column and backfilling before making it required, and never dropping or renaming in the same release that stops using it; API changes are additive; and message formats must be readable by both versions. Around that, the mechanics are rolling updates replacing instances a few at a time, with readiness probes so traffic only goes to instances that can serve and liveness probes to restart genuinely stuck ones. Graceful shutdown matters as much as startup — on SIGTERM, fail the readiness probe first so the load balancer removes you, then stop accepting new connections, finish in-flight requests within a bounded timeout, and close resources; skipping this drops requests on every deploy. Then verify: post-deploy smoke tests, per-version metrics, and automatic rollback if error rate or latency breaches its SLO. Feature flags complete the picture by separating deploying code from enabling behaviour, so a risky change can be turned off without a redeploy.",
      why: "It combines infrastructure, database, and application concerns, which is where real deployment problems live.",
      trap: "Focusing on the orchestration strategy and ignoring schema compatibility. That's what actually breaks during rollouts.",
      followUps: ["Why fail the readiness probe before closing connections?", "Walk through renaming a column with zero downtime."],
      depth: "Advanced",
      tags: ["deployment"],
      topic: "release-strategies",
    },
    {
      id: "devops-ci-cd",
      q: "What belongs in a CI pipeline?",
      a: "Everything that can catch a problem cheaply, ordered fastest-first so failures surface quickly. Typically: install dependencies from a lockfile so the build is reproducible; lint and format check; type check; unit tests; build; integration tests against real dependencies in containers; security scanning of dependencies and of the built image; and for a merge to main, publishing an immutable artefact tagged with the commit. Two principles matter more than the list. It must be blocking — a pipeline whose failures can be merged past is decoration — and it must be fast, because a suite taking forty minutes means people batch changes and stop running it locally, which defeats the purpose; caching dependencies and parallelising test shards are the usual levers. Then CD takes the artefact built once and promotes that same artefact through environments, rather than rebuilding per environment, which guarantees what you tested is what you ship. Deployment configuration differs per environment; the artefact does not. Add smoke tests after deploy and automatic rollback on SLO breach, and you have a pipeline where merging is genuinely safe.",
      why: "It shows whether someone has built a pipeline or only used one.",
      trap: "Rebuilding the artefact for each environment. Then staging and production are different builds and 'it worked in staging' means less than it should.",
      followUps: ["Why promote the same artefact rather than rebuild?", "How do you keep the pipeline under ten minutes?"],
      depth: "Intermediate",
      tags: ["ci-cd"],
      topic: "continuous-integration",
    },
    {
      id: "devops-k8s-basics",
      q: "Explain the Kubernetes objects you'd actually use.",
      a: "A Pod is the unit of scheduling — one or more containers sharing a network namespace and storage — but you rarely create one directly because it isn't self-healing. A Deployment manages a ReplicaSet which manages Pods, giving you declarative replica count, rolling updates, and rollback; that's what you deploy a stateless service as. A Service gives a stable virtual IP and DNS name in front of a changing set of Pods, load-balancing across those matching its selector, which solves the problem that Pod IPs change constantly. An Ingress (or Gateway API) handles external HTTP routing and TLS termination. ConfigMaps and Secrets inject configuration and credentials, keeping them out of the image. For stateful workloads a StatefulSet gives stable identities and per-Pod persistent volumes. The concepts that matter operationally are: resource requests, which drive scheduling, and limits, which cause throttling or OOM-kills when exceeded; readiness probes, which control whether traffic is sent to a Pod, versus liveness probes, which restart it; and the reconciliation loop, where you declare desired state and controllers work continuously to make reality match.",
      why: "Kubernetes vocabulary is assumed in most backend roles, and the probe distinction is where real incidents come from.",
      trap: "Confusing readiness and liveness. A liveness probe that's really a readiness check restarts healthy Pods under load and turns a slowdown into an outage.",
      followUps: ["What happens when a container exceeds its memory limit?", "Why do CPU limits cause latency spikes?"],
      depth: "Advanced",
      tags: ["kubernetes"],
      topic: "k8s-architecture",
    },
    {
      id: "devops-iac",
      q: "Why infrastructure as code?",
      a: "Because manually-configured infrastructure is undocumented, unreproducible, and undiffable. With Terraform or an equivalent, the desired state is in version control, so changes are reviewed like code, the history explains why something is the way it is, and you can recreate an environment from scratch — which is what makes disaster recovery and spinning up a realistic staging environment feasible rather than theoretical. It also eliminates configuration drift between environments, which is the usual reason something works in staging and fails in production. The practical concerns worth raising are state management, since Terraform's state file is the mapping between config and real resources and must live in shared, locked, versioned remote storage or two engineers applying simultaneously will corrupt it; the plan-and-review discipline, where you read the plan before applying rather than trusting it; separating environments so a mistake in staging can't touch production; and drift detection, because someone will eventually change something in the console and the code will silently no longer match. Secrets don't belong in the code — reference a secret manager — and remember that state files can contain sensitive values, so they need protecting too.",
      why: "IaC is standard practice, and state management is the operational detail that separates users from practitioners.",
      trap: "Keeping Terraform state locally or in the repo. It's a shared source of truth that needs locking, and it can contain secrets.",
      followUps: ["What happens if two people apply at once?", "How do you handle a resource changed manually in the console?"],
      depth: "Advanced",
      tags: ["iac", "cloud"],
      topic: "infrastructure-as-code",
    },
  ],

  pitfalls: [
    "Don't aim for heavy end-to-end coverage — slow, flaky suites get ignored.",
    "Don't mock your own database — SQL and migrations are exactly where the bugs are.",
    "Don't fix a flaky test with an automatic retry — diagnose it or quarantine it with an owner.",
    "Don't treat 100% coverage as a goal — it produces assertion-free tests.",
    "Don't rebase a branch someone else may have pulled.",
    "Don't copy source before installing dependencies in a Dockerfile.",
    "Don't rebuild the artefact per environment — promote the one you tested.",
    "Don't conflate readiness and liveness probes — the wrong one restarts healthy pods under load.",
    "Don't plan a deploy without checking that old and new code can run against the same schema.",
  ],

  numbers: [
    { label: "Target CI duration", value: "< 10 min", note: "Beyond this, people batch changes and stop running it locally." },
    { label: "Coverage floor", value: "70–80%", note: "A floor that can't decrease, not a target of 100%." },
    { label: "Git unreachable object retention", value: "~30 days", note: "The window in which reflog can save you." },
    { label: "Canary first step", value: "1–5% of traffic", note: "Enough to see error-rate movement, small enough to contain it." },
  ],

  relatedTopics: [
    "test-pyramid",
    "unit-testing",
    "integration-testing",
    "test-doubles",
    "tdd",
    "git-fundamentals",
    "rebasing",
    "branching-merging",
    "container-fundamentals",
    "images-layers",
    "k8s-architecture",
    "continuous-integration",
    "continuous-delivery",
    "release-strategies",
    "infrastructure-as-code",
  ],
};
