import type { Area } from "../types";

export const typescript: Area = {
  slug: "typescript",
  title: "TypeScript",
  icon: "🔷",
  stream: "Language & Runtime",
  blurb:
    "Structural typing, narrowing, generics, and the `any`/`unknown` distinction — plus knowing that types vanish at runtime.",

  mustKnow: [
    "TypeScript is erased at compile time. Types do not exist at runtime, so you cannot check them with `typeof` on a custom interface, and data crossing a network boundary is unvalidated regardless of its declared type.",
    "The type system is STRUCTURAL, not nominal: a value is assignable if its shape matches, whatever it was declared as. Two unrelated interfaces with identical members are interchangeable.",
    "`any` disables all checking and spreads silently through everything it touches. `unknown` is the safe counterpart — you must narrow it before use.",
    "Narrowing is how you go from a union to one member: `typeof`, `instanceof`, `in`, truthiness, equality, discriminated unions, and user-defined type guards (`x is Foo`).",
    "`interface` and `type` overlap almost entirely; the real differences are declaration merging (interface only) and the ability to express unions, tuples, and mapped types (type only).",
    "Generics carry a type through a function so the output type relates to the input — `function first<T>(xs: T[]): T | undefined`. Constrain them with `extends` when you need to access members.",
    "`strict` mode is the point of using TypeScript; with it off, `strictNullChecks` in particular, most of the value is gone.",
    "A discriminated union (a shared literal field like `kind`) is the idiomatic way to model 'one of several shapes' and gives you exhaustiveness checking with `never`.",
    "`as` is an assertion, not a conversion — it tells the compiler to stop arguing and produces no runtime check whatsoever.",
    "Utility types you should be able to use without looking up: `Partial`, `Required`, `Pick`, `Omit`, `Record`, `Readonly`, `ReturnType`, `Awaited`, `NonNullable`.",
  ],

  sheets: [
    {
      title: "Narrowing techniques",
      points: [
        "`typeof x === 'string'` — primitives only.",
        "`x instanceof Date` — classes and constructor functions.",
        "`'kind' in x` — presence of a property distinguishes object shapes.",
        "Truthiness `if (x)` — removes `null`/`undefined`, but also removes `0` and `''`, which is a real bug source.",
        "Discriminated union on a literal field — the cleanest and the one to reach for.",
        "Type predicate `function isCat(a: Animal): a is Cat` — for logic the compiler can't follow.",
        "Assertion function `function assertIsUser(x: unknown): asserts x is User` — narrows for the rest of the scope.",
        "`switch` on the discriminant with a `default` assigning to `never` gives a compile error when a new variant is added.",
      ],
    },
    {
      title: "`any` vs `unknown` vs `never`",
      points: [
        "`any` — anything in, anything out, no checks. One `any` silently disables checking downstream.",
        "`unknown` — anything in, nothing out until narrowed. The correct type for `JSON.parse`, `catch` bindings, and API responses.",
        "`never` — the empty type; no value has it. Returned by functions that always throw or never return.",
        "`never` is the exhaustiveness tool: in a `switch` default, assign the value to `never` and adding an unhandled variant becomes a compile error.",
        "`unknown` is the top type (everything is assignable TO it); `never` is the bottom (assignable FROM nothing, assignable to everything).",
        "In `catch (e)`, `e` is `unknown` under `useUnknownInCatchVariables` — check `e instanceof Error` before touching `.message`.",
      ],
    },
    {
      title: "`interface` vs `type` — the actual differences",
      points: [
        "Both: object shapes, extension, implements, generics, optional and readonly members.",
        "Interface only: declaration merging — reopening the same name adds members. Required for augmenting library or global types.",
        "Type only: unions (`A | B`), tuples, primitives, mapped types, conditional types, template literal types.",
        "Interfaces give slightly nicer error messages and are cached better by the compiler in large codebases.",
        "Convention that works: `interface` for object shapes you might extend or augment, `type` for everything else.",
      ],
    },
    {
      title: "Generics — the useful subset",
      points: [
        "`<T>` infers from the argument; you rarely need to pass it explicitly.",
        "`<T extends { id: string }>` constrains so you can access members inside.",
        "`keyof T` — union of T's keys. `T[K]` — indexed access, the type of that property.",
        "`<T, K extends keyof T>(obj: T, key: K): T[K]` — the canonical type-safe `get`.",
        "`Partial<T>` = `{ [K in keyof T]?: T[K] }` — every mapped type is this shape.",
        "Conditional: `T extends U ? X : Y`; with `infer` you can extract, e.g. `ReturnType<T> = T extends (...a: any) => infer R ? R : never`.",
        "Distributive conditionals: a naked type parameter distributes over unions — `Exclude` relies on this.",
      ],
    },
    {
      title: "Runtime safety — where types don't help",
      points: [
        "API responses, `JSON.parse`, `localStorage`, form data, env vars, query params — all `unknown` in reality however you typed them.",
        "Validate at the boundary with Zod/Valibot and infer the static type from the schema, so there is one source of truth.",
        "`as SomeType` on a fetch response is a lie the compiler believes and production disproves.",
        "Non-null assertion `!` similarly removes the check without adding safety.",
        "Type-only code has no runtime cost; `enum` is a rare exception that emits real JavaScript (prefer `as const` unions).",
      ],
    },
  ],

  decisions: [
    {
      title: "`interface` vs `type`",
      options: [
        {
          name: "interface",
          pick: ["Object shapes that others may extend.", "Public API surface of a library.", "You need declaration merging to augment a third-party or global type."],
          cost: ["Cannot express unions, tuples, or mapped/conditional types.", "Merging can surprise readers — a type can gain members from a file they never opened."],
        },
        {
          name: "type",
          pick: ["Unions and intersections.", "Tuples, function types, primitives.", "Mapped, conditional, and template literal types.", "You want a closed definition that cannot be reopened."],
          cost: ["No declaration merging, so you cannot augment library types with it."],
        },
      ],
      verdict: "Object shapes → `interface`. Anything involving unions or type-level computation → `type`. Pick one convention and be consistent.",
    },
    {
      title: "`unknown` vs `any`",
      options: [
        {
          name: "unknown",
          pick: ["Every boundary: fetch responses, `JSON.parse`, `catch` bindings, third-party data.", "Anywhere you want the compiler to force a check."],
          cost: ["You must narrow before use, which is more code — that code is the point."],
        },
        {
          name: "any",
          pick: ["A genuine escape hatch during migration, with a TODO.", "Deliberately generic library internals where the constraint is enforced elsewhere."],
          cost: ["Disables checking not just here but everywhere the value flows — errors surface far from the cast."],
        },
      ],
      verdict: "`unknown` is the safe `any`. Reach for `any` only as a temporary, commented escape hatch.",
    },
    {
      title: "`enum` vs union of literals vs `as const`",
      options: [
        {
          name: "Union of string literals",
          pick: ["Default choice. `type Status = 'idle' | 'loading' | 'done'`.", "Zero runtime output, works naturally with JSON, narrows perfectly."],
          cost: ["No runtime object to iterate — pair with an `as const` array if you need the values at runtime."],
        },
        {
          name: "`as const` object",
          pick: ["You need both the union type AND a runtime object to iterate or map over."],
          cost: ["Slightly more verbose: the object plus a derived `typeof X[keyof typeof X]` type."],
        },
        {
          name: "`enum`",
          pick: ["Interop with code that expects numeric enum values.", "Existing codebase convention."],
          cost: ["Emits real JavaScript, so it is not erasable and breaks `isolatedModules`/`erasableSyntaxOnly` setups.", "Numeric enums are unsound — any number is assignable.", "`const enum` has its own build caveats."],
        },
      ],
      verdict: "Prefer string literal unions; add `as const` when you need runtime values. Avoid `enum` in new code.",
    },
    {
      title: "Type assertion (`as`) vs type guard vs schema validation",
      options: [
        {
          name: "`as`",
          pick: ["You genuinely know more than the compiler and the value is already checked — e.g. after a `switch` the compiler can't follow."],
          cost: ["Zero runtime verification. `data as User` on a fetch response is a lie that fails in production, not at build."],
        },
        {
          name: "Type guard / predicate",
          pick: ["Reusable narrowing logic you control, checked at runtime.", "Internal shapes where you trust the source but want the compiler to follow."],
          cost: ["You must keep the guard in sync with the type by hand — the compiler does not verify the check is complete."],
        },
        {
          name: "Schema validation (Zod)",
          pick: ["Any external boundary: HTTP, env vars, localStorage, message queues.", "You want one source of truth for validation and the type."],
          cost: ["A dependency, plus runtime validation cost on every parse — usually negligible next to the network call."],
        },
      ],
      verdict: "External data → validate with a schema and infer the type. Internal narrowing → type guard. `as` only when you've already proved it.",
    },
  ],

  qa: [
    {
      id: "ts-why",
      q: "What does TypeScript actually buy you?",
      a: "Errors at build time instead of runtime, and that's a smaller claim than it sounds — it catches shape mismatches, null dereferences, and missed cases, not logic bugs. The larger practical wins are editor tooling and refactoring: accurate autocomplete, go-to-definition, and rename-across-a-codebase are only possible because the compiler knows the types. Types also act as enforced documentation — a signature tells you what a function needs and returns, and it can't drift out of date the way a comment can. On large teams that's the dominant benefit. The cost is real: build complexity, some ceremony, and a tendency for type-level cleverness to become its own problem. And it guarantees nothing about data arriving from outside the program, which people consistently over-assume.",
      why: "Tests whether someone has a calibrated view rather than treating TS as a magic safety net.",
      trap: "Claiming it prevents runtime errors. It prevents a class of them; anything crossing a boundary is still unchecked.",
      followUps: ["What kinds of bugs does it NOT catch?", "What's the cost of adopting it?"],
      depth: "Core",
      tags: ["fundamentals"],
      topic: "type-systems",
    },
    {
      id: "ts-structural",
      q: "What is structural typing?",
      a: "Assignability is decided by shape, not by name or declared ancestry. If a value has all the members a target type requires, it's assignable, even if the two types were declared independently and share no relationship. So a function expecting `{ name: string }` accepts any object with a `name: string`, including instances of unrelated classes. This is why TypeScript feels natural over JavaScript, where objects are ad-hoc. The consequence to know is that you can't distinguish two types with identical shapes — a `UserId` and an `OrderId` that are both `string` are interchangeable, and the compiler won't stop you passing one where the other belongs. If you need that distinction you create it artificially with branded types: `type UserId = string & { readonly __brand: 'UserId' }`, which nothing else structurally matches.",
      why: "The branding follow-up shows whether someone has hit the limits of the type system in practice.",
      trap: "Assuming `class A` and `class B` with the same members are incompatible. In TypeScript they are interchangeable — unless one has a `private` member, which does introduce nominal behaviour.",
      followUps: ["How do you make two string types incompatible?", "Why do `private` members break structural compatibility?"],
      depth: "Intermediate",
      tags: ["type-system"],
      topic: "type-systems",
    },
    {
      id: "ts-any-unknown",
      q: "`any` vs `unknown` — when do you use each?",
      a: "Both accept any value, but they differ entirely on the way out. With `any`, every operation is allowed and no error is ever reported, and worse, the `any` propagates: assign it to a typed variable and checking quietly stops there too, so the eventual failure appears far from the cast. With `unknown`, nothing is allowed until you narrow — you must check with `typeof`, `instanceof`, `in`, or a guard before touching it. That makes `unknown` correct for every boundary: `JSON.parse` returns it, `catch` bindings are it under `useUnknownInCatchVariables`, and API responses should be it before validation. Use `any` only as a deliberate, commented escape hatch during migration. `noImplicitAny` catches the accidental cases; the explicit ones need review discipline.",
      why: "It's a direct proxy for whether someone writes defensively at boundaries.",
      trap: "Typing a fetch response `as User` and treating it as validated. That's an assertion, not a check.",
      followUps: ["What type is `e` in `catch (e)`?", "How do you safely narrow `unknown` from an API?"],
      depth: "Core",
      tags: ["safety"],
    },
    {
      id: "ts-discriminated-union",
      q: "What is a discriminated union and why is it the idiomatic pattern?",
      a: "It's a union of object types sharing a literal field that identifies which member you have: `type Result = { status: 'ok'; data: User } | { status: 'error'; message: string }`. Switching on `status` narrows the type in each branch, so `data` is only accessible where it exists — the compiler enforces that you can't read `data` off an error. This is better than a single interface with optional fields, because that would let you construct impossible states like both `data` and `message` present, or neither. You also get exhaustiveness: give the `switch` a `default` that assigns the value to `never`, and adding a third variant becomes a compile error at every site that handles the union, which turns 'find all the places to update' into a build failure instead of a code search.",
      why: "It's how you model state properly in TypeScript, and it demonstrates make-invalid-states-unrepresentable thinking.",
      trap: "Modelling async state as `{ loading: boolean; data?: T; error?: E }`, which permits loading-and-error-and-data simultaneously.",
      followUps: ["Show the `never` exhaustiveness check.", "How would you model a fetch lifecycle as a union?"],
      depth: "Intermediate",
      tags: ["unions", "modelling"],
    },
    {
      id: "ts-never-exhaustive",
      q: "How do you get exhaustiveness checking?",
      a: "Use `never`. In a `switch` over a discriminated union, add a default branch that assigns the value to a `never`-typed variable: `default: { const _exhaustive: never = value; throw new Error('Unhandled: ' + value); }`. Inside that branch, if every variant has been handled, the narrowed type is `never` and the assignment compiles. If someone later adds a variant to the union, the narrowed type is now that variant, which isn't assignable to `never`, and you get a compile error pointing at exactly this spot. That's the whole trick, and it's valuable because it converts a silent gap into a build failure everywhere the union is consumed. The same pattern works with a helper `function assertNever(x: never): never { throw ... }`.",
      why: "It's the practical payoff of `never` and shows the type system being used to prevent future mistakes, not just describe present ones.",
      trap: "Using a `default` that just throws at runtime. That catches the bug in production instead of at compile time.",
      followUps: ["Why does the narrowed type become `never`?", "Does this work with `if/else` chains too?"],
      depth: "Intermediate",
      tags: ["never", "unions"],
    },
    {
      id: "ts-generics",
      q: "Explain generics with a real example.",
      a: "A generic lets a function relate its output type to its input type instead of fixing both. `function first<T>(items: T[]): T | undefined { return items[0]; }` — call it with `string[]` and you get `string | undefined`, with `User[]` and you get `User | undefined`. Without the parameter you'd have to return `any` and lose everything, or write one overload per type. Constraints let you use the parameter: `function byId<T extends { id: string }>(items: T[], id: string): T | undefined` can read `.id` because `extends` guarantees it, while still returning the caller's exact type. The most useful pairing is `keyof`: `function get<T, K extends keyof T>(obj: T, key: K): T[K]` gives a getter where the return type depends on which key you passed, and a typo in the key is a compile error.",
      why: "Generics are where TypeScript stops being annotations and starts being a type system.",
      trap: "Adding type parameters that appear only once in the signature. If `T` isn't used to relate two positions, it's doing nothing and should be `unknown` or a concrete type.",
      followUps: ["What does `extends` do in a generic?", "Write a type-safe `pick` function."],
      depth: "Intermediate",
      tags: ["generics"],
    },
    {
      id: "ts-utility-types",
      q: "Which utility types do you use, and how are they built?",
      a: "The everyday set: `Partial<T>` makes all properties optional (patch payloads), `Required<T>` the reverse, `Pick<T, K>` and `Omit<T, K>` select or drop keys, `Record<K, V>` builds a dictionary type, `Readonly<T>` freezes at the type level, `ReturnType<F>` and `Parameters<F>` extract from a function, `Awaited<T>` unwraps a promise, and `NonNullable<T>` strips `null | undefined`. They're not magic — they're mapped and conditional types you could write yourself: `Partial<T>` is `{ [K in keyof T]?: T[K] }`, `Omit<T, K>` is `Pick<T, Exclude<keyof T, K>>`, and `ReturnType<T>` is `T extends (...args: any) => infer R ? R : never`. Knowing that is what lets you build the one you need when none of the built-ins fit.",
      why: "Using them is table stakes; being able to write them shows real type-system fluency.",
      trap: "Reaching for `Omit` on a union type. It collapses the union because `keyof` on a union gives only shared keys — you need a distributive helper.",
      followUps: ["Implement `Partial` yourself.", "Why does `Omit` misbehave on unions?"],
      depth: "Advanced",
      tags: ["utility-types", "generics"],
    },
    {
      id: "ts-runtime-validation",
      q: "How do you type an API response safely?",
      a: "You validate it, because the declared type is a claim about data you don't control. `const user = await res.json() as User` compiles and tells you nothing — if the API renames a field, TypeScript is perfectly happy and the failure surfaces later as an undefined property somewhere unrelated. The right pattern is a schema at the boundary: define it once with Zod or Valibot, `parse` the response, and derive the static type from the schema with `z.infer<typeof UserSchema>` so there's a single source of truth that can't drift. You get an immediate, localised error with a useful message when the shape is wrong, plus the option to coerce and apply defaults. The same reasoning applies to environment variables, `localStorage`, query params, and message payloads.",
      why: "It's the highest-value practical TypeScript habit and the one most commonly missing.",
      trap: "Believing the type annotation performs a check. Types are erased; only a validator runs.",
      followUps: ["Where else does unvalidated data enter?", "How do you keep the schema and type in sync?"],
      depth: "Intermediate",
      tags: ["validation", "safety"],
    },
    {
      id: "ts-strict",
      q: "What does `strict` enable, and which flag matters most?",
      a: "`strict` is an umbrella turning on `strictNullChecks`, `noImplicitAny`, `strictFunctionTypes`, `strictBindCallApply`, `strictPropertyInitialization`, `noImplicitThis`, `alwaysStrict`, and `useUnknownInCatchVariables`. The one that carries most of the value is `strictNullChecks`: without it, `null` and `undefined` are assignable to every type, so the compiler can't warn about the most common runtime error in JavaScript. With it, `string | null` is distinct from `string` and you're forced to handle absence explicitly. `noImplicitAny` is second, since an unannotated parameter silently becoming `any` is how checking quietly disappears. Enabling strict on an existing codebase is best done file-by-file — turn it on globally, then use `// @ts-expect-error` or a per-file exclusion list, and burn the list down, since `@ts-expect-error` fails the build once the underlying error is fixed.",
      why: "'Which flag matters most' separates people who configured it from people who inherited it.",
      trap: "Running with strict off and claiming the benefits of TypeScript. Most of the safety comes from `strictNullChecks`.",
      followUps: ["Why is `@ts-expect-error` better than `@ts-ignore`?", "How do you migrate a large codebase incrementally?"],
      depth: "Intermediate",
      tags: ["config"],
    },
    {
      id: "ts-type-guard",
      q: "What is a user-defined type guard?",
      a: "A function whose return type is `arg is Type` rather than `boolean`. When it returns true, the compiler narrows the argument in the calling scope: `function isUser(x: unknown): x is User { return typeof x === 'object' && x !== null && 'id' in x; }` lets you write `if (isUser(data)) { data.id }` with full type safety. It exists because the compiler can't follow arbitrary logic — it understands `typeof` and `in` inline, but not the same checks hidden inside a function call. The important caveat is that the compiler does not verify your check actually proves the type; the predicate is a promise you make, and a sloppy guard is as unsound as a cast. Related is the assertion form, `function assertIsUser(x: unknown): asserts x is User`, which throws instead of returning and narrows for the remainder of the scope.",
      why: "It shows understanding of where inference ends and where you must help the compiler.",
      trap: "Writing a guard that checks one field and claims a large interface. The compiler trusts you completely.",
      followUps: ["How does an assertion function differ?", "Why are schema validators safer than hand-written guards?"],
      depth: "Intermediate",
      tags: ["narrowing"],
    },
    {
      id: "ts-conditional-infer",
      q: "What are conditional types and `infer`?",
      a: "A conditional type branches at the type level: `T extends U ? X : Y`. `infer` introduces a type variable inside the `extends` clause that gets bound to whatever matched, which is how you extract parts of a type. `type ReturnType<T> = T extends (...args: any[]) => infer R ? R : never` reads as 'if T is a function, capture its return type as R and produce it'. The same shape gives you `Awaited` (unwrap a promise), `ElementType` (unwrap an array), and `Parameters` (capture the argument tuple). One behaviour to know: when the checked type is a naked type parameter and you pass a union, the conditional DISTRIBUTES over the union members and re-unions the results — that's what makes `Exclude<T, U>` work. You can disable that by wrapping both sides in tuples: `[T] extends [U] ? ...`.",
      why: "Distribution is the subtlety that trips people up when their conditional type mysteriously returns a union.",
      trap: "Not knowing about distribution, then being confused when `NonNullable<string | null>` behaves elementwise.",
      followUps: ["Write `ElementType<T>`.", "How do you stop distribution?"],
      depth: "Advanced",
      tags: ["generics", "type-level"],
    },
    {
      id: "ts-declaration-merging",
      q: "What is declaration merging and when do you need it?",
      a: "Declaring an `interface` with a name that already exists merges the members rather than erroring, which `type` cannot do. It matters for augmenting types you don't own: adding a property to Express's `Request` so middleware can attach `req.user`, extending `Window` with something a script injects, or adding fields to a library's config type. You do it inside `declare module 'express'` or `declare global`, reopening the interface and adding members. The trade-off is that it makes types non-local — a property can appear on a type from a file the reader never opens — so it should be confined to a small number of clearly-named declaration files. Namespaces and enums also merge, and a function can merge with a namespace to model a callable object with properties.",
      why: "It's the concrete reason to choose `interface` over `type` for public shapes.",
      trap: "Trying to extend a library type with `type` and an intersection. That creates a new name; it doesn't change what the library's own code sees.",
      followUps: ["How would you add `req.user` in Express?", "Why is this a downside as well as a feature?"],
      depth: "Advanced",
      tags: ["modules", "interfaces"],
    },
    {
      id: "ts-variance",
      q: "Why are function parameter types checked the way they are?",
      a: "Return types are covariant, which is intuitive: a function returning `Dog` is usable where one returning `Animal` is expected. Parameters are contravariant in principle — a handler accepting `Animal` can safely stand in for one accepting `Dog`, since it handles more. TypeScript under `strictFunctionTypes` enforces that for function *type* expressions, but deliberately keeps method parameters bivariant for compatibility, which is why array and DOM APIs behave loosely. The practical consequence people hit is with callbacks: passing a narrower-parameter callback where a wider one is expected compiles in method position and fails in function position, which looks inconsistent until you know the rule. It also explains why `Array<Dog>` being assignable to `Array<Animal>` is unsound — mutating through the wider reference could insert a `Cat`.",
      why: "It's an advanced signal; few candidates can explain why arrays are unsoundly covariant.",
      trap: "Asserting TypeScript is fully sound. It makes documented pragmatic trade-offs — array covariance and method bivariance among them.",
      followUps: ["Give an example of unsound array covariance.", "What does `strictFunctionTypes` change?"],
      depth: "Advanced",
      tags: ["type-system", "variance"],
    },
    {
      id: "ts-satisfies",
      q: "What does `satisfies` do that `as` and a type annotation don't?",
      a: "It checks a value against a type without widening it. If you annotate `const config: Record<string, string> = { host: 'x' }`, the checker validates it but the variable's type is now the annotation, so you lose the knowledge that `host` specifically exists. If you use `as`, you get no real checking at all. `satisfies` gives you both: `const config = { host: 'x' } satisfies Record<string, string>` validates the constraint while the inferred type stays the literal shape, so `config.host` autocompletes and a typo is an error. It's especially useful for route maps, theme objects, and config where you want a constraint enforced but also want precise keys and literal value types preserved.",
      why: "It's a relatively recent addition (4.9) and knowing it signals someone keeping current.",
      trap: "Using an annotation for config objects and then wondering why key autocomplete disappeared.",
      followUps: ["When would an annotation still be preferable?"],
      depth: "Advanced",
      tags: ["inference"],
    },
    {
      id: "ts-erasure",
      q: "What does it mean that types are erased?",
      a: "The compiler checks types and then deletes them; the emitted JavaScript has no type information at all. Practical consequences: you cannot write `if (x instanceof MyInterface)` because the interface doesn't exist at runtime, you cannot switch on a generic type parameter, and reflection over types requires a separate runtime representation such as a schema or decorator metadata. It also means TypeScript adds no runtime overhead, which is a genuine benefit. The exceptions are the few constructs that emit code — `enum` produces a real object, parameter properties in constructors produce assignments, and legacy decorators emit metadata — which is why `isolatedModules` and newer erasable-syntax settings push you toward the fully-erasable subset. Anywhere you need a runtime check, you need runtime code: a discriminant field, a validator, or a class you can `instanceof`.",
      why: "It's the root cause of a whole family of 'why can't I do this' questions.",
      trap: "Trying to validate data against an interface at runtime. You need a schema, not a type.",
      followUps: ["Why does `enum` break erasability?", "How do you check a shape at runtime?"],
      depth: "Intermediate",
      tags: ["compilation"],
      topic: "compilation-vs-interpretation",
    },
  ],

  pitfalls: [
    "Don't say TypeScript prevents runtime errors — say it catches a class of them at build time, and boundaries still need validation.",
    "Don't use `as` on a fetch response and call it typed — that's an unchecked assertion.",
    "Don't claim `interface` and `type` are identical — declaration merging and unions are the real differences.",
    "Don't model async state as optional booleans and fields — use a discriminated union so invalid states can't be constructed.",
    "Don't leave `strictNullChecks` off and claim the benefits of TypeScript.",
    "Don't add type parameters that appear only once in a signature — they're doing no work.",
    "Don't reach for `enum` in new code — string literal unions erase cleanly and narrow better.",
  ],

  relatedTopics: ["type-systems", "compilation-vs-interpretation", "error-handling", "immutability"],
};
